# 72 ? Experimento TF-IDF + DBSCAN

Este notebook testa agrupamento de descri??es normalizadas de itens de supermercado usando TF-IDF e DBSCAN. A an?lise usa dist?ncia cosseno, n?o usa NCM nem r?tulos humanos, e trata ru?do como resultado expl?cito do algoritmo. A amostra configur?vel mant?m o custo do c?lculo de vizinhan?a controlado. Execute de cima para baixo em uma sess?o limpa.

In [1]:
from hashlib import sha256
from datetime import datetime, timezone
from pathlib import Path
import logging
import json

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display
from sklearn import config_context
from sklearn.cluster import DBSCAN
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import silhouette_score
from sklearn.manifold import TSNE
from sklearn.decomposition import TruncatedSVD
from matplotlib.colors import ListedColormap

from nofis_classifier.schema import DESCRIPTION_NORMALIZED, FREQUENCY

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("notebook72")
pd.set_option("display.max_colwidth", 140)

## Configuracoes e comparabilidade

Controles comuns aos notebooks 70 a 76:

- Base completa `2025_NCMs_filtrados_semstopwords`, periodo 202501-202512.
- Ate 20.000 descricoes unicas para agrupamento, amostradas com semente 42 e ordenadas por descricao normalizada. Frequencia nao pondera o ajuste.
- Silhouette cosseno sobre uma amostra base fixa de ate 20.000 linhas, com semente 42. Ruido do algoritmo e excluido depois da amostragem; a quantidade efetivamente avaliada e registrada.
- Ranking exige silhouette definida e de 10 a 1.000 clusters efetivamente formados, sem contar ruido. Pesos: 0,75 para silhouette reescalada e 0,25 para cobertura do algoritmo.
- t-SNE 2D e 3D: mesmos ate 5.000 itens, semente 42, TruncatedSVD de ate 50 componentes, perplexidade 30, 1.000 iteracoes, init PCA (quando ha dimensoes suficientes), learning_rate auto e Barnes-Hut. As projecoes de representacoes diferentes sao exploratorias, nao um espaco comum de distancias.
- `comparison` em `run.json` registra os controles e o hash das descricoes/frequencias usadas no agrupamento.

TF-IDF: os mesmos 10 analyzers dos experimentos de texto, cruzados com `MIN_DF_VALUES = [1, 2, 5, 10]`, max_features 100.000, max_df 1.0, sublinear_tf True, norm l2 e dtype float64. Os vetores zerados sao registrados como diagnostico da representacao, separados do ruido do algoritmo.

DBSCAN: a mesma grade de eps e min_samples do notebook 73, preservando a uniao dos valores ja configurados nos dois. Grade atual: 40 representacoes x 11 valores de eps x 8 valores de min_samples = 3.520 ajustes.

In [2]:
DATASET_NAME = "2025_NCMs_filtrados_semstopwords"


PROJECT_ROOT = next(
    (parent for parent in (Path.cwd(), *Path.cwd().parents)
     if (parent / "data" / "processed").is_dir()),
    None,
)
if PROJECT_ROOT is None:
    raise FileNotFoundError("Nao encontrei a raiz do repositorio com data/processed/.")
DATASET_DIR = PROJECT_ROOT / "data" / "processed" / DATASET_NAME
DATASET_FILES = sorted(DATASET_DIR.glob("*.parquet"))
if not DATASET_FILES:
    raise FileNotFoundError(f"Nenhum Parquet encontrado para {DATASET_NAME}: {DATASET_DIR}")
if len(DATASET_FILES) > 1:
    raise ValueError(
        f"Mais de um Parquet encontrado em {DATASET_DIR}; selecione o arquivo/periodo explicitamente: "
        f"{[path.name for path in DATASET_FILES]}"
    )
DATASET_PATH = DATASET_FILES[0]
if not DATASET_PATH.stem.startswith(f"{DATASET_NAME}-"):
    raise ValueError(
        f"O nome do arquivo deve comecar com '{DATASET_NAME}-' para derivar o periodo: "
        f"{DATASET_PATH.name}"
    )



PERIOD_LABEL = DATASET_PATH.stem[len(DATASET_NAME) + 1:]
MAX_DESCRIPTIONS = 20_000
CONSIDER_FREQUENCY_IN_CLUSTERING = False
SAMPLE_SEEDS = [42]
ANALYZER_CONFIGS = {'char_wb_2_4': ('char_wb', (2, 4)), 'char_wb_2_10': ('char_wb', (2, 10)), 'char_wb_3_5': ('char_wb', (3, 5)), 'char_wb_3_10': ('char_wb', (3, 10)), 'char_wb_4_8': ('char_wb', (4, 8)), 'char_wb_4_10': ('char_wb', (4, 10)), 'char_wb_5_10': ('char_wb', (5, 10)), 'word_1_3': ('word', (1, 3)), 'word_1_5': ('word', (1, 5)), 'word_2_5': ('word', (2, 5))}
MIN_DF_VALUES = [1, 2, 5, 10]
MAX_FEATURES = 100_000
SILHOUETTE_SAMPLE_SIZE = 20_000
DBSCAN_N_JOBS = 1
PAIRWISE_WORKING_MEMORY_MIB = 64
EPS_VALUES = [0.01, 0.02, 0.025, 0.03, 0.035, 0.04, 0.05, 0.07, 0.1, 0.5, 1]
MIN_SAMPLES_VALUES = [2, 3, 5, 7, 10, 20, 30, 100]
OUTPUT_ROOT = PROJECT_ROOT / Path("reports/tfidf_dbscan")

TSNE_MAX_POINTS = 5_000
TSNE_PERPLEXITY = 30
TSNE_MAX_ITER = 1_000
TSNE_RANDOM_STATE = 42
TSNE_3D_N_COMPONENTS = 3
TSNE_SVD_COMPONENTS = 50
METRIC_RANDOM_STATE = 42

MAX_DF = 1.0

### Configuracao do ranking final

`MIN_CLUSTER_FOR_RANKING = 10` define o minimo do ranking. O intervalo ate `MAX_CLUSTERS_FOR_RANKING` inclui os dois extremos e nao altera os ajustes da grade. Em DBSCAN/HDBSCAN, a contagem exclui o grupo de ruido (-1).

In [3]:
# O limite filtra apenas o ranking e a selecao final; nao altera os ajustes do DBSCAN.
MAX_CLUSTERS_FOR_RANKING = 1000
MIN_CLUSTER_FOR_RANKING = 10

# Os pesos definem a contribuicao relativa de silhouette e cobertura (1 - ruido).
# Com pesos iguais, as duas dimensoes contribuem igualmente para a metrica composta.
SILHOUETTE_WEIGHT = 0.75
NOISE_WEIGHT = 0.25

## 2. Fun??es da an?lise

A prepara??o remove descri??es vazias, mant?m uma linha por descri??o e valida que a frequ?ncia total n?o foi alterada. Cada configura??o ? executada em uma c?pia l?gica da mesma matriz TF-IDF.

In [4]:
def prepare_items(frame):
    initial_frequency = frame[FREQUENCY].sum()
    prepared = frame[[DESCRIPTION_NORMALIZED, FREQUENCY]].copy()
    prepared[DESCRIPTION_NORMALIZED] = prepared[DESCRIPTION_NORMALIZED].astype("string").str.strip()
    prepared = prepared[prepared[DESCRIPTION_NORMALIZED].notna() & prepared[DESCRIPTION_NORMALIZED].ne("")]
    prepared = prepared[prepared[FREQUENCY] >= 1].copy()
    prepared = (
        prepared.groupby(DESCRIPTION_NORMALIZED, as_index=False, sort=False)[FREQUENCY]
        .sum()
    )
    if prepared[FREQUENCY].sum() != initial_frequency:
        raise ValueError("A prepara??o alterou a soma de frequ?ncia.")
    return prepared.sort_values(DESCRIPTION_NORMALIZED).reset_index(drop=True)

def summarize_clusters(items, labels):
    result = items.copy()
    result["cluster"] = labels
    result["ruido"] = result["cluster"].eq(-1)
    summary = (
        result.groupby("cluster", as_index=False)
        .agg(descricoes_unicas=(DESCRIPTION_NORMALIZED, "size"), frequencia_total=(FREQUENCY, "sum"))
        .sort_values("descricoes_unicas", ascending=False)
    )
    return result, summary

def score_configuration(matrix, labels, sample_size, random_state):
    """Avalia a mesma amostra de linhas, excluindo ruido somente apos amostrar."""
    labels = np.asarray(labels)
    noise_mask = labels == -1
    cluster_count = len(np.unique(labels[~noise_mask]))
    base_count = min(sample_size, len(labels))
    rng = np.random.default_rng(random_state)
    positions = np.sort(rng.choice(len(labels), size=base_count, replace=False))
    positions = positions[~noise_mask[positions]]
    sample_labels = labels[positions]
    sample_cluster_count = len(np.unique(sample_labels))
    score = np.nan
    actual_count = len(positions)
    if 2 <= sample_cluster_count < actual_count:
        with config_context(working_memory=PAIRWISE_WORKING_MEMORY_MIB):
            score = float(silhouette_score(matrix[positions], sample_labels, metric="cosine"))
    else:
        actual_count = 0
    return {
        "cluster_count_excluding_noise": cluster_count,
        "noise_count": int(noise_mask.sum()),
        "noise_fraction": float(noise_mask.mean()),
        "silhouette_base_sample_size": base_count,
        "silhouette_sample_size": actual_count,
        "silhouette_cosine_without_noise": score,
    }


def compute_tsne_projection(features, max_points, perplexity, max_iter, random_state, n_components=2):
    """Usa a mesma amostra, SVD e parametros t-SNE em todas as representacoes."""
    point_count = features.shape[0]
    sample_count = min(point_count, max_points)
    if sample_count < 3 or n_components not in (2, 3):
        raise ValueError("t-SNE exige pelo menos tres itens e n_components 2 ou 3.")
    rng = np.random.default_rng(random_state)
    indices = np.sort(rng.choice(point_count, size=sample_count, replace=False))
    sampled = features[indices]
    dimensions = min(TSNE_SVD_COMPONENTS, sampled.shape[1] - 1, sample_count - 1)
    if dimensions >= 1:
        reduced = TruncatedSVD(n_components=dimensions, random_state=random_state).fit_transform(sampled)
    else:
        reduced = sampled.toarray() if hasattr(sampled, "toarray") else np.asarray(sampled)
        dimensions = reduced.shape[1]
    coordinates = TSNE(
        n_components=n_components,
        perplexity=min(float(perplexity), (sample_count - 1) / 3),
        init="pca" if dimensions >= n_components else "random",
        learning_rate="auto", max_iter=max_iter, random_state=random_state,
        method="barnes_hut",
    ).fit_transform(reduced)
    return indices, coordinates, dimensions


def save_tsne_plot(coordinates, labels, run_id, output_path):
    """Salva um PNG t-SNE colorido pelos clusters, com o ru?do em cinza."""
    labels = np.asarray(labels)
    noise_mask = labels == -1
    cluster_ids = np.unique(labels[~noise_mask])
    if cluster_ids.size:
        palette = plt.get_cmap("tab20").colors
        cluster_cmap = ListedColormap([
            palette[index % len(palette)] for index in range(len(cluster_ids))
        ])
        cluster_codes = np.searchsorted(cluster_ids, labels[~noise_mask])
    else:
        cluster_cmap = None
        cluster_codes = np.empty(0, dtype=int)

    figure, axis = plt.subplots(figsize=(11, 8), constrained_layout=True)
    if noise_mask.any():
        axis.scatter(
            coordinates[noise_mask, 0], coordinates[noise_mask, 1],
            c="#b8b8b8", s=8, alpha=0.3, linewidths=0,
        )
    if cluster_ids.size:
        axis.scatter(
            coordinates[~noise_mask, 0], coordinates[~noise_mask, 1],
            c=cluster_codes, cmap=cluster_cmap, vmin=-0.5,
            vmax=len(cluster_ids) - 0.5, s=9, alpha=0.75, linewidths=0,
        )
    axis.set_title(
        f"t-SNE: {run_id}\n{len(cluster_ids)} clusters; "
        f"{int(noise_mask.sum()):,} descri??es como ru?do"
    )
    axis.set_xlabel("t-SNE 1")
    axis.set_ylabel("t-SNE 2")
    axis.text(
        0.01, 0.01,
        "Ru?do em cinza; as cores se repetem a cada 20 clusters.",
        transform=axis.transAxes, fontsize=8, color="#555555",
    )
    figure.savefig(output_path, dpi=160)
    plt.close(figure)


def save_tsne_3d_html(coordinates, labels, run_id, output_path):
    """Salva uma visualiza??o t-SNE 3D interativa e autocontida em HTML."""
    points = [
        {"x": float(x), "y": float(y), "z": float(z), "label": int(label)}
        for (x, y, z), label in zip(coordinates, labels)
    ]
    data_json = json.dumps(points, separators=(",", ":"))
    title = str(run_id).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    page = r"""<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>t-SNE 3D: __TITLE__</title>
<style>
html, body { margin: 0; height: 100%; background: #f7f8fa; color: #202124; font: 14px system-ui, sans-serif; }
main { display: flex; flex-direction: column; height: 100%; }
header { padding: 12px 18px; background: white; border-bottom: 1px solid #ddd; }
h1 { margin: 0 0 4px; font-size: 17px; }
p { margin: 0; color: #555; }
canvas { display: block; width: 100%; flex: 1; min-height: 300px; cursor: grab; }
canvas:active { cursor: grabbing; }
</style>
</head>
<body>
<main>
<header><h1>Proje??o t-SNE 3D: __TITLE__</h1><p>Arraste para girar; use a roda do mouse para aproximar. Ru?do em cinza.</p></header>
<canvas id="plot"></canvas>
</main>
<script>
const points = __POINTS__;
const canvas = document.getElementById("plot");
const ctx = canvas.getContext("2d");
let yaw = 0.65, pitch = -0.35, zoom = 1, dragging = false, lastX = 0, lastY = 0;
const colors = ["#3366cc", "#dc3912", "#ff9900", "#109618", "#990099", "#0099c6", "#dd4477", "#66aa00", "#b82e2e", "#316395", "#994499", "#22aa99", "#aaaa11", "#6633cc", "#e67300", "#8b0707", "#651067", "#329262", "#5574a6", "#3b3eac"];
const bounds = ["x", "y", "z"].map(key => {
  const values = points.map(point => point[key]);
  const low = Math.min(...values), high = Math.max(...values);
  return { low, span: Math.max(high - low, 1e-9) };
});
function resize() {
  const ratio = window.devicePixelRatio || 1;
  canvas.width = Math.max(1, Math.floor(canvas.clientWidth * ratio));
  canvas.height = Math.max(1, Math.floor(canvas.clientHeight * ratio));
  ctx.setTransform(ratio, 0, 0, ratio, 0, 0);
  draw();
}
function draw() {
  const width = canvas.clientWidth, height = canvas.clientHeight;
  ctx.clearRect(0, 0, width, height);
  const scale = Math.min(width, height) * 0.7 * zoom;
  const cy = Math.cos(yaw), sy = Math.sin(yaw), cp = Math.cos(pitch), sp = Math.sin(pitch);
  const projected = points.map(point => {
    const x = ((point.x - bounds[0].low) / bounds[0].span - 0.5) * 2;
    const y = ((point.y - bounds[1].low) / bounds[1].span - 0.5) * 2;
    const z = ((point.z - bounds[2].low) / bounds[2].span - 0.5) * 2;
    const rx = x * cy - z * sy, rz = x * sy + z * cy;
    const ry = y * cp - rz * sp, depth = y * sp + rz * cp;
    return { x: width / 2 + rx * scale / 2, y: height / 2 - ry * scale / 2, depth, label: point.label };
  }).sort((a, b) => a.depth - b.depth);
  for (const point of projected) {
    ctx.globalAlpha = point.label === -1 ? 0.24 : 0.78;
    ctx.fillStyle = point.label === -1 ? "#999999" : colors[Math.abs(point.label) % colors.length];
    ctx.beginPath();
    ctx.arc(point.x, point.y, point.label === -1 ? 2 : 3, 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.globalAlpha = 1;
}
canvas.addEventListener("pointerdown", event => { dragging = true; lastX = event.clientX; lastY = event.clientY; canvas.setPointerCapture(event.pointerId); });
canvas.addEventListener("pointerup", () => { dragging = false; });
canvas.addEventListener("pointermove", event => {
  if (!dragging) return;
  yaw += (event.clientX - lastX) * 0.008;
  pitch = Math.max(-1.5, Math.min(1.5, pitch + (event.clientY - lastY) * 0.008));
  lastX = event.clientX; lastY = event.clientY; draw();
});
canvas.addEventListener("wheel", event => { event.preventDefault(); zoom = Math.max(0.3, Math.min(5, zoom * (event.deltaY < 0 ? 1.1 : 0.9))); draw(); }, { passive: false });
window.addEventListener("resize", resize);
resize();
</script>
</body>
</html>"""
    page = page.replace("__TITLE__", title).replace("__POINTS__", data_json)
    output_path.write_text(page, encoding="utf-8")


def comparison_metadata(frame):
    """Registra controles comuns e a identidade exata da amostra de agrupamento."""
    sample = frame[[DESCRIPTION_NORMALIZED, FREQUENCY]].sort_values(DESCRIPTION_NORMALIZED).reset_index(drop=True)
    return {
        "dataset_name": DATASET_NAME,
        "training_description_count": len(sample),
        "training_sample_sha256": sha256(pd.util.hash_pandas_object(sample, index=False).values.tobytes()).hexdigest(),
        "max_descriptions": MAX_DESCRIPTIONS, "sample_seed": 42,
        "frequency_weighted": False,
        "silhouette_metric": "cosine", "silhouette_sample_size": SILHOUETTE_SAMPLE_SIZE,
        "metric_random_state": METRIC_RANDOM_STATE,
        "metric_sampling": "fixed rows, then exclude algorithmic noise",
        "min_cluster_for_ranking": MIN_CLUSTER_FOR_RANKING,
        "max_clusters_for_ranking": MAX_CLUSTERS_FOR_RANKING,
        "silhouette_weight": SILHOUETTE_WEIGHT, "noise_weight": NOISE_WEIGHT,
        "tsne": {
            "max_points": TSNE_MAX_POINTS, "perplexity": TSNE_PERPLEXITY,
            "max_iter": TSNE_MAX_ITER, "random_state": TSNE_RANDOM_STATE,
            "reduction": "TruncatedSVD", "svd_components": TSNE_SVD_COMPONENTS,
            "dimensions": [2, 3], "init": "pca", "learning_rate": "auto",
            "method": "barnes_hut",
        },
    }

## 3. Carregar e preparar dados

Origem: Parquet produzido pelos notebooks de preparacao de dados do projeto, com descricoes de supermercado, NCMs e duplicatas agregadas por descricao. A amostragem e feita uma vez por semente e reutilizada entre os analyzers daquela semente.

In [5]:
raw_items = pd.read_parquet(DATASET_PATH)
required_columns = {DESCRIPTION_NORMALIZED, FREQUENCY}
missing_columns = required_columns - set(raw_items.columns)
if missing_columns:
    raise ValueError(f"Colunas ausentes no dataset: {sorted(missing_columns)}")
base_items = prepare_items(raw_items)
logger.info("Descricoes disponiveis apos preparacao: %d", len(base_items))

2026-10-24 18:25:42,879 INFO Descricoes disponiveis apos preparacao: 146999

## 4. Vetorizar, ajustar DBSCAN e comparar parametros

Cada combinacao de semente e analyzer gera uma matriz TF-IDF propria. `metric="cosine"` permite trabalhar diretamente com a matriz esparsa. O ruido (`cluster = -1`) e excluido da silhouette e contabilizado separadamente; configuracoes com menos de dois clusters validos ficam sem silhouette. A matriz completa nao e convertida para densa.

Para visualizacao, uma amostra fixa de ate `TSNE_MAX_POINTS` descricoes e reduzida com TruncatedSVD e projetada uma vez por representacao. As coordenadas sao reutilizadas para salvar um PNG por combinacao de parametros.

A proje??o t-SNE 3D ? calculada separadamente e cada configura??o tamb?m ? salva como HTML interativo autocontido em `tsne_3d_html/`.

In [6]:
logger.info("Grade planejada: %d ajustes", len(SAMPLE_SEEDS) * len(ANALYZER_CONFIGS) * len(MIN_DF_VALUES) * len(EPS_VALUES) * len(MIN_SAMPLES_VALUES))

records = []
labels_by_run = {}
items_by_run = {}
matrices_by_representation = {}
items_by_seed = {}

for sample_seed in SAMPLE_SEEDS:
    sampled_items = base_items
    if MAX_DESCRIPTIONS is not None and len(base_items) > MAX_DESCRIPTIONS:
        sampled_items = base_items.sample(n=MAX_DESCRIPTIONS, random_state=sample_seed)
    sampled_items = sampled_items.sort_values(DESCRIPTION_NORMALIZED).reset_index(drop=True)
    items_by_seed[sample_seed] = sampled_items

    for representation, (analyzer, ngram_range) in ANALYZER_CONFIGS.items():
        for min_df in MIN_DF_VALUES:
            logger.info(
                "Vetorizando analyzer=%s, min_df=%d, seed=%d, descricoes=%d",
                analyzer, min_df, sample_seed, len(sampled_items),
            )
            vectorizer = TfidfVectorizer(
                analyzer=analyzer, ngram_range=ngram_range, min_df=min_df,
                max_features=MAX_FEATURES, max_df=MAX_DF, sublinear_tf=True, norm="l2", dtype=np.float64,
            )
            matrix = vectorizer.fit_transform(sampled_items[DESCRIPTION_NORMALIZED].astype(str))
            zero_vector_count = int((matrix.getnnz(axis=1) == 0).sum())
            # Mantem as matrizes esparsas para gerar as projecoes em uma celula separada.
            matrices_by_representation[(sample_seed, representation, min_df)] = matrix
            logger.info(
                "Analyzer=%s min_df=%d seed=%d: %d termos, %d vetores zerados",
                analyzer, min_df, sample_seed, matrix.shape[1], zero_vector_count,
            )

            for eps in EPS_VALUES:
                for min_samples in MIN_SAMPLES_VALUES:
                    run_id = f"seed{sample_seed}_{representation}_min_df{min_df}_eps{eps:g}_min_samples{min_samples}"
                    logger.info("Ajustando DBSCAN %s", run_id)
                    model = DBSCAN(
                        eps=eps, min_samples=min_samples, metric="cosine",
                        algorithm="brute", n_jobs=DBSCAN_N_JOBS,
                    )
                    sample_weight = (
                        sampled_items[FREQUENCY].to_numpy(dtype=float)
                        if CONSIDER_FREQUENCY_IN_CLUSTERING else None
                    )
                    with config_context(working_memory=PAIRWISE_WORKING_MEMORY_MIB):
                        model.fit(matrix, sample_weight=sample_weight)
                    labels = model.labels_
                    with config_context(working_memory=PAIRWISE_WORKING_MEMORY_MIB):
                        metrics = score_configuration(
                            matrix, labels, SILHOUETTE_SAMPLE_SIZE,
                            METRIC_RANDOM_STATE,
                        )
                    records.append({
                        "run_id": run_id, "sample_seed": sample_seed,
                        "representation": representation, "analyzer": analyzer,
                        "ngram_range": str(ngram_range), "min_df": min_df,
                        "feature_count": matrix.shape[1], "zero_vector_count": zero_vector_count,
                        "eps": eps, "min_samples": min_samples,
                        "frequency_weighted": CONSIDER_FREQUENCY_IN_CLUSTERING, **metrics,
                    })
                    labels_by_run[run_id] = labels
                    items_by_run[run_id] = sampled_items

# Mantem todas as metricas para persistencia; o ranking e calculado em uma celula separada.
results = pd.DataFrame(records)

2026-10-24 18:25:42,892 INFO Grade planejada: 3520 ajustes

2026-10-24 18:25:42,915 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-24 18:25:43,567 INFO Analyzer=char_wb min_df=1 seed=42: 36881 termos, 0 vetores zerados

2026-10-24 18:25:43,567 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.01_min_samples2

2026-10-24 18:25:50,213 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.01_min_samples3

2026-10-24 18:25:56,605 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.01_min_samples5

2026-10-24 18:26:02,992 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.01_min_samples7

2026-10-24 18:26:09,412 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.01_min_samples10

2026-10-24 18:26:15,792 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.01_min_samples20

2026-10-24 18:26:22,276 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.01_min_samples30

2026-10-24 18:26:28,781 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.01_min_samples100

2026-10-24 18:26:35,262 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.02_min_samples2

2026-10-24 18:26:41,725 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.02_min_samples3

2026-10-24 18:26:48,188 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.02_min_samples5

2026-10-24 18:26:54,697 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.02_min_samples7

2026-10-24 18:27:01,213 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.02_min_samples10

2026-10-24 18:27:08,496 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.02_min_samples20

2026-10-24 18:27:16,115 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.02_min_samples30

2026-10-24 18:27:23,675 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.02_min_samples100

2026-10-24 18:27:31,358 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.025_min_samples2

2026-10-24 18:27:38,610 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.025_min_samples3

2026-10-24 18:27:46,361 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.025_min_samples5

2026-10-24 18:27:54,897 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.025_min_samples7

2026-10-24 18:28:02,793 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.025_min_samples10

2026-10-24 18:28:10,069 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.025_min_samples20

2026-10-24 18:28:17,142 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.025_min_samples30

2026-10-24 18:28:23,827 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.025_min_samples100

2026-10-24 18:28:30,594 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.03_min_samples2

2026-10-24 18:28:37,109 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.03_min_samples3

2026-10-24 18:28:43,701 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.03_min_samples5

2026-10-24 18:28:50,397 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.03_min_samples7

2026-10-24 18:28:56,892 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.03_min_samples10

2026-10-24 18:29:03,359 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.03_min_samples20

2026-10-24 18:29:09,848 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.03_min_samples30

2026-10-24 18:29:17,259 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.03_min_samples100

2026-10-24 18:29:25,520 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.035_min_samples2

2026-10-24 18:29:37,546 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.035_min_samples3

2026-10-24 18:29:45,926 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.035_min_samples5

2026-10-24 18:29:53,574 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.035_min_samples7

2026-10-24 18:30:01,834 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.035_min_samples10

2026-10-24 18:30:09,692 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.035_min_samples20

2026-10-24 18:30:17,399 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.035_min_samples30

2026-10-24 18:30:24,418 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.035_min_samples100

2026-10-24 18:30:30,983 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.04_min_samples2

2026-10-24 18:30:37,566 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.04_min_samples3

2026-10-24 18:30:44,059 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.04_min_samples5

2026-10-24 18:30:50,492 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.04_min_samples7

2026-10-24 18:30:57,081 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.04_min_samples10

2026-10-24 18:31:03,550 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.04_min_samples20

2026-10-24 18:31:10,088 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.04_min_samples30

2026-10-24 18:31:16,590 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.04_min_samples100

2026-10-24 18:31:23,052 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.05_min_samples2

2026-10-24 18:31:29,693 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.05_min_samples3

2026-10-24 18:31:37,082 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.05_min_samples5

2026-10-24 18:31:44,814 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.05_min_samples7

2026-10-24 18:31:52,709 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.05_min_samples10

2026-10-24 18:32:00,141 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.05_min_samples20

2026-10-24 18:32:07,458 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.05_min_samples30

2026-10-24 18:32:14,924 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.05_min_samples100

2026-10-24 18:32:21,776 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.07_min_samples2

2026-10-24 18:32:28,903 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.07_min_samples3

2026-10-24 18:32:35,509 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.07_min_samples5

2026-10-24 18:32:41,958 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.07_min_samples7

2026-10-24 18:32:48,408 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.07_min_samples10

2026-10-24 18:32:54,899 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.07_min_samples20

2026-10-24 18:33:01,348 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.07_min_samples30

2026-10-24 18:33:07,827 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.07_min_samples100

2026-10-24 18:33:14,329 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.1_min_samples2

2026-10-24 18:33:20,812 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.1_min_samples3

2026-10-24 18:33:27,293 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.1_min_samples5

2026-10-24 18:33:33,790 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.1_min_samples7

2026-10-24 18:33:40,293 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.1_min_samples10

2026-10-24 18:33:46,786 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.1_min_samples20

2026-10-24 18:33:53,764 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.1_min_samples30

2026-10-24 18:34:01,645 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.1_min_samples100

2026-10-24 18:34:08,982 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.5_min_samples2

2026-10-24 18:34:21,485 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.5_min_samples3

2026-10-24 18:34:33,626 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.5_min_samples5

2026-10-24 18:34:45,580 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.5_min_samples7

2026-10-24 18:34:55,843 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.5_min_samples10

2026-10-24 18:35:05,183 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.5_min_samples20

2026-10-24 18:35:13,169 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.5_min_samples30

2026-10-24 18:35:20,360 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps0.5_min_samples100

2026-10-24 18:35:26,849 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps1_min_samples2

2026-10-24 18:35:37,517 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps1_min_samples3

2026-10-24 18:35:47,584 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps1_min_samples5

2026-10-24 18:35:57,227 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps1_min_samples7

2026-10-24 18:36:06,911 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps1_min_samples10

2026-10-24 18:36:17,425 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps1_min_samples20

2026-10-24 18:36:28,060 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps1_min_samples30

2026-10-24 18:36:38,860 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df1_eps1_min_samples100

2026-10-24 18:36:50,093 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-24 18:36:50,911 INFO Analyzer=char_wb min_df=2 seed=42: 23288 termos, 0 vetores zerados

2026-10-24 18:36:50,911 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.01_min_samples2

2026-10-24 18:36:58,332 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.01_min_samples3

2026-10-24 18:37:07,451 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.01_min_samples5

2026-10-24 18:37:14,695 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.01_min_samples7

2026-10-24 18:37:21,494 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.01_min_samples10

2026-10-24 18:37:28,566 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.01_min_samples20

2026-10-24 18:37:35,127 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.01_min_samples30

2026-10-24 18:37:41,876 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.01_min_samples100

2026-10-24 18:37:48,593 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.02_min_samples2

2026-10-24 18:37:54,891 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.02_min_samples3

2026-10-24 18:38:01,287 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.02_min_samples5

2026-10-24 18:38:07,660 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.02_min_samples7

2026-10-24 18:38:14,593 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.02_min_samples10

2026-10-24 18:38:21,151 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.02_min_samples20

2026-10-24 18:38:27,648 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.02_min_samples30

2026-10-24 18:38:34,196 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.02_min_samples100

2026-10-24 18:38:40,729 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.025_min_samples2

2026-10-24 18:38:47,213 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.025_min_samples3

2026-10-24 18:38:53,914 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.025_min_samples5

2026-10-24 18:39:00,867 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.025_min_samples7

2026-10-24 18:39:08,126 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.025_min_samples10

2026-10-24 18:39:15,860 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.025_min_samples20

2026-10-24 18:39:23,556 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.025_min_samples30

2026-10-24 18:39:32,000 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.025_min_samples100

2026-10-24 18:39:39,360 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.03_min_samples2

2026-10-24 18:39:46,911 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.03_min_samples3

2026-10-24 18:39:54,327 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.03_min_samples5

2026-10-24 18:40:01,694 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.03_min_samples7

2026-10-24 18:40:08,881 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.03_min_samples10

2026-10-24 18:40:15,958 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.03_min_samples20

2026-10-24 18:40:22,895 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.03_min_samples30

2026-10-24 18:40:29,358 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.03_min_samples100

2026-10-24 18:40:35,821 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.035_min_samples2

2026-10-24 18:40:42,346 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.035_min_samples3

2026-10-24 18:40:48,743 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.035_min_samples5

2026-10-24 18:40:55,301 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.035_min_samples7

2026-10-24 18:41:01,897 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.035_min_samples10

2026-10-24 18:41:08,639 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.035_min_samples20

2026-10-24 18:41:15,488 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.035_min_samples30

2026-10-24 18:41:22,490 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.035_min_samples100

2026-10-24 18:41:29,844 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.04_min_samples2

2026-10-24 18:41:37,411 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.04_min_samples3

2026-10-24 18:41:45,023 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.04_min_samples5

2026-10-24 18:41:52,987 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.04_min_samples7

2026-10-24 18:42:00,458 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.04_min_samples10

2026-10-24 18:42:07,697 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.04_min_samples20

2026-10-24 18:42:15,596 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.04_min_samples30

2026-10-24 18:42:22,811 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.04_min_samples100

2026-10-24 18:42:29,527 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.05_min_samples2

2026-10-24 18:42:36,193 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.05_min_samples3

2026-10-24 18:42:42,690 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.05_min_samples5

2026-10-24 18:42:49,170 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.05_min_samples7

2026-10-24 18:42:55,628 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.05_min_samples10

2026-10-24 18:43:02,116 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.05_min_samples20

2026-10-24 18:43:08,620 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.05_min_samples30

2026-10-24 18:43:15,061 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.05_min_samples100

2026-10-24 18:43:21,583 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.07_min_samples2

2026-10-24 18:43:28,094 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.07_min_samples3

2026-10-24 18:43:34,584 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.07_min_samples5

2026-10-24 18:43:41,161 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.07_min_samples7

2026-10-24 18:43:48,561 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.07_min_samples10

2026-10-24 18:43:55,959 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.07_min_samples20

2026-10-24 18:44:03,291 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.07_min_samples30

2026-10-24 18:44:11,128 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.07_min_samples100

2026-10-24 18:44:18,589 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.1_min_samples2

2026-10-24 18:44:25,917 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.1_min_samples3

2026-10-24 18:44:33,448 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.1_min_samples5

2026-10-24 18:44:40,328 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.1_min_samples7

2026-10-24 18:44:47,050 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.1_min_samples10

2026-10-24 18:44:53,723 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.1_min_samples20

2026-10-24 18:45:00,317 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.1_min_samples30

2026-10-24 18:45:06,756 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.1_min_samples100

2026-10-24 18:45:13,154 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.5_min_samples2

2026-10-24 18:45:24,544 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.5_min_samples3

2026-10-24 18:45:35,587 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.5_min_samples5

2026-10-24 18:45:46,028 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.5_min_samples7

2026-10-24 18:45:56,020 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.5_min_samples10

2026-10-24 18:46:05,731 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.5_min_samples20

2026-10-24 18:46:14,933 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.5_min_samples30

2026-10-24 18:46:23,128 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps0.5_min_samples100

2026-10-24 18:46:30,880 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps1_min_samples2

2026-10-24 18:46:41,865 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps1_min_samples3

2026-10-24 18:46:53,053 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps1_min_samples5

2026-10-24 18:47:03,019 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps1_min_samples7

2026-10-24 18:47:12,795 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps1_min_samples10

2026-10-24 18:47:22,590 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps1_min_samples20

2026-10-24 18:47:32,254 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps1_min_samples30

2026-10-24 18:47:42,023 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df2_eps1_min_samples100

2026-10-24 18:47:51,902 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-24 18:47:52,511 INFO Analyzer=char_wb min_df=5 seed=42: 14247 termos, 0 vetores zerados

2026-10-24 18:47:52,511 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.01_min_samples2

2026-10-24 18:47:58,961 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.01_min_samples3

2026-10-24 18:48:05,412 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.01_min_samples5

2026-10-24 18:48:11,862 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.01_min_samples7

2026-10-24 18:48:19,028 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.01_min_samples10

2026-10-24 18:48:26,383 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.01_min_samples20

2026-10-24 18:48:33,696 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.01_min_samples30

2026-10-24 18:48:41,199 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.01_min_samples100

2026-10-24 18:48:48,836 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.02_min_samples2

2026-10-24 18:48:56,141 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.02_min_samples3

2026-10-24 18:49:03,096 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.02_min_samples5

2026-10-24 18:49:09,853 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.02_min_samples7

2026-10-24 18:49:16,528 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.02_min_samples10

2026-10-24 18:49:22,890 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.02_min_samples20

2026-10-24 18:49:29,220 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.02_min_samples30

2026-10-24 18:49:35,737 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.02_min_samples100

2026-10-24 18:49:42,204 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.025_min_samples2

2026-10-24 18:49:48,629 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.025_min_samples3

2026-10-24 18:49:55,105 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.025_min_samples5

2026-10-24 18:50:01,605 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.025_min_samples7

2026-10-24 18:50:08,354 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.025_min_samples10

2026-10-24 18:50:15,416 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.025_min_samples20

2026-10-24 18:50:23,217 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.025_min_samples30

2026-10-24 18:50:30,495 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.025_min_samples100

2026-10-24 18:50:37,795 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.03_min_samples2

2026-10-24 18:50:45,574 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.03_min_samples3

2026-10-24 18:50:52,849 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.03_min_samples5

2026-10-24 18:50:59,895 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.03_min_samples7

2026-10-24 18:51:06,895 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.03_min_samples10

2026-10-24 18:51:13,507 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.03_min_samples20

2026-10-24 18:51:20,082 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.03_min_samples30

2026-10-24 18:51:26,412 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.03_min_samples100

2026-10-24 18:51:32,729 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.035_min_samples2

2026-10-24 18:51:39,164 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.035_min_samples3

2026-10-24 18:51:45,629 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.035_min_samples5

2026-10-24 18:51:52,095 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.035_min_samples7

2026-10-24 18:51:58,529 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.035_min_samples10

2026-10-24 18:52:04,985 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.035_min_samples20

2026-10-24 18:52:11,459 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.035_min_samples30

2026-10-24 18:52:18,111 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.035_min_samples100

2026-10-24 18:52:25,062 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.04_min_samples2

2026-10-24 18:52:32,318 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.04_min_samples3

2026-10-24 18:52:40,145 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.04_min_samples5

2026-10-24 18:52:47,729 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.04_min_samples7

2026-10-24 18:52:55,088 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.04_min_samples10

2026-10-24 18:53:02,597 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.04_min_samples20

2026-10-24 18:53:09,962 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.04_min_samples30

2026-10-24 18:53:17,879 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.04_min_samples100

2026-10-24 18:53:24,993 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.05_min_samples2

2026-10-24 18:53:31,683 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.05_min_samples3

2026-10-24 18:53:38,498 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.05_min_samples5

2026-10-24 18:53:44,929 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.05_min_samples7

2026-10-24 18:53:51,413 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.05_min_samples10

2026-10-24 18:53:57,830 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.05_min_samples20

2026-10-24 18:54:04,300 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.05_min_samples30

2026-10-24 18:54:10,760 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.05_min_samples100

2026-10-24 18:54:17,196 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.07_min_samples2

2026-10-24 18:54:23,662 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.07_min_samples3

2026-10-24 18:54:30,096 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.07_min_samples5

2026-10-24 18:54:36,557 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.07_min_samples7

2026-10-24 18:54:42,996 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.07_min_samples10

2026-10-24 18:54:50,002 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.07_min_samples20

2026-10-24 18:54:58,963 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.07_min_samples30

2026-10-24 18:55:06,396 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.07_min_samples100

2026-10-24 18:55:13,768 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.1_min_samples2

2026-10-24 18:55:21,099 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.1_min_samples3

2026-10-24 18:55:28,363 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.1_min_samples5

2026-10-24 18:55:35,796 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.1_min_samples7

2026-10-24 18:55:43,450 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.1_min_samples10

2026-10-24 18:55:50,669 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.1_min_samples20

2026-10-24 18:55:57,464 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.1_min_samples30

2026-10-24 18:56:03,929 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.1_min_samples100

2026-10-24 18:56:10,285 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.5_min_samples2

2026-10-24 18:56:21,863 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.5_min_samples3

2026-10-24 18:56:33,163 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.5_min_samples5

2026-10-24 18:56:43,865 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.5_min_samples7

2026-10-24 18:56:54,082 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.5_min_samples10

2026-10-24 18:57:03,731 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.5_min_samples20

2026-10-24 18:57:12,025 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.5_min_samples30

2026-10-24 18:57:19,955 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps0.5_min_samples100

2026-10-24 18:57:27,063 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps1_min_samples2

2026-10-24 18:57:38,342 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps1_min_samples3

2026-10-24 18:57:49,607 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps1_min_samples5

2026-10-24 18:58:00,650 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps1_min_samples7

2026-10-24 18:58:12,020 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps1_min_samples10

2026-10-24 18:58:22,156 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps1_min_samples20

2026-10-24 18:58:32,035 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps1_min_samples30

2026-10-24 18:58:42,012 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df5_eps1_min_samples100

2026-10-24 18:58:51,996 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-24 18:58:52,613 INFO Analyzer=char_wb min_df=10 seed=42: 10098 termos, 0 vetores zerados

2026-10-24 18:58:52,613 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.01_min_samples2

2026-10-24 18:58:59,057 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.01_min_samples3

2026-10-24 18:59:05,525 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.01_min_samples5

2026-10-24 18:59:11,941 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.01_min_samples7

2026-10-24 18:59:18,373 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.01_min_samples10

2026-10-24 18:59:24,817 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.01_min_samples20

2026-10-24 18:59:31,294 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.01_min_samples30

2026-10-24 18:59:38,813 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.01_min_samples100

2026-10-24 18:59:46,792 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.02_min_samples2

2026-10-24 18:59:54,084 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.02_min_samples3

2026-10-24 19:00:01,330 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.02_min_samples5

2026-10-24 19:00:08,615 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.02_min_samples7

2026-10-24 19:00:16,214 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.02_min_samples10

2026-10-24 19:00:24,130 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.02_min_samples20

2026-10-24 19:00:30,997 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.02_min_samples30

2026-10-24 19:00:37,547 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.02_min_samples100

2026-10-24 19:00:44,430 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.025_min_samples2

2026-10-24 19:00:50,767 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.025_min_samples3

2026-10-24 19:00:57,197 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.025_min_samples5

2026-10-24 19:01:03,564 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.025_min_samples7

2026-10-24 19:01:09,947 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.025_min_samples10

2026-10-24 19:01:16,363 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.025_min_samples20

2026-10-24 19:01:22,772 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.025_min_samples30

2026-10-24 19:01:29,217 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.025_min_samples100

2026-10-24 19:01:35,671 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.03_min_samples2

2026-10-24 19:01:42,081 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.03_min_samples3

2026-10-24 19:01:49,145 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.03_min_samples5

2026-10-24 19:01:56,798 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.03_min_samples7

2026-10-24 19:02:04,110 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.03_min_samples10

2026-10-24 19:02:11,463 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.03_min_samples20

2026-10-24 19:02:18,830 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.03_min_samples30

2026-10-24 19:02:26,097 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.03_min_samples100

2026-10-24 19:02:33,714 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.035_min_samples2

2026-10-24 19:02:41,097 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.035_min_samples3

2026-10-24 19:02:48,380 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.035_min_samples5

2026-10-24 19:02:55,535 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.035_min_samples7

2026-10-24 19:03:02,030 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.035_min_samples10

2026-10-24 19:03:08,393 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.035_min_samples20

2026-10-24 19:03:14,732 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.035_min_samples30

2026-10-24 19:03:21,131 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.035_min_samples100

2026-10-24 19:03:27,514 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.04_min_samples2

2026-10-24 19:03:33,921 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.04_min_samples3

2026-10-24 19:03:40,397 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.04_min_samples5

2026-10-24 19:03:46,797 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.04_min_samples7

2026-10-24 19:03:53,193 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.04_min_samples10

2026-10-24 19:03:59,623 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.04_min_samples20

2026-10-24 19:04:06,047 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.04_min_samples30

2026-10-24 19:04:12,595 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.04_min_samples100

2026-10-24 19:04:19,479 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.05_min_samples2

2026-10-24 19:04:27,249 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.05_min_samples3

2026-10-24 19:04:34,533 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.05_min_samples5

2026-10-24 19:04:41,866 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.05_min_samples7

2026-10-24 19:04:49,523 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.05_min_samples10

2026-10-24 19:04:56,832 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.05_min_samples20

2026-10-24 19:05:04,115 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.05_min_samples30

2026-10-24 19:05:11,715 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.05_min_samples100

2026-10-24 19:05:18,631 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.07_min_samples2

2026-10-24 19:05:25,298 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.07_min_samples3

2026-10-24 19:05:31,764 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.07_min_samples5

2026-10-24 19:05:38,252 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.07_min_samples7

2026-10-24 19:05:44,811 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.07_min_samples10

2026-10-24 19:05:51,183 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.07_min_samples20

2026-10-24 19:05:57,710 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.07_min_samples30

2026-10-24 19:06:04,104 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.07_min_samples100

2026-10-24 19:06:10,474 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.1_min_samples2

2026-10-24 19:06:16,981 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.1_min_samples3

2026-10-24 19:06:23,729 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.1_min_samples5

2026-10-24 19:06:30,549 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.1_min_samples7

2026-10-24 19:06:37,632 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.1_min_samples10

2026-10-24 19:06:45,971 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.1_min_samples20

2026-10-24 19:06:53,251 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.1_min_samples30

2026-10-24 19:07:00,699 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.1_min_samples100

2026-10-24 19:07:07,914 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.5_min_samples2

2026-10-24 19:07:20,967 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.5_min_samples3

2026-10-24 19:07:33,207 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.5_min_samples5

2026-10-24 19:07:44,170 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.5_min_samples7

2026-10-24 19:07:54,781 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.5_min_samples10

2026-10-24 19:08:04,809 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.5_min_samples20

2026-10-24 19:08:13,384 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.5_min_samples30

2026-10-24 19:08:20,997 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps0.5_min_samples100

2026-10-24 19:08:27,500 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps1_min_samples2

2026-10-24 19:08:37,613 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps1_min_samples3

2026-10-24 19:08:47,642 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps1_min_samples5

2026-10-24 19:08:57,698 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps1_min_samples7

2026-10-24 19:09:08,382 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps1_min_samples10

2026-10-24 19:09:20,003 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps1_min_samples20

2026-10-24 19:09:31,368 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps1_min_samples30

2026-10-24 19:09:43,133 INFO Ajustando DBSCAN seed42_char_wb_2_4_min_df10_eps1_min_samples100

2026-10-24 19:09:54,782 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-24 19:09:56,087 INFO Analyzer=char_wb min_df=1 seed=42: 100000 termos, 0 vetores zerados

2026-10-24 19:09:56,087 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.01_min_samples2

2026-10-24 19:10:03,467 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.01_min_samples3

2026-10-24 19:10:10,819 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.01_min_samples5

2026-10-24 19:10:18,081 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.01_min_samples7

2026-10-24 19:10:25,338 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.01_min_samples10

2026-10-24 19:10:32,633 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.01_min_samples20

2026-10-24 19:10:39,992 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.01_min_samples30

2026-10-24 19:10:47,415 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.01_min_samples100

2026-10-24 19:10:54,815 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.02_min_samples2

2026-10-24 19:11:02,243 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.02_min_samples3

2026-10-24 19:11:09,657 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.02_min_samples5

2026-10-24 19:11:17,010 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.02_min_samples7

2026-10-24 19:11:24,703 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.02_min_samples10

2026-10-24 19:11:32,804 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.02_min_samples20

2026-10-24 19:11:41,415 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.02_min_samples30

2026-10-24 19:11:50,031 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.02_min_samples100

2026-10-24 19:11:58,548 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.025_min_samples2

2026-10-24 19:12:07,180 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.025_min_samples3

2026-10-24 19:12:15,584 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.025_min_samples5

2026-10-24 19:12:24,106 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.025_min_samples7

2026-10-24 19:12:31,915 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.025_min_samples10

2026-10-24 19:12:39,482 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.025_min_samples20

2026-10-24 19:12:46,915 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.025_min_samples30

2026-10-24 19:12:54,348 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.025_min_samples100

2026-10-24 19:13:01,673 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.03_min_samples2

2026-10-24 19:13:09,015 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.03_min_samples3

2026-10-24 19:13:16,337 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.03_min_samples5

2026-10-24 19:13:23,693 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.03_min_samples7

2026-10-24 19:13:31,044 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.03_min_samples10

2026-10-24 19:13:38,442 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.03_min_samples20

2026-10-24 19:13:45,784 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.03_min_samples30

2026-10-24 19:13:53,172 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.03_min_samples100

2026-10-24 19:14:00,869 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.035_min_samples2

2026-10-24 19:14:08,968 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.035_min_samples3

2026-10-24 19:14:17,417 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.035_min_samples5

2026-10-24 19:14:26,221 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.035_min_samples7

2026-10-24 19:14:34,427 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.035_min_samples10

2026-10-24 19:14:42,828 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.035_min_samples20

2026-10-24 19:14:51,066 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.035_min_samples30

2026-10-24 19:14:59,112 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.035_min_samples100

2026-10-24 19:15:06,649 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.04_min_samples2

2026-10-24 19:15:15,453 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.04_min_samples3

2026-10-24 19:15:23,284 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.04_min_samples5

2026-10-24 19:15:30,486 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.04_min_samples7

2026-10-24 19:15:37,828 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.04_min_samples10

2026-10-24 19:15:45,149 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.04_min_samples20

2026-10-24 19:15:52,507 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.04_min_samples30

2026-10-24 19:15:59,904 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.04_min_samples100

2026-10-24 19:16:07,244 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.05_min_samples2

2026-10-24 19:16:14,608 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.05_min_samples3

2026-10-24 19:16:21,957 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.05_min_samples5

2026-10-24 19:16:29,266 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.05_min_samples7

2026-10-24 19:16:36,661 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.05_min_samples10

2026-10-24 19:16:45,425 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.05_min_samples20

2026-10-24 19:16:53,816 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.05_min_samples30

2026-10-24 19:17:01,911 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.05_min_samples100

2026-10-24 19:17:09,738 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.07_min_samples2

2026-10-24 19:17:17,404 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.07_min_samples3

2026-10-24 19:17:24,755 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.07_min_samples5

2026-10-24 19:17:32,171 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.07_min_samples7

2026-10-24 19:17:39,504 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.07_min_samples10

2026-10-24 19:17:46,793 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.07_min_samples20

2026-10-24 19:17:54,164 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.07_min_samples30

2026-10-24 19:18:01,521 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.07_min_samples100

2026-10-24 19:18:08,863 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.1_min_samples2

2026-10-24 19:18:16,387 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.1_min_samples3

2026-10-24 19:18:23,743 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.1_min_samples5

2026-10-24 19:18:31,083 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.1_min_samples7

2026-10-24 19:18:38,523 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.1_min_samples10

2026-10-24 19:18:45,850 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.1_min_samples20

2026-10-24 19:18:53,205 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.1_min_samples30

2026-10-24 19:19:00,535 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.1_min_samples100

2026-10-24 19:19:07,887 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.5_min_samples2

2026-10-24 19:19:21,868 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.5_min_samples3

2026-10-24 19:19:36,019 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.5_min_samples5

2026-10-24 19:19:50,489 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.5_min_samples7

2026-10-24 19:20:02,545 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.5_min_samples10

2026-10-24 19:20:13,417 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.5_min_samples20

2026-10-24 19:20:22,636 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.5_min_samples30

2026-10-24 19:20:30,923 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps0.5_min_samples100

2026-10-24 19:20:38,284 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps1_min_samples2

2026-10-24 19:20:49,576 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps1_min_samples3

2026-10-24 19:21:00,869 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps1_min_samples5

2026-10-24 19:21:12,175 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps1_min_samples7

2026-10-24 19:21:23,515 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps1_min_samples10

2026-10-24 19:21:34,958 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps1_min_samples20

2026-10-24 19:21:46,438 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps1_min_samples30

2026-10-24 19:21:57,917 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df1_eps1_min_samples100

2026-10-24 19:22:09,513 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-24 19:22:10,777 INFO Analyzer=char_wb min_df=2 seed=42: 90460 termos, 0 vetores zerados

2026-10-24 19:22:10,778 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.01_min_samples2

2026-10-24 19:22:18,056 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.01_min_samples3

2026-10-24 19:22:25,376 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.01_min_samples5

2026-10-24 19:22:32,750 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.01_min_samples7

2026-10-24 19:22:40,094 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.01_min_samples10

2026-10-24 19:22:47,764 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.01_min_samples20

2026-10-24 19:22:56,194 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.01_min_samples30

2026-10-24 19:23:04,188 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.01_min_samples100

2026-10-24 19:23:12,233 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.02_min_samples2

2026-10-24 19:23:19,815 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.02_min_samples3

2026-10-24 19:23:27,151 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.02_min_samples5

2026-10-24 19:23:34,408 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.02_min_samples7

2026-10-24 19:23:41,817 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.02_min_samples10

2026-10-24 19:23:49,166 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.02_min_samples20

2026-10-24 19:23:56,488 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.02_min_samples30

2026-10-24 19:24:03,832 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.02_min_samples100

2026-10-24 19:24:11,173 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.025_min_samples2

2026-10-24 19:24:18,503 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.025_min_samples3

2026-10-24 19:24:25,900 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.025_min_samples5

2026-10-24 19:24:33,265 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.025_min_samples7

2026-10-24 19:24:40,665 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.025_min_samples10

2026-10-24 19:24:47,983 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.025_min_samples20

2026-10-24 19:24:55,775 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.025_min_samples30

2026-10-24 19:25:03,837 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.025_min_samples100

2026-10-24 19:25:12,273 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.03_min_samples2

2026-10-24 19:25:20,236 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.03_min_samples3

2026-10-24 19:25:27,867 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.03_min_samples5

2026-10-24 19:25:35,173 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.03_min_samples7

2026-10-24 19:25:42,550 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.03_min_samples10

2026-10-24 19:25:50,013 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.03_min_samples20

2026-10-24 19:25:57,355 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.03_min_samples30

2026-10-24 19:26:04,687 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.03_min_samples100

2026-10-24 19:26:12,013 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.035_min_samples2

2026-10-24 19:26:19,364 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.035_min_samples3

2026-10-24 19:26:26,679 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.035_min_samples5

2026-10-24 19:26:34,048 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.035_min_samples7

2026-10-24 19:26:41,459 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.035_min_samples10

2026-10-24 19:26:48,830 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.035_min_samples20

2026-10-24 19:26:56,176 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.035_min_samples30

2026-10-24 19:27:03,480 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.035_min_samples100

2026-10-24 19:27:10,826 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.04_min_samples2

2026-10-24 19:27:18,861 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.04_min_samples3

2026-10-24 19:27:26,981 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.04_min_samples5

2026-10-24 19:27:35,437 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.04_min_samples7

2026-10-24 19:27:43,720 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.04_min_samples10

2026-10-24 19:27:51,717 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.04_min_samples20

2026-10-24 19:27:59,383 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.04_min_samples30

2026-10-24 19:28:06,610 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.04_min_samples100

2026-10-24 19:28:13,874 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.05_min_samples2

2026-10-24 19:28:21,378 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.05_min_samples3

2026-10-24 19:28:28,715 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.05_min_samples5

2026-10-24 19:28:36,014 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.05_min_samples7

2026-10-24 19:28:43,332 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.05_min_samples10

2026-10-24 19:28:50,618 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.05_min_samples20

2026-10-24 19:28:57,965 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.05_min_samples30

2026-10-24 19:29:05,388 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.05_min_samples100

2026-10-24 19:29:12,722 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.07_min_samples2

2026-10-24 19:29:20,162 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.07_min_samples3

2026-10-24 19:29:27,484 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.07_min_samples5

2026-10-24 19:29:34,858 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.07_min_samples7

2026-10-24 19:29:42,251 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.07_min_samples10

2026-10-24 19:29:49,653 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.07_min_samples20

2026-10-24 19:29:57,041 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.07_min_samples30

2026-10-24 19:30:04,422 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.07_min_samples100

2026-10-24 19:30:11,818 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.1_min_samples2

2026-10-24 19:30:19,284 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.1_min_samples3

2026-10-24 19:30:27,151 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.1_min_samples5

2026-10-24 19:30:35,667 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.1_min_samples7

2026-10-24 19:30:44,070 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.1_min_samples10

2026-10-24 19:30:51,918 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.1_min_samples20

2026-10-24 19:30:59,874 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.1_min_samples30

2026-10-24 19:31:07,815 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.1_min_samples100

2026-10-24 19:31:15,384 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.5_min_samples2

2026-10-24 19:31:29,292 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.5_min_samples3

2026-10-24 19:31:42,308 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.5_min_samples5

2026-10-24 19:31:54,511 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.5_min_samples7

2026-10-24 19:32:06,242 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.5_min_samples10

2026-10-24 19:32:17,221 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.5_min_samples20

2026-10-24 19:32:26,677 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.5_min_samples30

2026-10-24 19:32:35,179 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps0.5_min_samples100

2026-10-24 19:32:42,605 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps1_min_samples2

2026-10-24 19:32:54,248 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps1_min_samples3

2026-10-24 19:33:05,953 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps1_min_samples5

2026-10-24 19:33:17,573 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps1_min_samples7

2026-10-24 19:33:29,876 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps1_min_samples10

2026-10-24 19:33:43,482 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps1_min_samples20

2026-10-24 19:33:56,120 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps1_min_samples30

2026-10-24 19:34:07,746 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df2_eps1_min_samples100

2026-10-24 19:34:19,518 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-24 19:34:20,772 INFO Analyzer=char_wb min_df=5 seed=42: 45657 termos, 0 vetores zerados

2026-10-24 19:34:20,772 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.01_min_samples2

2026-10-24 19:34:28,011 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.01_min_samples3

2026-10-24 19:34:35,252 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.01_min_samples5

2026-10-24 19:34:42,470 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.01_min_samples7

2026-10-24 19:34:49,692 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.01_min_samples10

2026-10-24 19:34:56,890 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.01_min_samples20

2026-10-24 19:35:04,101 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.01_min_samples30

2026-10-24 19:35:11,380 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.01_min_samples100

2026-10-24 19:35:18,589 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.02_min_samples2

2026-10-24 19:35:25,847 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.02_min_samples3

2026-10-24 19:35:33,054 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.02_min_samples5

2026-10-24 19:35:40,338 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.02_min_samples7

2026-10-24 19:35:47,627 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.02_min_samples10

2026-10-24 19:35:54,862 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.02_min_samples20

2026-10-24 19:36:02,131 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.02_min_samples30

2026-10-24 19:36:09,402 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.02_min_samples100

2026-10-24 19:36:16,589 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.025_min_samples2

2026-10-24 19:36:23,873 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.025_min_samples3

2026-10-24 19:36:31,153 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.025_min_samples5

2026-10-24 19:36:38,961 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.025_min_samples7

2026-10-24 19:36:47,698 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.025_min_samples10

2026-10-24 19:36:55,574 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.025_min_samples20

2026-10-24 19:37:03,511 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.025_min_samples30

2026-10-24 19:37:11,173 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.025_min_samples100

2026-10-24 19:37:18,757 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.03_min_samples2

2026-10-24 19:37:25,944 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.03_min_samples3

2026-10-24 19:37:33,320 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.03_min_samples5

2026-10-24 19:37:40,353 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.03_min_samples7

2026-10-24 19:37:47,545 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.03_min_samples10

2026-10-24 19:37:54,791 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.03_min_samples20

2026-10-24 19:38:02,019 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.03_min_samples30

2026-10-24 19:38:09,260 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.03_min_samples100

2026-10-24 19:38:16,519 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.035_min_samples2

2026-10-24 19:38:23,781 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.035_min_samples3

2026-10-24 19:38:31,090 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.035_min_samples5

2026-10-24 19:38:38,305 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.035_min_samples7

2026-10-24 19:38:45,523 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.035_min_samples10

2026-10-24 19:38:52,762 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.035_min_samples20

2026-10-24 19:39:00,086 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.035_min_samples30

2026-10-24 19:39:07,719 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.035_min_samples100

2026-10-24 19:39:15,902 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.04_min_samples2

2026-10-24 19:39:24,053 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.04_min_samples3

2026-10-24 19:39:32,085 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.04_min_samples5

2026-10-24 19:39:39,465 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.04_min_samples7

2026-10-24 19:39:47,294 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.04_min_samples10

2026-10-24 19:39:54,529 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.04_min_samples20

2026-10-24 19:40:01,679 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.04_min_samples30

2026-10-24 19:40:08,928 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.04_min_samples100

2026-10-24 19:40:16,153 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.05_min_samples2

2026-10-24 19:40:23,419 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.05_min_samples3

2026-10-24 19:40:30,691 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.05_min_samples5

2026-10-24 19:40:38,011 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.05_min_samples7

2026-10-24 19:40:45,353 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.05_min_samples10

2026-10-24 19:40:52,583 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.05_min_samples20

2026-10-24 19:40:59,833 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.05_min_samples30

2026-10-24 19:41:07,090 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.05_min_samples100

2026-10-24 19:41:14,300 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.07_min_samples2

2026-10-24 19:41:21,589 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.07_min_samples3

2026-10-24 19:41:28,832 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.07_min_samples5

2026-10-24 19:41:36,133 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.07_min_samples7

2026-10-24 19:41:43,421 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.07_min_samples10

2026-10-24 19:41:51,606 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.07_min_samples20

2026-10-24 19:41:59,586 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.07_min_samples30

2026-10-24 19:42:07,953 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.07_min_samples100

2026-10-24 19:42:15,884 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.1_min_samples2

2026-10-24 19:42:24,295 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.1_min_samples3

2026-10-24 19:42:32,069 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.1_min_samples5

2026-10-24 19:42:39,777 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.1_min_samples7

2026-10-24 19:42:47,124 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.1_min_samples10

2026-10-24 19:42:54,723 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.1_min_samples20

2026-10-24 19:43:01,866 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.1_min_samples30

2026-10-24 19:43:09,059 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.1_min_samples100

2026-10-24 19:43:16,220 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.5_min_samples2

2026-10-24 19:43:29,945 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.5_min_samples3

2026-10-24 19:43:43,394 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.5_min_samples5

2026-10-24 19:43:56,353 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.5_min_samples7

2026-10-24 19:44:08,676 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.5_min_samples10

2026-10-24 19:44:20,217 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.5_min_samples20

2026-10-24 19:44:30,185 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.5_min_samples30

2026-10-24 19:44:38,988 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps0.5_min_samples100

2026-10-24 19:44:46,305 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps1_min_samples2

2026-10-24 19:44:58,153 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps1_min_samples3

2026-10-24 19:45:10,054 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps1_min_samples5

2026-10-24 19:45:21,971 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps1_min_samples7

2026-10-24 19:45:34,408 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps1_min_samples10

2026-10-24 19:45:46,577 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps1_min_samples20

2026-10-24 19:45:58,820 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps1_min_samples30

2026-10-24 19:46:11,021 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df5_eps1_min_samples100

2026-10-24 19:46:23,120 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-24 19:46:24,412 INFO Analyzer=char_wb min_df=10 seed=42: 28020 termos, 0 vetores zerados

2026-10-24 19:46:24,414 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.01_min_samples2

2026-10-24 19:46:31,519 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.01_min_samples3

2026-10-24 19:46:38,612 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.01_min_samples5

2026-10-24 19:46:45,783 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.01_min_samples7

2026-10-24 19:46:52,871 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.01_min_samples10

2026-10-24 19:47:00,014 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.01_min_samples20

2026-10-24 19:47:07,136 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.01_min_samples30

2026-10-24 19:47:14,209 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.01_min_samples100

2026-10-24 19:47:21,353 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.02_min_samples2

2026-10-24 19:47:28,570 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.02_min_samples3

2026-10-24 19:47:35,718 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.02_min_samples5

2026-10-24 19:47:42,816 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.02_min_samples7

2026-10-24 19:47:49,912 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.02_min_samples10

2026-10-24 19:47:56,993 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.02_min_samples20

2026-10-24 19:48:04,143 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.02_min_samples30

2026-10-24 19:48:11,299 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.02_min_samples100

2026-10-24 19:48:18,511 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.025_min_samples2

2026-10-24 19:48:26,448 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.025_min_samples3

2026-10-24 19:48:34,187 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.025_min_samples5

2026-10-24 19:48:41,887 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.025_min_samples7

2026-10-24 19:48:49,554 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.025_min_samples10

2026-10-24 19:48:57,220 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.025_min_samples20

2026-10-24 19:49:05,035 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.025_min_samples30

2026-10-24 19:49:12,155 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.025_min_samples100

2026-10-24 19:49:19,363 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.03_min_samples2

2026-10-24 19:49:26,532 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.03_min_samples3

2026-10-24 19:49:33,707 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.03_min_samples5

2026-10-24 19:49:40,821 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.03_min_samples7

2026-10-24 19:49:48,120 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.03_min_samples10

2026-10-24 19:49:55,222 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.03_min_samples20

2026-10-24 19:50:02,354 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.03_min_samples30

2026-10-24 19:50:09,474 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.03_min_samples100

2026-10-24 19:50:16,588 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.035_min_samples2

2026-10-24 19:50:23,718 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.035_min_samples3

2026-10-24 19:50:30,804 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.035_min_samples5

2026-10-24 19:50:37,962 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.035_min_samples7

2026-10-24 19:50:45,230 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.035_min_samples10

2026-10-24 19:50:52,338 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.035_min_samples20

2026-10-24 19:50:59,491 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.035_min_samples30

2026-10-24 19:51:06,815 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.035_min_samples100

2026-10-24 19:51:14,759 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.04_min_samples2

2026-10-24 19:51:23,582 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.04_min_samples3

2026-10-24 19:51:31,238 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.04_min_samples5

2026-10-24 19:51:38,950 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.04_min_samples7

2026-10-24 19:51:46,792 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.04_min_samples10

2026-10-24 19:51:54,207 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.04_min_samples20

2026-10-24 19:52:01,288 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.04_min_samples30

2026-10-24 19:52:08,448 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.04_min_samples100

2026-10-24 19:52:15,513 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.05_min_samples2

2026-10-24 19:52:22,657 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.05_min_samples3

2026-10-24 19:52:29,791 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.05_min_samples5

2026-10-24 19:52:36,952 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.05_min_samples7

2026-10-24 19:52:44,007 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.05_min_samples10

2026-10-24 19:52:51,166 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.05_min_samples20

2026-10-24 19:52:58,321 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.05_min_samples30

2026-10-24 19:53:05,454 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.05_min_samples100

2026-10-24 19:53:12,521 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.07_min_samples2

2026-10-24 19:53:19,725 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.07_min_samples3

2026-10-24 19:53:26,854 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.07_min_samples5

2026-10-24 19:53:34,052 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.07_min_samples7

2026-10-24 19:53:41,283 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.07_min_samples10

2026-10-24 19:53:48,459 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.07_min_samples20

2026-10-24 19:53:56,104 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.07_min_samples30

2026-10-24 19:54:03,871 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.07_min_samples100

2026-10-24 19:54:11,709 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.1_min_samples2

2026-10-24 19:54:19,982 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.1_min_samples3

2026-10-24 19:54:28,161 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.1_min_samples5

2026-10-24 19:54:35,623 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.1_min_samples7

2026-10-24 19:54:42,926 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.1_min_samples10

2026-10-24 19:54:49,949 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.1_min_samples20

2026-10-24 19:54:56,988 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.1_min_samples30

2026-10-24 19:55:04,075 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.1_min_samples100

2026-10-24 19:55:11,114 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.5_min_samples2

2026-10-24 19:55:24,807 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.5_min_samples3

2026-10-24 19:55:38,240 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.5_min_samples5

2026-10-24 19:55:51,193 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.5_min_samples7

2026-10-24 19:56:03,909 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.5_min_samples10

2026-10-24 19:56:15,992 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.5_min_samples20

2026-10-24 19:56:26,621 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.5_min_samples30

2026-10-24 19:56:35,975 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps0.5_min_samples100

2026-10-24 19:56:43,342 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps1_min_samples2

2026-10-24 19:56:55,296 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps1_min_samples3

2026-10-24 19:57:07,417 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps1_min_samples5

2026-10-24 19:57:19,451 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps1_min_samples7

2026-10-24 19:57:32,037 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps1_min_samples10

2026-10-24 19:57:44,762 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps1_min_samples20

2026-10-24 19:57:57,511 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps1_min_samples30

2026-10-24 19:58:09,983 INFO Ajustando DBSCAN seed42_char_wb_2_10_min_df10_eps1_min_samples100

2026-10-24 19:58:22,346 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-24 19:58:22,948 INFO Analyzer=char_wb min_df=1 seed=42: 73193 termos, 0 vetores zerados

2026-10-24 19:58:22,948 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.01_min_samples2

2026-10-24 19:58:28,022 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.01_min_samples3

2026-10-24 19:58:33,177 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.01_min_samples5

2026-10-24 19:58:38,293 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.01_min_samples7

2026-10-24 19:58:43,447 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.01_min_samples10

2026-10-24 19:58:48,604 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.01_min_samples20

2026-10-24 19:58:53,739 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.01_min_samples30

2026-10-24 19:58:58,889 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.01_min_samples100

2026-10-24 19:59:04,055 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.02_min_samples2

2026-10-24 19:59:09,188 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.02_min_samples3

2026-10-24 19:59:14,318 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.02_min_samples5

2026-10-24 19:59:19,482 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.02_min_samples7

2026-10-24 19:59:24,626 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.02_min_samples10

2026-10-24 19:59:29,748 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.02_min_samples20

2026-10-24 19:59:34,871 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.02_min_samples30

2026-10-24 19:59:39,984 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.02_min_samples100

2026-10-24 19:59:45,130 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.025_min_samples2

2026-10-24 19:59:50,325 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.025_min_samples3

2026-10-24 19:59:55,437 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.025_min_samples5

2026-10-24 20:00:00,585 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.025_min_samples7

2026-10-24 20:00:05,762 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.025_min_samples10

2026-10-24 20:00:10,893 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.025_min_samples20

2026-10-24 20:00:16,040 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.025_min_samples30

2026-10-24 20:00:21,209 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.025_min_samples100

2026-10-24 20:00:26,744 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.03_min_samples2

2026-10-24 20:00:32,513 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.03_min_samples3

2026-10-24 20:00:38,155 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.03_min_samples5

2026-10-24 20:00:44,176 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.03_min_samples7

2026-10-24 20:00:49,574 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.03_min_samples10

2026-10-24 20:00:54,978 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.03_min_samples20

2026-10-24 20:01:00,375 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.03_min_samples30

2026-10-24 20:01:05,762 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.03_min_samples100

2026-10-24 20:01:10,940 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.035_min_samples2

2026-10-24 20:01:16,155 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.035_min_samples3

2026-10-24 20:01:21,439 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.035_min_samples5

2026-10-24 20:01:26,518 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.035_min_samples7

2026-10-24 20:01:31,690 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.035_min_samples10

2026-10-24 20:01:36,825 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.035_min_samples20

2026-10-24 20:01:41,949 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.035_min_samples30

2026-10-24 20:01:47,041 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.035_min_samples100

2026-10-24 20:01:52,120 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.04_min_samples2

2026-10-24 20:01:57,206 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.04_min_samples3

2026-10-24 20:02:02,349 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.04_min_samples5

2026-10-24 20:02:07,513 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.04_min_samples7

2026-10-24 20:02:12,616 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.04_min_samples10

2026-10-24 20:02:17,741 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.04_min_samples20

2026-10-24 20:02:22,889 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.04_min_samples30

2026-10-24 20:02:27,993 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.04_min_samples100

2026-10-24 20:02:33,153 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.05_min_samples2

2026-10-24 20:02:38,289 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.05_min_samples3

2026-10-24 20:02:43,450 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.05_min_samples5

2026-10-24 20:02:48,575 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.05_min_samples7

2026-10-24 20:02:53,722 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.05_min_samples10

2026-10-24 20:02:58,856 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.05_min_samples20

2026-10-24 20:03:04,015 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.05_min_samples30

2026-10-24 20:03:09,373 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.05_min_samples100

2026-10-24 20:03:15,010 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.07_min_samples2

2026-10-24 20:03:20,690 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.07_min_samples3

2026-10-24 20:03:26,172 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.07_min_samples5

2026-10-24 20:03:31,590 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.07_min_samples7

2026-10-24 20:03:37,106 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.07_min_samples10

2026-10-24 20:03:42,556 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.07_min_samples20

2026-10-24 20:03:47,705 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.07_min_samples30

2026-10-24 20:03:52,856 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.07_min_samples100

2026-10-24 20:03:58,056 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.1_min_samples2

2026-10-24 20:04:03,251 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.1_min_samples3

2026-10-24 20:04:08,388 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.1_min_samples5

2026-10-24 20:04:13,493 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.1_min_samples7

2026-10-24 20:04:18,621 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.1_min_samples10

2026-10-24 20:04:23,745 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.1_min_samples20

2026-10-24 20:04:28,856 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.1_min_samples30

2026-10-24 20:04:33,979 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.1_min_samples100

2026-10-24 20:04:39,154 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.5_min_samples2

2026-10-24 20:04:48,088 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.5_min_samples3

2026-10-24 20:04:56,678 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.5_min_samples5

2026-10-24 20:05:04,709 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.5_min_samples7

2026-10-24 20:05:12,356 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.5_min_samples10

2026-10-24 20:05:19,622 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.5_min_samples20

2026-10-24 20:05:25,816 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.5_min_samples30

2026-10-24 20:05:31,456 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps0.5_min_samples100

2026-10-24 20:05:36,623 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps1_min_samples2

2026-10-24 20:05:46,869 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps1_min_samples3

2026-10-24 20:05:57,769 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps1_min_samples5

2026-10-24 20:06:08,472 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps1_min_samples7

2026-10-24 20:06:19,072 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps1_min_samples10

2026-10-24 20:06:29,493 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps1_min_samples20

2026-10-24 20:06:39,773 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps1_min_samples30

2026-10-24 20:06:50,207 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df1_eps1_min_samples100

2026-10-24 20:07:00,623 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-24 20:07:01,195 INFO Analyzer=char_wb min_df=2 seed=42: 41044 termos, 0 vetores zerados

2026-10-24 20:07:01,195 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.01_min_samples2

2026-10-24 20:07:06,190 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.01_min_samples3

2026-10-24 20:07:11,247 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.01_min_samples5

2026-10-24 20:07:16,255 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.01_min_samples7

2026-10-24 20:07:21,264 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.01_min_samples10

2026-10-24 20:07:26,370 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.01_min_samples20

2026-10-24 20:07:31,543 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.01_min_samples30

2026-10-24 20:07:36,643 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.01_min_samples100

2026-10-24 20:07:41,623 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.02_min_samples2

2026-10-24 20:07:46,716 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.02_min_samples3

2026-10-24 20:07:51,755 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.02_min_samples5

2026-10-24 20:07:56,953 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.02_min_samples7

2026-10-24 20:08:02,106 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.02_min_samples10

2026-10-24 20:08:07,273 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.02_min_samples20

2026-10-24 20:08:12,370 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.02_min_samples30

2026-10-24 20:08:17,489 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.02_min_samples100

2026-10-24 20:08:22,623 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.025_min_samples2

2026-10-24 20:08:27,955 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.025_min_samples3

2026-10-24 20:08:33,451 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.025_min_samples5

2026-10-24 20:08:38,890 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.025_min_samples7

2026-10-24 20:08:44,391 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.025_min_samples10

2026-10-24 20:08:49,924 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.025_min_samples20

2026-10-24 20:08:55,357 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.025_min_samples30

2026-10-24 20:09:01,186 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.025_min_samples100

2026-10-24 20:09:06,637 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.03_min_samples2

2026-10-24 20:09:12,107 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.03_min_samples3

2026-10-24 20:09:17,646 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.03_min_samples5

2026-10-24 20:09:23,219 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.03_min_samples7

2026-10-24 20:09:28,546 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.03_min_samples10

2026-10-24 20:09:33,874 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.03_min_samples20

2026-10-24 20:09:38,890 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.03_min_samples30

2026-10-24 20:09:43,974 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.03_min_samples100

2026-10-24 20:09:49,192 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.035_min_samples2

2026-10-24 20:09:54,468 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.035_min_samples3

2026-10-24 20:09:59,597 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.035_min_samples5

2026-10-24 20:10:04,682 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.035_min_samples7

2026-10-24 20:10:09,817 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.035_min_samples10

2026-10-24 20:10:14,923 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.035_min_samples20

2026-10-24 20:10:20,017 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.035_min_samples30

2026-10-24 20:10:25,154 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.035_min_samples100

2026-10-24 20:10:30,290 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.04_min_samples2

2026-10-24 20:10:35,390 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.04_min_samples3

2026-10-24 20:10:40,574 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.04_min_samples5

2026-10-24 20:10:45,657 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.04_min_samples7

2026-10-24 20:10:50,757 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.04_min_samples10

2026-10-24 20:10:55,885 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.04_min_samples20

2026-10-24 20:11:00,990 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.04_min_samples30

2026-10-24 20:11:06,118 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.04_min_samples100

2026-10-24 20:11:11,273 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.05_min_samples2

2026-10-24 20:11:16,413 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.05_min_samples3

2026-10-24 20:11:21,484 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.05_min_samples5

2026-10-24 20:11:26,890 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.05_min_samples7

2026-10-24 20:11:32,390 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.05_min_samples10

2026-10-24 20:11:37,855 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.05_min_samples20

2026-10-24 20:11:43,690 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.05_min_samples30

2026-10-24 20:11:49,263 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.05_min_samples100

2026-10-24 20:11:55,024 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.07_min_samples2

2026-10-24 20:12:00,567 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.07_min_samples3

2026-10-24 20:12:06,188 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.07_min_samples5

2026-10-24 20:12:11,462 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.07_min_samples7

2026-10-24 20:12:16,758 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.07_min_samples10

2026-10-24 20:12:21,950 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.07_min_samples20

2026-10-24 20:12:26,983 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.07_min_samples30

2026-10-24 20:12:31,980 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.07_min_samples100

2026-10-24 20:12:37,082 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.1_min_samples2

2026-10-24 20:12:42,191 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.1_min_samples3

2026-10-24 20:12:47,307 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.1_min_samples5

2026-10-24 20:12:52,457 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.1_min_samples7

2026-10-24 20:12:57,611 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.1_min_samples10

2026-10-24 20:13:02,753 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.1_min_samples20

2026-10-24 20:13:07,892 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.1_min_samples30

2026-10-24 20:13:12,976 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.1_min_samples100

2026-10-24 20:13:18,105 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.5_min_samples2

2026-10-24 20:13:27,465 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.5_min_samples3

2026-10-24 20:13:36,387 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.5_min_samples5

2026-10-24 20:13:44,609 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.5_min_samples7

2026-10-24 20:13:52,486 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.5_min_samples10

2026-10-24 20:13:59,949 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.5_min_samples20

2026-10-24 20:14:06,267 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.5_min_samples30

2026-10-24 20:14:11,954 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps0.5_min_samples100

2026-10-24 20:14:17,091 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps1_min_samples2

2026-10-24 20:14:27,606 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps1_min_samples3

2026-10-24 20:14:38,340 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps1_min_samples5

2026-10-24 20:14:49,333 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps1_min_samples7

2026-10-24 20:15:00,099 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps1_min_samples10

2026-10-24 20:15:10,591 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps1_min_samples20

2026-10-24 20:15:21,148 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps1_min_samples30

2026-10-24 20:15:31,707 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df2_eps1_min_samples100

2026-10-24 20:15:42,401 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-24 20:15:43,007 INFO Analyzer=char_wb min_df=5 seed=42: 22987 termos, 0 vetores zerados

2026-10-24 20:15:43,007 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.01_min_samples2

2026-10-24 20:15:48,092 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.01_min_samples3

2026-10-24 20:15:53,179 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.01_min_samples5

2026-10-24 20:15:58,276 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.01_min_samples7

2026-10-24 20:16:03,291 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.01_min_samples10

2026-10-24 20:16:08,374 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.01_min_samples20

2026-10-24 20:16:13,418 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.01_min_samples30

2026-10-24 20:16:18,506 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.01_min_samples100

2026-10-24 20:16:23,558 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.02_min_samples2

2026-10-24 20:16:28,626 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.02_min_samples3

2026-10-24 20:16:33,695 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.02_min_samples5

2026-10-24 20:16:38,745 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.02_min_samples7

2026-10-24 20:16:43,861 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.02_min_samples10

2026-10-24 20:16:48,891 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.02_min_samples20

2026-10-24 20:16:53,944 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.02_min_samples30

2026-10-24 20:16:59,035 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.02_min_samples100

2026-10-24 20:17:04,137 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.025_min_samples2

2026-10-24 20:17:09,191 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.025_min_samples3

2026-10-24 20:17:14,272 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.025_min_samples5

2026-10-24 20:17:19,333 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.025_min_samples7

2026-10-24 20:17:24,434 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.025_min_samples10

2026-10-24 20:17:29,523 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.025_min_samples20

2026-10-24 20:17:34,647 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.025_min_samples30

2026-10-24 20:17:39,725 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.025_min_samples100

2026-10-24 20:17:44,810 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.03_min_samples2

2026-10-24 20:17:49,877 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.03_min_samples3

2026-10-24 20:17:54,948 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.03_min_samples5

2026-10-24 20:18:00,030 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.03_min_samples7

2026-10-24 20:18:05,126 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.03_min_samples10

2026-10-24 20:18:10,194 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.03_min_samples20

2026-10-24 20:18:16,021 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.03_min_samples30

2026-10-24 20:18:21,661 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.03_min_samples100

2026-10-24 20:18:27,158 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.035_min_samples2

2026-10-24 20:18:32,614 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.035_min_samples3

2026-10-24 20:18:37,975 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.035_min_samples5

2026-10-24 20:18:43,391 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.035_min_samples7

2026-10-24 20:18:48,683 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.035_min_samples10

2026-10-24 20:18:53,791 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.035_min_samples20

2026-10-24 20:18:58,918 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.035_min_samples30

2026-10-24 20:19:04,145 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.035_min_samples100

2026-10-24 20:19:09,161 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.04_min_samples2

2026-10-24 20:19:14,092 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.04_min_samples3

2026-10-24 20:19:19,173 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.04_min_samples5

2026-10-24 20:19:24,220 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.04_min_samples7

2026-10-24 20:19:29,258 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.04_min_samples10

2026-10-24 20:19:34,298 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.04_min_samples20

2026-10-24 20:19:39,379 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.04_min_samples30

2026-10-24 20:19:44,453 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.04_min_samples100

2026-10-24 20:19:49,455 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.05_min_samples2

2026-10-24 20:19:54,483 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.05_min_samples3

2026-10-24 20:19:59,581 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.05_min_samples5

2026-10-24 20:20:04,664 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.05_min_samples7

2026-10-24 20:20:09,743 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.05_min_samples10

2026-10-24 20:20:14,822 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.05_min_samples20

2026-10-24 20:20:19,892 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.05_min_samples30

2026-10-24 20:20:24,999 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.05_min_samples100

2026-10-24 20:20:30,092 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.07_min_samples2

2026-10-24 20:20:35,225 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.07_min_samples3

2026-10-24 20:20:40,441 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.07_min_samples5

2026-10-24 20:20:45,529 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.07_min_samples7

2026-10-24 20:20:50,646 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.07_min_samples10

2026-10-24 20:20:55,730 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.07_min_samples20

2026-10-24 20:21:00,843 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.07_min_samples30

2026-10-24 20:21:05,975 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.07_min_samples100

2026-10-24 20:21:11,037 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.1_min_samples2

2026-10-24 20:21:16,223 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.1_min_samples3

2026-10-24 20:21:21,949 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.1_min_samples5

2026-10-24 20:21:27,422 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.1_min_samples7

2026-10-24 20:21:32,883 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.1_min_samples10

2026-10-24 20:21:38,181 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.1_min_samples20

2026-10-24 20:21:43,633 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.1_min_samples30

2026-10-24 20:21:49,158 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.1_min_samples100

2026-10-24 20:21:54,684 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.5_min_samples2

2026-10-24 20:22:04,728 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.5_min_samples3

2026-10-24 20:22:13,817 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.5_min_samples5

2026-10-24 20:22:22,595 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.5_min_samples7

2026-10-24 20:22:30,925 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.5_min_samples10

2026-10-24 20:22:38,796 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.5_min_samples20

2026-10-24 20:22:45,345 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.5_min_samples30

2026-10-24 20:22:51,213 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps0.5_min_samples100

2026-10-24 20:22:56,257 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps1_min_samples2

2026-10-24 20:23:06,842 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps1_min_samples3

2026-10-24 20:23:17,379 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps1_min_samples5

2026-10-24 20:23:28,176 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps1_min_samples7

2026-10-24 20:23:38,825 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps1_min_samples10

2026-10-24 20:23:49,456 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps1_min_samples20

2026-10-24 20:24:00,185 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps1_min_samples30

2026-10-24 20:24:11,012 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df5_eps1_min_samples100

2026-10-24 20:24:21,864 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-24 20:24:22,492 INFO Analyzer=char_wb min_df=10 seed=42: 15191 termos, 0 vetores zerados

2026-10-24 20:24:22,492 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.01_min_samples2

2026-10-24 20:24:27,459 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.01_min_samples3

2026-10-24 20:24:32,452 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.01_min_samples5

2026-10-24 20:24:37,513 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.01_min_samples7

2026-10-24 20:24:42,512 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.01_min_samples10

2026-10-24 20:24:47,612 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.01_min_samples20

2026-10-24 20:24:52,648 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.01_min_samples30

2026-10-24 20:24:57,684 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.01_min_samples100

2026-10-24 20:25:02,700 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.02_min_samples2

2026-10-24 20:25:07,710 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.02_min_samples3

2026-10-24 20:25:12,693 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.02_min_samples5

2026-10-24 20:25:17,666 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.02_min_samples7

2026-10-24 20:25:22,714 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.02_min_samples10

2026-10-24 20:25:27,759 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.02_min_samples20

2026-10-24 20:25:32,829 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.02_min_samples30

2026-10-24 20:25:37,859 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.02_min_samples100

2026-10-24 20:25:42,859 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.025_min_samples2

2026-10-24 20:25:47,859 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.025_min_samples3

2026-10-24 20:25:52,916 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.025_min_samples5

2026-10-24 20:25:57,927 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.025_min_samples7

2026-10-24 20:26:02,926 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.025_min_samples10

2026-10-24 20:26:07,955 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.025_min_samples20

2026-10-24 20:26:12,959 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.025_min_samples30

2026-10-24 20:26:18,016 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.025_min_samples100

2026-10-24 20:26:23,110 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.03_min_samples2

2026-10-24 20:26:28,176 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.03_min_samples3

2026-10-24 20:26:33,259 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.03_min_samples5

2026-10-24 20:26:38,279 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.03_min_samples7

2026-10-24 20:26:43,926 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.03_min_samples10

2026-10-24 20:26:49,492 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.03_min_samples20

2026-10-24 20:26:54,850 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.03_min_samples30

2026-10-24 20:27:00,249 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.03_min_samples100

2026-10-24 20:27:05,443 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.035_min_samples2

2026-10-24 20:27:10,726 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.035_min_samples3

2026-10-24 20:27:16,076 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.035_min_samples5

2026-10-24 20:27:21,509 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.035_min_samples7

2026-10-24 20:27:26,748 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.035_min_samples10

2026-10-24 20:27:31,859 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.035_min_samples20

2026-10-24 20:27:36,815 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.035_min_samples30

2026-10-24 20:27:41,767 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.035_min_samples100

2026-10-24 20:27:46,701 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.04_min_samples2

2026-10-24 20:27:51,693 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.04_min_samples3

2026-10-24 20:27:56,727 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.04_min_samples5

2026-10-24 20:28:01,709 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.04_min_samples7

2026-10-24 20:28:06,726 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.04_min_samples10

2026-10-24 20:28:11,754 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.04_min_samples20

2026-10-24 20:28:16,768 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.04_min_samples30

2026-10-24 20:28:21,848 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.04_min_samples100

2026-10-24 20:28:26,885 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.05_min_samples2

2026-10-24 20:28:31,959 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.05_min_samples3

2026-10-24 20:28:37,010 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.05_min_samples5

2026-10-24 20:28:42,016 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.05_min_samples7

2026-10-24 20:28:46,999 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.05_min_samples10

2026-10-24 20:28:52,014 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.05_min_samples20

2026-10-24 20:28:57,077 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.05_min_samples30

2026-10-24 20:29:02,162 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.05_min_samples100

2026-10-24 20:29:07,195 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.07_min_samples2

2026-10-24 20:29:12,270 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.07_min_samples3

2026-10-24 20:29:17,331 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.07_min_samples5

2026-10-24 20:29:22,393 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.07_min_samples7

2026-10-24 20:29:27,493 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.07_min_samples10

2026-10-24 20:29:32,892 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.07_min_samples20

2026-10-24 20:29:38,251 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.07_min_samples30

2026-10-24 20:29:43,591 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.07_min_samples100

2026-10-24 20:29:49,285 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.1_min_samples2

2026-10-24 20:29:54,773 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.1_min_samples3

2026-10-24 20:30:00,293 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.1_min_samples5

2026-10-24 20:30:05,460 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.1_min_samples7

2026-10-24 20:30:10,526 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.1_min_samples10

2026-10-24 20:30:15,588 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.1_min_samples20

2026-10-24 20:30:20,618 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.1_min_samples30

2026-10-24 20:30:25,618 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.1_min_samples100

2026-10-24 20:30:30,538 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.5_min_samples2

2026-10-24 20:30:40,204 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.5_min_samples3

2026-10-24 20:30:49,695 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.5_min_samples5

2026-10-24 20:30:58,722 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.5_min_samples7

2026-10-24 20:31:07,414 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.5_min_samples10

2026-10-24 20:31:15,649 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.5_min_samples20

2026-10-24 20:31:22,719 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.5_min_samples30

2026-10-24 20:31:28,860 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps0.5_min_samples100

2026-10-24 20:31:33,944 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps1_min_samples2

2026-10-24 20:31:44,843 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps1_min_samples3

2026-10-24 20:31:55,670 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps1_min_samples5

2026-10-24 20:32:06,460 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps1_min_samples7

2026-10-24 20:32:17,173 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps1_min_samples10

2026-10-24 20:32:28,017 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps1_min_samples20

2026-10-24 20:32:38,915 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps1_min_samples30

2026-10-24 20:32:49,797 INFO Ajustando DBSCAN seed42_char_wb_3_5_min_df10_eps1_min_samples100

2026-10-24 20:33:00,707 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-24 20:33:01,769 INFO Analyzer=char_wb min_df=1 seed=42: 100000 termos, 0 vetores zerados

2026-10-24 20:33:01,769 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.01_min_samples2

2026-10-24 20:33:07,415 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.01_min_samples3

2026-10-24 20:33:13,027 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.01_min_samples5

2026-10-24 20:33:18,716 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.01_min_samples7

2026-10-24 20:33:24,377 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.01_min_samples10

2026-10-24 20:33:30,046 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.01_min_samples20

2026-10-24 20:33:35,762 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.01_min_samples30

2026-10-24 20:33:41,493 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.01_min_samples100

2026-10-24 20:33:47,082 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.02_min_samples2

2026-10-24 20:33:52,694 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.02_min_samples3

2026-10-24 20:33:58,231 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.02_min_samples5

2026-10-24 20:34:03,820 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.02_min_samples7

2026-10-24 20:34:09,362 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.02_min_samples10

2026-10-24 20:34:14,929 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.02_min_samples20

2026-10-24 20:34:20,764 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.02_min_samples30

2026-10-24 20:34:26,820 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.02_min_samples100

2026-10-24 20:34:33,427 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.025_min_samples2

2026-10-24 20:34:39,828 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.025_min_samples3

2026-10-24 20:34:46,160 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.025_min_samples5

2026-10-24 20:34:52,560 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.025_min_samples7

2026-10-24 20:34:58,757 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.025_min_samples10

2026-10-24 20:35:04,967 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.025_min_samples20

2026-10-24 20:35:11,060 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.025_min_samples30

2026-10-24 20:35:17,360 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.025_min_samples100

2026-10-24 20:35:23,896 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.03_min_samples2

2026-10-24 20:35:30,107 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.03_min_samples3

2026-10-24 20:35:36,227 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.03_min_samples5

2026-10-24 20:35:42,410 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.03_min_samples7

2026-10-24 20:35:48,749 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.03_min_samples10

2026-10-24 20:35:54,933 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.03_min_samples20

2026-10-24 20:36:01,128 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.03_min_samples30

2026-10-24 20:36:07,194 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.03_min_samples100

2026-10-24 20:36:13,069 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.035_min_samples2

2026-10-24 20:36:19,203 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.035_min_samples3

2026-10-24 20:36:25,392 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.035_min_samples5

2026-10-24 20:36:31,231 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.035_min_samples7

2026-10-24 20:36:36,995 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.035_min_samples10

2026-10-24 20:36:42,998 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.035_min_samples20

2026-10-24 20:36:48,994 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.035_min_samples30

2026-10-24 20:36:55,183 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.035_min_samples100

2026-10-24 20:37:00,861 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.04_min_samples2

2026-10-24 20:37:06,456 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.04_min_samples3

2026-10-24 20:37:11,961 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.04_min_samples5

2026-10-24 20:37:17,494 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.04_min_samples7

2026-10-24 20:37:23,090 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.04_min_samples10

2026-10-24 20:37:29,022 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.04_min_samples20

2026-10-24 20:37:35,161 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.04_min_samples30

2026-10-24 20:37:41,904 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.04_min_samples100

2026-10-24 20:37:48,419 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.05_min_samples2

2026-10-24 20:37:55,641 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.05_min_samples3

2026-10-24 20:38:02,689 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.05_min_samples5

2026-10-24 20:38:09,561 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.05_min_samples7

2026-10-24 20:38:16,661 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.05_min_samples10

2026-10-24 20:38:23,527 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.05_min_samples20

2026-10-24 20:38:30,961 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.05_min_samples30

2026-10-24 20:38:37,594 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.05_min_samples100

2026-10-24 20:38:44,184 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.07_min_samples2

2026-10-24 20:38:50,825 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.07_min_samples3

2026-10-24 20:38:57,292 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.07_min_samples5

2026-10-24 20:39:03,926 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.07_min_samples7

2026-10-24 20:39:10,505 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.07_min_samples10

2026-10-24 20:39:18,065 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.07_min_samples20

2026-10-24 20:39:24,994 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.07_min_samples30

2026-10-24 20:39:31,714 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.07_min_samples100

2026-10-24 20:39:38,161 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.1_min_samples2

2026-10-24 20:39:44,978 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.1_min_samples3

2026-10-24 20:39:51,761 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.1_min_samples5

2026-10-24 20:39:58,481 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.1_min_samples7

2026-10-24 20:40:06,253 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.1_min_samples10

2026-10-24 20:40:13,183 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.1_min_samples20

2026-10-24 20:40:19,992 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.1_min_samples30

2026-10-24 20:40:27,029 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.1_min_samples100

2026-10-24 20:40:33,998 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.5_min_samples2

2026-10-24 20:40:48,085 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.5_min_samples3

2026-10-24 20:41:00,378 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.5_min_samples5

2026-10-24 20:41:10,675 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.5_min_samples7

2026-10-24 20:41:20,578 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.5_min_samples10

2026-10-24 20:41:29,894 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.5_min_samples20

2026-10-24 20:41:38,802 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.5_min_samples30

2026-10-24 20:41:46,028 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps0.5_min_samples100

2026-10-24 20:41:52,428 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps1_min_samples2

2026-10-24 20:42:06,457 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps1_min_samples3

2026-10-24 20:42:18,758 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps1_min_samples5

2026-10-24 20:42:30,628 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps1_min_samples7

2026-10-24 20:42:42,293 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps1_min_samples10

2026-10-24 20:42:53,953 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps1_min_samples20

2026-10-24 20:43:05,696 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps1_min_samples30

2026-10-24 20:43:17,382 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df1_eps1_min_samples100

2026-10-24 20:43:29,057 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-24 20:43:30,086 INFO Analyzer=char_wb min_df=2 seed=42: 89379 termos, 0 vetores zerados

2026-10-24 20:43:30,086 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.01_min_samples2

2026-10-24 20:43:35,763 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.01_min_samples3

2026-10-24 20:43:41,395 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.01_min_samples5

2026-10-24 20:43:47,052 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.01_min_samples7

2026-10-24 20:43:52,679 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.01_min_samples10

2026-10-24 20:43:58,329 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.01_min_samples20

2026-10-24 20:44:03,960 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.01_min_samples30

2026-10-24 20:44:09,626 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.01_min_samples100

2026-10-24 20:44:15,296 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.02_min_samples2

2026-10-24 20:44:20,962 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.02_min_samples3

2026-10-24 20:44:26,688 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.02_min_samples5

2026-10-24 20:44:32,361 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.02_min_samples7

2026-10-24 20:44:38,055 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.02_min_samples10

2026-10-24 20:44:43,702 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.02_min_samples20

2026-10-24 20:44:49,365 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.02_min_samples30

2026-10-24 20:44:55,024 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.02_min_samples100

2026-10-24 20:45:00,702 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.025_min_samples2

2026-10-24 20:45:06,429 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.025_min_samples3

2026-10-24 20:45:12,084 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.025_min_samples5

2026-10-24 20:45:17,752 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.025_min_samples7

2026-10-24 20:45:23,417 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.025_min_samples10

2026-10-24 20:45:29,116 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.025_min_samples20

2026-10-24 20:45:34,851 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.025_min_samples30

2026-10-24 20:45:40,583 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.025_min_samples100

2026-10-24 20:45:46,289 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.03_min_samples2

2026-10-24 20:45:51,998 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.03_min_samples3

2026-10-24 20:45:58,105 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.03_min_samples5

2026-10-24 20:46:04,362 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.03_min_samples7

2026-10-24 20:46:10,883 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.03_min_samples10

2026-10-24 20:46:17,229 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.03_min_samples20

2026-10-24 20:46:23,262 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.03_min_samples30

2026-10-24 20:46:29,262 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.03_min_samples100

2026-10-24 20:46:34,956 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.035_min_samples2

2026-10-24 20:46:40,680 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.035_min_samples3

2026-10-24 20:46:46,387 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.035_min_samples5

2026-10-24 20:46:51,993 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.035_min_samples7

2026-10-24 20:46:57,512 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.035_min_samples10

2026-10-24 20:47:03,133 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.035_min_samples20

2026-10-24 20:47:08,735 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.035_min_samples30

2026-10-24 20:47:14,375 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.035_min_samples100

2026-10-24 20:47:20,029 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.04_min_samples2

2026-10-24 20:47:25,731 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.04_min_samples3

2026-10-24 20:47:31,387 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.04_min_samples5

2026-10-24 20:47:37,085 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.04_min_samples7

2026-10-24 20:47:42,762 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.04_min_samples10

2026-10-24 20:47:48,419 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.04_min_samples20

2026-10-24 20:47:54,229 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.04_min_samples30

2026-10-24 20:48:00,300 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.04_min_samples100

2026-10-24 20:48:06,547 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.05_min_samples2

2026-10-24 20:48:12,752 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.05_min_samples3

2026-10-24 20:48:19,029 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.05_min_samples5

2026-10-24 20:48:25,213 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.05_min_samples7

2026-10-24 20:48:31,999 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.05_min_samples10

2026-10-24 20:48:37,781 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.05_min_samples20

2026-10-24 20:48:43,529 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.05_min_samples30

2026-10-24 20:48:49,201 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.05_min_samples100

2026-10-24 20:48:54,886 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.07_min_samples2

2026-10-24 20:49:00,644 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.07_min_samples3

2026-10-24 20:49:06,353 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.07_min_samples5

2026-10-24 20:49:12,021 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.07_min_samples7

2026-10-24 20:49:17,679 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.07_min_samples10

2026-10-24 20:49:23,362 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.07_min_samples20

2026-10-24 20:49:28,987 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.07_min_samples30

2026-10-24 20:49:34,669 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.07_min_samples100

2026-10-24 20:49:40,329 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.1_min_samples2

2026-10-24 20:49:46,154 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.1_min_samples3

2026-10-24 20:49:51,829 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.1_min_samples5

2026-10-24 20:49:57,558 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.1_min_samples7

2026-10-24 20:50:03,260 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.1_min_samples10

2026-10-24 20:50:08,888 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.1_min_samples20

2026-10-24 20:50:14,526 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.1_min_samples30

2026-10-24 20:50:20,161 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.1_min_samples100

2026-10-24 20:50:25,862 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.5_min_samples2

2026-10-24 20:50:36,651 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.5_min_samples3

2026-10-24 20:50:46,922 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.5_min_samples5

2026-10-24 20:50:56,636 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.5_min_samples7

2026-10-24 20:51:06,290 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.5_min_samples10

2026-10-24 20:51:15,563 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.5_min_samples20

2026-10-24 20:51:23,563 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.5_min_samples30

2026-10-24 20:51:30,297 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps0.5_min_samples100

2026-10-24 20:51:36,520 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps1_min_samples2

2026-10-24 20:51:48,296 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps1_min_samples3

2026-10-24 20:52:00,067 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps1_min_samples5

2026-10-24 20:52:11,862 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps1_min_samples7

2026-10-24 20:52:23,729 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps1_min_samples10

2026-10-24 20:52:35,662 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps1_min_samples20

2026-10-24 20:52:47,360 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps1_min_samples30

2026-10-24 20:52:59,289 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df2_eps1_min_samples100

2026-10-24 20:53:11,078 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-24 20:53:12,104 INFO Analyzer=char_wb min_df=5 seed=42: 44780 termos, 0 vetores zerados

2026-10-24 20:53:12,112 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.01_min_samples2

2026-10-24 20:53:17,713 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.01_min_samples3

2026-10-24 20:53:23,263 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.01_min_samples5

2026-10-24 20:53:28,788 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.01_min_samples7

2026-10-24 20:53:34,346 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.01_min_samples10

2026-10-24 20:53:39,917 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.01_min_samples20

2026-10-24 20:53:45,463 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.01_min_samples30

2026-10-24 20:53:51,063 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.01_min_samples100

2026-10-24 20:53:56,596 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.02_min_samples2

2026-10-24 20:54:02,160 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.02_min_samples3

2026-10-24 20:54:07,756 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.02_min_samples5

2026-10-24 20:54:13,269 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.02_min_samples7

2026-10-24 20:54:18,853 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.02_min_samples10

2026-10-24 20:54:24,435 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.02_min_samples20

2026-10-24 20:54:30,052 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.02_min_samples30

2026-10-24 20:54:35,627 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.02_min_samples100

2026-10-24 20:54:41,246 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.025_min_samples2

2026-10-24 20:54:46,874 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.025_min_samples3

2026-10-24 20:54:52,422 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.025_min_samples5

2026-10-24 20:54:58,030 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.025_min_samples7

2026-10-24 20:55:03,635 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.025_min_samples10

2026-10-24 20:55:09,299 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.025_min_samples20

2026-10-24 20:55:14,852 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.025_min_samples30

2026-10-24 20:55:20,718 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.025_min_samples100

2026-10-24 20:55:27,105 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.03_min_samples2

2026-10-24 20:55:32,961 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.03_min_samples3

2026-10-24 20:55:38,791 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.03_min_samples5

2026-10-24 20:55:44,690 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.03_min_samples7

2026-10-24 20:55:50,960 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.03_min_samples10

2026-10-24 20:55:57,007 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.03_min_samples20

2026-10-24 20:56:02,743 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.03_min_samples30

2026-10-24 20:56:08,464 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.03_min_samples100

2026-10-24 20:56:14,296 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.035_min_samples2

2026-10-24 20:56:19,851 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.035_min_samples3

2026-10-24 20:56:25,390 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.035_min_samples5

2026-10-24 20:56:30,882 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.035_min_samples7

2026-10-24 20:56:36,386 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.035_min_samples10

2026-10-24 20:56:41,836 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.035_min_samples20

2026-10-24 20:56:47,254 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.035_min_samples30

2026-10-24 20:56:52,654 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.035_min_samples100

2026-10-24 20:56:58,062 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.04_min_samples2

2026-10-24 20:57:03,497 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.04_min_samples3

2026-10-24 20:57:08,927 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.04_min_samples5

2026-10-24 20:57:14,361 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.04_min_samples7

2026-10-24 20:57:19,817 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.04_min_samples10

2026-10-24 20:57:25,264 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.04_min_samples20

2026-10-24 20:57:30,720 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.04_min_samples30

2026-10-24 20:57:36,230 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.04_min_samples100

2026-10-24 20:57:42,421 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.05_min_samples2

2026-10-24 20:57:48,791 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.05_min_samples3

2026-10-24 20:57:54,848 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.05_min_samples5

2026-10-24 20:58:00,852 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.05_min_samples7

2026-10-24 20:58:07,098 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.05_min_samples10

2026-10-24 20:58:13,328 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.05_min_samples20

2026-10-24 20:58:19,399 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.05_min_samples30

2026-10-24 20:58:25,330 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.05_min_samples100

2026-10-24 20:58:31,731 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.07_min_samples2

2026-10-24 20:58:37,930 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.07_min_samples3

2026-10-24 20:58:43,998 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.07_min_samples5

2026-10-24 20:58:50,163 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.07_min_samples7

2026-10-24 20:58:55,883 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.07_min_samples10

2026-10-24 20:59:01,298 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.07_min_samples20

2026-10-24 20:59:06,624 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.07_min_samples30

2026-10-24 20:59:12,085 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.07_min_samples100

2026-10-24 20:59:17,619 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.1_min_samples2

2026-10-24 20:59:23,198 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.1_min_samples3

2026-10-24 20:59:28,597 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.1_min_samples5

2026-10-24 20:59:34,030 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.1_min_samples7

2026-10-24 20:59:39,464 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.1_min_samples10

2026-10-24 20:59:44,936 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.1_min_samples20

2026-10-24 20:59:50,682 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.1_min_samples30

2026-10-24 20:59:56,597 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.1_min_samples100

2026-10-24 21:00:03,034 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.5_min_samples2

2026-10-24 21:00:15,198 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.5_min_samples3

2026-10-24 21:00:26,911 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.5_min_samples5

2026-10-24 21:00:37,927 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.5_min_samples7

2026-10-24 21:00:48,548 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.5_min_samples10

2026-10-24 21:00:57,636 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.5_min_samples20

2026-10-24 21:01:05,164 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.5_min_samples30

2026-10-24 21:01:11,781 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps0.5_min_samples100

2026-10-24 21:01:17,331 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps1_min_samples2

2026-10-24 21:01:28,883 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps1_min_samples3

2026-10-24 21:01:40,656 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps1_min_samples5

2026-10-24 21:01:52,247 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps1_min_samples7

2026-10-24 21:02:03,848 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps1_min_samples10

2026-10-24 21:02:16,864 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps1_min_samples20

2026-10-24 21:02:30,047 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps1_min_samples30

2026-10-24 21:02:42,385 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df5_eps1_min_samples100

2026-10-24 21:02:54,331 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-24 21:02:55,364 INFO Analyzer=char_wb min_df=10 seed=42: 27271 termos, 0 vetores zerados

2026-10-24 21:02:55,364 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.01_min_samples2

2026-10-24 21:03:00,736 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.01_min_samples3

2026-10-24 21:03:06,236 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.01_min_samples5

2026-10-24 21:03:11,652 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.01_min_samples7

2026-10-24 21:03:17,144 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.01_min_samples10

2026-10-24 21:03:22,617 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.01_min_samples20

2026-10-24 21:03:28,116 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.01_min_samples30

2026-10-24 21:03:33,583 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.01_min_samples100

2026-10-24 21:03:39,094 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.02_min_samples2

2026-10-24 21:03:44,548 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.02_min_samples3

2026-10-24 21:03:50,083 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.02_min_samples5

2026-10-24 21:03:55,586 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.02_min_samples7

2026-10-24 21:04:01,101 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.02_min_samples10

2026-10-24 21:04:06,575 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.02_min_samples20

2026-10-24 21:04:11,990 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.02_min_samples30

2026-10-24 21:04:17,430 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.02_min_samples100

2026-10-24 21:04:22,924 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.025_min_samples2

2026-10-24 21:04:28,404 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.025_min_samples3

2026-10-24 21:04:33,903 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.025_min_samples5

2026-10-24 21:04:39,396 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.025_min_samples7

2026-10-24 21:04:44,877 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.025_min_samples10

2026-10-24 21:04:50,342 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.025_min_samples20

2026-10-24 21:04:55,785 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.025_min_samples30

2026-10-24 21:05:01,266 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.025_min_samples100

2026-10-24 21:05:06,749 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.03_min_samples2

2026-10-24 21:05:12,215 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.03_min_samples3

2026-10-24 21:05:17,670 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.03_min_samples5

2026-10-24 21:05:23,315 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.03_min_samples7

2026-10-24 21:05:29,643 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.03_min_samples10

2026-10-24 21:05:35,398 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.03_min_samples20

2026-10-24 21:05:41,315 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.03_min_samples30

2026-10-24 21:05:47,236 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.03_min_samples100

2026-10-24 21:05:53,018 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.035_min_samples2

2026-10-24 21:05:58,861 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.035_min_samples3

2026-10-24 21:06:04,510 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.035_min_samples5

2026-10-24 21:06:10,148 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.035_min_samples7

2026-10-24 21:06:15,967 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.035_min_samples10

2026-10-24 21:06:21,426 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.035_min_samples20

2026-10-24 21:06:26,849 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.035_min_samples30

2026-10-24 21:06:32,348 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.035_min_samples100

2026-10-24 21:06:37,802 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.04_min_samples2

2026-10-24 21:06:43,265 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.04_min_samples3

2026-10-24 21:06:48,739 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.04_min_samples5

2026-10-24 21:06:54,221 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.04_min_samples7

2026-10-24 21:06:59,722 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.04_min_samples10

2026-10-24 21:07:05,200 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.04_min_samples20

2026-10-24 21:07:10,667 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.04_min_samples30

2026-10-24 21:07:16,067 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.04_min_samples100

2026-10-24 21:07:21,482 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.05_min_samples2

2026-10-24 21:07:27,015 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.05_min_samples3

2026-10-24 21:07:32,481 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.05_min_samples5

2026-10-24 21:07:37,952 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.05_min_samples7

2026-10-24 21:07:43,368 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.05_min_samples10

2026-10-24 21:07:48,816 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.05_min_samples20

2026-10-24 21:07:54,320 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.05_min_samples30

2026-10-24 21:07:59,786 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.05_min_samples100

2026-10-24 21:08:05,304 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.07_min_samples2

2026-10-24 21:08:10,857 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.07_min_samples3

2026-10-24 21:08:16,378 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.07_min_samples5

2026-10-24 21:08:21,871 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.07_min_samples7

2026-10-24 21:08:27,848 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.07_min_samples10

2026-10-24 21:08:34,085 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.07_min_samples20

2026-10-24 21:08:39,939 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.07_min_samples30

2026-10-24 21:08:45,860 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.07_min_samples100

2026-10-24 21:08:51,569 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.1_min_samples2

2026-10-24 21:08:57,513 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.1_min_samples3

2026-10-24 21:09:03,237 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.1_min_samples5

2026-10-24 21:09:08,674 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.1_min_samples7

2026-10-24 21:09:14,161 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.1_min_samples10

2026-10-24 21:09:19,775 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.1_min_samples20

2026-10-24 21:09:25,298 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.1_min_samples30

2026-10-24 21:09:30,767 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.1_min_samples100

2026-10-24 21:09:36,282 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.5_min_samples2

2026-10-24 21:09:47,068 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.5_min_samples3

2026-10-24 21:09:57,567 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.5_min_samples5

2026-10-24 21:10:07,798 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.5_min_samples7

2026-10-24 21:10:17,712 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.5_min_samples10

2026-10-24 21:10:27,337 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.5_min_samples20

2026-10-24 21:10:35,736 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.5_min_samples30

2026-10-24 21:10:43,135 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps0.5_min_samples100

2026-10-24 21:10:48,728 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps1_min_samples2

2026-10-24 21:11:00,529 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps1_min_samples3

2026-10-24 21:11:12,249 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps1_min_samples5

2026-10-24 21:11:23,986 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps1_min_samples7

2026-10-24 21:11:36,119 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps1_min_samples10

2026-10-24 21:11:48,603 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps1_min_samples20

2026-10-24 21:12:00,382 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps1_min_samples30

2026-10-24 21:12:12,102 INFO Ajustando DBSCAN seed42_char_wb_3_10_min_df10_eps1_min_samples100

2026-10-24 21:12:23,832 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-24 21:12:24,559 INFO Analyzer=char_wb min_df=1 seed=42: 100000 termos, 0 vetores zerados

2026-10-24 21:12:24,559 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.01_min_samples2

2026-10-24 21:12:29,434 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.01_min_samples3

2026-10-24 21:12:34,389 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.01_min_samples5

2026-10-24 21:12:39,299 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.01_min_samples7

2026-10-24 21:12:44,199 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.01_min_samples10

2026-10-24 21:12:49,173 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.01_min_samples20

2026-10-24 21:12:54,116 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.01_min_samples30

2026-10-24 21:12:59,049 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.01_min_samples100

2026-10-24 21:13:03,983 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.02_min_samples2

2026-10-24 21:13:08,935 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.02_min_samples3

2026-10-24 21:13:13,814 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.02_min_samples5

2026-10-24 21:13:18,750 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.02_min_samples7

2026-10-24 21:13:23,649 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.02_min_samples10

2026-10-24 21:13:28,585 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.02_min_samples20

2026-10-24 21:13:33,522 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.02_min_samples30

2026-10-24 21:13:38,416 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.02_min_samples100

2026-10-24 21:13:43,366 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.025_min_samples2

2026-10-24 21:13:48,282 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.025_min_samples3

2026-10-24 21:13:53,178 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.025_min_samples5

2026-10-24 21:13:58,045 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.025_min_samples7

2026-10-24 21:14:02,998 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.025_min_samples10

2026-10-24 21:14:07,958 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.025_min_samples20

2026-10-24 21:14:12,879 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.025_min_samples30

2026-10-24 21:14:17,779 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.025_min_samples100

2026-10-24 21:14:22,686 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.03_min_samples2

2026-10-24 21:14:27,616 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.03_min_samples3

2026-10-24 21:14:32,568 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.03_min_samples5

2026-10-24 21:14:37,516 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.03_min_samples7

2026-10-24 21:14:42,460 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.03_min_samples10

2026-10-24 21:14:47,429 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.03_min_samples20

2026-10-24 21:14:52,583 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.03_min_samples30

2026-10-24 21:14:57,783 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.03_min_samples100

2026-10-24 21:15:03,003 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.035_min_samples2

2026-10-24 21:15:08,150 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.035_min_samples3

2026-10-24 21:15:13,504 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.035_min_samples5

2026-10-24 21:15:18,656 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.035_min_samples7

2026-10-24 21:15:24,131 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.035_min_samples10

2026-10-24 21:15:29,387 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.035_min_samples20

2026-10-24 21:15:34,383 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.035_min_samples30

2026-10-24 21:15:39,260 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.035_min_samples100

2026-10-24 21:15:44,006 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.04_min_samples2

2026-10-24 21:15:48,850 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.04_min_samples3

2026-10-24 21:15:53,775 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.04_min_samples5

2026-10-24 21:15:58,673 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.04_min_samples7

2026-10-24 21:16:03,607 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.04_min_samples10

2026-10-24 21:16:08,552 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.04_min_samples20

2026-10-24 21:16:13,432 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.04_min_samples30

2026-10-24 21:16:18,317 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.04_min_samples100

2026-10-24 21:16:23,250 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.05_min_samples2

2026-10-24 21:16:28,225 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.05_min_samples3

2026-10-24 21:16:33,150 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.05_min_samples5

2026-10-24 21:16:38,069 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.05_min_samples7

2026-10-24 21:16:42,969 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.05_min_samples10

2026-10-24 21:16:47,844 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.05_min_samples20

2026-10-24 21:16:52,744 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.05_min_samples30

2026-10-24 21:16:57,648 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.05_min_samples100

2026-10-24 21:17:02,584 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.07_min_samples2

2026-10-24 21:17:07,640 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.07_min_samples3

2026-10-24 21:17:12,538 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.07_min_samples5

2026-10-24 21:17:17,502 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.07_min_samples7

2026-10-24 21:17:22,458 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.07_min_samples10

2026-10-24 21:17:27,736 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.07_min_samples20

2026-10-24 21:17:32,918 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.07_min_samples30

2026-10-24 21:17:38,124 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.07_min_samples100

2026-10-24 21:17:43,489 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.1_min_samples2

2026-10-24 21:17:49,175 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.1_min_samples3

2026-10-24 21:17:54,450 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.1_min_samples5

2026-10-24 21:17:59,474 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.1_min_samples7

2026-10-24 21:18:04,356 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.1_min_samples10

2026-10-24 21:18:09,183 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.1_min_samples20

2026-10-24 21:18:14,146 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.1_min_samples30

2026-10-24 21:18:18,910 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.1_min_samples100

2026-10-24 21:18:23,741 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.5_min_samples2

2026-10-24 21:18:32,733 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.5_min_samples3

2026-10-24 21:18:41,423 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.5_min_samples5

2026-10-24 21:18:49,558 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.5_min_samples7

2026-10-24 21:18:57,237 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.5_min_samples10

2026-10-24 21:19:04,438 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.5_min_samples20

2026-10-24 21:19:10,950 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.5_min_samples30

2026-10-24 21:19:17,401 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps0.5_min_samples100

2026-10-24 21:19:22,712 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps1_min_samples2

2026-10-24 21:19:34,960 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps1_min_samples3

2026-10-24 21:19:47,050 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps1_min_samples5

2026-10-24 21:19:58,650 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps1_min_samples7

2026-10-24 21:20:09,728 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps1_min_samples10

2026-10-24 21:20:20,669 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps1_min_samples20

2026-10-24 21:20:31,742 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps1_min_samples30

2026-10-24 21:20:42,502 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df1_eps1_min_samples100

2026-10-24 21:20:53,606 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-24 21:20:54,347 INFO Analyzer=char_wb min_df=2 seed=42: 73051 termos, 0 vetores zerados

2026-10-24 21:20:54,347 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.01_min_samples2

2026-10-24 21:20:59,104 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.01_min_samples3

2026-10-24 21:21:03,857 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.01_min_samples5

2026-10-24 21:21:08,613 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.01_min_samples7

2026-10-24 21:21:13,309 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.01_min_samples10

2026-10-24 21:21:18,050 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.01_min_samples20

2026-10-24 21:21:22,812 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.01_min_samples30

2026-10-24 21:21:27,582 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.01_min_samples100

2026-10-24 21:21:32,350 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.02_min_samples2

2026-10-24 21:21:37,249 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.02_min_samples3

2026-10-24 21:21:42,551 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.02_min_samples5

2026-10-24 21:21:47,884 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.02_min_samples7

2026-10-24 21:21:53,251 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.02_min_samples10

2026-10-24 21:21:58,677 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.02_min_samples20

2026-10-24 21:22:04,095 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.02_min_samples30

2026-10-24 21:22:09,317 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.02_min_samples100

2026-10-24 21:22:14,884 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.025_min_samples2

2026-10-24 21:22:20,255 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.025_min_samples3

2026-10-24 21:22:25,968 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.025_min_samples5

2026-10-24 21:22:31,202 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.025_min_samples7

2026-10-24 21:22:36,418 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.025_min_samples10

2026-10-24 21:22:41,734 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.025_min_samples20

2026-10-24 21:22:46,884 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.025_min_samples30

2026-10-24 21:22:52,084 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.025_min_samples100

2026-10-24 21:22:56,918 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.03_min_samples2

2026-10-24 21:23:01,727 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.03_min_samples3

2026-10-24 21:23:06,470 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.03_min_samples5

2026-10-24 21:23:11,284 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.03_min_samples7

2026-10-24 21:23:16,009 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.03_min_samples10

2026-10-24 21:23:20,751 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.03_min_samples20

2026-10-24 21:23:25,484 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.03_min_samples30

2026-10-24 21:23:30,273 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.03_min_samples100

2026-10-24 21:23:35,051 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.035_min_samples2

2026-10-24 21:23:39,834 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.035_min_samples3

2026-10-24 21:23:44,619 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.035_min_samples5

2026-10-24 21:23:49,438 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.035_min_samples7

2026-10-24 21:23:54,375 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.035_min_samples10

2026-10-24 21:23:59,301 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.035_min_samples20

2026-10-24 21:24:04,451 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.035_min_samples30

2026-10-24 21:24:09,528 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.035_min_samples100

2026-10-24 21:24:15,011 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.04_min_samples2

2026-10-24 21:24:20,469 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.04_min_samples3

2026-10-24 21:24:25,916 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.04_min_samples5

2026-10-24 21:24:31,010 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.04_min_samples7

2026-10-24 21:24:36,180 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.04_min_samples10

2026-10-24 21:24:41,628 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.04_min_samples20

2026-10-24 21:24:46,706 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.04_min_samples30

2026-10-24 21:24:51,659 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.04_min_samples100

2026-10-24 21:24:56,506 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.05_min_samples2

2026-10-24 21:25:01,426 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.05_min_samples3

2026-10-24 21:25:06,318 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.05_min_samples5

2026-10-24 21:25:11,219 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.05_min_samples7

2026-10-24 21:25:16,090 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.05_min_samples10

2026-10-24 21:25:20,978 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.05_min_samples20

2026-10-24 21:25:25,858 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.05_min_samples30

2026-10-24 21:25:30,718 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.05_min_samples100

2026-10-24 21:25:35,601 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.07_min_samples2

2026-10-24 21:25:40,583 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.07_min_samples3

2026-10-24 21:25:45,451 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.07_min_samples5

2026-10-24 21:25:50,285 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.07_min_samples7

2026-10-24 21:25:55,171 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.07_min_samples10

2026-10-24 21:26:00,079 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.07_min_samples20

2026-10-24 21:26:04,984 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.07_min_samples30

2026-10-24 21:26:09,885 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.07_min_samples100

2026-10-24 21:26:14,764 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.1_min_samples2

2026-10-24 21:26:19,868 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.1_min_samples3

2026-10-24 21:26:24,756 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.1_min_samples5

2026-10-24 21:26:29,622 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.1_min_samples7

2026-10-24 21:26:34,579 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.1_min_samples10

2026-10-24 21:26:39,435 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.1_min_samples20

2026-10-24 21:26:44,320 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.1_min_samples30

2026-10-24 21:26:49,194 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.1_min_samples100

2026-10-24 21:26:54,112 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.5_min_samples2

2026-10-24 21:27:03,634 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.5_min_samples3

2026-10-24 21:27:12,813 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.5_min_samples5

2026-10-24 21:27:21,280 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.5_min_samples7

2026-10-24 21:27:29,444 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.5_min_samples10

2026-10-24 21:27:37,337 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.5_min_samples20

2026-10-24 21:27:44,323 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.5_min_samples30

2026-10-24 21:27:50,791 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps0.5_min_samples100

2026-10-24 21:27:56,116 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps1_min_samples2

2026-10-24 21:28:07,438 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps1_min_samples3

2026-10-24 21:28:18,681 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps1_min_samples5

2026-10-24 21:28:29,956 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps1_min_samples7

2026-10-24 21:28:41,385 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps1_min_samples10

2026-10-24 21:28:52,519 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps1_min_samples20

2026-10-24 21:29:03,757 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps1_min_samples30

2026-10-24 21:29:14,902 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df2_eps1_min_samples100

2026-10-24 21:29:26,218 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-24 21:29:27,121 INFO Analyzer=char_wb min_df=5 seed=42: 36185 termos, 3 vetores zerados

2026-10-24 21:29:27,121 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.01_min_samples2

2026-10-24 21:29:31,818 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.01_min_samples3

2026-10-24 21:29:36,642 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.01_min_samples5

2026-10-24 21:29:41,461 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.01_min_samples7

2026-10-24 21:29:46,257 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.01_min_samples10

2026-10-24 21:29:50,995 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.01_min_samples20

2026-10-24 21:29:55,806 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.01_min_samples30

2026-10-24 21:30:00,552 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.01_min_samples100

2026-10-24 21:30:05,312 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.02_min_samples2

2026-10-24 21:30:10,120 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.02_min_samples3

2026-10-24 21:30:14,944 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.02_min_samples5

2026-10-24 21:30:19,762 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.02_min_samples7

2026-10-24 21:30:24,531 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.02_min_samples10

2026-10-24 21:30:29,357 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.02_min_samples20

2026-10-24 21:30:34,219 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.02_min_samples30

2026-10-24 21:30:39,049 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.02_min_samples100

2026-10-24 21:30:43,885 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.025_min_samples2

2026-10-24 21:30:48,696 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.025_min_samples3

2026-10-24 21:30:53,485 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.025_min_samples5

2026-10-24 21:30:58,346 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.025_min_samples7

2026-10-24 21:31:03,165 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.025_min_samples10

2026-10-24 21:31:07,999 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.025_min_samples20

2026-10-24 21:31:12,801 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.025_min_samples30

2026-10-24 21:31:17,621 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.025_min_samples100

2026-10-24 21:31:22,451 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.03_min_samples2

2026-10-24 21:31:27,285 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.03_min_samples3

2026-10-24 21:31:32,118 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.03_min_samples5

2026-10-24 21:31:36,847 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.03_min_samples7

2026-10-24 21:31:41,672 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.03_min_samples10

2026-10-24 21:31:46,458 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.03_min_samples20

2026-10-24 21:31:51,221 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.03_min_samples30

2026-10-24 21:31:56,044 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.03_min_samples100

2026-10-24 21:32:01,175 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.035_min_samples2

2026-10-24 21:32:06,315 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.035_min_samples3

2026-10-24 21:32:11,356 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.035_min_samples5

2026-10-24 21:32:16,777 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.035_min_samples7

2026-10-24 21:32:22,119 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.035_min_samples10

2026-10-24 21:32:27,457 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.035_min_samples20

2026-10-24 21:32:32,551 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.035_min_samples30

2026-10-24 21:32:37,560 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.035_min_samples100

2026-10-24 21:32:42,490 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.04_min_samples2

2026-10-24 21:32:47,355 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.04_min_samples3

2026-10-24 21:32:52,118 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.04_min_samples5

2026-10-24 21:32:56,885 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.04_min_samples7

2026-10-24 21:33:01,589 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.04_min_samples10

2026-10-24 21:33:06,357 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.04_min_samples20

2026-10-24 21:33:11,119 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.04_min_samples30

2026-10-24 21:33:15,903 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.04_min_samples100

2026-10-24 21:33:20,652 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.05_min_samples2

2026-10-24 21:33:25,519 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.05_min_samples3

2026-10-24 21:33:30,379 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.05_min_samples5

2026-10-24 21:33:35,219 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.05_min_samples7

2026-10-24 21:33:40,040 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.05_min_samples10

2026-10-24 21:33:44,835 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.05_min_samples20

2026-10-24 21:33:49,642 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.05_min_samples30

2026-10-24 21:33:54,396 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.05_min_samples100

2026-10-24 21:33:59,210 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.07_min_samples2

2026-10-24 21:34:04,138 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.07_min_samples3

2026-10-24 21:34:09,028 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.07_min_samples5

2026-10-24 21:34:13,826 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.07_min_samples7

2026-10-24 21:34:18,619 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.07_min_samples10

2026-10-24 21:34:23,519 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.07_min_samples20

2026-10-24 21:34:28,777 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.07_min_samples30

2026-10-24 21:34:34,103 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.07_min_samples100

2026-10-24 21:34:39,152 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.1_min_samples2

2026-10-24 21:34:44,707 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.1_min_samples3

2026-10-24 21:34:49,960 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.1_min_samples5

2026-10-24 21:34:55,058 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.1_min_samples7

2026-10-24 21:34:59,872 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.1_min_samples10

2026-10-24 21:35:04,665 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.1_min_samples20

2026-10-24 21:35:09,419 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.1_min_samples30

2026-10-24 21:35:14,169 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.1_min_samples100

2026-10-24 21:35:18,952 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.5_min_samples2

2026-10-24 21:35:28,607 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.5_min_samples3

2026-10-24 21:35:38,152 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.5_min_samples5

2026-10-24 21:35:47,329 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.5_min_samples7

2026-10-24 21:35:56,130 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.5_min_samples10

2026-10-24 21:36:04,394 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.5_min_samples20

2026-10-24 21:36:11,445 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.5_min_samples30

2026-10-24 21:36:17,540 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps0.5_min_samples100

2026-10-24 21:36:22,369 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps1_min_samples2

2026-10-24 21:36:33,589 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps1_min_samples3

2026-10-24 21:36:44,720 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps1_min_samples5

2026-10-24 21:36:55,919 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps1_min_samples7

2026-10-24 21:37:07,186 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps1_min_samples10

2026-10-24 21:37:18,352 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps1_min_samples20

2026-10-24 21:37:29,377 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps1_min_samples30

2026-10-24 21:37:40,619 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df5_eps1_min_samples100

2026-10-24 21:37:51,833 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-24 21:37:52,554 INFO Analyzer=char_wb min_df=10 seed=42: 21744 termos, 6 vetores zerados

2026-10-24 21:37:52,554 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.01_min_samples2

2026-10-24 21:37:57,218 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.01_min_samples3

2026-10-24 21:38:01,936 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.01_min_samples5

2026-10-24 21:38:06,646 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.01_min_samples7

2026-10-24 21:38:11,383 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.01_min_samples10

2026-10-24 21:38:16,087 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.01_min_samples20

2026-10-24 21:38:20,818 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.01_min_samples30

2026-10-24 21:38:25,510 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.01_min_samples100

2026-10-24 21:38:30,193 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.02_min_samples2

2026-10-24 21:38:34,918 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.02_min_samples3

2026-10-24 21:38:39,636 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.02_min_samples5

2026-10-24 21:38:44,357 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.02_min_samples7

2026-10-24 21:38:49,086 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.02_min_samples10

2026-10-24 21:38:53,620 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.02_min_samples20

2026-10-24 21:38:58,176 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.02_min_samples30

2026-10-24 21:39:02,753 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.02_min_samples100

2026-10-24 21:39:07,375 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.025_min_samples2

2026-10-24 21:39:11,952 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.025_min_samples3

2026-10-24 21:39:16,486 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.025_min_samples5

2026-10-24 21:39:20,986 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.025_min_samples7

2026-10-24 21:39:25,586 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.025_min_samples10

2026-10-24 21:39:30,153 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.025_min_samples20

2026-10-24 21:39:34,783 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.025_min_samples30

2026-10-24 21:39:39,389 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.025_min_samples100

2026-10-24 21:39:43,978 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.03_min_samples2

2026-10-24 21:39:48,617 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.03_min_samples3

2026-10-24 21:39:53,186 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.03_min_samples5

2026-10-24 21:39:57,750 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.03_min_samples7

2026-10-24 21:40:02,320 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.03_min_samples10

2026-10-24 21:40:06,853 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.03_min_samples20

2026-10-24 21:40:11,739 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.03_min_samples30

2026-10-24 21:40:16,936 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.03_min_samples100

2026-10-24 21:40:21,948 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.035_min_samples2

2026-10-24 21:40:27,003 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.035_min_samples3

2026-10-24 21:40:32,020 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.035_min_samples5

2026-10-24 21:40:37,117 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.035_min_samples7

2026-10-24 21:40:42,409 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.035_min_samples10

2026-10-24 21:40:47,279 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.035_min_samples20

2026-10-24 21:40:52,884 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.035_min_samples30

2026-10-24 21:40:57,920 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.035_min_samples100

2026-10-24 21:41:02,966 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.04_min_samples2

2026-10-24 21:41:08,020 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.04_min_samples3

2026-10-24 21:41:13,119 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.04_min_samples5

2026-10-24 21:41:18,062 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.04_min_samples7

2026-10-24 21:41:23,117 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.04_min_samples10

2026-10-24 21:41:28,081 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.04_min_samples20

2026-10-24 21:41:32,870 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.04_min_samples30

2026-10-24 21:41:37,924 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.04_min_samples100

2026-10-24 21:41:42,639 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.05_min_samples2

2026-10-24 21:41:47,353 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.05_min_samples3

2026-10-24 21:41:51,946 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.05_min_samples5

2026-10-24 21:41:56,453 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.05_min_samples7

2026-10-24 21:42:01,159 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.05_min_samples10

2026-10-24 21:42:05,742 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.05_min_samples20

2026-10-24 21:42:10,385 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.05_min_samples30

2026-10-24 21:42:14,853 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.05_min_samples100

2026-10-24 21:42:19,703 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.07_min_samples2

2026-10-24 21:42:25,097 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.07_min_samples3

2026-10-24 21:42:30,039 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.07_min_samples5

2026-10-24 21:42:35,214 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.07_min_samples7

2026-10-24 21:42:40,288 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.07_min_samples10

2026-10-24 21:42:45,523 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.07_min_samples20

2026-10-24 21:42:50,554 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.07_min_samples30

2026-10-24 21:42:55,818 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.07_min_samples100

2026-10-24 21:43:01,004 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.1_min_samples2

2026-10-24 21:43:06,388 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.1_min_samples3

2026-10-24 21:43:11,561 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.1_min_samples5

2026-10-24 21:43:16,320 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.1_min_samples7

2026-10-24 21:43:20,930 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.1_min_samples10

2026-10-24 21:43:25,524 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.1_min_samples20

2026-10-24 21:43:29,987 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.1_min_samples30

2026-10-24 21:43:34,587 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.1_min_samples100

2026-10-24 21:43:39,159 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.5_min_samples2

2026-10-24 21:43:48,487 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.5_min_samples3

2026-10-24 21:43:57,640 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.5_min_samples5

2026-10-24 21:44:06,634 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.5_min_samples7

2026-10-24 21:44:15,475 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.5_min_samples10

2026-10-24 21:44:23,978 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.5_min_samples20

2026-10-24 21:44:31,955 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.5_min_samples30

2026-10-24 21:44:39,139 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps0.5_min_samples100

2026-10-24 21:44:44,787 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps1_min_samples2

2026-10-24 21:44:56,098 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps1_min_samples3

2026-10-24 21:45:07,545 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps1_min_samples5

2026-10-24 21:45:18,900 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps1_min_samples7

2026-10-24 21:45:30,093 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps1_min_samples10

2026-10-24 21:45:41,258 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps1_min_samples20

2026-10-24 21:45:52,340 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps1_min_samples30

2026-10-24 21:46:03,421 INFO Ajustando DBSCAN seed42_char_wb_4_8_min_df10_eps1_min_samples100

2026-10-24 21:46:14,321 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-24 21:46:15,150 INFO Analyzer=char_wb min_df=1 seed=42: 100000 termos, 0 vetores zerados

2026-10-24 21:46:15,150 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.01_min_samples2

2026-10-24 21:46:20,054 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.01_min_samples3

2026-10-24 21:46:25,054 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.01_min_samples5

2026-10-24 21:46:30,043 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.01_min_samples7

2026-10-24 21:46:35,034 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.01_min_samples10

2026-10-24 21:46:40,037 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.01_min_samples20

2026-10-24 21:46:44,971 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.01_min_samples30

2026-10-24 21:46:49,921 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.01_min_samples100

2026-10-24 21:46:54,890 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.02_min_samples2

2026-10-24 21:46:59,871 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.02_min_samples3

2026-10-24 21:47:04,877 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.02_min_samples5

2026-10-24 21:47:09,924 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.02_min_samples7

2026-10-24 21:47:14,888 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.02_min_samples10

2026-10-24 21:47:19,887 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.02_min_samples20

2026-10-24 21:47:24,911 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.02_min_samples30

2026-10-24 21:47:29,887 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.02_min_samples100

2026-10-24 21:47:34,929 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.025_min_samples2

2026-10-24 21:47:39,917 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.025_min_samples3

2026-10-24 21:47:44,927 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.025_min_samples5

2026-10-24 21:47:49,896 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.025_min_samples7

2026-10-24 21:47:54,925 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.025_min_samples10

2026-10-24 21:47:59,918 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.025_min_samples20

2026-10-24 21:48:04,915 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.025_min_samples30

2026-10-24 21:48:09,921 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.025_min_samples100

2026-10-24 21:48:14,938 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.03_min_samples2

2026-10-24 21:48:19,972 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.03_min_samples3

2026-10-24 21:48:24,974 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.03_min_samples5

2026-10-24 21:48:30,013 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.03_min_samples7

2026-10-24 21:48:35,020 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.03_min_samples10

2026-10-24 21:48:40,254 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.03_min_samples20

2026-10-24 21:48:45,616 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.03_min_samples30

2026-10-24 21:48:50,973 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.03_min_samples100

2026-10-24 21:48:56,287 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.035_min_samples2

2026-10-24 21:49:01,610 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.035_min_samples3

2026-10-24 21:49:06,872 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.035_min_samples5

2026-10-24 21:49:12,138 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.035_min_samples7

2026-10-24 21:49:17,607 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.035_min_samples10

2026-10-24 21:49:22,754 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.035_min_samples20

2026-10-24 21:49:27,754 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.035_min_samples30

2026-10-24 21:49:32,722 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.035_min_samples100

2026-10-24 21:49:37,717 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.04_min_samples2

2026-10-24 21:49:42,749 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.04_min_samples3

2026-10-24 21:49:47,721 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.04_min_samples5

2026-10-24 21:49:52,690 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.04_min_samples7

2026-10-24 21:49:57,711 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.04_min_samples10

2026-10-24 21:50:02,713 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.04_min_samples20

2026-10-24 21:50:07,710 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.04_min_samples30

2026-10-24 21:50:12,719 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.04_min_samples100

2026-10-24 21:50:17,771 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.05_min_samples2

2026-10-24 21:50:22,806 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.05_min_samples3

2026-10-24 21:50:27,789 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.05_min_samples5

2026-10-24 21:50:32,797 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.05_min_samples7

2026-10-24 21:50:37,814 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.05_min_samples10

2026-10-24 21:50:42,847 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.05_min_samples20

2026-10-24 21:50:47,858 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.05_min_samples30

2026-10-24 21:50:52,912 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.05_min_samples100

2026-10-24 21:50:57,921 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.07_min_samples2

2026-10-24 21:51:03,044 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.07_min_samples3

2026-10-24 21:51:08,088 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.07_min_samples5

2026-10-24 21:51:13,079 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.07_min_samples7

2026-10-24 21:51:18,108 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.07_min_samples10

2026-10-24 21:51:23,116 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.07_min_samples20

2026-10-24 21:51:28,189 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.07_min_samples30

2026-10-24 21:51:33,228 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.07_min_samples100

2026-10-24 21:51:38,737 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.1_min_samples2

2026-10-24 21:51:44,571 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.1_min_samples3

2026-10-24 21:51:50,096 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.1_min_samples5

2026-10-24 21:51:55,671 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.1_min_samples7

2026-10-24 21:52:00,997 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.1_min_samples10

2026-10-24 21:52:06,277 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.1_min_samples20

2026-10-24 21:52:11,405 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.1_min_samples30

2026-10-24 21:52:16,546 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.1_min_samples100

2026-10-24 21:52:21,670 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.5_min_samples2

2026-10-24 21:52:31,359 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.5_min_samples3

2026-10-24 21:52:40,455 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.5_min_samples5

2026-10-24 21:52:48,975 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.5_min_samples7

2026-10-24 21:52:57,103 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.5_min_samples10

2026-10-24 21:53:04,716 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.5_min_samples20

2026-10-24 21:53:11,214 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.5_min_samples30

2026-10-24 21:53:17,046 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps0.5_min_samples100

2026-10-24 21:53:22,096 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps1_min_samples2

2026-10-24 21:53:33,483 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps1_min_samples3

2026-10-24 21:53:44,909 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps1_min_samples5

2026-10-24 21:53:56,088 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps1_min_samples7

2026-10-24 21:54:07,522 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps1_min_samples10

2026-10-24 21:54:18,955 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps1_min_samples20

2026-10-24 21:54:30,456 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps1_min_samples30

2026-10-24 21:54:41,840 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df1_eps1_min_samples100

2026-10-24 21:54:53,317 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-24 21:54:54,153 INFO Analyzer=char_wb min_df=2 seed=42: 82710 termos, 0 vetores zerados

2026-10-24 21:54:54,154 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.01_min_samples2

2026-10-24 21:54:59,172 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.01_min_samples3

2026-10-24 21:55:04,150 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.01_min_samples5

2026-10-24 21:55:09,160 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.01_min_samples7

2026-10-24 21:55:14,074 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.01_min_samples10

2026-10-24 21:55:19,108 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.01_min_samples20

2026-10-24 21:55:24,044 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.01_min_samples30

2026-10-24 21:55:29,028 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.01_min_samples100

2026-10-24 21:55:34,055 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.02_min_samples2

2026-10-24 21:55:39,072 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.02_min_samples3

2026-10-24 21:55:44,022 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.02_min_samples5

2026-10-24 21:55:49,040 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.02_min_samples7

2026-10-24 21:55:53,972 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.02_min_samples10

2026-10-24 21:55:58,948 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.02_min_samples20

2026-10-24 21:56:03,963 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.02_min_samples30

2026-10-24 21:56:08,951 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.02_min_samples100

2026-10-24 21:56:13,914 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.025_min_samples2

2026-10-24 21:56:18,907 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.025_min_samples3

2026-10-24 21:56:23,922 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.025_min_samples5

2026-10-24 21:56:28,947 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.025_min_samples7

2026-10-24 21:56:33,891 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.025_min_samples10

2026-10-24 21:56:38,843 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.025_min_samples20

2026-10-24 21:56:43,789 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.025_min_samples30

2026-10-24 21:56:48,741 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.025_min_samples100

2026-10-24 21:56:53,722 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.03_min_samples2

2026-10-24 21:56:58,713 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.03_min_samples3

2026-10-24 21:57:03,702 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.03_min_samples5

2026-10-24 21:57:08,656 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.03_min_samples7

2026-10-24 21:57:13,638 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.03_min_samples10

2026-10-24 21:57:18,638 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.03_min_samples20

2026-10-24 21:57:23,622 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.03_min_samples30

2026-10-24 21:57:28,564 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.03_min_samples100

2026-10-24 21:57:33,598 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.035_min_samples2

2026-10-24 21:57:38,619 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.035_min_samples3

2026-10-24 21:57:43,622 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.035_min_samples5

2026-10-24 21:57:48,589 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.035_min_samples7

2026-10-24 21:57:53,622 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.035_min_samples10

2026-10-24 21:57:58,641 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.035_min_samples20

2026-10-24 21:58:03,782 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.035_min_samples30

2026-10-24 21:58:09,007 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.035_min_samples100

2026-10-24 21:58:14,452 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.04_min_samples2

2026-10-24 21:58:19,711 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.04_min_samples3

2026-10-24 21:58:25,227 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.04_min_samples5

2026-10-24 21:58:30,632 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.04_min_samples7

2026-10-24 21:58:36,022 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.04_min_samples10

2026-10-24 21:58:41,073 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.04_min_samples20

2026-10-24 21:58:46,080 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.04_min_samples30

2026-10-24 21:58:51,022 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.04_min_samples100

2026-10-24 21:58:55,986 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.05_min_samples2

2026-10-24 21:59:00,972 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.05_min_samples3

2026-10-24 21:59:05,982 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.05_min_samples5

2026-10-24 21:59:10,940 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.05_min_samples7

2026-10-24 21:59:15,823 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.05_min_samples10

2026-10-24 21:59:20,752 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.05_min_samples20

2026-10-24 21:59:25,725 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.05_min_samples30

2026-10-24 21:59:30,711 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.05_min_samples100

2026-10-24 21:59:35,696 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.07_min_samples2

2026-10-24 21:59:40,789 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.07_min_samples3

2026-10-24 21:59:45,756 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.07_min_samples5

2026-10-24 21:59:50,586 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.07_min_samples7

2026-10-24 21:59:55,423 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.07_min_samples10

2026-10-24 22:00:00,250 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.07_min_samples20

2026-10-24 22:00:05,084 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.07_min_samples30

2026-10-24 22:00:09,923 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.07_min_samples100

2026-10-24 22:00:14,755 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.1_min_samples2

2026-10-24 22:00:19,791 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.1_min_samples3

2026-10-24 22:00:24,693 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.1_min_samples5

2026-10-24 22:00:29,558 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.1_min_samples7

2026-10-24 22:00:34,446 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.1_min_samples10

2026-10-24 22:00:39,310 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.1_min_samples20

2026-10-24 22:00:44,198 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.1_min_samples30

2026-10-24 22:00:49,049 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.1_min_samples100

2026-10-24 22:00:53,856 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.5_min_samples2

2026-10-24 22:01:03,347 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.5_min_samples3

2026-10-24 22:01:12,923 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.5_min_samples5

2026-10-24 22:01:22,290 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.5_min_samples7

2026-10-24 22:01:31,256 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.5_min_samples10

2026-10-24 22:01:39,772 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.5_min_samples20

2026-10-24 22:01:47,116 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.5_min_samples30

2026-10-24 22:01:53,806 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps0.5_min_samples100

2026-10-24 22:01:59,253 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps1_min_samples2

2026-10-24 22:02:11,258 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps1_min_samples3

2026-10-24 22:02:23,689 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps1_min_samples5

2026-10-24 22:02:34,941 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps1_min_samples7

2026-10-24 22:02:46,290 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps1_min_samples10

2026-10-24 22:02:57,423 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps1_min_samples20

2026-10-24 22:03:08,823 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps1_min_samples30

2026-10-24 22:03:19,975 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df2_eps1_min_samples100

2026-10-24 22:03:31,116 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-24 22:03:31,940 INFO Analyzer=char_wb min_df=5 seed=42: 40332 termos, 3 vetores zerados

2026-10-24 22:03:31,940 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.01_min_samples2

2026-10-24 22:03:36,690 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.01_min_samples3

2026-10-24 22:03:41,463 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.01_min_samples5

2026-10-24 22:03:46,241 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.01_min_samples7

2026-10-24 22:03:51,009 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.01_min_samples10

2026-10-24 22:03:55,740 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.01_min_samples20

2026-10-24 22:04:00,498 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.01_min_samples30

2026-10-24 22:04:05,257 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.01_min_samples100

2026-10-24 22:04:10,081 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.02_min_samples2

2026-10-24 22:04:14,848 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.02_min_samples3

2026-10-24 22:04:19,657 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.02_min_samples5

2026-10-24 22:04:24,377 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.02_min_samples7

2026-10-24 22:04:29,160 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.02_min_samples10

2026-10-24 22:04:33,923 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.02_min_samples20

2026-10-24 22:04:39,048 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.02_min_samples30

2026-10-24 22:04:44,794 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.02_min_samples100

2026-10-24 22:04:50,051 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.025_min_samples2

2026-10-24 22:04:55,399 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.025_min_samples3

2026-10-24 22:05:00,624 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.025_min_samples5

2026-10-24 22:05:05,939 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.025_min_samples7

2026-10-24 22:05:11,088 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.025_min_samples10

2026-10-24 22:05:16,283 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.025_min_samples20

2026-10-24 22:05:21,474 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.025_min_samples30

2026-10-24 22:05:26,832 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.025_min_samples100

2026-10-24 22:05:32,373 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.03_min_samples2

2026-10-24 22:05:37,521 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.03_min_samples3

2026-10-24 22:05:42,559 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.03_min_samples5

2026-10-24 22:05:47,776 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.03_min_samples7

2026-10-24 22:05:52,844 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.03_min_samples10

2026-10-24 22:05:57,884 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.03_min_samples20

2026-10-24 22:06:02,790 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.03_min_samples30

2026-10-24 22:06:07,673 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.03_min_samples100

2026-10-24 22:06:12,524 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.035_min_samples2

2026-10-24 22:06:17,405 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.035_min_samples3

2026-10-24 22:06:22,257 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.035_min_samples5

2026-10-24 22:06:27,154 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.035_min_samples7

2026-10-24 22:06:32,065 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.035_min_samples10

2026-10-24 22:06:36,950 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.035_min_samples20

2026-10-24 22:06:41,811 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.035_min_samples30

2026-10-24 22:06:46,625 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.035_min_samples100

2026-10-24 22:06:51,378 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.04_min_samples2

2026-10-24 22:06:56,291 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.04_min_samples3

2026-10-24 22:07:01,167 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.04_min_samples5

2026-10-24 22:07:06,014 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.04_min_samples7

2026-10-24 22:07:10,814 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.04_min_samples10

2026-10-24 22:07:15,584 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.04_min_samples20

2026-10-24 22:07:20,374 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.04_min_samples30

2026-10-24 22:07:25,125 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.04_min_samples100

2026-10-24 22:07:29,933 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.05_min_samples2

2026-10-24 22:07:35,332 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.05_min_samples3

2026-10-24 22:07:40,645 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.05_min_samples5

2026-10-24 22:07:46,141 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.05_min_samples7

2026-10-24 22:07:51,657 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.05_min_samples10

2026-10-24 22:07:57,046 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.05_min_samples20

2026-10-24 22:08:02,219 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.05_min_samples30

2026-10-24 22:08:07,397 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.05_min_samples100

2026-10-24 22:08:12,586 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.07_min_samples2

2026-10-24 22:08:17,927 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.07_min_samples3

2026-10-24 22:08:22,991 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.07_min_samples5

2026-10-24 22:08:28,151 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.07_min_samples7

2026-10-24 22:08:33,244 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.07_min_samples10

2026-10-24 22:08:38,094 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.07_min_samples20

2026-10-24 22:08:42,985 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.07_min_samples30

2026-10-24 22:08:47,881 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.07_min_samples100

2026-10-24 22:08:52,805 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.1_min_samples2

2026-10-24 22:08:57,940 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.1_min_samples3

2026-10-24 22:09:02,853 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.1_min_samples5

2026-10-24 22:09:07,724 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.1_min_samples7

2026-10-24 22:09:12,553 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.1_min_samples10

2026-10-24 22:09:17,423 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.1_min_samples20

2026-10-24 22:09:22,282 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.1_min_samples30

2026-10-24 22:09:27,186 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.1_min_samples100

2026-10-24 22:09:32,049 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.5_min_samples2

2026-10-24 22:09:41,949 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.5_min_samples3

2026-10-24 22:09:51,635 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.5_min_samples5

2026-10-24 22:10:01,039 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.5_min_samples7

2026-10-24 22:10:10,041 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.5_min_samples10

2026-10-24 22:10:18,521 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.5_min_samples20

2026-10-24 22:10:25,791 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.5_min_samples30

2026-10-24 22:10:32,175 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps0.5_min_samples100

2026-10-24 22:10:37,163 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps1_min_samples2

2026-10-24 22:10:48,619 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps1_min_samples3

2026-10-24 22:11:00,086 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps1_min_samples5

2026-10-24 22:11:11,408 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps1_min_samples7

2026-10-24 22:11:22,763 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps1_min_samples10

2026-10-24 22:11:34,074 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps1_min_samples20

2026-10-24 22:11:45,510 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps1_min_samples30

2026-10-24 22:11:56,708 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df5_eps1_min_samples100

2026-10-24 22:12:08,072 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-24 22:12:08,886 INFO Analyzer=char_wb min_df=10 seed=42: 23938 termos, 6 vetores zerados

2026-10-24 22:12:08,887 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.01_min_samples2

2026-10-24 22:12:13,686 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.01_min_samples3

2026-10-24 22:12:18,475 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.01_min_samples5

2026-10-24 22:12:23,357 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.01_min_samples7

2026-10-24 22:12:28,186 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.01_min_samples10

2026-10-24 22:12:32,987 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.01_min_samples20

2026-10-24 22:12:37,774 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.01_min_samples30

2026-10-24 22:12:42,542 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.01_min_samples100

2026-10-24 22:12:47,358 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.02_min_samples2

2026-10-24 22:12:52,189 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.02_min_samples3

2026-10-24 22:12:57,029 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.02_min_samples5

2026-10-24 22:13:01,807 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.02_min_samples7

2026-10-24 22:13:06,647 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.02_min_samples10

2026-10-24 22:13:11,424 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.02_min_samples20

2026-10-24 22:13:16,187 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.02_min_samples30

2026-10-24 22:13:20,994 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.02_min_samples100

2026-10-24 22:13:25,802 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.025_min_samples2

2026-10-24 22:13:30,625 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.025_min_samples3

2026-10-24 22:13:35,424 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.025_min_samples5

2026-10-24 22:13:40,277 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.025_min_samples7

2026-10-24 22:13:45,043 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.025_min_samples10

2026-10-24 22:13:49,841 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.025_min_samples20

2026-10-24 22:13:54,608 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.025_min_samples30

2026-10-24 22:13:59,446 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.025_min_samples100

2026-10-24 22:14:04,258 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.03_min_samples2

2026-10-24 22:14:09,109 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.03_min_samples3

2026-10-24 22:14:13,886 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.03_min_samples5

2026-10-24 22:14:18,725 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.03_min_samples7

2026-10-24 22:14:23,492 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.03_min_samples10

2026-10-24 22:14:28,281 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.03_min_samples20

2026-10-24 22:14:33,087 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.03_min_samples30

2026-10-24 22:14:38,061 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.03_min_samples100

2026-10-24 22:14:43,417 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.035_min_samples2

2026-10-24 22:14:48,512 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.035_min_samples3

2026-10-24 22:14:53,526 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.035_min_samples5

2026-10-24 22:14:58,629 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.035_min_samples7

2026-10-24 22:15:03,625 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.035_min_samples10

2026-10-24 22:15:08,564 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.035_min_samples20

2026-10-24 22:15:13,624 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.035_min_samples30

2026-10-24 22:15:18,390 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.035_min_samples100

2026-10-24 22:15:23,351 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.04_min_samples2

2026-10-24 22:15:28,316 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.04_min_samples3

2026-10-24 22:15:33,091 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.04_min_samples5

2026-10-24 22:15:37,902 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.04_min_samples7

2026-10-24 22:15:42,683 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.04_min_samples10

2026-10-24 22:15:47,493 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.04_min_samples20

2026-10-24 22:15:52,291 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.04_min_samples30

2026-10-24 22:15:57,095 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.04_min_samples100

2026-10-24 22:16:01,844 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.05_min_samples2

2026-10-24 22:16:06,758 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.05_min_samples3

2026-10-24 22:16:11,513 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.05_min_samples5

2026-10-24 22:16:16,301 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.05_min_samples7

2026-10-24 22:16:21,092 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.05_min_samples10

2026-10-24 22:16:25,874 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.05_min_samples20

2026-10-24 22:16:30,647 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.05_min_samples30

2026-10-24 22:16:35,411 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.05_min_samples100

2026-10-24 22:16:40,237 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.07_min_samples2

2026-10-24 22:16:45,205 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.07_min_samples3

2026-10-24 22:16:50,059 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.07_min_samples5

2026-10-24 22:16:54,847 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.07_min_samples7

2026-10-24 22:16:59,593 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.07_min_samples10

2026-10-24 22:17:04,360 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.07_min_samples20

2026-10-24 22:17:09,175 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.07_min_samples30

2026-10-24 22:17:13,981 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.07_min_samples100

2026-10-24 22:17:18,792 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.1_min_samples2

2026-10-24 22:17:23,990 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.1_min_samples3

2026-10-24 22:17:28,954 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.1_min_samples5

2026-10-24 22:17:33,811 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.1_min_samples7

2026-10-24 22:17:38,641 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.1_min_samples10

2026-10-24 22:17:43,425 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.1_min_samples20

2026-10-24 22:17:48,192 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.1_min_samples30

2026-10-24 22:17:53,034 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.1_min_samples100

2026-10-24 22:17:58,247 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.5_min_samples2

2026-10-24 22:18:08,569 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.5_min_samples3

2026-10-24 22:18:18,865 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.5_min_samples5

2026-10-24 22:18:28,869 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.5_min_samples7

2026-10-24 22:18:38,130 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.5_min_samples10

2026-10-24 22:18:46,998 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.5_min_samples20

2026-10-24 22:18:54,900 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.5_min_samples30

2026-10-24 22:19:01,846 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps0.5_min_samples100

2026-10-24 22:19:06,859 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps1_min_samples2

2026-10-24 22:19:18,216 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps1_min_samples3

2026-10-24 22:19:29,413 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps1_min_samples5

2026-10-24 22:19:40,743 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps1_min_samples7

2026-10-24 22:19:52,033 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps1_min_samples10

2026-10-24 22:20:03,396 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps1_min_samples20

2026-10-24 22:20:14,627 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps1_min_samples30

2026-10-24 22:20:25,809 INFO Ajustando DBSCAN seed42_char_wb_4_10_min_df10_eps1_min_samples100

2026-10-24 22:20:37,097 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-24 22:20:37,722 INFO Analyzer=char_wb min_df=1 seed=42: 100000 termos, 1 vetores zerados

2026-10-24 22:20:37,723 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.01_min_samples2

2026-10-24 22:20:42,231 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.01_min_samples3

2026-10-24 22:20:46,744 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.01_min_samples5

2026-10-24 22:20:51,148 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.01_min_samples7

2026-10-24 22:20:55,613 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.01_min_samples10

2026-10-24 22:21:00,055 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.01_min_samples20

2026-10-24 22:21:04,511 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.01_min_samples30

2026-10-24 22:21:08,955 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.01_min_samples100

2026-10-24 22:21:13,368 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.02_min_samples2

2026-10-24 22:21:17,822 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.02_min_samples3

2026-10-24 22:21:22,225 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.02_min_samples5

2026-10-24 22:21:26,693 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.02_min_samples7

2026-10-24 22:21:31,159 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.02_min_samples10

2026-10-24 22:21:35,559 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.02_min_samples20

2026-10-24 22:21:40,008 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.02_min_samples30

2026-10-24 22:21:44,426 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.02_min_samples100

2026-10-24 22:21:48,855 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.025_min_samples2

2026-10-24 22:21:53,294 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.025_min_samples3

2026-10-24 22:21:57,726 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.025_min_samples5

2026-10-24 22:22:02,242 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.025_min_samples7

2026-10-24 22:22:06,730 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.025_min_samples10

2026-10-24 22:22:11,217 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.025_min_samples20

2026-10-24 22:22:15,723 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.025_min_samples30

2026-10-24 22:22:20,226 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.025_min_samples100

2026-10-24 22:22:24,659 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.03_min_samples2

2026-10-24 22:22:29,526 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.03_min_samples3

2026-10-24 22:22:34,426 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.03_min_samples5

2026-10-24 22:22:39,579 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.03_min_samples7

2026-10-24 22:22:44,493 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.03_min_samples10

2026-10-24 22:22:49,359 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.03_min_samples20

2026-10-24 22:22:54,595 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.03_min_samples30

2026-10-24 22:22:59,516 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.03_min_samples100

2026-10-24 22:23:04,310 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.035_min_samples2

2026-10-24 22:23:09,486 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.035_min_samples3

2026-10-24 22:23:14,553 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.035_min_samples5

2026-10-24 22:23:19,316 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.035_min_samples7

2026-10-24 22:23:24,126 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.035_min_samples10

2026-10-24 22:23:28,948 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.035_min_samples20

2026-10-24 22:23:33,847 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.035_min_samples30

2026-10-24 22:23:38,653 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.035_min_samples100

2026-10-24 22:23:43,493 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.04_min_samples2

2026-10-24 22:23:48,282 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.04_min_samples3

2026-10-24 22:23:53,078 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.04_min_samples5

2026-10-24 22:23:58,100 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.04_min_samples7

2026-10-24 22:24:02,596 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.04_min_samples10

2026-10-24 22:24:07,026 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.04_min_samples20

2026-10-24 22:24:11,408 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.04_min_samples30

2026-10-24 22:24:15,777 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.04_min_samples100

2026-10-24 22:24:20,076 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.05_min_samples2

2026-10-24 22:24:24,511 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.05_min_samples3

2026-10-24 22:24:28,952 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.05_min_samples5

2026-10-24 22:24:33,285 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.05_min_samples7

2026-10-24 22:24:37,790 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.05_min_samples10

2026-10-24 22:24:42,259 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.05_min_samples20

2026-10-24 22:24:46,720 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.05_min_samples30

2026-10-24 22:24:51,218 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.05_min_samples100

2026-10-24 22:24:55,693 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.07_min_samples2

2026-10-24 22:25:00,300 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.07_min_samples3

2026-10-24 22:25:04,776 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.07_min_samples5

2026-10-24 22:25:09,482 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.07_min_samples7

2026-10-24 22:25:14,326 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.07_min_samples10

2026-10-24 22:25:19,159 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.07_min_samples20

2026-10-24 22:25:24,024 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.07_min_samples30

2026-10-24 22:25:29,245 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.07_min_samples100

2026-10-24 22:25:34,182 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.1_min_samples2

2026-10-24 22:25:39,346 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.1_min_samples3

2026-10-24 22:25:44,311 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.1_min_samples5

2026-10-24 22:25:49,260 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.1_min_samples7

2026-10-24 22:25:54,424 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.1_min_samples10

2026-10-24 22:25:59,326 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.1_min_samples20

2026-10-24 22:26:04,160 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.1_min_samples30

2026-10-24 22:26:08,846 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.1_min_samples100

2026-10-24 22:26:13,621 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.5_min_samples2

2026-10-24 22:26:22,309 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.5_min_samples3

2026-10-24 22:26:30,420 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.5_min_samples5

2026-10-24 22:26:38,293 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.5_min_samples7

2026-10-24 22:26:45,826 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.5_min_samples10

2026-10-24 22:26:52,961 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.5_min_samples20

2026-10-24 22:26:59,085 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.5_min_samples30

2026-10-24 22:27:04,612 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps0.5_min_samples100

2026-10-24 22:27:09,260 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps1_min_samples2

2026-10-24 22:27:20,432 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps1_min_samples3

2026-10-24 22:27:31,581 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps1_min_samples5

2026-10-24 22:27:42,694 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps1_min_samples7

2026-10-24 22:27:53,893 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps1_min_samples10

2026-10-24 22:28:04,949 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps1_min_samples20

2026-10-24 22:28:15,997 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps1_min_samples30

2026-10-24 22:28:27,127 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df1_eps1_min_samples100

2026-10-24 22:28:38,390 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-24 22:28:39,012 INFO Analyzer=char_wb min_df=2 seed=42: 67664 termos, 9 vetores zerados

2026-10-24 22:28:39,013 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.01_min_samples2

2026-10-24 22:28:43,523 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.01_min_samples3

2026-10-24 22:28:48,096 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.01_min_samples5

2026-10-24 22:28:52,575 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.01_min_samples7

2026-10-24 22:28:57,145 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.01_min_samples10

2026-10-24 22:29:01,693 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.01_min_samples20

2026-10-24 22:29:06,213 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.01_min_samples30

2026-10-24 22:29:10,768 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.01_min_samples100

2026-10-24 22:29:15,312 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.02_min_samples2

2026-10-24 22:29:19,860 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.02_min_samples3

2026-10-24 22:29:24,392 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.02_min_samples5

2026-10-24 22:29:28,927 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.02_min_samples7

2026-10-24 22:29:33,486 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.02_min_samples10

2026-10-24 22:29:38,053 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.02_min_samples20

2026-10-24 22:29:42,581 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.02_min_samples30

2026-10-24 22:29:47,151 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.02_min_samples100

2026-10-24 22:29:51,696 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.025_min_samples2

2026-10-24 22:29:56,216 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.025_min_samples3

2026-10-24 22:30:00,758 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.025_min_samples5

2026-10-24 22:30:05,285 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.025_min_samples7

2026-10-24 22:30:09,848 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.025_min_samples10

2026-10-24 22:30:14,452 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.025_min_samples20

2026-10-24 22:30:19,027 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.025_min_samples30

2026-10-24 22:30:23,612 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.025_min_samples100

2026-10-24 22:30:28,170 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.03_min_samples2

2026-10-24 22:30:32,794 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.03_min_samples3

2026-10-24 22:30:37,355 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.03_min_samples5

2026-10-24 22:30:41,894 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.03_min_samples7

2026-10-24 22:30:46,461 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.03_min_samples10

2026-10-24 22:30:51,065 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.03_min_samples20

2026-10-24 22:30:55,678 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.03_min_samples30

2026-10-24 22:31:00,252 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.03_min_samples100

2026-10-24 22:31:04,846 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.035_min_samples2

2026-10-24 22:31:09,482 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.035_min_samples3

2026-10-24 22:31:14,011 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.035_min_samples5

2026-10-24 22:31:18,544 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.035_min_samples7

2026-10-24 22:31:23,053 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.035_min_samples10

2026-10-24 22:31:27,649 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.035_min_samples20

2026-10-24 22:31:32,255 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.035_min_samples30

2026-10-24 22:31:36,781 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.035_min_samples100

2026-10-24 22:31:41,353 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.04_min_samples2

2026-10-24 22:31:45,937 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.04_min_samples3

2026-10-24 22:31:50,861 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.04_min_samples5

2026-10-24 22:31:55,961 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.04_min_samples7

2026-10-24 22:32:00,831 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.04_min_samples10

2026-10-24 22:32:05,654 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.04_min_samples20

2026-10-24 22:32:10,404 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.04_min_samples30

2026-10-24 22:32:15,328 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.04_min_samples100

2026-10-24 22:32:20,021 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.05_min_samples2

2026-10-24 22:32:25,230 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.05_min_samples3

2026-10-24 22:32:30,061 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.05_min_samples5

2026-10-24 22:32:34,804 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.05_min_samples7

2026-10-24 22:32:39,451 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.05_min_samples10

2026-10-24 22:32:44,047 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.05_min_samples20

2026-10-24 22:32:48,533 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.05_min_samples30

2026-10-24 22:32:53,052 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.05_min_samples100

2026-10-24 22:32:57,602 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.07_min_samples2

2026-10-24 22:33:02,343 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.07_min_samples3

2026-10-24 22:33:06,945 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.07_min_samples5

2026-10-24 22:33:11,428 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.07_min_samples7

2026-10-24 22:33:15,928 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.07_min_samples10

2026-10-24 22:33:20,527 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.07_min_samples20

2026-10-24 22:33:25,098 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.07_min_samples30

2026-10-24 22:33:29,691 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.07_min_samples100

2026-10-24 22:33:34,277 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.1_min_samples2

2026-10-24 22:33:39,120 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.1_min_samples3

2026-10-24 22:33:43,761 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.1_min_samples5

2026-10-24 22:33:48,382 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.1_min_samples7

2026-10-24 22:33:52,961 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.1_min_samples10

2026-10-24 22:33:57,495 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.1_min_samples20

2026-10-24 22:34:02,068 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.1_min_samples30

2026-10-24 22:34:06,691 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.1_min_samples100

2026-10-24 22:34:11,286 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.5_min_samples2

2026-10-24 22:34:20,490 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.5_min_samples3

2026-10-24 22:34:29,328 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.5_min_samples5

2026-10-24 22:34:37,602 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.5_min_samples7

2026-10-24 22:34:45,454 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.5_min_samples10

2026-10-24 22:34:52,794 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.5_min_samples20

2026-10-24 22:34:59,197 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.5_min_samples30

2026-10-24 22:35:04,905 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps0.5_min_samples100

2026-10-24 22:35:09,548 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps1_min_samples2

2026-10-24 22:35:20,636 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps1_min_samples3

2026-10-24 22:35:31,817 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps1_min_samples5

2026-10-24 22:35:43,372 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps1_min_samples7

2026-10-24 22:35:54,499 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps1_min_samples10

2026-10-24 22:36:05,594 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps1_min_samples20

2026-10-24 22:36:16,834 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps1_min_samples30

2026-10-24 22:36:28,066 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df2_eps1_min_samples100

2026-10-24 22:36:39,129 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-24 22:36:39,758 INFO Analyzer=char_wb min_df=5 seed=42: 31705 termos, 22 vetores zerados

2026-10-24 22:36:39,759 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.01_min_samples2

2026-10-24 22:36:44,153 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.01_min_samples3

2026-10-24 22:36:48,628 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.01_min_samples5

2026-10-24 22:36:53,102 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.01_min_samples7

2026-10-24 22:36:57,543 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.01_min_samples10

2026-10-24 22:37:01,990 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.01_min_samples20

2026-10-24 22:37:06,484 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.01_min_samples30

2026-10-24 22:37:10,990 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.01_min_samples100

2026-10-24 22:37:15,398 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.02_min_samples2

2026-10-24 22:37:19,895 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.02_min_samples3

2026-10-24 22:37:24,361 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.02_min_samples5

2026-10-24 22:37:28,828 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.02_min_samples7

2026-10-24 22:37:33,317 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.02_min_samples10

2026-10-24 22:37:37,790 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.02_min_samples20

2026-10-24 22:37:42,229 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.02_min_samples30

2026-10-24 22:37:46,680 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.02_min_samples100

2026-10-24 22:37:51,119 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.025_min_samples2

2026-10-24 22:37:55,616 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.025_min_samples3

2026-10-24 22:38:00,080 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.025_min_samples5

2026-10-24 22:38:04,603 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.025_min_samples7

2026-10-24 22:38:09,120 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.025_min_samples10

2026-10-24 22:38:13,533 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.025_min_samples20

2026-10-24 22:38:18,061 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.025_min_samples30

2026-10-24 22:38:22,562 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.025_min_samples100

2026-10-24 22:38:27,045 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.03_min_samples2

2026-10-24 22:38:31,588 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.03_min_samples3

2026-10-24 22:38:36,082 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.03_min_samples5

2026-10-24 22:38:40,585 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.03_min_samples7

2026-10-24 22:38:45,049 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.03_min_samples10

2026-10-24 22:38:49,560 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.03_min_samples20

2026-10-24 22:38:54,079 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.03_min_samples30

2026-10-24 22:38:58,561 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.03_min_samples100

2026-10-24 22:39:03,261 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.035_min_samples2

2026-10-24 22:39:08,082 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.035_min_samples3

2026-10-24 22:39:12,823 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.035_min_samples5

2026-10-24 22:39:17,729 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.035_min_samples7

2026-10-24 22:39:22,628 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.035_min_samples10

2026-10-24 22:39:27,278 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.035_min_samples20

2026-10-24 22:39:31,809 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.035_min_samples30

2026-10-24 22:39:36,203 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.035_min_samples100

2026-10-24 22:39:40,644 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.04_min_samples2

2026-10-24 22:39:45,214 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.04_min_samples3

2026-10-24 22:39:49,662 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.04_min_samples5

2026-10-24 22:39:54,161 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.04_min_samples7

2026-10-24 22:39:58,628 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.04_min_samples10

2026-10-24 22:40:03,062 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.04_min_samples20

2026-10-24 22:40:07,496 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.04_min_samples30

2026-10-24 22:40:11,932 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.04_min_samples100

2026-10-24 22:40:16,413 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.05_min_samples2

2026-10-24 22:40:21,045 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.05_min_samples3

2026-10-24 22:40:25,562 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.05_min_samples5

2026-10-24 22:40:30,029 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.05_min_samples7

2026-10-24 22:40:34,495 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.05_min_samples10

2026-10-24 22:40:38,984 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.05_min_samples20

2026-10-24 22:40:43,446 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.05_min_samples30

2026-10-24 22:40:47,795 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.05_min_samples100

2026-10-24 22:40:52,212 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.07_min_samples2

2026-10-24 22:40:56,889 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.07_min_samples3

2026-10-24 22:41:01,413 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.07_min_samples5

2026-10-24 22:41:05,928 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.07_min_samples7

2026-10-24 22:41:10,403 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.07_min_samples10

2026-10-24 22:41:14,862 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.07_min_samples20

2026-10-24 22:41:19,355 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.07_min_samples30

2026-10-24 22:41:23,835 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.07_min_samples100

2026-10-24 22:41:28,525 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.1_min_samples2

2026-10-24 22:41:33,863 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.1_min_samples3

2026-10-24 22:41:39,173 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.1_min_samples5

2026-10-24 22:41:44,146 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.1_min_samples7

2026-10-24 22:41:48,965 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.1_min_samples10

2026-10-24 22:41:53,756 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.1_min_samples20

2026-10-24 22:41:58,491 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.1_min_samples30

2026-10-24 22:42:03,262 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.1_min_samples100

2026-10-24 22:42:07,991 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.5_min_samples2

2026-10-24 22:42:17,762 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.5_min_samples3

2026-10-24 22:42:27,396 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.5_min_samples5

2026-10-24 22:42:36,041 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.5_min_samples7

2026-10-24 22:42:44,329 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.5_min_samples10

2026-10-24 22:42:52,209 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.5_min_samples20

2026-10-24 22:42:59,096 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.5_min_samples30

2026-10-24 22:43:05,195 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps0.5_min_samples100

2026-10-24 22:43:09,615 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps1_min_samples2

2026-10-24 22:43:20,466 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps1_min_samples3

2026-10-24 22:43:31,429 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps1_min_samples5

2026-10-24 22:43:42,129 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps1_min_samples7

2026-10-24 22:43:55,196 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps1_min_samples10

2026-10-24 22:44:07,712 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps1_min_samples20

2026-10-24 22:44:19,458 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps1_min_samples30

2026-10-24 22:44:30,751 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df5_eps1_min_samples100

2026-10-24 22:44:42,429 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-24 22:44:43,129 INFO Analyzer=char_wb min_df=10 seed=42: 18111 termos, 47 vetores zerados

2026-10-24 22:44:43,129 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.01_min_samples2

2026-10-24 22:44:47,328 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.01_min_samples3

2026-10-24 22:44:51,511 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.01_min_samples5

2026-10-24 22:44:55,714 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.01_min_samples7

2026-10-24 22:44:59,979 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.01_min_samples10

2026-10-24 22:45:04,179 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.01_min_samples20

2026-10-24 22:45:08,434 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.01_min_samples30

2026-10-24 22:45:12,697 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.01_min_samples100

2026-10-24 22:45:16,937 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.02_min_samples2

2026-10-24 22:45:21,260 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.02_min_samples3

2026-10-24 22:45:25,529 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.02_min_samples5

2026-10-24 22:45:29,797 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.02_min_samples7

2026-10-24 22:45:34,123 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.02_min_samples10

2026-10-24 22:45:38,421 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.02_min_samples20

2026-10-24 22:45:42,713 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.02_min_samples30

2026-10-24 22:45:47,030 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.02_min_samples100

2026-10-24 22:45:51,300 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.025_min_samples2

2026-10-24 22:45:55,662 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.025_min_samples3

2026-10-24 22:46:00,034 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.025_min_samples5

2026-10-24 22:46:04,530 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.025_min_samples7

2026-10-24 22:46:09,142 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.025_min_samples10

2026-10-24 22:46:14,071 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.025_min_samples20

2026-10-24 22:46:18,963 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.025_min_samples30

2026-10-24 22:46:23,663 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.025_min_samples100

2026-10-24 22:46:28,323 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.03_min_samples2

2026-10-24 22:46:33,083 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.03_min_samples3

2026-10-24 22:46:37,696 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.03_min_samples5

2026-10-24 22:46:42,411 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.03_min_samples7

2026-10-24 22:46:47,169 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.03_min_samples10

2026-10-24 22:46:51,896 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.03_min_samples20

2026-10-24 22:46:56,705 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.03_min_samples30

2026-10-24 22:47:01,697 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.03_min_samples100

2026-10-24 22:47:06,287 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.035_min_samples2

2026-10-24 22:47:10,886 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.035_min_samples3

2026-10-24 22:47:15,230 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.035_min_samples5

2026-10-24 22:47:19,465 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.035_min_samples7

2026-10-24 22:47:23,851 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.035_min_samples10

2026-10-24 22:47:28,247 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.035_min_samples20

2026-10-24 22:47:32,620 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.035_min_samples30

2026-10-24 22:47:37,006 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.035_min_samples100

2026-10-24 22:47:41,327 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.04_min_samples2

2026-10-24 22:47:45,860 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.04_min_samples3

2026-10-24 22:47:50,230 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.04_min_samples5

2026-10-24 22:47:54,653 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.04_min_samples7

2026-10-24 22:47:59,068 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.04_min_samples10

2026-10-24 22:48:03,496 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.04_min_samples20

2026-10-24 22:48:07,965 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.04_min_samples30

2026-10-24 22:48:12,305 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.04_min_samples100

2026-10-24 22:48:16,703 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.05_min_samples2

2026-10-24 22:48:21,329 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.05_min_samples3

2026-10-24 22:48:25,763 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.05_min_samples5

2026-10-24 22:48:30,197 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.05_min_samples7

2026-10-24 22:48:34,558 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.05_min_samples10

2026-10-24 22:48:38,952 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.05_min_samples20

2026-10-24 22:48:43,364 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.05_min_samples30

2026-10-24 22:48:47,793 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.05_min_samples100

2026-10-24 22:48:52,219 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.07_min_samples2

2026-10-24 22:48:57,039 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.07_min_samples3

2026-10-24 22:49:01,696 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.07_min_samples5

2026-10-24 22:49:06,430 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.07_min_samples7

2026-10-24 22:49:11,043 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.07_min_samples10

2026-10-24 22:49:15,758 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.07_min_samples20

2026-10-24 22:49:20,697 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.07_min_samples30

2026-10-24 22:49:25,308 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.07_min_samples100

2026-10-24 22:49:29,930 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.1_min_samples2

2026-10-24 22:49:35,025 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.1_min_samples3

2026-10-24 22:49:39,747 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.1_min_samples5

2026-10-24 22:49:44,299 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.1_min_samples7

2026-10-24 22:49:48,681 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.1_min_samples10

2026-10-24 22:49:53,088 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.1_min_samples20

2026-10-24 22:49:57,518 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.1_min_samples30

2026-10-24 22:50:01,930 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.1_min_samples100

2026-10-24 22:50:06,278 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.5_min_samples2

2026-10-24 22:50:15,620 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.5_min_samples3

2026-10-24 22:50:24,868 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.5_min_samples5

2026-10-24 22:50:34,002 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.5_min_samples7

2026-10-24 22:50:42,945 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.5_min_samples10

2026-10-24 22:50:51,548 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.5_min_samples20

2026-10-24 22:50:59,371 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.5_min_samples30

2026-10-24 22:51:06,330 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps0.5_min_samples100

2026-10-24 22:51:11,025 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps1_min_samples2

2026-10-24 22:51:21,913 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps1_min_samples3

2026-10-24 22:51:32,796 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps1_min_samples5

2026-10-24 22:51:43,635 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps1_min_samples7

2026-10-24 22:51:54,523 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps1_min_samples10

2026-10-24 22:52:05,394 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps1_min_samples20

2026-10-24 22:52:16,216 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps1_min_samples30

2026-10-24 22:52:27,004 INFO Ajustando DBSCAN seed42_char_wb_5_10_min_df10_eps1_min_samples100

2026-10-24 22:52:37,655 INFO Vetorizando analyzer=word, min_df=1, seed=42, descricoes=20000

2026-10-24 22:52:37,967 INFO Analyzer=word min_df=1 seed=42: 100000 termos, 24 vetores zerados

2026-10-24 22:52:37,967 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.01_min_samples2

2026-10-24 22:52:41,896 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.01_min_samples3

2026-10-24 22:52:45,829 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.01_min_samples5

2026-10-24 22:52:49,730 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.01_min_samples7

2026-10-24 22:52:53,660 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.01_min_samples10

2026-10-24 22:52:57,597 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.01_min_samples20

2026-10-24 22:53:01,523 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.01_min_samples30

2026-10-24 22:53:05,466 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.01_min_samples100

2026-10-24 22:53:09,364 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.02_min_samples2

2026-10-24 22:53:13,223 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.02_min_samples3

2026-10-24 22:53:17,153 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.02_min_samples5

2026-10-24 22:53:21,063 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.02_min_samples7

2026-10-24 22:53:25,030 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.02_min_samples10

2026-10-24 22:53:28,987 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.02_min_samples20

2026-10-24 22:53:32,944 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.02_min_samples30

2026-10-24 22:53:36,926 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.02_min_samples100

2026-10-24 22:53:40,814 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.025_min_samples2

2026-10-24 22:53:44,757 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.025_min_samples3

2026-10-24 22:53:48,715 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.025_min_samples5

2026-10-24 22:53:52,623 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.025_min_samples7

2026-10-24 22:53:56,560 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.025_min_samples10

2026-10-24 22:54:00,487 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.025_min_samples20

2026-10-24 22:54:04,447 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.025_min_samples30

2026-10-24 22:54:08,398 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.025_min_samples100

2026-10-24 22:54:12,272 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.03_min_samples2

2026-10-24 22:54:16,184 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.03_min_samples3

2026-10-24 22:54:20,110 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.03_min_samples5

2026-10-24 22:54:24,015 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.03_min_samples7

2026-10-24 22:54:27,997 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.03_min_samples10

2026-10-24 22:54:31,934 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.03_min_samples20

2026-10-24 22:54:35,864 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.03_min_samples30

2026-10-24 22:54:39,782 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.03_min_samples100

2026-10-24 22:54:43,713 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.035_min_samples2

2026-10-24 22:54:47,665 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.035_min_samples3

2026-10-24 22:54:51,662 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.035_min_samples5

2026-10-24 22:54:55,649 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.035_min_samples7

2026-10-24 22:54:59,676 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.035_min_samples10

2026-10-24 22:55:03,606 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.035_min_samples20

2026-10-24 22:55:07,556 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.035_min_samples30

2026-10-24 22:55:11,499 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.035_min_samples100

2026-10-24 22:55:15,748 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.04_min_samples2

2026-10-24 22:55:19,889 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.04_min_samples3

2026-10-24 22:55:24,009 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.04_min_samples5

2026-10-24 22:55:28,347 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.04_min_samples7

2026-10-24 22:55:32,550 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.04_min_samples10

2026-10-24 22:55:36,624 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.04_min_samples20

2026-10-24 22:55:40,850 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.04_min_samples30

2026-10-24 22:55:45,031 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.04_min_samples100

2026-10-24 22:55:49,126 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.05_min_samples2

2026-10-24 22:55:53,575 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.05_min_samples3

2026-10-24 22:55:57,459 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.05_min_samples5

2026-10-24 22:56:01,300 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.05_min_samples7

2026-10-24 22:56:05,223 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.05_min_samples10

2026-10-24 22:56:09,152 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.05_min_samples20

2026-10-24 22:56:13,028 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.05_min_samples30

2026-10-24 22:56:16,928 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.05_min_samples100

2026-10-24 22:56:20,873 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.07_min_samples2

2026-10-24 22:56:24,797 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.07_min_samples3

2026-10-24 22:56:28,669 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.07_min_samples5

2026-10-24 22:56:32,596 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.07_min_samples7

2026-10-24 22:56:36,519 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.07_min_samples10

2026-10-24 22:56:40,379 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.07_min_samples20

2026-10-24 22:56:44,230 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.07_min_samples30

2026-10-24 22:56:48,136 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.07_min_samples100

2026-10-24 22:56:52,060 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.1_min_samples2

2026-10-24 22:56:56,007 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.1_min_samples3

2026-10-24 22:56:59,914 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.1_min_samples5

2026-10-24 22:57:03,842 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.1_min_samples7

2026-10-24 22:57:07,786 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.1_min_samples10

2026-10-24 22:57:11,697 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.1_min_samples20

2026-10-24 22:57:15,624 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.1_min_samples30

2026-10-24 22:57:19,591 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.1_min_samples100

2026-10-24 22:57:23,473 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.5_min_samples2

2026-10-24 22:57:27,841 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.5_min_samples3

2026-10-24 22:57:32,003 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.5_min_samples5

2026-10-24 22:57:35,967 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.5_min_samples7

2026-10-24 22:57:39,876 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.5_min_samples10

2026-10-24 22:57:43,756 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.5_min_samples20

2026-10-24 22:57:47,698 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.5_min_samples30

2026-10-24 22:57:51,614 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps0.5_min_samples100

2026-10-24 22:57:55,536 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps1_min_samples2

2026-10-24 22:58:06,014 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps1_min_samples3

2026-10-24 22:58:16,314 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps1_min_samples5

2026-10-24 22:58:26,635 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps1_min_samples7

2026-10-24 22:58:37,615 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps1_min_samples10

2026-10-24 22:58:47,811 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps1_min_samples20

2026-10-24 22:58:58,218 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps1_min_samples30

2026-10-24 22:59:08,598 INFO Ajustando DBSCAN seed42_word_1_3_min_df1_eps1_min_samples100

2026-10-24 22:59:19,265 INFO Vetorizando analyzer=word, min_df=2, seed=42, descricoes=20000

2026-10-24 22:59:19,574 INFO Analyzer=word min_df=2 seed=42: 23325 termos, 81 vetores zerados

2026-10-24 22:59:19,574 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.01_min_samples2

2026-10-24 22:59:23,400 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.01_min_samples3

2026-10-24 22:59:27,211 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.01_min_samples5

2026-10-24 22:59:31,015 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.01_min_samples7

2026-10-24 22:59:34,768 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.01_min_samples10

2026-10-24 22:59:38,568 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.01_min_samples20

2026-10-24 22:59:42,339 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.01_min_samples30

2026-10-24 22:59:46,148 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.01_min_samples100

2026-10-24 22:59:49,974 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.02_min_samples2

2026-10-24 22:59:53,814 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.02_min_samples3

2026-10-24 22:59:57,581 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.02_min_samples5

2026-10-24 23:00:01,381 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.02_min_samples7

2026-10-24 23:00:05,184 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.02_min_samples10

2026-10-24 23:00:09,015 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.02_min_samples20

2026-10-24 23:00:12,781 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.02_min_samples30

2026-10-24 23:00:16,583 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.02_min_samples100

2026-10-24 23:00:20,445 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.025_min_samples2

2026-10-24 23:00:24,239 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.025_min_samples3

2026-10-24 23:00:28,107 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.025_min_samples5

2026-10-24 23:00:31,931 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.025_min_samples7

2026-10-24 23:00:35,753 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.025_min_samples10

2026-10-24 23:00:39,548 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.025_min_samples20

2026-10-24 23:00:43,360 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.025_min_samples30

2026-10-24 23:00:47,208 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.025_min_samples100

2026-10-24 23:00:50,973 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.03_min_samples2

2026-10-24 23:00:54,815 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.03_min_samples3

2026-10-24 23:00:58,713 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.03_min_samples5

2026-10-24 23:01:02,581 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.03_min_samples7

2026-10-24 23:01:06,446 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.03_min_samples10

2026-10-24 23:01:10,299 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.03_min_samples20

2026-10-24 23:01:14,115 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.03_min_samples30

2026-10-24 23:01:17,915 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.03_min_samples100

2026-10-24 23:01:21,766 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.035_min_samples2

2026-10-24 23:01:25,567 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.035_min_samples3

2026-10-24 23:01:29,411 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.035_min_samples5

2026-10-24 23:01:33,248 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.035_min_samples7

2026-10-24 23:01:37,047 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.035_min_samples10

2026-10-24 23:01:40,882 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.035_min_samples20

2026-10-24 23:01:44,666 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.035_min_samples30

2026-10-24 23:01:48,470 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.035_min_samples100

2026-10-24 23:01:52,476 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.04_min_samples2

2026-10-24 23:01:56,827 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.04_min_samples3

2026-10-24 23:02:00,922 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.04_min_samples5

2026-10-24 23:02:04,937 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.04_min_samples7

2026-10-24 23:02:09,040 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.04_min_samples10

2026-10-24 23:02:13,108 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.04_min_samples20

2026-10-24 23:02:17,108 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.04_min_samples30

2026-10-24 23:02:21,149 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.04_min_samples100

2026-10-24 23:02:25,552 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.05_min_samples2

2026-10-24 23:02:29,675 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.05_min_samples3

2026-10-24 23:02:33,615 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.05_min_samples5

2026-10-24 23:02:37,482 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.05_min_samples7

2026-10-24 23:02:41,291 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.05_min_samples10

2026-10-24 23:02:44,968 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.05_min_samples20

2026-10-24 23:02:48,585 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.05_min_samples30

2026-10-24 23:02:52,209 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.05_min_samples100

2026-10-24 23:02:55,782 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.07_min_samples2

2026-10-24 23:02:59,400 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.07_min_samples3

2026-10-24 23:03:03,108 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.07_min_samples5

2026-10-24 23:03:06,815 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.07_min_samples7

2026-10-24 23:03:10,480 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.07_min_samples10

2026-10-24 23:03:14,151 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.07_min_samples20

2026-10-24 23:03:17,857 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.07_min_samples30

2026-10-24 23:03:21,556 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.07_min_samples100

2026-10-24 23:03:25,157 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.1_min_samples2

2026-10-24 23:03:28,803 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.1_min_samples3

2026-10-24 23:03:32,473 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.1_min_samples5

2026-10-24 23:03:36,251 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.1_min_samples7

2026-10-24 23:03:40,015 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.1_min_samples10

2026-10-24 23:03:44,011 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.1_min_samples20

2026-10-24 23:03:48,148 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.1_min_samples30

2026-10-24 23:03:52,086 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.1_min_samples100

2026-10-24 23:03:56,444 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.5_min_samples2

2026-10-24 23:04:03,682 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.5_min_samples3

2026-10-24 23:04:09,697 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.5_min_samples5

2026-10-24 23:04:14,695 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.5_min_samples7

2026-10-24 23:04:19,185 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.5_min_samples10

2026-10-24 23:04:23,448 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.5_min_samples20

2026-10-24 23:04:27,510 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.5_min_samples30

2026-10-24 23:04:31,374 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps0.5_min_samples100

2026-10-24 23:04:35,190 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps1_min_samples2

2026-10-24 23:04:45,848 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps1_min_samples3

2026-10-24 23:04:55,729 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps1_min_samples5

2026-10-24 23:05:05,849 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps1_min_samples7

2026-10-24 23:05:15,858 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps1_min_samples10

2026-10-24 23:05:26,043 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps1_min_samples20

2026-10-24 23:05:36,149 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps1_min_samples30

2026-10-24 23:05:46,053 INFO Ajustando DBSCAN seed42_word_1_3_min_df2_eps1_min_samples100

2026-10-24 23:05:56,135 INFO Vetorizando analyzer=word, min_df=5, seed=42, descricoes=20000

2026-10-24 23:05:56,449 INFO Analyzer=word min_df=5 seed=42: 5821 termos, 218 vetores zerados

2026-10-24 23:05:56,449 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.01_min_samples2

2026-10-24 23:06:00,212 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.01_min_samples3

2026-10-24 23:06:03,915 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.01_min_samples5

2026-10-24 23:06:07,621 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.01_min_samples7

2026-10-24 23:06:11,316 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.01_min_samples10

2026-10-24 23:06:14,933 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.01_min_samples20

2026-10-24 23:06:18,613 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.01_min_samples30

2026-10-24 23:06:22,339 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.01_min_samples100

2026-10-24 23:06:26,016 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.02_min_samples2

2026-10-24 23:06:29,749 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.02_min_samples3

2026-10-24 23:06:33,465 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.02_min_samples5

2026-10-24 23:06:37,199 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.02_min_samples7

2026-10-24 23:06:40,915 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.02_min_samples10

2026-10-24 23:06:44,582 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.02_min_samples20

2026-10-24 23:06:48,306 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.02_min_samples30

2026-10-24 23:06:52,049 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.02_min_samples100

2026-10-24 23:06:55,805 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.025_min_samples2

2026-10-24 23:06:59,549 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.025_min_samples3

2026-10-24 23:07:03,282 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.025_min_samples5

2026-10-24 23:07:07,232 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.025_min_samples7

2026-10-24 23:07:11,282 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.025_min_samples10

2026-10-24 23:07:15,383 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.025_min_samples20

2026-10-24 23:07:19,416 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.025_min_samples30

2026-10-24 23:07:23,508 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.025_min_samples100

2026-10-24 23:07:27,482 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.03_min_samples2

2026-10-24 23:07:31,667 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.03_min_samples3

2026-10-24 23:07:35,582 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.03_min_samples5

2026-10-24 23:07:39,572 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.03_min_samples7

2026-10-24 23:07:43,748 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.03_min_samples10

2026-10-24 23:07:48,140 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.03_min_samples20

2026-10-24 23:07:52,235 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.03_min_samples30

2026-10-24 23:07:56,438 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.03_min_samples100

2026-10-24 23:08:00,399 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.035_min_samples2

2026-10-24 23:08:04,364 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.035_min_samples3

2026-10-24 23:08:08,370 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.035_min_samples5

2026-10-24 23:08:12,442 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.035_min_samples7

2026-10-24 23:08:16,449 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.035_min_samples10

2026-10-24 23:08:20,505 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.035_min_samples20

2026-10-24 23:08:24,480 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.035_min_samples30

2026-10-24 23:08:28,398 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.035_min_samples100

2026-10-24 23:08:32,358 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.04_min_samples2

2026-10-24 23:08:36,458 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.04_min_samples3

2026-10-24 23:08:40,254 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.04_min_samples5

2026-10-24 23:08:44,069 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.04_min_samples7

2026-10-24 23:08:47,749 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.04_min_samples10

2026-10-24 23:08:51,406 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.04_min_samples20

2026-10-24 23:08:55,083 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.04_min_samples30

2026-10-24 23:08:58,794 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.04_min_samples100

2026-10-24 23:09:02,482 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.05_min_samples2

2026-10-24 23:09:06,364 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.05_min_samples3

2026-10-24 23:09:10,150 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.05_min_samples5

2026-10-24 23:09:13,939 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.05_min_samples7

2026-10-24 23:09:17,800 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.05_min_samples10

2026-10-24 23:09:21,519 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.05_min_samples20

2026-10-24 23:09:25,306 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.05_min_samples30

2026-10-24 23:09:29,162 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.05_min_samples100

2026-10-24 23:09:32,990 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.07_min_samples2

2026-10-24 23:09:36,929 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.07_min_samples3

2026-10-24 23:09:40,777 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.07_min_samples5

2026-10-24 23:09:44,516 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.07_min_samples7

2026-10-24 23:09:48,363 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.07_min_samples10

2026-10-24 23:09:52,179 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.07_min_samples20

2026-10-24 23:09:55,973 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.07_min_samples30

2026-10-24 23:09:59,839 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.07_min_samples100

2026-10-24 23:10:03,666 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.1_min_samples2

2026-10-24 23:10:07,599 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.1_min_samples3

2026-10-24 23:10:11,483 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.1_min_samples5

2026-10-24 23:10:15,249 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.1_min_samples7

2026-10-24 23:10:19,083 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.1_min_samples10

2026-10-24 23:10:22,877 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.1_min_samples20

2026-10-24 23:10:26,691 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.1_min_samples30

2026-10-24 23:10:30,537 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.1_min_samples100

2026-10-24 23:10:34,393 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.5_min_samples2

2026-10-24 23:10:42,216 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.5_min_samples3

2026-10-24 23:10:50,083 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.5_min_samples5

2026-10-24 23:10:58,301 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.5_min_samples7

2026-10-24 23:11:05,219 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.5_min_samples10

2026-10-24 23:11:11,347 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.5_min_samples20

2026-10-24 23:11:15,918 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.5_min_samples30

2026-10-24 23:11:20,061 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps0.5_min_samples100

2026-10-24 23:11:24,007 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps1_min_samples2

2026-10-24 23:11:34,473 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps1_min_samples3

2026-10-24 23:11:44,932 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps1_min_samples5

2026-10-24 23:11:55,216 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps1_min_samples7

2026-10-24 23:12:05,641 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps1_min_samples10

2026-10-24 23:12:16,000 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps1_min_samples20

2026-10-24 23:12:26,116 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps1_min_samples30

2026-10-24 23:12:36,545 INFO Ajustando DBSCAN seed42_word_1_3_min_df5_eps1_min_samples100

2026-10-24 23:12:46,947 INFO Vetorizando analyzer=word, min_df=10, seed=42, descricoes=20000

2026-10-24 23:12:47,285 INFO Analyzer=word min_df=10 seed=42: 2593 termos, 386 vetores zerados

2026-10-24 23:12:47,285 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.01_min_samples2

2026-10-24 23:12:51,185 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.01_min_samples3

2026-10-24 23:12:54,983 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.01_min_samples5

2026-10-24 23:12:58,783 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.01_min_samples7

2026-10-24 23:13:02,604 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.01_min_samples10

2026-10-24 23:13:06,380 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.01_min_samples20

2026-10-24 23:13:10,083 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.01_min_samples30

2026-10-24 23:13:13,813 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.01_min_samples100

2026-10-24 23:13:17,577 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.02_min_samples2

2026-10-24 23:13:21,498 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.02_min_samples3

2026-10-24 23:13:25,288 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.02_min_samples5

2026-10-24 23:13:29,081 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.02_min_samples7

2026-10-24 23:13:32,870 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.02_min_samples10

2026-10-24 23:13:36,583 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.02_min_samples20

2026-10-24 23:13:40,383 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.02_min_samples30

2026-10-24 23:13:44,140 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.02_min_samples100

2026-10-24 23:13:47,904 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.025_min_samples2

2026-10-24 23:13:51,817 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.025_min_samples3

2026-10-24 23:13:55,563 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.025_min_samples5

2026-10-24 23:13:59,316 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.025_min_samples7

2026-10-24 23:14:03,165 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.025_min_samples10

2026-10-24 23:14:06,983 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.025_min_samples20

2026-10-24 23:14:10,816 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.025_min_samples30

2026-10-24 23:14:14,617 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.025_min_samples100

2026-10-24 23:14:18,400 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.03_min_samples2

2026-10-24 23:14:22,304 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.03_min_samples3

2026-10-24 23:14:26,138 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.03_min_samples5

2026-10-24 23:14:29,938 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.03_min_samples7

2026-10-24 23:14:33,752 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.03_min_samples10

2026-10-24 23:14:37,537 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.03_min_samples20

2026-10-24 23:14:41,251 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.03_min_samples30

2026-10-24 23:14:45,030 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.03_min_samples100

2026-10-24 23:14:48,837 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.035_min_samples2

2026-10-24 23:14:52,745 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.035_min_samples3

2026-10-24 23:14:56,601 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.035_min_samples5

2026-10-24 23:15:00,405 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.035_min_samples7

2026-10-24 23:15:04,236 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.035_min_samples10

2026-10-24 23:15:08,050 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.035_min_samples20

2026-10-24 23:15:11,811 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.035_min_samples30

2026-10-24 23:15:15,570 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.035_min_samples100

2026-10-24 23:15:19,450 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.04_min_samples2

2026-10-24 23:15:23,898 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.04_min_samples3

2026-10-24 23:15:28,134 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.04_min_samples5

2026-10-24 23:15:32,342 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.04_min_samples7

2026-10-24 23:15:36,310 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.04_min_samples10

2026-10-24 23:15:40,303 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.04_min_samples20

2026-10-24 23:15:44,356 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.04_min_samples30

2026-10-24 23:15:48,409 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.04_min_samples100

2026-10-24 23:15:52,509 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.05_min_samples2

2026-10-24 23:15:56,736 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.05_min_samples3

2026-10-24 23:16:00,691 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.05_min_samples5

2026-10-24 23:16:04,683 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.05_min_samples7

2026-10-24 23:16:08,683 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.05_min_samples10

2026-10-24 23:16:12,742 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.05_min_samples20

2026-10-24 23:16:17,133 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.05_min_samples30

2026-10-24 23:16:21,105 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.05_min_samples100

2026-10-24 23:16:25,108 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.07_min_samples2

2026-10-24 23:16:29,265 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.07_min_samples3

2026-10-24 23:16:33,268 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.07_min_samples5

2026-10-24 23:16:37,205 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.07_min_samples7

2026-10-24 23:16:41,217 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.07_min_samples10

2026-10-24 23:16:45,384 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.07_min_samples20

2026-10-24 23:16:49,239 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.07_min_samples30

2026-10-24 23:16:53,246 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.07_min_samples100

2026-10-24 23:16:57,042 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.1_min_samples2

2026-10-24 23:17:01,112 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.1_min_samples3

2026-10-24 23:17:05,007 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.1_min_samples5

2026-10-24 23:17:08,804 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.1_min_samples7

2026-10-24 23:17:12,602 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.1_min_samples10

2026-10-24 23:17:16,393 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.1_min_samples20

2026-10-24 23:17:20,165 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.1_min_samples30

2026-10-24 23:17:23,933 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.1_min_samples100

2026-10-24 23:17:27,758 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.5_min_samples2

2026-10-24 23:17:35,792 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.5_min_samples3

2026-10-24 23:17:44,051 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.5_min_samples5

2026-10-24 23:17:52,745 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.5_min_samples7

2026-10-24 23:18:00,959 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.5_min_samples10

2026-10-24 23:18:08,728 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.5_min_samples20

2026-10-24 23:18:14,984 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.5_min_samples30

2026-10-24 23:18:19,913 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps0.5_min_samples100

2026-10-24 23:18:24,069 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps1_min_samples2

2026-10-24 23:18:34,769 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps1_min_samples3

2026-10-24 23:18:45,228 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps1_min_samples5

2026-10-24 23:18:55,584 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps1_min_samples7

2026-10-24 23:19:06,086 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps1_min_samples10

2026-10-24 23:19:16,388 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps1_min_samples20

2026-10-24 23:19:26,947 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps1_min_samples30

2026-10-24 23:19:37,283 INFO Ajustando DBSCAN seed42_word_1_3_min_df10_eps1_min_samples100

2026-10-24 23:19:47,584 INFO Vetorizando analyzer=word, min_df=1, seed=42, descricoes=20000

2026-10-24 23:19:48,068 INFO Analyzer=word min_df=1 seed=42: 100000 termos, 43 vetores zerados

2026-10-24 23:19:48,083 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.01_min_samples2

2026-10-24 23:19:52,066 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.01_min_samples3

2026-10-24 23:19:55,984 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.01_min_samples5

2026-10-24 23:19:59,936 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.01_min_samples7

2026-10-24 23:20:03,917 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.01_min_samples10

2026-10-24 23:20:07,870 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.01_min_samples20

2026-10-24 23:20:11,817 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.01_min_samples30

2026-10-24 23:20:15,817 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.01_min_samples100

2026-10-24 23:20:19,806 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.02_min_samples2

2026-10-24 23:20:23,847 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.02_min_samples3

2026-10-24 23:20:27,805 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.02_min_samples5

2026-10-24 23:20:31,834 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.02_min_samples7

2026-10-24 23:20:35,824 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.02_min_samples10

2026-10-24 23:20:39,820 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.02_min_samples20

2026-10-24 23:20:43,774 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.02_min_samples30

2026-10-24 23:20:47,817 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.02_min_samples100

2026-10-24 23:20:51,957 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.025_min_samples2

2026-10-24 23:20:56,539 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.025_min_samples3

2026-10-24 23:21:00,751 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.025_min_samples5

2026-10-24 23:21:04,985 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.025_min_samples7

2026-10-24 23:21:09,158 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.025_min_samples10

2026-10-24 23:21:13,447 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.025_min_samples20

2026-10-24 23:21:17,668 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.025_min_samples30

2026-10-24 23:21:22,051 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.025_min_samples100

2026-10-24 23:21:26,418 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.03_min_samples2

2026-10-24 23:21:30,618 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.03_min_samples3

2026-10-24 23:21:34,781 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.03_min_samples5

2026-10-24 23:21:39,311 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.03_min_samples7

2026-10-24 23:21:43,651 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.03_min_samples10

2026-10-24 23:21:47,980 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.03_min_samples20

2026-10-24 23:21:52,298 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.03_min_samples30

2026-10-24 23:21:56,605 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.03_min_samples100

2026-10-24 23:22:00,746 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.035_min_samples2

2026-10-24 23:22:04,935 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.035_min_samples3

2026-10-24 23:22:09,121 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.035_min_samples5

2026-10-24 23:22:13,354 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.035_min_samples7

2026-10-24 23:22:17,541 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.035_min_samples10

2026-10-24 23:22:21,671 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.035_min_samples20

2026-10-24 23:22:26,151 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.035_min_samples30

2026-10-24 23:22:30,268 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.035_min_samples100

2026-10-24 23:22:34,333 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.04_min_samples2

2026-10-24 23:22:38,405 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.04_min_samples3

2026-10-24 23:22:42,418 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.04_min_samples5

2026-10-24 23:22:46,412 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.04_min_samples7

2026-10-24 23:22:50,269 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.04_min_samples10

2026-10-24 23:22:54,168 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.04_min_samples20

2026-10-24 23:22:58,151 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.04_min_samples30

2026-10-24 23:23:02,135 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.04_min_samples100

2026-10-24 23:23:06,133 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.05_min_samples2

2026-10-24 23:23:10,118 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.05_min_samples3

2026-10-24 23:23:13,980 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.05_min_samples5

2026-10-24 23:23:17,818 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.05_min_samples7

2026-10-24 23:23:21,751 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.05_min_samples10

2026-10-24 23:23:25,818 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.05_min_samples20

2026-10-24 23:23:29,911 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.05_min_samples30

2026-10-24 23:23:34,118 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.05_min_samples100

2026-10-24 23:23:38,274 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.07_min_samples2

2026-10-24 23:23:42,452 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.07_min_samples3

2026-10-24 23:23:46,518 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.07_min_samples5

2026-10-24 23:23:50,852 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.07_min_samples7

2026-10-24 23:23:55,171 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.07_min_samples10

2026-10-24 23:23:59,622 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.07_min_samples20

2026-10-24 23:24:03,720 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.07_min_samples30

2026-10-24 23:24:07,910 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.07_min_samples100

2026-10-24 23:24:12,045 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.1_min_samples2

2026-10-24 23:24:16,301 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.1_min_samples3

2026-10-24 23:24:20,418 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.1_min_samples5

2026-10-24 23:24:24,818 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.1_min_samples7

2026-10-24 23:24:29,052 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.1_min_samples10

2026-10-24 23:24:33,233 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.1_min_samples20

2026-10-24 23:24:37,279 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.1_min_samples30

2026-10-24 23:24:41,473 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.1_min_samples100

2026-10-24 23:24:46,235 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.5_min_samples2

2026-10-24 23:24:51,118 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.5_min_samples3

2026-10-24 23:24:55,513 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.5_min_samples5

2026-10-24 23:24:59,667 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.5_min_samples7

2026-10-24 23:25:03,905 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.5_min_samples10

2026-10-24 23:25:07,952 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.5_min_samples20

2026-10-24 23:25:11,918 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.5_min_samples30

2026-10-24 23:25:15,745 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps0.5_min_samples100

2026-10-24 23:25:19,518 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps1_min_samples2

2026-10-24 23:25:30,647 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps1_min_samples3

2026-10-24 23:25:41,618 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps1_min_samples5

2026-10-24 23:25:52,918 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps1_min_samples7

2026-10-24 23:26:03,015 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps1_min_samples10

2026-10-24 23:26:13,241 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps1_min_samples20

2026-10-24 23:26:23,469 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps1_min_samples30

2026-10-24 23:26:33,741 INFO Ajustando DBSCAN seed42_word_1_5_min_df1_eps1_min_samples100

2026-10-24 23:26:43,918 INFO Vetorizando analyzer=word, min_df=2, seed=42, descricoes=20000

2026-10-24 23:26:44,581 INFO Analyzer=word min_df=2 seed=42: 27572 termos, 81 vetores zerados

2026-10-24 23:26:44,582 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.01_min_samples2

2026-10-24 23:26:48,618 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.01_min_samples3

2026-10-24 23:26:52,604 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.01_min_samples5

2026-10-24 23:26:56,585 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.01_min_samples7

2026-10-24 23:27:00,683 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.01_min_samples10

2026-10-24 23:27:05,213 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.01_min_samples20

2026-10-24 23:27:09,321 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.01_min_samples30

2026-10-24 23:27:13,402 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.01_min_samples100

2026-10-24 23:27:17,456 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.02_min_samples2

2026-10-24 23:27:21,481 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.02_min_samples3

2026-10-24 23:27:25,686 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.02_min_samples5

2026-10-24 23:27:29,706 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.02_min_samples7

2026-10-24 23:27:33,752 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.02_min_samples10

2026-10-24 23:27:37,844 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.02_min_samples20

2026-10-24 23:27:41,830 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.02_min_samples30

2026-10-24 23:27:45,984 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.02_min_samples100

2026-10-24 23:27:50,367 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.025_min_samples2

2026-10-24 23:27:54,485 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.025_min_samples3

2026-10-24 23:27:58,619 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.025_min_samples5

2026-10-24 23:28:02,710 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.025_min_samples7

2026-10-24 23:28:06,757 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.025_min_samples10

2026-10-24 23:28:10,788 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.025_min_samples20

2026-10-24 23:28:14,643 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.025_min_samples30

2026-10-24 23:28:18,419 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.025_min_samples100

2026-10-24 23:28:22,119 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.03_min_samples2

2026-10-24 23:28:25,847 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.03_min_samples3

2026-10-24 23:28:29,514 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.03_min_samples5

2026-10-24 23:28:33,256 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.03_min_samples7

2026-10-24 23:28:36,883 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.03_min_samples10

2026-10-24 23:28:40,485 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.03_min_samples20

2026-10-24 23:28:44,222 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.03_min_samples30

2026-10-24 23:28:47,852 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.03_min_samples100

2026-10-24 23:28:51,690 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.035_min_samples2

2026-10-24 23:28:55,754 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.035_min_samples3

2026-10-24 23:28:59,652 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.035_min_samples5

2026-10-24 23:29:03,542 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.035_min_samples7

2026-10-24 23:29:07,505 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.035_min_samples10

2026-10-24 23:29:11,653 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.035_min_samples20

2026-10-24 23:29:15,807 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.035_min_samples30

2026-10-24 23:29:19,885 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.035_min_samples100

2026-10-24 23:29:24,252 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.04_min_samples2

2026-10-24 23:29:28,386 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.04_min_samples3

2026-10-24 23:29:32,509 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.04_min_samples5

2026-10-24 23:29:36,552 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.04_min_samples7

2026-10-24 23:29:40,616 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.04_min_samples10

2026-10-24 23:29:44,673 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.04_min_samples20

2026-10-24 23:29:48,674 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.04_min_samples30

2026-10-24 23:29:52,752 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.04_min_samples100

2026-10-24 23:29:56,859 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.05_min_samples2

2026-10-24 23:30:00,911 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.05_min_samples3

2026-10-24 23:30:04,952 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.05_min_samples5

2026-10-24 23:30:09,240 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.05_min_samples7

2026-10-24 23:30:13,352 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.05_min_samples10

2026-10-24 23:30:17,312 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.05_min_samples20

2026-10-24 23:30:21,136 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.05_min_samples30

2026-10-24 23:30:25,148 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.05_min_samples100

2026-10-24 23:30:28,932 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.07_min_samples2

2026-10-24 23:30:32,844 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.07_min_samples3

2026-10-24 23:30:36,719 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.07_min_samples5

2026-10-24 23:30:40,552 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.07_min_samples7

2026-10-24 23:30:44,325 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.07_min_samples10

2026-10-24 23:30:48,122 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.07_min_samples20

2026-10-24 23:30:52,019 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.07_min_samples30

2026-10-24 23:30:55,819 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.07_min_samples100

2026-10-24 23:30:59,719 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.1_min_samples2

2026-10-24 23:31:03,620 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.1_min_samples3

2026-10-24 23:31:07,517 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.1_min_samples5

2026-10-24 23:31:11,319 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.1_min_samples7

2026-10-24 23:31:15,119 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.1_min_samples10

2026-10-24 23:31:18,956 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.1_min_samples20

2026-10-24 23:31:23,101 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.1_min_samples30

2026-10-24 23:31:27,150 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.1_min_samples100

2026-10-24 23:31:31,207 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.5_min_samples2

2026-10-24 23:31:38,205 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.5_min_samples3

2026-10-24 23:31:44,760 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.5_min_samples5

2026-10-24 23:31:49,673 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.5_min_samples7

2026-10-24 23:31:54,383 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.5_min_samples10

2026-10-24 23:31:58,721 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.5_min_samples20

2026-10-24 23:32:02,886 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.5_min_samples30

2026-10-24 23:32:06,919 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps0.5_min_samples100

2026-10-24 23:32:10,966 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps1_min_samples2

2026-10-24 23:32:21,764 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps1_min_samples3

2026-10-24 23:32:32,650 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps1_min_samples5

2026-10-24 23:32:43,119 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps1_min_samples7

2026-10-24 23:32:53,636 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps1_min_samples10

2026-10-24 23:33:04,073 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps1_min_samples20

2026-10-24 23:33:14,305 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps1_min_samples30

2026-10-24 23:33:24,785 INFO Ajustando DBSCAN seed42_word_1_5_min_df2_eps1_min_samples100

2026-10-24 23:33:35,225 INFO Vetorizando analyzer=word, min_df=5, seed=42, descricoes=20000

2026-10-24 23:33:35,718 INFO Analyzer=word min_df=5 seed=42: 6211 termos, 218 vetores zerados

2026-10-24 23:33:35,719 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.01_min_samples2

2026-10-24 23:33:39,587 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.01_min_samples3

2026-10-24 23:33:43,453 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.01_min_samples5

2026-10-24 23:33:47,244 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.01_min_samples7

2026-10-24 23:33:51,107 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.01_min_samples10

2026-10-24 23:33:54,969 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.01_min_samples20

2026-10-24 23:33:58,757 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.01_min_samples30

2026-10-24 23:34:02,638 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.01_min_samples100

2026-10-24 23:34:06,480 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.02_min_samples2

2026-10-24 23:34:10,413 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.02_min_samples3

2026-10-24 23:34:14,215 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.02_min_samples5

2026-10-24 23:34:18,116 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.02_min_samples7

2026-10-24 23:34:22,015 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.02_min_samples10

2026-10-24 23:34:25,919 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.02_min_samples20

2026-10-24 23:34:29,824 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.02_min_samples30

2026-10-24 23:34:33,736 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.02_min_samples100

2026-10-24 23:34:37,623 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.025_min_samples2

2026-10-24 23:34:41,536 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.025_min_samples3

2026-10-24 23:34:45,387 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.025_min_samples5

2026-10-24 23:34:49,186 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.025_min_samples7

2026-10-24 23:34:53,050 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.025_min_samples10

2026-10-24 23:34:56,882 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.025_min_samples20

2026-10-24 23:35:00,788 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.025_min_samples30

2026-10-24 23:35:04,641 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.025_min_samples100

2026-10-24 23:35:08,484 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.03_min_samples2

2026-10-24 23:35:12,376 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.03_min_samples3

2026-10-24 23:35:16,284 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.03_min_samples5

2026-10-24 23:35:20,153 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.03_min_samples7

2026-10-24 23:35:24,056 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.03_min_samples10

2026-10-24 23:35:27,911 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.03_min_samples20

2026-10-24 23:35:32,086 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.03_min_samples30

2026-10-24 23:35:36,239 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.03_min_samples100

2026-10-24 23:35:40,308 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.035_min_samples2

2026-10-24 23:35:44,573 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.035_min_samples3

2026-10-24 23:35:48,637 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.035_min_samples5

2026-10-24 23:35:52,820 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.035_min_samples7

2026-10-24 23:35:56,962 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.035_min_samples10

2026-10-24 23:36:01,020 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.035_min_samples20

2026-10-24 23:36:05,103 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.035_min_samples30

2026-10-24 23:36:09,118 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.035_min_samples100

2026-10-24 23:36:13,283 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.04_min_samples2

2026-10-24 23:36:17,581 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.04_min_samples3

2026-10-24 23:36:21,710 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.04_min_samples5

2026-10-24 23:36:26,055 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.04_min_samples7

2026-10-24 23:36:30,116 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.04_min_samples10

2026-10-24 23:36:34,153 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.04_min_samples20

2026-10-24 23:36:38,212 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.04_min_samples30

2026-10-24 23:36:42,287 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.04_min_samples100

2026-10-24 23:36:46,495 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.05_min_samples2

2026-10-24 23:36:50,804 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.05_min_samples3

2026-10-24 23:36:54,953 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.05_min_samples5

2026-10-24 23:36:59,018 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.05_min_samples7

2026-10-24 23:37:02,967 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.05_min_samples10

2026-10-24 23:37:07,020 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.05_min_samples20

2026-10-24 23:37:10,850 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.05_min_samples30

2026-10-24 23:37:14,691 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.05_min_samples100

2026-10-24 23:37:18,522 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.07_min_samples2

2026-10-24 23:37:22,351 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.07_min_samples3

2026-10-24 23:37:26,076 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.07_min_samples5

2026-10-24 23:37:29,820 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.07_min_samples7

2026-10-24 23:37:33,570 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.07_min_samples10

2026-10-24 23:37:37,339 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.07_min_samples20

2026-10-24 23:37:41,154 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.07_min_samples30

2026-10-24 23:37:45,170 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.07_min_samples100

2026-10-24 23:37:49,308 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.1_min_samples2

2026-10-24 23:37:53,921 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.1_min_samples3

2026-10-24 23:37:58,509 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.1_min_samples5

2026-10-24 23:38:02,639 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.1_min_samples7

2026-10-24 23:38:06,638 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.1_min_samples10

2026-10-24 23:38:10,691 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.1_min_samples20

2026-10-24 23:38:14,820 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.1_min_samples30

2026-10-24 23:38:18,896 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.1_min_samples100

2026-10-24 23:38:22,882 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.5_min_samples2

2026-10-24 23:38:30,734 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.5_min_samples3

2026-10-24 23:38:38,464 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.5_min_samples5

2026-10-24 23:38:45,747 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.5_min_samples7

2026-10-24 23:38:52,346 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.5_min_samples10

2026-10-24 23:38:58,078 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.5_min_samples20

2026-10-24 23:39:02,354 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.5_min_samples30

2026-10-24 23:39:06,378 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps0.5_min_samples100

2026-10-24 23:39:10,275 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps1_min_samples2

2026-10-24 23:39:20,721 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps1_min_samples3

2026-10-24 23:39:32,078 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps1_min_samples5

2026-10-24 23:39:42,951 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps1_min_samples7

2026-10-24 23:39:53,717 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps1_min_samples10

2026-10-24 23:40:04,154 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps1_min_samples20

2026-10-24 23:40:14,587 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps1_min_samples30

2026-10-24 23:40:25,153 INFO Ajustando DBSCAN seed42_word_1_5_min_df5_eps1_min_samples100

2026-10-24 23:40:35,842 INFO Vetorizando analyzer=word, min_df=10, seed=42, descricoes=20000

2026-10-24 23:40:36,320 INFO Analyzer=word min_df=10 seed=42: 2661 termos, 386 vetores zerados

2026-10-24 23:40:36,320 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.01_min_samples2

2026-10-24 23:40:40,209 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.01_min_samples3

2026-10-24 23:40:44,043 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.01_min_samples5

2026-10-24 23:40:47,815 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.01_min_samples7

2026-10-24 23:40:51,554 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.01_min_samples10

2026-10-24 23:40:55,320 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.01_min_samples20

2026-10-24 23:40:59,083 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.01_min_samples30

2026-10-24 23:41:02,911 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.01_min_samples100

2026-10-24 23:41:06,719 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.02_min_samples2

2026-10-24 23:41:10,607 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.02_min_samples3

2026-10-24 23:41:14,341 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.02_min_samples5

2026-10-24 23:41:18,122 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.02_min_samples7

2026-10-24 23:41:21,945 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.02_min_samples10

2026-10-24 23:41:25,728 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.02_min_samples20

2026-10-24 23:41:29,524 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.02_min_samples30

2026-10-24 23:41:33,352 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.02_min_samples100

2026-10-24 23:41:37,154 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.025_min_samples2

2026-10-24 23:41:41,022 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.025_min_samples3

2026-10-24 23:41:44,827 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.025_min_samples5

2026-10-24 23:41:48,651 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.025_min_samples7

2026-10-24 23:41:52,416 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.025_min_samples10

2026-10-24 23:41:56,221 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.025_min_samples20

2026-10-24 23:41:59,947 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.025_min_samples30

2026-10-24 23:42:03,755 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.025_min_samples100

2026-10-24 23:42:07,578 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.03_min_samples2

2026-10-24 23:42:11,487 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.03_min_samples3

2026-10-24 23:42:15,671 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.03_min_samples5

2026-10-24 23:42:19,675 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.03_min_samples7

2026-10-24 23:42:23,844 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.03_min_samples10

2026-10-24 23:42:27,909 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.03_min_samples20

2026-10-24 23:42:31,898 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.03_min_samples30

2026-10-24 23:42:35,921 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.03_min_samples100

2026-10-24 23:42:39,953 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.035_min_samples2

2026-10-24 23:42:44,154 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.035_min_samples3

2026-10-24 23:42:48,534 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.035_min_samples5

2026-10-24 23:42:52,787 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.035_min_samples7

2026-10-24 23:42:56,808 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.035_min_samples10

2026-10-24 23:43:00,854 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.035_min_samples20

2026-10-24 23:43:04,916 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.035_min_samples30

2026-10-24 23:43:08,896 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.035_min_samples100

2026-10-24 23:43:12,921 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.04_min_samples2

2026-10-24 23:43:17,121 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.04_min_samples3

2026-10-24 23:43:21,115 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.04_min_samples5

2026-10-24 23:43:25,126 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.04_min_samples7

2026-10-24 23:43:29,187 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.04_min_samples10

2026-10-24 23:43:33,357 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.04_min_samples20

2026-10-24 23:43:37,375 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.04_min_samples30

2026-10-24 23:43:41,351 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.04_min_samples100

2026-10-24 23:43:45,312 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.05_min_samples2

2026-10-24 23:43:49,501 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.05_min_samples3

2026-10-24 23:43:53,521 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.05_min_samples5

2026-10-24 23:43:57,521 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.05_min_samples7

2026-10-24 23:44:01,316 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.05_min_samples10

2026-10-24 23:44:05,016 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.05_min_samples20

2026-10-24 23:44:08,678 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.05_min_samples30

2026-10-24 23:44:12,284 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.05_min_samples100

2026-10-24 23:44:15,956 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.07_min_samples2

2026-10-24 23:44:19,916 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.07_min_samples3

2026-10-24 23:44:23,654 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.07_min_samples5

2026-10-24 23:44:27,454 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.07_min_samples7

2026-10-24 23:44:31,210 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.07_min_samples10

2026-10-24 23:44:34,971 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.07_min_samples20

2026-10-24 23:44:38,858 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.07_min_samples30

2026-10-24 23:44:43,136 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.07_min_samples100

2026-10-24 23:44:47,212 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.1_min_samples2

2026-10-24 23:44:52,054 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.1_min_samples3

2026-10-24 23:44:56,354 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.1_min_samples5

2026-10-24 23:45:00,588 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.1_min_samples7

2026-10-24 23:45:04,819 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.1_min_samples10

2026-10-24 23:45:08,833 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.1_min_samples20

2026-10-24 23:45:12,831 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.1_min_samples30

2026-10-24 23:45:16,742 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.1_min_samples100

2026-10-24 23:45:20,788 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.5_min_samples2

2026-10-24 23:45:29,588 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.5_min_samples3

2026-10-24 23:45:37,973 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.5_min_samples5

2026-10-24 23:45:46,371 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.5_min_samples7

2026-10-24 23:45:54,676 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.5_min_samples10

2026-10-24 23:46:02,114 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.5_min_samples20

2026-10-24 23:46:07,752 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.5_min_samples30

2026-10-24 23:46:12,239 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps0.5_min_samples100

2026-10-24 23:46:15,898 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps1_min_samples2

2026-10-24 23:46:25,971 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps1_min_samples3

2026-10-24 23:46:36,675 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps1_min_samples5

2026-10-24 23:46:48,096 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps1_min_samples7

2026-10-24 23:46:59,765 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps1_min_samples10

2026-10-24 23:47:10,471 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps1_min_samples20

2026-10-24 23:47:21,148 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps1_min_samples30

2026-10-24 23:47:31,427 INFO Ajustando DBSCAN seed42_word_1_5_min_df10_eps1_min_samples100

2026-10-24 23:47:41,533 INFO Vetorizando analyzer=word, min_df=1, seed=42, descricoes=20000

2026-10-24 23:47:42,021 INFO Analyzer=word min_df=1 seed=42: 100000 termos, 1046 vetores zerados

2026-10-24 23:47:42,021 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.01_min_samples2

2026-10-24 23:47:45,722 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.01_min_samples3

2026-10-24 23:47:49,406 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.01_min_samples5

2026-10-24 23:47:53,121 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.01_min_samples7

2026-10-24 23:47:56,811 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.01_min_samples10

2026-10-24 23:48:00,536 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.01_min_samples20

2026-10-24 23:48:04,246 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.01_min_samples30

2026-10-24 23:48:07,946 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.01_min_samples100

2026-10-24 23:48:11,609 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.02_min_samples2

2026-10-24 23:48:15,373 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.02_min_samples3

2026-10-24 23:48:19,213 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.02_min_samples5

2026-10-24 23:48:22,967 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.02_min_samples7

2026-10-24 23:48:26,988 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.02_min_samples10

2026-10-24 23:48:31,083 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.02_min_samples20

2026-10-24 23:48:35,047 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.02_min_samples30

2026-10-24 23:48:39,010 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.02_min_samples100

2026-10-24 23:48:43,245 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.025_min_samples2

2026-10-24 23:48:47,255 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.025_min_samples3

2026-10-24 23:48:51,326 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.025_min_samples5

2026-10-24 23:48:55,388 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.025_min_samples7

2026-10-24 23:48:59,811 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.025_min_samples10

2026-10-24 23:49:03,911 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.025_min_samples20

2026-10-24 23:49:07,927 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.025_min_samples30

2026-10-24 23:49:11,955 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.025_min_samples100

2026-10-24 23:49:16,188 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.03_min_samples2

2026-10-24 23:49:20,350 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.03_min_samples3

2026-10-24 23:49:24,189 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.03_min_samples5

2026-10-24 23:49:28,349 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.03_min_samples7

2026-10-24 23:49:32,255 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.03_min_samples10

2026-10-24 23:49:36,138 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.03_min_samples20

2026-10-24 23:49:40,151 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.03_min_samples30

2026-10-24 23:49:44,608 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.03_min_samples100

2026-10-24 23:49:48,605 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.035_min_samples2

2026-10-24 23:49:52,821 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.035_min_samples3

2026-10-24 23:49:57,055 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.035_min_samples5

2026-10-24 23:50:01,119 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.035_min_samples7

2026-10-24 23:50:05,122 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.035_min_samples10

2026-10-24 23:50:09,222 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.035_min_samples20

2026-10-24 23:50:13,318 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.035_min_samples30

2026-10-24 23:50:17,325 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.035_min_samples100

2026-10-24 23:50:21,193 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.04_min_samples2

2026-10-24 23:50:25,088 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.04_min_samples3

2026-10-24 23:50:29,027 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.04_min_samples5

2026-10-24 23:50:32,972 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.04_min_samples7

2026-10-24 23:50:36,789 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.04_min_samples10

2026-10-24 23:50:40,546 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.04_min_samples20

2026-10-24 23:50:44,339 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.04_min_samples30

2026-10-24 23:50:48,167 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.04_min_samples100

2026-10-24 23:50:51,922 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.05_min_samples2

2026-10-24 23:50:55,753 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.05_min_samples3

2026-10-24 23:50:59,582 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.05_min_samples5

2026-10-24 23:51:03,356 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.05_min_samples7

2026-10-24 23:51:07,222 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.05_min_samples10

2026-10-24 23:51:11,122 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.05_min_samples20

2026-10-24 23:51:15,435 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.05_min_samples30

2026-10-24 23:51:19,572 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.05_min_samples100

2026-10-24 23:51:23,697 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.07_min_samples2

2026-10-24 23:51:27,834 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.07_min_samples3

2026-10-24 23:51:31,856 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.07_min_samples5

2026-10-24 23:51:36,041 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.07_min_samples7

2026-10-24 23:51:40,157 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.07_min_samples10

2026-10-24 23:51:44,367 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.07_min_samples20

2026-10-24 23:51:48,418 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.07_min_samples30

2026-10-24 23:51:52,540 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.07_min_samples100

2026-10-24 23:51:56,649 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.1_min_samples2

2026-10-24 23:52:00,759 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.1_min_samples3

2026-10-24 23:52:05,239 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.1_min_samples5

2026-10-24 23:52:09,222 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.1_min_samples7

2026-10-24 23:52:13,289 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.1_min_samples10

2026-10-24 23:52:17,107 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.1_min_samples20

2026-10-24 23:52:20,874 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.1_min_samples30

2026-10-24 23:52:24,690 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.1_min_samples100

2026-10-24 23:52:28,427 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.5_min_samples2

2026-10-24 23:52:32,585 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.5_min_samples3

2026-10-24 23:52:36,481 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.5_min_samples5

2026-10-24 23:52:40,311 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.5_min_samples7

2026-10-24 23:52:44,122 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.5_min_samples10

2026-10-24 23:52:47,916 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.5_min_samples20

2026-10-24 23:52:51,674 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.5_min_samples30

2026-10-24 23:52:55,424 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps0.5_min_samples100

2026-10-24 23:52:59,206 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps1_min_samples2

2026-10-24 23:53:09,748 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps1_min_samples3

2026-10-24 23:53:20,322 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps1_min_samples5

2026-10-24 23:53:30,816 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps1_min_samples7

2026-10-24 23:53:41,422 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps1_min_samples10

2026-10-24 23:53:51,908 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps1_min_samples20

2026-10-24 23:54:02,572 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps1_min_samples30

2026-10-24 23:54:13,219 INFO Ajustando DBSCAN seed42_word_2_5_min_df1_eps1_min_samples100

2026-10-24 23:54:23,813 INFO Vetorizando analyzer=word, min_df=2, seed=42, descricoes=20000

2026-10-24 23:54:24,258 INFO Analyzer=word min_df=2 seed=42: 20692 termos, 3690 vetores zerados

2026-10-24 23:54:24,258 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.01_min_samples2

2026-10-24 23:54:28,351 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.01_min_samples3

2026-10-24 23:54:32,189 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.01_min_samples5

2026-10-24 23:54:35,989 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.01_min_samples7

2026-10-24 23:54:39,771 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.01_min_samples10

2026-10-24 23:54:43,490 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.01_min_samples20

2026-10-24 23:54:47,230 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.01_min_samples30

2026-10-24 23:54:50,981 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.01_min_samples100

2026-10-24 23:54:54,623 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.02_min_samples2

2026-10-24 23:54:58,769 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.02_min_samples3

2026-10-24 23:55:02,631 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.02_min_samples5

2026-10-24 23:55:06,372 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.02_min_samples7

2026-10-24 23:55:10,184 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.02_min_samples10

2026-10-24 23:55:13,927 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.02_min_samples20

2026-10-24 23:55:17,656 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.02_min_samples30

2026-10-24 23:55:21,423 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.02_min_samples100

2026-10-24 23:55:25,190 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.025_min_samples2

2026-10-24 23:55:29,274 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.025_min_samples3

2026-10-24 23:55:33,145 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.025_min_samples5

2026-10-24 23:55:36,922 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.025_min_samples7

2026-10-24 23:55:40,658 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.025_min_samples10

2026-10-24 23:55:44,412 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.025_min_samples20

2026-10-24 23:55:48,252 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.025_min_samples30

2026-10-24 23:55:52,492 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.025_min_samples100

2026-10-24 23:55:56,909 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.03_min_samples2

2026-10-24 23:56:01,266 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.03_min_samples3

2026-10-24 23:56:05,296 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.03_min_samples5

2026-10-24 23:56:09,281 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.03_min_samples7

2026-10-24 23:56:13,381 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.03_min_samples10

2026-10-24 23:56:17,345 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.03_min_samples20

2026-10-24 23:56:21,293 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.03_min_samples30

2026-10-24 23:56:25,245 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.03_min_samples100

2026-10-24 23:56:29,165 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.035_min_samples2

2026-10-24 23:56:33,549 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.035_min_samples3

2026-10-24 23:56:37,457 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.035_min_samples5

2026-10-24 23:56:41,790 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.035_min_samples7

2026-10-24 23:56:45,915 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.035_min_samples10

2026-10-24 23:56:49,875 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.035_min_samples20

2026-10-24 23:56:53,969 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.035_min_samples30

2026-10-24 23:56:58,031 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.035_min_samples100

2026-10-24 23:57:01,942 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.04_min_samples2

2026-10-24 23:57:06,222 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.04_min_samples3

2026-10-24 23:57:10,119 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.04_min_samples5

2026-10-24 23:57:13,956 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.04_min_samples7

2026-10-24 23:57:17,723 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.04_min_samples10

2026-10-24 23:57:21,369 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.04_min_samples20

2026-10-24 23:57:25,336 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.04_min_samples30

2026-10-24 23:57:29,078 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.04_min_samples100

2026-10-24 23:57:32,867 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.05_min_samples2

2026-10-24 23:57:37,015 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.05_min_samples3

2026-10-24 23:57:40,844 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.05_min_samples5

2026-10-24 23:57:44,623 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.05_min_samples7

2026-10-24 23:57:48,445 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.05_min_samples10

2026-10-24 23:57:52,209 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.05_min_samples20

2026-10-24 23:57:55,949 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.05_min_samples30

2026-10-24 23:57:59,749 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.05_min_samples100

2026-10-24 23:58:04,056 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.07_min_samples2

2026-10-24 23:58:08,557 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.07_min_samples3

2026-10-24 23:58:13,001 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.07_min_samples5

2026-10-24 23:58:17,051 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.07_min_samples7

2026-10-24 23:58:21,017 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.07_min_samples10

2026-10-24 23:58:25,008 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.07_min_samples20

2026-10-24 23:58:28,979 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.07_min_samples30

2026-10-24 23:58:32,950 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.07_min_samples100

2026-10-24 23:58:36,831 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.1_min_samples2

2026-10-24 23:58:41,386 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.1_min_samples3

2026-10-24 23:58:45,424 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.1_min_samples5

2026-10-24 23:58:49,363 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.1_min_samples7

2026-10-24 23:58:53,320 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.1_min_samples10

2026-10-24 23:58:57,430 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.1_min_samples20

2026-10-24 23:59:01,225 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.1_min_samples30

2026-10-24 23:59:04,889 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.1_min_samples100

2026-10-24 23:59:08,521 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.5_min_samples2

2026-10-24 23:59:14,682 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.5_min_samples3

2026-10-24 23:59:19,873 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.5_min_samples5

2026-10-24 23:59:24,210 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.5_min_samples7

2026-10-24 23:59:28,240 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.5_min_samples10

2026-10-24 23:59:32,073 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.5_min_samples20

2026-10-24 23:59:35,857 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.5_min_samples30

2026-10-24 23:59:39,581 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps0.5_min_samples100

2026-10-24 23:59:43,659 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps1_min_samples2

2026-10-24 23:59:54,717 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps1_min_samples3

2026-10-25 00:00:05,353 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps1_min_samples5

2026-10-25 00:00:15,951 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps1_min_samples7

2026-10-25 00:00:26,146 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps1_min_samples10

2026-10-25 00:00:36,472 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps1_min_samples20

2026-10-25 00:00:47,125 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps1_min_samples30

2026-10-25 00:00:57,623 INFO Ajustando DBSCAN seed42_word_2_5_min_df2_eps1_min_samples100

2026-10-25 00:01:08,099 INFO Vetorizando analyzer=word, min_df=5, seed=42, descricoes=20000

2026-10-25 00:01:08,540 INFO Analyzer=word min_df=5 seed=42: 3150 termos, 7981 vetores zerados

2026-10-25 00:01:08,540 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.01_min_samples2

2026-10-25 00:01:13,047 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.01_min_samples3

2026-10-25 00:01:17,280 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.01_min_samples5

2026-10-25 00:01:21,323 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.01_min_samples7

2026-10-25 00:01:25,172 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.01_min_samples10

2026-10-25 00:01:28,918 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.01_min_samples20

2026-10-25 00:01:32,696 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.01_min_samples30

2026-10-25 00:01:36,373 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.01_min_samples100

2026-10-25 00:01:40,122 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.02_min_samples2

2026-10-25 00:01:44,606 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.02_min_samples3

2026-10-25 00:01:48,890 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.02_min_samples5

2026-10-25 00:01:52,945 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.02_min_samples7

2026-10-25 00:01:56,807 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.02_min_samples10

2026-10-25 00:02:00,605 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.02_min_samples20

2026-10-25 00:02:04,292 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.02_min_samples30

2026-10-25 00:02:08,007 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.02_min_samples100

2026-10-25 00:02:11,724 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.025_min_samples2

2026-10-25 00:02:16,324 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.025_min_samples3

2026-10-25 00:02:20,591 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.025_min_samples5

2026-10-25 00:02:24,691 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.025_min_samples7

2026-10-25 00:02:28,657 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.025_min_samples10

2026-10-25 00:02:32,490 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.025_min_samples20

2026-10-25 00:02:36,253 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.025_min_samples30

2026-10-25 00:02:40,024 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.025_min_samples100

2026-10-25 00:02:43,722 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.03_min_samples2

2026-10-25 00:02:48,270 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.03_min_samples3

2026-10-25 00:02:52,574 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.03_min_samples5

2026-10-25 00:02:56,742 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.03_min_samples7

2026-10-25 00:03:00,919 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.03_min_samples10

2026-10-25 00:03:05,094 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.03_min_samples20

2026-10-25 00:03:09,110 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.03_min_samples30

2026-10-25 00:03:13,171 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.03_min_samples100

2026-10-25 00:03:17,157 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.035_min_samples2

2026-10-25 00:03:21,925 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.035_min_samples3

2026-10-25 00:03:26,783 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.035_min_samples5

2026-10-25 00:03:31,057 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.035_min_samples7

2026-10-25 00:03:35,447 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.035_min_samples10

2026-10-25 00:03:39,511 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.035_min_samples20

2026-10-25 00:03:43,608 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.035_min_samples30

2026-10-25 00:03:47,553 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.035_min_samples100

2026-10-25 00:03:51,515 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.04_min_samples2

2026-10-25 00:03:56,347 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.04_min_samples3

2026-10-25 00:04:00,828 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.04_min_samples5

2026-10-25 00:04:05,089 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.04_min_samples7

2026-10-25 00:04:09,178 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.04_min_samples10

2026-10-25 00:04:13,269 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.04_min_samples20

2026-10-25 00:04:17,174 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.04_min_samples30

2026-10-25 00:04:21,129 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.04_min_samples100

2026-10-25 00:04:25,101 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.05_min_samples2

2026-10-25 00:04:29,700 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.05_min_samples3

2026-10-25 00:04:33,971 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.05_min_samples5

2026-10-25 00:04:37,973 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.05_min_samples7

2026-10-25 00:04:41,862 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.05_min_samples10

2026-10-25 00:04:45,657 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.05_min_samples20

2026-10-25 00:04:49,427 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.05_min_samples30

2026-10-25 00:04:53,158 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.05_min_samples100

2026-10-25 00:04:56,817 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.07_min_samples2

2026-10-25 00:05:01,357 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.07_min_samples3

2026-10-25 00:05:05,557 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.07_min_samples5

2026-10-25 00:05:09,599 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.07_min_samples7

2026-10-25 00:05:13,391 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.07_min_samples10

2026-10-25 00:05:17,162 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.07_min_samples20

2026-10-25 00:05:20,916 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.07_min_samples30

2026-10-25 00:05:24,758 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.07_min_samples100

2026-10-25 00:05:28,677 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.1_min_samples2

2026-10-25 00:05:33,474 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.1_min_samples3

2026-10-25 00:05:38,157 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.1_min_samples5

2026-10-25 00:05:42,439 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.1_min_samples7

2026-10-25 00:05:46,679 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.1_min_samples10

2026-10-25 00:05:50,724 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.1_min_samples20

2026-10-25 00:05:54,844 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.1_min_samples30

2026-10-25 00:05:59,020 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.1_min_samples100

2026-10-25 00:06:02,910 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.5_min_samples2

2026-10-25 00:06:08,557 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.5_min_samples3

2026-10-25 00:06:14,358 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.5_min_samples5

2026-10-25 00:06:20,053 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.5_min_samples7

2026-10-25 00:06:25,556 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.5_min_samples10

2026-10-25 00:06:30,628 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.5_min_samples20

2026-10-25 00:06:34,855 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.5_min_samples30

2026-10-25 00:06:38,753 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps0.5_min_samples100

2026-10-25 00:06:43,278 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps1_min_samples2

2026-10-25 00:06:56,224 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps1_min_samples3

2026-10-25 00:07:06,627 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps1_min_samples5

2026-10-25 00:07:16,625 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps1_min_samples7

2026-10-25 00:07:27,189 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps1_min_samples10

2026-10-25 00:07:37,291 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps1_min_samples20

2026-10-25 00:07:48,473 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps1_min_samples30

2026-10-25 00:08:00,035 INFO Ajustando DBSCAN seed42_word_2_5_min_df5_eps1_min_samples100

2026-10-25 00:08:10,908 INFO Vetorizando analyzer=word, min_df=10, seed=42, descricoes=20000

2026-10-25 00:08:11,427 INFO Analyzer=word min_df=10 seed=42: 930 termos, 10796 vetores zerados

2026-10-25 00:08:11,427 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.01_min_samples2

2026-10-25 00:08:16,692 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.01_min_samples3

2026-10-25 00:08:21,192 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.01_min_samples5

2026-10-25 00:08:25,618 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.01_min_samples7

2026-10-25 00:08:29,858 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.01_min_samples10

2026-10-25 00:08:33,847 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.01_min_samples20

2026-10-25 00:08:37,654 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.01_min_samples30

2026-10-25 00:08:41,391 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.01_min_samples100

2026-10-25 00:08:44,915 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.02_min_samples2

2026-10-25 00:08:48,998 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.02_min_samples3

2026-10-25 00:08:52,992 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.02_min_samples5

2026-10-25 00:08:57,054 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.02_min_samples7

2026-10-25 00:09:01,120 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.02_min_samples10

2026-10-25 00:09:05,158 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.02_min_samples20

2026-10-25 00:09:08,842 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.02_min_samples30

2026-10-25 00:09:12,749 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.02_min_samples100

2026-10-25 00:09:16,553 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.025_min_samples2

2026-10-25 00:09:21,096 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.025_min_samples3

2026-10-25 00:09:25,658 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.025_min_samples5

2026-10-25 00:09:30,157 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.025_min_samples7

2026-10-25 00:09:34,488 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.025_min_samples10

2026-10-25 00:09:38,558 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.025_min_samples20

2026-10-25 00:09:42,510 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.025_min_samples30

2026-10-25 00:09:46,722 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.025_min_samples100

2026-10-25 00:09:50,736 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.03_min_samples2

2026-10-25 00:09:55,923 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.03_min_samples3

2026-10-25 00:10:00,658 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.03_min_samples5

2026-10-25 00:10:04,888 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.03_min_samples7

2026-10-25 00:10:09,214 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.03_min_samples10

2026-10-25 00:10:13,501 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.03_min_samples20

2026-10-25 00:10:17,620 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.03_min_samples30

2026-10-25 00:10:21,658 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.03_min_samples100

2026-10-25 00:10:25,451 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.035_min_samples2

2026-10-25 00:10:30,003 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.035_min_samples3

2026-10-25 00:10:34,644 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.035_min_samples5

2026-10-25 00:10:38,758 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.035_min_samples7

2026-10-25 00:10:42,831 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.035_min_samples10

2026-10-25 00:10:46,576 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.035_min_samples20

2026-10-25 00:10:50,058 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.035_min_samples30

2026-10-25 00:10:53,852 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.035_min_samples100

2026-10-25 00:10:57,758 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.04_min_samples2

2026-10-25 00:11:02,130 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.04_min_samples3

2026-10-25 00:11:06,475 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.04_min_samples5

2026-10-25 00:11:10,791 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.04_min_samples7

2026-10-25 00:11:15,175 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.04_min_samples10

2026-10-25 00:11:19,487 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.04_min_samples20

2026-10-25 00:11:23,579 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.04_min_samples30

2026-10-25 00:11:27,558 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.04_min_samples100

2026-10-25 00:11:31,536 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.05_min_samples2

2026-10-25 00:11:36,091 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.05_min_samples3

2026-10-25 00:11:40,543 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.05_min_samples5

2026-10-25 00:11:45,073 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.05_min_samples7

2026-10-25 00:11:49,115 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.05_min_samples10

2026-10-25 00:11:53,136 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.05_min_samples20

2026-10-25 00:11:56,954 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.05_min_samples30

2026-10-25 00:12:00,654 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.05_min_samples100

2026-10-25 00:12:04,291 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.07_min_samples2

2026-10-25 00:12:08,693 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.07_min_samples3

2026-10-25 00:12:12,916 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.07_min_samples5

2026-10-25 00:12:17,053 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.07_min_samples7

2026-10-25 00:12:21,130 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.07_min_samples10

2026-10-25 00:12:25,051 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.07_min_samples20

2026-10-25 00:12:28,823 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.07_min_samples30

2026-10-25 00:12:32,546 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.07_min_samples100

2026-10-25 00:12:36,307 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.1_min_samples2

2026-10-25 00:12:40,692 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.1_min_samples3

2026-10-25 00:12:44,958 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.1_min_samples5

2026-10-25 00:12:49,139 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.1_min_samples7

2026-10-25 00:12:53,620 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.1_min_samples10

2026-10-25 00:12:57,951 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.1_min_samples20

2026-10-25 00:13:02,035 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.1_min_samples30

2026-10-25 00:13:05,948 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.1_min_samples100

2026-10-25 00:13:09,957 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.5_min_samples2

2026-10-25 00:13:14,992 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.5_min_samples3

2026-10-25 00:13:19,929 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.5_min_samples5

2026-10-25 00:13:24,846 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.5_min_samples7

2026-10-25 00:13:29,755 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.5_min_samples10

2026-10-25 00:13:34,675 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.5_min_samples20

2026-10-25 00:13:39,725 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.5_min_samples30

2026-10-25 00:13:44,128 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps0.5_min_samples100

2026-10-25 00:13:47,937 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps1_min_samples2

2026-10-25 00:13:58,683 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps1_min_samples3

2026-10-25 00:14:08,884 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps1_min_samples5

2026-10-25 00:14:19,225 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps1_min_samples7

2026-10-25 00:14:29,652 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps1_min_samples10

2026-10-25 00:14:40,138 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps1_min_samples20

2026-10-25 00:14:50,707 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps1_min_samples30

2026-10-25 00:15:01,118 INFO Ajustando DBSCAN seed42_word_2_5_min_df10_eps1_min_samples100

### Calcular a metrica composta e ordenar os resultados

A silhouette e reescalada para 0 a 1 e combinada com a proporcao de descricoes classificadas (`1 - noise_fraction`). O score composto determina a ordem; silhouette e ruido servem apenas de desempate quando os scores forem iguais.

In [7]:
if not 1 <= MIN_CLUSTER_FOR_RANKING <= MAX_CLUSTERS_FOR_RANKING:
    raise ValueError(
        "Os limites devem atender a 1 <= MIN_CLUSTER_FOR_RANKING <= MAX_CLUSTERS_FOR_RANKING."
    )

if SILHOUETTE_WEIGHT < 0 or NOISE_WEIGHT < 0 or SILHOUETTE_WEIGHT + NOISE_WEIGHT <= 0:
    raise ValueError("Os pesos devem ser nao negativos e pelo menos um deles deve ser maior que zero.")

# Silhouette varia de -1 a 1; reescale para 0 a 1 para combinar com cobertura.
results["silhouette_quality"] = (results["silhouette_cosine_without_noise"] + 1) / 2
results["noise_quality"] = 1 - results["noise_fraction"]
weight_total = SILHOUETTE_WEIGHT + NOISE_WEIGHT
results["composite_score"] = (
    SILHOUETTE_WEIGHT * results["silhouette_quality"]
    + NOISE_WEIGHT * results["noise_quality"]
) / weight_total

# O score composto e o criterio principal; os outros criterios so desempataram scores iguais.
ranking = (
    results.loc[
        results["cluster_count_excluding_noise"].between(
            MIN_CLUSTER_FOR_RANKING, MAX_CLUSTERS_FOR_RANKING, inclusive="both",
        ) & results["silhouette_cosine_without_noise"].notna()
    ]
    .sort_values(
        ["composite_score", "silhouette_cosine_without_noise", "noise_fraction"],
        ascending=[False, False, True], na_position="last",
    )
    .reset_index(drop=True)
)
if ranking.empty:
    raise ValueError(
        f"Nenhum resultado atende ao intervalo de {MIN_CLUSTER_FOR_RANKING} a "
        f"{MAX_CLUSTERS_FOR_RANKING} clusters. Ajuste eps/min_samples ou o limite."
    )
# Explicita a posicao de cada configuracao depois dos filtros e criterios acima.
ranking.insert(0, "rank", range(1, len(ranking) + 1))

In [8]:
display(ranking)

,rank,run_id,sample_seed,representation,analyzer,ngram_range,min_df,feature_count,zero_vector_count,eps,...,frequency_weighted,cluster_count_excluding_noise,noise_count,noise_fraction,silhouette_base_sample_size,silhouette_sample_size,silhouette_cosine_without_noise,silhouette_quality,noise_quality,composite_score
0,1,seed42_word_2_5_min_df10_eps0.025_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.025,...,False,734,12783,0.63915,20000,7217,0.999630,0.999815,0.36085,0.840074
1,2,seed42_word_2_5_min_df10_eps0.01_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.010,...,False,734,12792,0.63960,20000,7208,0.999859,0.999929,0.36040,0.840047
2,3,seed42_word_2_5_min_df10_eps0.03_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.030,...,False,734,12781,0.63905,20000,7219,0.999473,0.999737,0.36095,0.840040
3,4,seed42_word_2_5_min_df10_eps0.02_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.020,...,False,734,12788,0.63940,20000,7212,0.999681,0.999840,0.36060,0.840030
4,5,seed42_word_2_5_min_df10_eps0.05_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.050,...,False,734,12753,0.63765,20000,7247,0.998388,0.999194,0.36235,0.839983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1280,1281,seed42_char_wb_4_10_min_df1_eps0.5_min_samples30,42,char_wb_4_10,char_wb,"(4, 10)",1,100000,0,0.500,...,False,27,11876,0.59380,20000,8124,0.031995,0.515998,0.40620,0.488548
1281,1282,seed42_char_wb_5_10_min_df1_eps0.5_min_samples30,42,char_wb_5_10,char_wb,"(5, 10)",1,100000,1,0.500,...,False,20,11623,0.58115,20000,8377,0.019892,0.509946,0.41885,0.487172
1282,1283,seed42_word_2_5_min_df10_eps0.5_min_samples20,42,word_2_5,word,"(2, 5)",10,930,10796,0.500,...,False,29,11972,0.59860,20000,8028,0.031036,0.515518,0.40140,0.486988
1283,1284,seed42_word_2_5_min_df10_eps0.5_min_samples30,42,word_2_5,word,"(2, 5)",10,930,10796,0.500,...,False,26,13883,0.69415,20000,6117,0.054613,0.527307,0.30585,0.471942
1284,1285,seed42_word_2_5_min_df5_eps0.5_min_samples30,42,word_2_5,word,"(2, 5)",5,3150,7981,0.500,...,False,21,16549,0.82745,20000,3451,0.133639,0.566819,0.17255,0.468252

In [9]:
ranking.head(20)

,rank,run_id,sample_seed,representation,analyzer,ngram_range,min_df,feature_count,zero_vector_count,eps,...,frequency_weighted,cluster_count_excluding_noise,noise_count,noise_fraction,silhouette_base_sample_size,silhouette_sample_size,silhouette_cosine_without_noise,silhouette_quality,noise_quality,composite_score
0,1,seed42_word_2_5_min_df10_eps0.025_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.025,...,False,734,12783,0.63915,20000,7217,0.999630,0.999815,0.36085,0.840074
1,2,seed42_word_2_5_min_df10_eps0.01_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.010,...,False,734,12792,0.63960,20000,7208,0.999859,0.999929,0.36040,0.840047
2,3,seed42_word_2_5_min_df10_eps0.03_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.030,...,False,734,12781,0.63905,20000,7219,0.999473,0.999737,0.36095,0.840040
3,4,seed42_word_2_5_min_df10_eps0.02_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.020,...,False,734,12788,0.63940,20000,7212,0.999681,0.999840,0.36060,0.840030
4,5,seed42_word_2_5_min_df10_eps0.05_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.050,...,False,734,12753,0.63765,20000,7247,0.998388,0.999194,0.36235,0.839983
5,6,seed42_word_2_5_min_df10_eps0.07_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.070,...,False,737,12729,0.63645,20000,7271,0.997231,0.998616,0.36355,0.839849
6,7,seed42_word_2_5_min_df10_eps0.035_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.035,...,False,736,12768,0.63840,20000,7232,0.998382,0.999191,0.36160,0.839793
7,8,seed42_word_2_5_min_df10_eps0.04_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.040,...,False,735,12763,0.63815,20000,7237,0.998174,0.999087,0.36185,0.839778
8,9,seed42_word_2_5_min_df10_eps0.1_min_samples3,42,word_2_5,word,"(2, 5)",10,930,10796,0.100,...,False,745,12654,0.63270,20000,7346,0.992096,0.996048,0.36730,0.838861
9,10,seed42_word_2_5_min_df10_eps0.03_min_samples5,42,word_2_5,word,"(2, 5)",10,930,10796,0.030,...,False,514,13517,0.67585,20000,6483,0.999926,0.999963,0.32415,0.831010
10,11,seed42_word_2_5_min_df10_eps0.025_min_samples5,42,word_2_5,word,"(2, 5)",10,930,10796,0.025,...,False,514,13518,0.67590,20000,6482,0.999937,0.999968,0.32410,0.831001
11,12,seed42_word_2_5_min_df10_eps0.05_min_samples5,42,word_2_5,word,"(2, 5)",10,930,10796,0.050,...,False,515,13483,0.67415,20000,6517,0.998625,0.999313,0.32585,0.830947
12,13,seed42_word_2_5_min_df10_eps0.02_min_samples5,42,word_2_5,word,"(2, 5)",10,930,10796,0.020,...,False,514,13524,0.67620,20000,6476,0.999977,0.999988,0.32380,0.830941
13,14,seed42_word_2_5_min_df10_eps0.07_min_samples5,42,word_2_5,word,"(2, 5)",10,930,10796,0.070,...,False,519,13455,0.67275,20000,6545,0.997662,0.998831,0.32725,0.830936
14,15,seed42_word_2_5_min_df10_eps0.01_min_samples5,42,word_2_5,word,"(2, 5)",10,930,10796,0.010,...,False,513,13529,0.67645,20000,6471,0.999985,0.999993,0.32355,0.830882
15,16,seed42_word_2_5_min_df10_eps0.1_min_samples5,42,word_2_5,word,"(2, 5)",10,930,10796,0.100,...,False,522,13390,0.66950,20000,6610,0.995352,0.997676,0.33050,0.830882
16,17,seed42_word_2_5_min_df10_eps0.04_min_samples5,42,word_2_5,word,"(2, 5)",10,930,10796,0.040,...,False,514,13500,0.67500,20000,6500,0.998898,0.999449,0.32500,0.830837
17,18,seed42_word_2_5_min_df10_eps0.035_min_samples5,42,word_2_5,word,"(2, 5)",10,930,10796,0.035,...,False,512,13516,0.67580,20000,6484,0.999011,0.999506,0.32420,0.830679
18,19,seed42_word_2_5_min_df10_eps0.07_min_samples7,42,word_2_5,word,"(2, 5)",10,930,10796,0.070,...,False,410,14042,0.70210,20000,5958,0.998685,0.999342,0.29790,0.823982
19,20,seed42_word_2_5_min_df10_eps0.1_min_samples7,42,word_2_5,word,"(2, 5)",10,930,10796,0.100,...,False,415,13967,0.69835,20000,6033,0.996120,0.998060,0.30165,0.823958

## 5. Revisar um resultado e salvar relat?rios

Escolha `SELECTED_RUN_ID` ap?s comparar quantidade de clusters, ru?do e silhouette. A tabela de resumo inclui `-1` como grupo de ru?do. Os arquivos s?o gravados em uma pasta com identificador UTC ?nico para preservar execu??es anteriores.

Os graficos ficam em `tsne_plots/`, um PNG por combinacao, e as coordenadas da amostra em `tsne_coordinates/`, dentro da pasta da execucao.

In [10]:
SELECTED_RUN_ID = ranking.iloc[0]["run_id"]
selected = results.set_index("run_id").loc[SELECTED_RUN_ID]
selected_items = items_by_run[SELECTED_RUN_ID]
selected_labels = labels_by_run[SELECTED_RUN_ID]
assignments, cluster_summary = summarize_clusters(selected_items, selected_labels)
cluster_summary = cluster_summary.sort_values("frequencia_total", ascending=False).reset_index(drop=True)
cluster_sizes = assignments.loc[assignments["cluster"].ne(-1)].groupby("cluster")[DESCRIPTION_NORMALIZED].size()
singleton_clusters = cluster_sizes[cluster_sizes.eq(1)].index
frequent_singletons = assignments[assignments["cluster"].isin(singleton_clusters)].sort_values(
    FREQUENCY, ascending=False
)
frequent_noise = assignments[assignments["cluster"].eq(-1)].sort_values(
    FREQUENCY, ascending=False
)
display(cluster_summary.head(20))
display(frequent_singletons.head(20))
display(frequent_noise.head(20))

RUN_ID = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ%f")
output_dir = OUTPUT_ROOT / f"{PERIOD_LABEL}_{RUN_ID}"
output_dir.mkdir(parents=True, exist_ok=False)
results.to_csv(output_dir / "metrics.csv", index=False)
ranking.to_csv(output_dir / "ranking.csv", index=False)
assignments.to_csv(output_dir / "assignments.csv", index=False, encoding="utf-8-sig")
cluster_summary.to_csv(output_dir / "cluster_summary.csv", index=False, encoding="utf-8-sig")
frequent_singletons.to_csv(
    output_dir / "frequent_singleton_descriptions.csv", index=False, encoding="utf-8-sig"
)
frequent_noise.to_csv(
    output_dir / "frequent_noise_descriptions.csv", index=False, encoding="utf-8-sig"
)

    cluster  descricoes_unicas  frequencia_total
0        -1              12783             63659
1        18                 20              3622
2       246                 13              1952
3       101                 71              1669
4       264                 29              1543
5       609                 34              1164
6       437                 59              1061
7       402                 11               953
8       211                 31               942
9       332                 15               901
10      580                 23               851
11      367                  5               773
12      334                  6               754
13      686                126               648
14      392                 53               643
15       19                 86               588
16      663                 17               581
17      249                 13               576
18       23                 27               489
19       84                 55               478

Empty DataFrame
Columns: [descricao_normalizada, frequencia, cluster, ruido]
Index: []

                           descricao_normalizada  frequencia  cluster  ruido
10531                                     jantar        1493       -1   True
18043                                   salsicha        1339       -1   True
18070                                salsicha kg         906       -1   True
13101                    multiuso 500ml ye advir         871       -1   True
1727            apagador quadro branco go office         805       -1   True
4572                          caldo galinha 1 kg         717       -1   True
16199                                   refeicao         612       -1   True
15582            prancheta eucatex oficio c 1 un         574       -1   True
4904                                        ceia         567       -1   True
17795                                        sal         540       -1   True
5079              chamex solution a4 c 10 resmas         442       -1   True
8506              fermento biologico seco 500 gr         404       -1   True
8014                                      etanol         350       -1   True
6927                                  detergente         346       -1   True
12553                             milho conserva         331       -1   True
10201  inseticida aerosol 300ml multi inseticida         312       -1   True
13589                                       paes         288       -1   True
1850      aromatizante odorizante aerosol 400 ml         267       -1   True
580                               acucar mascavo         258       -1   True
769                                     adocante         245       -1   True

## 6. Gerar visualizacoes t-SNE 2D e 3D

Esta etapa roda depois do ajuste e do ranking. Ela projeta as matrizes TF-IDF ja calculadas e salva as coordenadas e os graficos, sem executar novamente o DBSCAN.

In [11]:
# Calcula as proje??es 2D existentes e uma proje??o 3D separada por representa??o.
tsne_by_representation = {}
tsne_3d_by_representation = {}
for (sample_seed, representation, min_df), matrix in matrices_by_representation.items():
    logger.info("Calculando t-SNE 2D para %s, min_df=%d, seed=%d", representation, min_df, sample_seed)
    tsne_indices, tsne_coordinates, tsne_dimensions = compute_tsne_projection(
        matrix, TSNE_MAX_POINTS, TSNE_PERPLEXITY, TSNE_MAX_ITER,
        TSNE_RANDOM_STATE,
    )
    tsne_by_representation[(sample_seed, representation, min_df)] = {
        "indices": tsne_indices, "coordinates": tsne_coordinates,
        "reduced_dimensions": tsne_dimensions,
    }

    logger.info("Calculando t-SNE 3D para %s, min_df=%d, seed=%d", representation, min_df, sample_seed)
    tsne_3d_indices, tsne_3d_coordinates, tsne_3d_dimensions = compute_tsne_projection(
        matrix, TSNE_MAX_POINTS, TSNE_PERPLEXITY, TSNE_MAX_ITER,
        TSNE_RANDOM_STATE, n_components=TSNE_3D_N_COMPONENTS,
    )
    if not np.array_equal(tsne_indices, tsne_3d_indices):
        raise ValueError("As proje??es 2D e 3D devem usar a mesma amostra de descri??es.")
    tsne_3d_by_representation[(sample_seed, representation, min_df)] = {
        "indices": tsne_3d_indices, "coordinates": tsne_3d_coordinates,
        "reduced_dimensions": tsne_3d_dimensions,
    }

# Salva coordenadas 2D e um PNG por configura??o.
tsne_coordinates_dir = output_dir / "tsne_coordinates"
tsne_plots_dir = output_dir / "tsne_plots"
tsne_3d_html_dir = output_dir / "tsne_3d_html"
tsne_coordinates_dir.mkdir()
tsne_plots_dir.mkdir()
tsne_3d_html_dir.mkdir()
tsne_artifacts = {}
for (sample_seed, representation, min_df), projection in tsne_by_representation.items():
    indices = projection["indices"]
    coordinates = projection["coordinates"]
    coordinate_frame = items_by_seed[sample_seed].iloc[indices][
        [DESCRIPTION_NORMALIZED, FREQUENCY]
    ].reset_index(drop=True)
    coordinate_frame["tsne_1"] = coordinates[:, 0]
    coordinate_frame["tsne_2"] = coordinates[:, 1]
    coordinate_name = f"seed{sample_seed}_{representation}_min_df{min_df}_coordinates.csv"
    coordinate_frame.to_csv(
        tsne_coordinates_dir / coordinate_name, index=False, encoding="utf-8-sig",
    )
    tsne_artifacts[f"seed{sample_seed}_{representation}_min_df{min_df}"] = {
        "coordinates_file": f"tsne_coordinates/{coordinate_name}",
        "sample_size": len(indices),
        "reduced_dimensions": projection["reduced_dimensions"],
    }

for run_id, labels in labels_by_run.items():
    result_row = results.loc[results["run_id"].eq(run_id)].iloc[0]
    representation_key = (
        int(result_row["sample_seed"]), result_row["representation"], int(result_row["min_df"]),
    )
    projection = tsne_by_representation[representation_key]
    projection_3d = tsne_3d_by_representation[representation_key]
    plot_labels = np.asarray(labels)[projection["indices"]]
    plot_path = tsne_plots_dir / f"{run_id}.png"
    save_tsne_plot(projection["coordinates"], plot_labels, run_id, plot_path)
    tsne_artifacts[f"plot:{run_id}"] = str(plot_path.relative_to(output_dir))

    plot_3d_path = tsne_3d_html_dir / f"{run_id}.html"
    save_tsne_3d_html(projection_3d["coordinates"], plot_labels, run_id, plot_3d_path)
    tsne_artifacts[f"plot_3d:{run_id}"] = str(plot_3d_path.relative_to(output_dir))

logger.info("Imagens t-SNE 2D e gr?ficos HTML 3D salvos: %d", len(labels_by_run))

run_metadata = {
    "comparison": comparison_metadata(items_by_seed[SAMPLE_SEEDS[0]]),
    "dataset_name": DATASET_NAME, "period": PERIOD_LABEL,
    "frequency_weighted": CONSIDER_FREQUENCY_IN_CLUSTERING,
    "dataset_path": str(DATASET_PATH), "max_descriptions": MAX_DESCRIPTIONS,
    "sample_seeds": SAMPLE_SEEDS, "analyzer_configs": {
        representation: {"analyzer": analyzer, "ngram_range": list(ngram_range)}
        for representation, (analyzer, ngram_range) in ANALYZER_CONFIGS.items()
    },
    "min_df_values": MIN_DF_VALUES, "max_features": MAX_FEATURES,
    "selected_run_id": SELECTED_RUN_ID,
    "eps_values": EPS_VALUES, "min_samples_values": MIN_SAMPLES_VALUES,
    "silhouette_sample_size": SILHOUETTE_SAMPLE_SIZE,
    "pairwise_working_memory_mib": PAIRWISE_WORKING_MEMORY_MIB,
    "max_clusters_for_ranking": MAX_CLUSTERS_FOR_RANKING,
    "min_cluster_for_ranking": MIN_CLUSTER_FOR_RANKING,
    "silhouette_weight": SILHOUETTE_WEIGHT, "noise_weight": NOISE_WEIGHT,
    "tsne": {
        "max_points": TSNE_MAX_POINTS, "perplexity": TSNE_PERPLEXITY,
        "max_iter": TSNE_MAX_ITER, "random_state": TSNE_RANDOM_STATE,
        "svd_components": TSNE_SVD_COMPONENTS,
        "three_dimensional_components": TSNE_3D_N_COMPONENTS,
        "artifacts": tsne_artifacts,
    },
}
(output_dir / "run.json").write_text(
    json.dumps(run_metadata, indent=2, ensure_ascii=False), encoding="utf-8"
)
logger.info("Relatorios e imagens t-SNE salvos em %s", output_dir)

2026-10-25 00:15:12,357 INFO Calculando t-SNE 2D para char_wb_2_4, min_df=1, seed=42

2026-10-25 00:15:21,116 INFO Calculando t-SNE 3D para char_wb_2_4, min_df=1, seed=42

2026-10-25 00:15:41,825 INFO Calculando t-SNE 2D para char_wb_2_4, min_df=2, seed=42

2026-10-25 00:15:52,053 INFO Calculando t-SNE 3D para char_wb_2_4, min_df=2, seed=42

2026-10-25 00:16:16,982 INFO Calculando t-SNE 2D para char_wb_2_4, min_df=5, seed=42

2026-10-25 00:16:29,921 INFO Calculando t-SNE 3D para char_wb_2_4, min_df=5, seed=42

2026-10-25 00:17:04,221 INFO Calculando t-SNE 2D para char_wb_2_4, min_df=10, seed=42

2026-10-25 00:17:20,959 INFO Calculando t-SNE 3D para char_wb_2_4, min_df=10, seed=42

2026-10-25 00:17:52,470 INFO Calculando t-SNE 2D para char_wb_2_10, min_df=1, seed=42

2026-10-25 00:18:05,507 INFO Calculando t-SNE 3D para char_wb_2_10, min_df=1, seed=42

2026-10-25 00:18:33,312 INFO Calculando t-SNE 2D para char_wb_2_10, min_df=2, seed=42

2026-10-25 00:18:45,699 INFO Calculando t-SNE 3D para char_wb_2_10, min_df=2, seed=42

2026-10-25 00:19:12,881 INFO Calculando t-SNE 2D para char_wb_2_10, min_df=5, seed=42

2026-10-25 00:19:28,675 INFO Calculando t-SNE 3D para char_wb_2_10, min_df=5, seed=42

2026-10-25 00:20:05,602 INFO Calculando t-SNE 2D para char_wb_2_10, min_df=10, seed=42

2026-10-25 00:20:20,713 INFO Calculando t-SNE 3D para char_wb_2_10, min_df=10, seed=42

2026-10-25 00:20:46,296 INFO Calculando t-SNE 2D para char_wb_3_5, min_df=1, seed=42

2026-10-25 00:20:57,926 INFO Calculando t-SNE 3D para char_wb_3_5, min_df=1, seed=42

2026-10-25 00:21:20,950 INFO Calculando t-SNE 2D para char_wb_3_5, min_df=2, seed=42

2026-10-25 00:21:33,384 INFO Calculando t-SNE 3D para char_wb_3_5, min_df=2, seed=42

2026-10-25 00:22:03,224 INFO Calculando t-SNE 2D para char_wb_3_5, min_df=5, seed=42

2026-10-25 00:22:20,464 INFO Calculando t-SNE 3D para char_wb_3_5, min_df=5, seed=42

2026-10-25 00:22:51,665 INFO Calculando t-SNE 2D para char_wb_3_5, min_df=10, seed=42

2026-10-25 00:23:04,505 INFO Calculando t-SNE 3D para char_wb_3_5, min_df=10, seed=42

2026-10-25 00:23:26,100 INFO Calculando t-SNE 2D para char_wb_3_10, min_df=1, seed=42

2026-10-25 00:23:38,530 INFO Calculando t-SNE 3D para char_wb_3_10, min_df=1, seed=42

2026-10-25 00:24:04,913 INFO Calculando t-SNE 2D para char_wb_3_10, min_df=2, seed=42

2026-10-25 00:24:21,565 INFO Calculando t-SNE 3D para char_wb_3_10, min_df=2, seed=42

2026-10-25 00:24:56,118 INFO Calculando t-SNE 2D para char_wb_3_10, min_df=5, seed=42

2026-10-25 00:25:10,226 INFO Calculando t-SNE 3D para char_wb_3_10, min_df=5, seed=42

2026-10-25 00:25:33,512 INFO Calculando t-SNE 2D para char_wb_3_10, min_df=10, seed=42

2026-10-25 00:25:44,054 INFO Calculando t-SNE 3D para char_wb_3_10, min_df=10, seed=42

2026-10-25 00:26:07,952 INFO Calculando t-SNE 2D para char_wb_4_8, min_df=1, seed=42

2026-10-25 00:26:23,253 INFO Calculando t-SNE 3D para char_wb_4_8, min_df=1, seed=42

2026-10-25 00:27:02,419 INFO Calculando t-SNE 2D para char_wb_4_8, min_df=2, seed=42

2026-10-25 00:27:19,847 INFO Calculando t-SNE 3D para char_wb_4_8, min_df=2, seed=42

2026-10-25 00:27:47,180 INFO Calculando t-SNE 2D para char_wb_4_8, min_df=5, seed=42

2026-10-25 00:27:58,646 INFO Calculando t-SNE 3D para char_wb_4_8, min_df=5, seed=42

2026-10-25 00:28:23,517 INFO Calculando t-SNE 2D para char_wb_4_8, min_df=10, seed=42

2026-10-25 00:28:38,537 INFO Calculando t-SNE 3D para char_wb_4_8, min_df=10, seed=42

2026-10-25 00:29:15,434 INFO Calculando t-SNE 2D para char_wb_4_10, min_df=1, seed=42

2026-10-25 00:29:34,056 INFO Calculando t-SNE 3D para char_wb_4_10, min_df=1, seed=42

2026-10-25 00:30:03,526 INFO Calculando t-SNE 2D para char_wb_4_10, min_df=2, seed=42

2026-10-25 00:30:15,640 INFO Calculando t-SNE 3D para char_wb_4_10, min_df=2, seed=42

2026-10-25 00:30:38,976 INFO Calculando t-SNE 2D para char_wb_4_10, min_df=5, seed=42

2026-10-25 00:30:53,805 INFO Calculando t-SNE 3D para char_wb_4_10, min_df=5, seed=42

2026-10-25 00:31:27,453 INFO Calculando t-SNE 2D para char_wb_4_10, min_df=10, seed=42

2026-10-25 00:31:46,021 INFO Calculando t-SNE 3D para char_wb_4_10, min_df=10, seed=42

2026-10-25 00:32:12,552 INFO Calculando t-SNE 2D para char_wb_5_10, min_df=1, seed=42

2026-10-25 00:32:25,329 INFO Calculando t-SNE 3D para char_wb_5_10, min_df=1, seed=42

2026-10-25 00:32:47,751 INFO Calculando t-SNE 2D para char_wb_5_10, min_df=2, seed=42

2026-10-25 00:33:00,113 INFO Calculando t-SNE 3D para char_wb_5_10, min_df=2, seed=42

2026-10-25 00:33:30,664 INFO Calculando t-SNE 2D para char_wb_5_10, min_df=5, seed=42

2026-10-25 00:33:49,117 INFO Calculando t-SNE 3D para char_wb_5_10, min_df=5, seed=42

2026-10-25 00:34:21,607 INFO Calculando t-SNE 2D para char_wb_5_10, min_df=10, seed=42

2026-10-25 00:34:35,309 INFO Calculando t-SNE 3D para char_wb_5_10, min_df=10, seed=42

2026-10-25 00:34:57,618 INFO Calculando t-SNE 2D para word_1_3, min_df=1, seed=42

2026-10-25 00:35:09,341 INFO Calculando t-SNE 3D para word_1_3, min_df=1, seed=42

2026-10-25 00:35:32,674 INFO Calculando t-SNE 2D para word_1_3, min_df=2, seed=42

2026-10-25 00:35:45,849 INFO Calculando t-SNE 3D para word_1_3, min_df=2, seed=42

2026-10-25 00:36:16,743 INFO Calculando t-SNE 2D para word_1_3, min_df=5, seed=42

2026-10-25 00:36:33,747 INFO Calculando t-SNE 3D para word_1_3, min_df=5, seed=42

2026-10-25 00:37:03,068 INFO Calculando t-SNE 2D para word_1_3, min_df=10, seed=42

2026-10-25 00:37:16,004 INFO Calculando t-SNE 3D para word_1_3, min_df=10, seed=42

2026-10-25 00:37:36,920 INFO Calculando t-SNE 2D para word_1_5, min_df=1, seed=42

2026-10-25 00:37:49,177 INFO Calculando t-SNE 3D para word_1_5, min_df=1, seed=42

2026-10-25 00:38:16,129 INFO Calculando t-SNE 2D para word_1_5, min_df=2, seed=42

2026-10-25 00:38:31,385 INFO Calculando t-SNE 3D para word_1_5, min_df=2, seed=42

2026-10-25 00:39:05,384 INFO Calculando t-SNE 2D para word_1_5, min_df=5, seed=42

2026-10-25 00:39:20,319 INFO Calculando t-SNE 3D para word_1_5, min_df=5, seed=42

2026-10-25 00:39:44,476 INFO Calculando t-SNE 2D para word_1_5, min_df=10, seed=42

2026-10-25 00:39:55,671 INFO Calculando t-SNE 3D para word_1_5, min_df=10, seed=42

2026-10-25 00:40:17,662 INFO Calculando t-SNE 2D para word_2_5, min_df=1, seed=42

2026-10-25 00:40:33,057 INFO Calculando t-SNE 3D para word_2_5, min_df=1, seed=42

2026-10-25 00:41:13,327 INFO Calculando t-SNE 2D para word_2_5, min_df=2, seed=42

2026-10-25 00:41:32,345 INFO Calculando t-SNE 3D para word_2_5, min_df=2, seed=42

2026-10-25 00:42:03,115 INFO Calculando t-SNE 2D para word_2_5, min_df=5, seed=42

2026-10-25 00:42:13,998 INFO Calculando t-SNE 3D para word_2_5, min_df=5, seed=42

2026-10-25 00:42:57,237 INFO Calculando t-SNE 2D para word_2_5, min_df=10, seed=42

2026-10-25 00:43:07,598 INFO Calculando t-SNE 3D para word_2_5, min_df=10, seed=42

2026-10-25 00:55:58,451 INFO Imagens t-SNE 2D e gr?ficos HTML 3D salvos: 3520

2026-10-25 00:55:58,481 INFO Relatorios e imagens t-SNE salvos em C:\Users\samuel.simao\Sources\Nofis-Classifier\reports\tfidf_dbscan\202501-202512_20261025T031512Z159795

## 7. Interpretacao??o

- `noise_fraction` alta significa que muitas descri??es n?o entraram em regi?es densas para os par?metros escolhidos.
- Poucos clusters ou um cluster dominante podem indicar que `eps` est? grande; quase tudo como ru?do pode indicar `eps` pequeno ou `min_samples` alto.
- Silhouette mais alta deve ser lida junto da fra??o de ru?do: uma pontua??o calculada em poucos itens pode ser enganosa.
- DBSCAN n?o atribui automaticamente novos produtos a clusters ap?s o ajuste e n?o define categorias sem revis?o humana.

- Os HTML em `tsne_3d_html/` cont?m uma proje??o t-SNE 3D que pode ser girada com o mouse e aberta sem depend?ncias externas.