# 74 ? Experimento TF-IDF + HDBSCAN

Este notebook agrupa descri??es normalizadas de itens de supermercado usando TF-IDF e HDBSCAN. A an?lise usa dist?ncia cosseno, n?o usa NCM nem r?tulos humanos e trata ru?do como resultado expl?cito do algoritmo. A amostra configur?vel mant?m o custo do experimento controlado. Execute de cima para baixo em uma sess?o limpa.

In [1]:
from sklearn import config_context
from hashlib import sha256
from datetime import datetime, timezone
from pathlib import Path
import logging
import json

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display
from sklearn.cluster import HDBSCAN
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import silhouette_score
from sklearn.manifold import TSNE
from sklearn.decomposition import TruncatedSVD
from matplotlib.colors import ListedColormap

from nofis_classifier.schema import DESCRIPTION_NORMALIZED, FREQUENCY

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("notebook74")
pd.set_option("display.max_colwidth", 140)

## Configuracoes e comparabilidade

Controles comuns aos notebooks 70 a 76:

- Base completa `2025_NCMs_filtrados_semstopwords`, periodo 202501-202512.
- Ate 20.000 descricoes unicas para agrupamento, amostradas com semente 42 e ordenadas por descricao normalizada. Frequencia nao pondera o ajuste.
- Silhouette cosseno sobre uma amostra base fixa de ate 20.000 linhas, com semente 42. Ruido do algoritmo e excluido depois da amostragem; a quantidade efetivamente avaliada e registrada.
- Ranking exige silhouette definida e de 10 a 1.000 clusters efetivamente formados, sem contar ruido. Pesos: 0,75 para silhouette reescalada e 0,25 para cobertura do algoritmo.
- t-SNE 2D e 3D: mesmos ate 5.000 itens, semente 42, TruncatedSVD de ate 50 componentes, perplexidade 30, 1.000 iteracoes, init PCA (quando ha dimensoes suficientes), learning_rate auto e Barnes-Hut. As projecoes de representacoes diferentes sao exploratorias, nao um espaco comum de distancias.
- `comparison` em `run.json` registra os controles e o hash das descricoes/frequencias usadas no agrupamento.

TF-IDF: os mesmos 10 analyzers dos experimentos de texto, cruzados com `MIN_DF_VALUES = [1, 2, 5, 10]`, max_features 100.000, max_df 1.0, sublinear_tf True, norm l2 e dtype float64. Os vetores zerados sao registrados como diagnostico da representacao, separados do ruido do algoritmo.

HDBSCAN: min_cluster_size 2/5/10/20, min_samples None/2/5/10, selecao eom, metric cosine, algorithm brute e n_jobs 1, como nos notebooks 75 e 76. Grade atual: 40 representacoes x 16 combinacoes = 640 ajustes.

In [2]:
DATASET_NAME = "2025_NCMs_filtrados_semstopwords"

PROJECT_ROOT = next(
    (parent for parent in (Path.cwd(), *Path.cwd().parents)
     if (parent / "data" / "processed").is_dir()),
    None,
)
if PROJECT_ROOT is None:
    raise FileNotFoundError("N?o encontrei a raiz do reposit?rio com data/processed/.")
DATASET_DIR = PROJECT_ROOT / "data" / "processed" / DATASET_NAME
DATASET_FILES = sorted(DATASET_DIR.glob("*.parquet"))
if not DATASET_FILES:
    raise FileNotFoundError(f"Nenhum Parquet encontrado para {DATASET_NAME}: {DATASET_DIR}")
if len(DATASET_FILES) > 1:
    raise ValueError(
        f"Mais de um Parquet encontrado em {DATASET_DIR}; selecione o arquivo/per?odo explicitamente: "
        f"{[path.name for path in DATASET_FILES]}"
    )
DATASET_PATH = DATASET_FILES[0]
if not DATASET_PATH.stem.startswith(f"{DATASET_NAME}-"):
    raise ValueError(
        f"O nome do arquivo deve come?ar com '{DATASET_NAME}-' para derivar o per?odo: "
        f"{DATASET_PATH.name}"
    )

PERIOD_LABEL = DATASET_PATH.stem[len(DATASET_NAME) + 1:]
MAX_DESCRIPTIONS = 20_000
SILHOUETTE_SAMPLE_SIZE = 20_000
SAMPLE_SEEDS = [42]
ANALYZER_CONFIGS = {'char_wb_2_4': ('char_wb', (2, 4)), 'char_wb_2_10': ('char_wb', (2, 10)), 'char_wb_3_5': ('char_wb', (3, 5)), 'char_wb_3_10': ('char_wb', (3, 10)), 'char_wb_4_8': ('char_wb', (4, 8)), 'char_wb_4_10': ('char_wb', (4, 10)), 'char_wb_5_10': ('char_wb', (5, 10)), 'word_1_3': ('word', (1, 3)), 'word_1_5': ('word', (1, 5)), 'word_2_5': ('word', (2, 5))}
MIN_DF_VALUES = [1, 2, 5, 10]
MAX_FEATURES = 100_000
MIN_CLUSTER_SIZE_VALUES = [2, 5, 10, 20]
MIN_SAMPLES_VALUES = [None, 2, 5, 10]
CLUSTER_SELECTION_METHOD = "eom"
HDBSCAN_N_JOBS = 1

OUTPUT_ROOT = PROJECT_ROOT / "reports/tfidf_hdbscan"
MODEL_ROOT = PROJECT_ROOT / "models/tfidf_hdbscan"


TSNE_MAX_POINTS = 5_000
TSNE_PERPLEXITY = 30
TSNE_MAX_ITER = 1_000
TSNE_RANDOM_STATE = 42
TSNE_3D_N_COMPONENTS = 3
TSNE_SVD_COMPONENTS = 50

METRIC_RANDOM_STATE = 42

PAIRWISE_WORKING_MEMORY_MIB = 64

MAX_DF = 1.0

ASSIGNMENT_RUN_ID = None

MODEL_RUN_ID = None

### Configura??o do ranking final

`MIN_CLUSTER_FOR_RANKING = 10` define o minimo do ranking. O intervalo ate `MAX_CLUSTERS_FOR_RANKING` inclui os dois extremos e nao altera os ajustes da grade. Em DBSCAN/HDBSCAN, a contagem exclui o grupo de ruido (-1).

In [3]:
# O limite filtra apenas o ranking e a sele??o final; n?o altera os ajustes do HDBSCAN.
MAX_CLUSTERS_FOR_RANKING = 1000
MIN_CLUSTER_FOR_RANKING = 10

# Os pesos definem a contribui??o relativa de silhouette e cobertura (1 - ru?do).
SILHOUETTE_WEIGHT = 0.75
NOISE_WEIGHT = 0.25

## 2. Fun??es da an?lise

A prepara??o remove descri??es vazias, mant?m uma linha por descri??o e valida que a frequ?ncia total n?o foi alterada. Cada configura??o ? executada sobre a mesma matriz TF-IDF da respectiva representa??o.

In [4]:
def prepare_items(frame):
    initial_frequency = frame[FREQUENCY].sum()
    prepared = frame[[DESCRIPTION_NORMALIZED, FREQUENCY]].copy()
    prepared[DESCRIPTION_NORMALIZED] = prepared[DESCRIPTION_NORMALIZED].astype("string").str.strip()
    prepared = prepared[prepared[DESCRIPTION_NORMALIZED].notna() & prepared[DESCRIPTION_NORMALIZED].ne("")]
    prepared = prepared[prepared[FREQUENCY] >= 1].copy()
    prepared = (
        prepared.groupby(DESCRIPTION_NORMALIZED, as_index=False, sort=False)[FREQUENCY]
        .sum()
    )
    if prepared[FREQUENCY].sum() != initial_frequency:
        raise ValueError("A prepara??o alterou a soma de frequ?ncia.")
    return prepared.sort_values(DESCRIPTION_NORMALIZED).reset_index(drop=True)

def summarize_clusters(items, labels):
    result = items.copy()
    result["cluster"] = labels
    result["ruido"] = result["cluster"].eq(-1)
    summary = (
        result.groupby("cluster", as_index=False)
        .agg(descricoes_unicas=(DESCRIPTION_NORMALIZED, "size"), frequencia_total=(FREQUENCY, "sum"))
        .sort_values("descricoes_unicas", ascending=False)
    )
    return result, summary

def score_configuration(matrix, labels, sample_size, random_state):
    """Avalia a mesma amostra de linhas, excluindo ruido somente apos amostrar."""
    labels = np.asarray(labels)
    noise_mask = labels == -1
    cluster_count = len(np.unique(labels[~noise_mask]))
    base_count = min(sample_size, len(labels))
    rng = np.random.default_rng(random_state)
    positions = np.sort(rng.choice(len(labels), size=base_count, replace=False))
    positions = positions[~noise_mask[positions]]
    sample_labels = labels[positions]
    sample_cluster_count = len(np.unique(sample_labels))
    score = np.nan
    actual_count = len(positions)
    if 2 <= sample_cluster_count < actual_count:
        with config_context(working_memory=PAIRWISE_WORKING_MEMORY_MIB):
            score = float(silhouette_score(matrix[positions], sample_labels, metric="cosine"))
    else:
        actual_count = 0
    return {
        "cluster_count_excluding_noise": cluster_count,
        "noise_count": int(noise_mask.sum()),
        "noise_fraction": float(noise_mask.mean()),
        "silhouette_base_sample_size": base_count,
        "silhouette_sample_size": actual_count,
        "silhouette_cosine_without_noise": score,
    }

def compute_tsne_projection(features, max_points, perplexity, max_iter, random_state, n_components=2):
    """Usa a mesma amostra, SVD e parametros t-SNE em todas as representacoes."""
    point_count = features.shape[0]
    sample_count = min(point_count, max_points)
    if sample_count < 3 or n_components not in (2, 3):
        raise ValueError("t-SNE exige pelo menos tres itens e n_components 2 ou 3.")
    rng = np.random.default_rng(random_state)
    indices = np.sort(rng.choice(point_count, size=sample_count, replace=False))
    sampled = features[indices]
    dimensions = min(TSNE_SVD_COMPONENTS, sampled.shape[1] - 1, sample_count - 1)
    if dimensions >= 1:
        reduced = TruncatedSVD(n_components=dimensions, random_state=random_state).fit_transform(sampled)
    else:
        reduced = sampled.toarray() if hasattr(sampled, "toarray") else np.asarray(sampled)
        dimensions = reduced.shape[1]
    coordinates = TSNE(
        n_components=n_components,
        perplexity=min(float(perplexity), (sample_count - 1) / 3),
        init="pca" if dimensions >= n_components else "random",
        learning_rate="auto", max_iter=max_iter, random_state=random_state,
        method="barnes_hut",
    ).fit_transform(reduced)
    return indices, coordinates, dimensions


def save_tsne_plot(coordinates, labels, run_id, output_path):
    """Salva um PNG t-SNE colorido pelos clusters, com o ru?do em cinza."""
    labels = np.asarray(labels)
    noise_mask = labels == -1
    cluster_ids = np.unique(labels[~noise_mask])
    if cluster_ids.size:
        palette = plt.get_cmap("tab20").colors
        cluster_cmap = ListedColormap([
            palette[index % len(palette)] for index in range(len(cluster_ids))
        ])
        cluster_codes = np.searchsorted(cluster_ids, labels[~noise_mask])
    else:
        cluster_cmap = None
        cluster_codes = np.empty(0, dtype=int)

    figure, axis = plt.subplots(figsize=(11, 8), constrained_layout=True)
    if noise_mask.any():
        axis.scatter(
            coordinates[noise_mask, 0], coordinates[noise_mask, 1],
            c="#b8b8b8", s=8, alpha=0.3, linewidths=0,
        )
    if cluster_ids.size:
        axis.scatter(
            coordinates[~noise_mask, 0], coordinates[~noise_mask, 1],
            c=cluster_codes, cmap=cluster_cmap, vmin=-0.5,
            vmax=len(cluster_ids) - 0.5, s=9, alpha=0.75, linewidths=0,
        )
    axis.set_title(
        f"t-SNE: {run_id}\n{len(cluster_ids)} clusters; "
        f"{int(noise_mask.sum()):,} descri??es como ru?do"
    )
    axis.set_xlabel("t-SNE 1")
    axis.set_ylabel("t-SNE 2")
    axis.text(
        0.01, 0.01,
        "Ru?do em cinza; as cores se repetem a cada 20 clusters.",
        transform=axis.transAxes, fontsize=8, color="#555555",
    )
    figure.savefig(output_path, dpi=160)
    plt.close(figure)


def save_tsne_3d_html(coordinates, labels, run_id, output_path):
    """Salva uma visualiza??o t-SNE 3D interativa e autocontida em HTML."""
    points = [
        {"x": float(x), "y": float(y), "z": float(z), "label": int(label)}
        for (x, y, z), label in zip(coordinates, labels)
    ]
    data_json = json.dumps(points, separators=(",", ":"))
    title = str(run_id).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    page = r"""<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>t-SNE 3D: __TITLE__</title>
<style>
html, body { margin: 0; height: 100%; background: #f7f8fa; color: #202124; font: 14px system-ui, sans-serif; }
main { display: flex; flex-direction: column; height: 100%; }
header { padding: 12px 18px; background: white; border-bottom: 1px solid #ddd; }
h1 { margin: 0 0 4px; font-size: 17px; }
p { margin: 0; color: #555; }
canvas { display: block; width: 100%; flex: 1; min-height: 300px; cursor: grab; }
canvas:active { cursor: grabbing; }
</style>
</head>
<body>
<main>
<header><h1>Proje??o t-SNE 3D: __TITLE__</h1><p>Arraste para girar; use a roda do mouse para aproximar. Ru?do em cinza.</p></header>
<canvas id="plot"></canvas>
</main>
<script>
const points = __POINTS__;
const canvas = document.getElementById("plot");
const ctx = canvas.getContext("2d");
let yaw = 0.65, pitch = -0.35, zoom = 1, dragging = false, lastX = 0, lastY = 0;
const colors = ["#3366cc", "#dc3912", "#ff9900", "#109618", "#990099", "#0099c6", "#dd4477", "#66aa00", "#b82e2e", "#316395", "#994499", "#22aa99", "#aaaa11", "#6633cc", "#e67300", "#8b0707", "#651067", "#329262", "#5574a6", "#3b3eac"];
const bounds = ["x", "y", "z"].map(key => {
  const values = points.map(point => point[key]);
  const low = Math.min(...values), high = Math.max(...values);
  return { low, span: Math.max(high - low, 1e-9) };
});
function resize() {
  const ratio = window.devicePixelRatio || 1;
  canvas.width = Math.max(1, Math.floor(canvas.clientWidth * ratio));
  canvas.height = Math.max(1, Math.floor(canvas.clientHeight * ratio));
  ctx.setTransform(ratio, 0, 0, ratio, 0, 0);
  draw();
}
function draw() {
  const width = canvas.clientWidth, height = canvas.clientHeight;
  ctx.clearRect(0, 0, width, height);
  const scale = Math.min(width, height) * 0.7 * zoom;
  const cy = Math.cos(yaw), sy = Math.sin(yaw), cp = Math.cos(pitch), sp = Math.sin(pitch);
  const projected = points.map(point => {
    const x = ((point.x - bounds[0].low) / bounds[0].span - 0.5) * 2;
    const y = ((point.y - bounds[1].low) / bounds[1].span - 0.5) * 2;
    const z = ((point.z - bounds[2].low) / bounds[2].span - 0.5) * 2;
    const rx = x * cy - z * sy, rz = x * sy + z * cy;
    const ry = y * cp - rz * sp, depth = y * sp + rz * cp;
    return { x: width / 2 + rx * scale / 2, y: height / 2 - ry * scale / 2, depth, label: point.label };
  }).sort((a, b) => a.depth - b.depth);
  for (const point of projected) {
    ctx.globalAlpha = point.label === -1 ? 0.24 : 0.78;
    ctx.fillStyle = point.label === -1 ? "#999999" : colors[Math.abs(point.label) % colors.length];
    ctx.beginPath();
    ctx.arc(point.x, point.y, point.label === -1 ? 2 : 3, 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.globalAlpha = 1;
}
canvas.addEventListener("pointerdown", event => { dragging = true; lastX = event.clientX; lastY = event.clientY; canvas.setPointerCapture(event.pointerId); });
canvas.addEventListener("pointerup", () => { dragging = false; });
canvas.addEventListener("pointermove", event => {
  if (!dragging) return;
  yaw += (event.clientX - lastX) * 0.008;
  pitch = Math.max(-1.5, Math.min(1.5, pitch + (event.clientY - lastY) * 0.008));
  lastX = event.clientX; lastY = event.clientY; draw();
});
canvas.addEventListener("wheel", event => { event.preventDefault(); zoom = Math.max(0.3, Math.min(5, zoom * (event.deltaY < 0 ? 1.1 : 0.9))); draw(); }, { passive: false });
window.addEventListener("resize", resize);
resize();
</script>
</body>
</html>"""
    page = page.replace("__TITLE__", title).replace("__POINTS__", data_json)
    output_path.write_text(page, encoding="utf-8")


def comparison_metadata(frame):
    """Registra controles comuns e a identidade exata da amostra de agrupamento."""
    sample = frame[[DESCRIPTION_NORMALIZED, FREQUENCY]].sort_values(DESCRIPTION_NORMALIZED).reset_index(drop=True)
    return {
        "dataset_name": DATASET_NAME,
        "training_description_count": len(sample),
        "training_sample_sha256": sha256(pd.util.hash_pandas_object(sample, index=False).values.tobytes()).hexdigest(),
        "max_descriptions": MAX_DESCRIPTIONS, "sample_seed": 42,
        "frequency_weighted": False,
        "silhouette_metric": "cosine", "silhouette_sample_size": SILHOUETTE_SAMPLE_SIZE,
        "metric_random_state": METRIC_RANDOM_STATE,
        "metric_sampling": "fixed rows, then exclude algorithmic noise",
        "min_cluster_for_ranking": MIN_CLUSTER_FOR_RANKING,
        "max_clusters_for_ranking": MAX_CLUSTERS_FOR_RANKING,
        "silhouette_weight": SILHOUETTE_WEIGHT, "noise_weight": NOISE_WEIGHT,
        "tsne": {
            "max_points": TSNE_MAX_POINTS, "perplexity": TSNE_PERPLEXITY,
            "max_iter": TSNE_MAX_ITER, "random_state": TSNE_RANDOM_STATE,
            "reduction": "TruncatedSVD", "svd_components": TSNE_SVD_COMPONENTS,
            "dimensions": [2, 3], "init": "pca", "learning_rate": "auto",
            "method": "barnes_hut",
        },
    }

## 3. Carregar e preparar dados

Origem: Parquet produzido pelos notebooks de prepara??o de dados do projeto, com descri??es de supermercado, NCMs e duplicatas agregadas por descri??o. A amostragem ? feita uma vez por semente e reutilizada entre os analyzers daquela semente.

In [5]:
raw_items = pd.read_parquet(DATASET_PATH)
required_columns = {DESCRIPTION_NORMALIZED, FREQUENCY}
missing_columns = required_columns - set(raw_items.columns)
if missing_columns:
    raise ValueError(f"Colunas ausentes no dataset: {sorted(missing_columns)}")
base_items = prepare_items(raw_items)
logger.info("Descricoes disponiveis apos preparacao: %d", len(base_items))

2026-10-25 01:11:04,111 INFO Descricoes disponiveis apos preparacao: 146999

## 4. Vetorizar, ajustar HDBSCAN e comparar par?metros

Cada combina??o de semente e analyzer gera uma matriz TF-IDF pr?pria. `metric="cosine"` trabalha diretamente com a matriz esparsa. O ru?do (`cluster = -1`) ? exclu?do da silhouette e contabilizado separadamente; configura??es com menos de dois clusters v?lidos ficam sem silhouette. Para controlar o custo, a silhouette usa no m?ximo `SILHOUETTE_SAMPLE_SIZE` itens n?o classificados como ru?do.

Para visualiza??o, uma amostra fixa de at? `TSNE_MAX_POINTS` descri??es ? reduzida com TruncatedSVD e projetada uma vez por representa??o. As coordenadas s?o reutilizadas para salvar um PNG por configura??o.

A proje??o t-SNE 3D ? calculada separadamente e cada configura??o tamb?m ? salva como HTML interativo autocontido em `tsne_3d_html/`.

In [6]:
records = []
labels_by_run = {}
items_by_run = {}
matrices_by_representation = {}
items_by_seed = {}

for sample_seed in SAMPLE_SEEDS:
    sampled_items = base_items
    if MAX_DESCRIPTIONS is not None and len(base_items) > MAX_DESCRIPTIONS:
        sampled_items = base_items.sample(n=MAX_DESCRIPTIONS, random_state=sample_seed)
    sampled_items = sampled_items.sort_values(DESCRIPTION_NORMALIZED).reset_index(drop=True)
    items_by_seed[sample_seed] = sampled_items

    for representation, (analyzer, ngram_range) in ANALYZER_CONFIGS.items():
        for min_df in MIN_DF_VALUES:
            logger.info(
                "Vetorizando analyzer=%s, min_df=%d, seed=%d, descricoes=%d",
                analyzer, min_df, sample_seed, len(sampled_items),
            )
            vectorizer = TfidfVectorizer(
                analyzer=analyzer, ngram_range=ngram_range, min_df=min_df,
                max_features=MAX_FEATURES, max_df=MAX_DF, sublinear_tf=True, norm="l2", dtype=np.float64,
            )
            matrix = vectorizer.fit_transform(sampled_items[DESCRIPTION_NORMALIZED].astype(str))
            zero_vector_count = int((matrix.getnnz(axis=1) == 0).sum())
            matrices_by_representation[(sample_seed, representation, min_df)] = matrix
            logger.info(
                "Analyzer=%s min_df=%d seed=%d: %d termos, %d vetores zerados",
                analyzer, min_df, sample_seed, matrix.shape[1], zero_vector_count,
            )

            for min_cluster_size in MIN_CLUSTER_SIZE_VALUES:
                for min_samples in MIN_SAMPLES_VALUES:
                    min_samples_label = "default" if min_samples is None else str(min_samples)
                    run_id = (
                        f"seed{sample_seed}_{representation}_min_df{min_df}_min_cluster_size{min_cluster_size}"
                        f"_min_samples{min_samples_label}_{CLUSTER_SELECTION_METHOD}"
                    )
                    logger.info("Ajustando HDBSCAN %s", run_id)
                    model = HDBSCAN(
                        min_cluster_size=min_cluster_size,
                        min_samples=min_samples,
                        metric="cosine",
                        algorithm="brute",
                        cluster_selection_method=CLUSTER_SELECTION_METHOD,
                        n_jobs=HDBSCAN_N_JOBS,
                        copy=True,
                    )
                    labels = model.fit_predict(matrix)
                    metrics = score_configuration(
                        matrix, labels, SILHOUETTE_SAMPLE_SIZE,
                        METRIC_RANDOM_STATE,
                    )
                    records.append({
                        "run_id": run_id, "sample_seed": sample_seed,
                        "representation": representation, "analyzer": analyzer,
                        "ngram_range": str(ngram_range), "min_df": min_df,
                        "feature_count": matrix.shape[1], "zero_vector_count": zero_vector_count,
                        "min_cluster_size": min_cluster_size,
                        "min_samples": min_samples,
                        "cluster_selection_method": CLUSTER_SELECTION_METHOD,
                        "frequency_weighted": False, **metrics,
                    })
                    labels_by_run[run_id] = labels
                    items_by_run[run_id] = sampled_items

results = pd.DataFrame(records)

2026-10-25 01:11:04,150 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-25 01:11:04,894 INFO Analyzer=char_wb min_df=1 seed=42: 36881 termos, 0 vetores zerados

2026-10-25 01:11:04,896 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:11:17,850 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size2_min_samples2_eom

2026-10-25 01:11:32,167 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size2_min_samples5_eom

2026-10-25 01:11:43,168 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size2_min_samples10_eom

2026-10-25 01:11:53,270 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:12:02,880 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size5_min_samples2_eom

2026-10-25 01:12:12,841 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size5_min_samples5_eom

2026-10-25 01:12:21,706 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size5_min_samples10_eom

2026-10-25 01:12:35,046 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:12:48,184 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size10_min_samples2_eom

2026-10-25 01:12:58,045 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size10_min_samples5_eom

2026-10-25 01:13:13,950 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size10_min_samples10_eom

2026-10-25 01:13:29,517 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:13:39,082 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size20_min_samples2_eom

2026-10-25 01:13:49,817 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size20_min_samples5_eom

2026-10-25 01:13:59,806 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_min_cluster_size20_min_samples10_eom

2026-10-25 01:14:09,217 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-25 01:14:09,976 INFO Analyzer=char_wb min_df=2 seed=42: 23288 termos, 0 vetores zerados

2026-10-25 01:14:09,977 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:14:22,418 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size2_min_samples2_eom

2026-10-25 01:14:33,567 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size2_min_samples5_eom

2026-10-25 01:14:42,780 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size2_min_samples10_eom

2026-10-25 01:14:51,485 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:15:00,477 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size5_min_samples2_eom

2026-10-25 01:15:10,551 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size5_min_samples5_eom

2026-10-25 01:15:19,451 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size5_min_samples10_eom

2026-10-25 01:15:32,942 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:15:47,440 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size10_min_samples2_eom

2026-10-25 01:15:58,497 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size10_min_samples5_eom

2026-10-25 01:16:14,518 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size10_min_samples10_eom

2026-10-25 01:16:29,014 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:16:37,653 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size20_min_samples2_eom

2026-10-25 01:16:47,551 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size20_min_samples5_eom

2026-10-25 01:16:56,429 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_min_cluster_size20_min_samples10_eom

2026-10-25 01:17:05,151 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-25 01:17:05,768 INFO Analyzer=char_wb min_df=5 seed=42: 14247 termos, 0 vetores zerados

2026-10-25 01:17:05,768 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:17:16,838 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size2_min_samples2_eom

2026-10-25 01:17:28,142 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size2_min_samples5_eom

2026-10-25 01:17:37,472 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size2_min_samples10_eom

2026-10-25 01:17:46,249 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:17:55,379 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size5_min_samples2_eom

2026-10-25 01:18:06,496 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size5_min_samples5_eom

2026-10-25 01:18:16,461 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size5_min_samples10_eom

2026-10-25 01:18:32,346 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:18:47,145 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size10_min_samples2_eom

2026-10-25 01:18:57,304 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size10_min_samples5_eom

2026-10-25 01:19:12,244 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size10_min_samples10_eom

2026-10-25 01:19:26,085 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:19:34,799 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size20_min_samples2_eom

2026-10-25 01:19:44,385 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size20_min_samples5_eom

2026-10-25 01:19:53,324 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_min_cluster_size20_min_samples10_eom

2026-10-25 01:20:02,002 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-25 01:20:02,642 INFO Analyzer=char_wb min_df=10 seed=42: 10098 termos, 0 vetores zerados

2026-10-25 01:20:02,643 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:20:14,438 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size2_min_samples2_eom

2026-10-25 01:20:26,576 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size2_min_samples5_eom

2026-10-25 01:20:36,617 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size2_min_samples10_eom

2026-10-25 01:20:46,172 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:20:55,908 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size5_min_samples2_eom

2026-10-25 01:21:06,814 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size5_min_samples5_eom

2026-10-25 01:21:16,021 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size5_min_samples10_eom

2026-10-25 01:21:30,250 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:21:44,552 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size10_min_samples2_eom

2026-10-25 01:21:54,581 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size10_min_samples5_eom

2026-10-25 01:22:09,805 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size10_min_samples10_eom

2026-10-25 01:22:24,783 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:22:34,061 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size20_min_samples2_eom

2026-10-25 01:22:45,182 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size20_min_samples5_eom

2026-10-25 01:22:55,006 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_min_cluster_size20_min_samples10_eom

2026-10-25 01:23:04,560 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-25 01:23:05,902 INFO Analyzer=char_wb min_df=1 seed=42: 100000 termos, 0 vetores zerados

2026-10-25 01:23:05,902 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:23:18,095 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size2_min_samples2_eom

2026-10-25 01:23:30,198 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size2_min_samples5_eom

2026-10-25 01:23:39,444 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size2_min_samples10_eom

2026-10-25 01:23:48,411 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:23:57,786 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size5_min_samples2_eom

2026-10-25 01:24:08,285 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size5_min_samples5_eom

2026-10-25 01:24:17,602 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size5_min_samples10_eom

2026-10-25 01:24:26,686 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:24:35,652 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size10_min_samples2_eom

2026-10-25 01:24:46,478 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size10_min_samples5_eom

2026-10-25 01:24:56,737 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size10_min_samples10_eom

2026-10-25 01:25:06,452 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:25:16,058 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size20_min_samples2_eom

2026-10-25 01:25:27,213 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size20_min_samples5_eom

2026-10-25 01:25:36,864 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_min_cluster_size20_min_samples10_eom

2026-10-25 01:25:45,749 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-25 01:25:47,119 INFO Analyzer=char_wb min_df=2 seed=42: 90460 termos, 0 vetores zerados

2026-10-25 01:25:47,119 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:25:59,213 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size2_min_samples2_eom

2026-10-25 01:26:11,176 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size2_min_samples5_eom

2026-10-25 01:26:20,736 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size2_min_samples10_eom

2026-10-25 01:26:29,710 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:26:39,144 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size5_min_samples2_eom

2026-10-25 01:26:49,761 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size5_min_samples5_eom

2026-10-25 01:26:59,587 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size5_min_samples10_eom

2026-10-25 01:27:09,404 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:27:19,553 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size10_min_samples2_eom

2026-10-25 01:27:30,985 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size10_min_samples5_eom

2026-10-25 01:27:41,194 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size10_min_samples10_eom

2026-10-25 01:27:51,273 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:28:00,152 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size20_min_samples2_eom

2026-10-25 01:28:09,753 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size20_min_samples5_eom

2026-10-25 01:28:18,922 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_min_cluster_size20_min_samples10_eom

2026-10-25 01:28:27,745 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-25 01:28:28,992 INFO Analyzer=char_wb min_df=5 seed=42: 45657 termos, 0 vetores zerados

2026-10-25 01:28:28,992 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:28:41,025 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size2_min_samples2_eom

2026-10-25 01:28:53,058 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size2_min_samples5_eom

2026-10-25 01:29:02,753 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size2_min_samples10_eom

2026-10-25 01:29:11,886 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:29:21,419 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size5_min_samples2_eom

2026-10-25 01:29:32,243 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size5_min_samples5_eom

2026-10-25 01:29:41,739 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size5_min_samples10_eom

2026-10-25 01:29:51,686 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:30:01,729 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size10_min_samples2_eom

2026-10-25 01:30:13,289 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size10_min_samples5_eom

2026-10-25 01:30:24,012 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size10_min_samples10_eom

2026-10-25 01:30:34,773 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:30:45,204 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size20_min_samples2_eom

2026-10-25 01:30:55,929 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size20_min_samples5_eom

2026-10-25 01:31:05,653 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_min_cluster_size20_min_samples10_eom

2026-10-25 01:31:14,987 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-25 01:31:16,639 INFO Analyzer=char_wb min_df=10 seed=42: 28020 termos, 0 vetores zerados

2026-10-25 01:31:16,640 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:31:27,934 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size2_min_samples2_eom

2026-10-25 01:31:39,153 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size2_min_samples5_eom

2026-10-25 01:31:48,920 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size2_min_samples10_eom

2026-10-25 01:31:58,561 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:32:09,177 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size5_min_samples2_eom

2026-10-25 01:32:20,997 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size5_min_samples5_eom

2026-10-25 01:32:31,747 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size5_min_samples10_eom

2026-10-25 01:32:42,137 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:32:52,153 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size10_min_samples2_eom

2026-10-25 01:33:04,245 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size10_min_samples5_eom

2026-10-25 01:33:15,121 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size10_min_samples10_eom

2026-10-25 01:33:24,653 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:33:33,733 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size20_min_samples2_eom

2026-10-25 01:33:43,409 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size20_min_samples5_eom

2026-10-25 01:33:52,352 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_min_cluster_size20_min_samples10_eom

2026-10-25 01:34:01,638 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-25 01:34:02,341 INFO Analyzer=char_wb min_df=1 seed=42: 73193 termos, 0 vetores zerados

2026-10-25 01:34:02,342 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:34:12,054 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size2_min_samples2_eom

2026-10-25 01:34:21,936 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size2_min_samples5_eom

2026-10-25 01:34:30,366 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size2_min_samples10_eom

2026-10-25 01:34:38,486 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:34:46,897 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size5_min_samples2_eom

2026-10-25 01:34:55,982 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size5_min_samples5_eom

2026-10-25 01:35:04,354 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size5_min_samples10_eom

2026-10-25 01:35:15,346 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:35:25,782 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size10_min_samples2_eom

2026-10-25 01:35:34,326 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size10_min_samples5_eom

2026-10-25 01:35:41,958 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size10_min_samples10_eom

2026-10-25 01:35:52,287 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:35:59,620 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size20_min_samples2_eom

2026-10-25 01:36:07,787 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size20_min_samples5_eom

2026-10-25 01:36:15,442 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_min_cluster_size20_min_samples10_eom

2026-10-25 01:36:22,933 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-25 01:36:23,558 INFO Analyzer=char_wb min_df=2 seed=42: 41044 termos, 0 vetores zerados

2026-10-25 01:36:23,558 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:36:33,216 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size2_min_samples2_eom

2026-10-25 01:36:43,192 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size2_min_samples5_eom

2026-10-25 01:36:51,754 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size2_min_samples10_eom

2026-10-25 01:36:59,930 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:37:08,316 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size5_min_samples2_eom

2026-10-25 01:37:18,104 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size5_min_samples5_eom

2026-10-25 01:37:26,554 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size5_min_samples10_eom

2026-10-25 01:37:37,606 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:37:48,359 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size10_min_samples2_eom

2026-10-25 01:37:56,721 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size10_min_samples5_eom

2026-10-25 01:38:04,546 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size10_min_samples10_eom

2026-10-25 01:38:15,154 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:38:22,418 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size20_min_samples2_eom

2026-10-25 01:38:30,644 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size20_min_samples5_eom

2026-10-25 01:38:38,355 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_min_cluster_size20_min_samples10_eom

2026-10-25 01:38:45,865 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-25 01:38:46,444 INFO Analyzer=char_wb min_df=5 seed=42: 22987 termos, 0 vetores zerados

2026-10-25 01:38:46,444 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:38:56,497 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size2_min_samples2_eom

2026-10-25 01:39:06,962 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size2_min_samples5_eom

2026-10-25 01:39:15,780 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size2_min_samples10_eom

2026-10-25 01:39:23,990 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:39:32,446 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size5_min_samples2_eom

2026-10-25 01:39:41,247 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size5_min_samples5_eom

2026-10-25 01:39:49,209 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size5_min_samples10_eom

2026-10-25 01:39:56,488 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:40:07,510 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size10_min_samples2_eom

2026-10-25 01:40:15,888 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size10_min_samples5_eom

2026-10-25 01:40:23,714 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size10_min_samples10_eom

2026-10-25 01:40:34,921 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:40:43,336 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size20_min_samples2_eom

2026-10-25 01:40:52,421 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size20_min_samples5_eom

2026-10-25 01:41:01,049 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_min_cluster_size20_min_samples10_eom

2026-10-25 01:41:09,110 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-25 01:41:09,771 INFO Analyzer=char_wb min_df=10 seed=42: 15191 termos, 0 vetores zerados

2026-10-25 01:41:09,775 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:41:20,163 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size2_min_samples2_eom

2026-10-25 01:41:30,088 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size2_min_samples5_eom

2026-10-25 01:41:38,206 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size2_min_samples10_eom

2026-10-25 01:41:45,855 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:41:53,731 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size5_min_samples2_eom

2026-10-25 01:42:02,488 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size5_min_samples5_eom

2026-10-25 01:42:10,513 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size5_min_samples10_eom

2026-10-25 01:42:18,098 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:42:30,221 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size10_min_samples2_eom

2026-10-25 01:42:38,912 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size10_min_samples5_eom

2026-10-25 01:42:51,725 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size10_min_samples10_eom

2026-10-25 01:43:04,820 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:43:13,243 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size20_min_samples2_eom

2026-10-25 01:43:22,308 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size20_min_samples5_eom

2026-10-25 01:43:30,719 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_min_cluster_size20_min_samples10_eom

2026-10-25 01:43:38,673 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-25 01:43:39,749 INFO Analyzer=char_wb min_df=1 seed=42: 100000 termos, 0 vetores zerados

2026-10-25 01:43:39,750 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:43:49,988 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size2_min_samples2_eom

2026-10-25 01:44:00,327 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size2_min_samples5_eom

2026-10-25 01:44:08,245 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size2_min_samples10_eom

2026-10-25 01:44:15,917 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:44:23,983 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size5_min_samples2_eom

2026-10-25 01:44:32,855 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size5_min_samples5_eom

2026-10-25 01:44:40,917 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size5_min_samples10_eom

2026-10-25 01:44:48,614 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:44:56,311 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size10_min_samples2_eom

2026-10-25 01:45:04,856 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size10_min_samples5_eom

2026-10-25 01:45:13,457 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size10_min_samples10_eom

2026-10-25 01:45:21,638 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:45:29,855 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size20_min_samples2_eom

2026-10-25 01:45:38,808 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size20_min_samples5_eom

2026-10-25 01:45:47,789 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_min_cluster_size20_min_samples10_eom

2026-10-25 01:45:55,713 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-25 01:45:56,889 INFO Analyzer=char_wb min_df=2 seed=42: 89379 termos, 0 vetores zerados

2026-10-25 01:45:56,889 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:46:07,206 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size2_min_samples2_eom

2026-10-25 01:46:17,385 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size2_min_samples5_eom

2026-10-25 01:46:25,489 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size2_min_samples10_eom

2026-10-25 01:46:33,155 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:46:41,284 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size5_min_samples2_eom

2026-10-25 01:46:49,754 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size5_min_samples5_eom

2026-10-25 01:46:57,789 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size5_min_samples10_eom

2026-10-25 01:47:05,465 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:47:13,158 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size10_min_samples2_eom

2026-10-25 01:47:22,145 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size10_min_samples5_eom

2026-10-25 01:47:31,215 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size10_min_samples10_eom

2026-10-25 01:47:39,352 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:47:47,359 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size20_min_samples2_eom

2026-10-25 01:47:56,177 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size20_min_samples5_eom

2026-10-25 01:48:04,614 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_min_cluster_size20_min_samples10_eom

2026-10-25 01:48:12,821 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-25 01:48:14,005 INFO Analyzer=char_wb min_df=5 seed=42: 44780 termos, 0 vetores zerados

2026-10-25 01:48:14,005 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:48:24,855 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size2_min_samples2_eom

2026-10-25 01:48:35,113 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size2_min_samples5_eom

2026-10-25 01:48:43,456 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size2_min_samples10_eom

2026-10-25 01:48:51,320 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:48:59,582 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size5_min_samples2_eom

2026-10-25 01:49:08,650 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size5_min_samples5_eom

2026-10-25 01:49:16,759 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size5_min_samples10_eom

2026-10-25 01:49:24,718 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:49:33,114 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size10_min_samples2_eom

2026-10-25 01:49:42,879 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size10_min_samples5_eom

2026-10-25 01:49:51,736 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size10_min_samples10_eom

2026-10-25 01:50:00,227 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:50:08,529 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size20_min_samples2_eom

2026-10-25 01:50:17,689 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size20_min_samples5_eom

2026-10-25 01:50:26,294 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_min_cluster_size20_min_samples10_eom

2026-10-25 01:50:34,468 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-25 01:50:35,756 INFO Analyzer=char_wb min_df=10 seed=42: 27271 termos, 0 vetores zerados

2026-10-25 01:50:35,756 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:50:47,133 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size2_min_samples2_eom

2026-10-25 01:50:58,085 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size2_min_samples5_eom

2026-10-25 01:51:06,422 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size2_min_samples10_eom

2026-10-25 01:51:14,310 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:51:22,311 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size5_min_samples2_eom

2026-10-25 01:51:31,109 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size5_min_samples5_eom

2026-10-25 01:51:39,044 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size5_min_samples10_eom

2026-10-25 01:51:46,956 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:51:54,823 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size10_min_samples2_eom

2026-10-25 01:52:03,900 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size10_min_samples5_eom

2026-10-25 01:52:12,756 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size10_min_samples10_eom

2026-10-25 01:52:20,985 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:52:28,852 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size20_min_samples2_eom

2026-10-25 01:52:38,323 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size20_min_samples5_eom

2026-10-25 01:52:46,923 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_min_cluster_size20_min_samples10_eom

2026-10-25 01:52:54,836 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-25 01:52:55,918 INFO Analyzer=char_wb min_df=1 seed=42: 100000 termos, 0 vetores zerados

2026-10-25 01:52:55,920 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:53:05,923 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size2_min_samples2_eom

2026-10-25 01:53:15,789 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size2_min_samples5_eom

2026-10-25 01:53:23,846 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size2_min_samples10_eom

2026-10-25 01:53:31,549 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:53:38,503 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size5_min_samples2_eom

2026-10-25 01:53:46,523 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size5_min_samples5_eom

2026-10-25 01:53:53,752 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size5_min_samples10_eom

2026-10-25 01:54:00,816 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:54:08,242 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size10_min_samples2_eom

2026-10-25 01:54:16,939 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size10_min_samples5_eom

2026-10-25 01:54:25,483 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size10_min_samples10_eom

2026-10-25 01:54:33,322 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:54:41,184 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size20_min_samples2_eom

2026-10-25 01:54:49,523 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size20_min_samples5_eom

2026-10-25 01:54:57,123 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_min_cluster_size20_min_samples10_eom

2026-10-25 01:55:04,415 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-25 01:55:05,320 INFO Analyzer=char_wb min_df=2 seed=42: 73051 termos, 0 vetores zerados

2026-10-25 01:55:05,320 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:55:15,283 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size2_min_samples2_eom

2026-10-25 01:55:24,380 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size2_min_samples5_eom

2026-10-25 01:55:31,611 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size2_min_samples10_eom

2026-10-25 01:55:38,458 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:55:45,923 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size5_min_samples2_eom

2026-10-25 01:55:54,277 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size5_min_samples5_eom

2026-10-25 01:56:01,507 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size5_min_samples10_eom

2026-10-25 01:56:08,774 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:56:16,309 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size10_min_samples2_eom

2026-10-25 01:56:25,112 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size10_min_samples5_eom

2026-10-25 01:56:33,115 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size10_min_samples10_eom

2026-10-25 01:56:40,985 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:56:48,423 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size20_min_samples2_eom

2026-10-25 01:56:56,984 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size20_min_samples5_eom

2026-10-25 01:57:04,799 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_min_cluster_size20_min_samples10_eom

2026-10-25 01:57:12,490 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-25 01:57:13,317 INFO Analyzer=char_wb min_df=5 seed=42: 36185 termos, 3 vetores zerados

2026-10-25 01:57:13,318 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:57:23,239 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size2_min_samples2_eom

2026-10-25 01:57:32,952 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size2_min_samples5_eom

2026-10-25 01:57:41,006 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size2_min_samples10_eom

2026-10-25 01:57:48,324 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size5_min_samplesdefault_eom

2026-10-25 01:57:56,278 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size5_min_samples2_eom

2026-10-25 01:58:05,045 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size5_min_samples5_eom

2026-10-25 01:58:12,949 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size5_min_samples10_eom

2026-10-25 01:58:25,820 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size10_min_samplesdefault_eom

2026-10-25 01:58:33,246 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size10_min_samples2_eom

2026-10-25 01:58:41,330 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size10_min_samples5_eom

2026-10-25 01:58:49,313 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size10_min_samples10_eom

2026-10-25 01:58:57,407 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size20_min_samplesdefault_eom

2026-10-25 01:59:04,971 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size20_min_samples2_eom

2026-10-25 01:59:13,679 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size20_min_samples5_eom

2026-10-25 01:59:21,740 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_min_cluster_size20_min_samples10_eom

2026-10-25 01:59:29,874 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-25 01:59:30,779 INFO Analyzer=char_wb min_df=10 seed=42: 21744 termos, 6 vetores zerados

2026-10-25 01:59:30,780 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size2_min_samplesdefault_eom

2026-10-25 01:59:40,691 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size2_min_samples2_eom

2026-10-25 01:59:50,268 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size2_min_samples5_eom

2026-10-25 01:59:58,292 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size2_min_samples10_eom

2026-10-25 02:00:05,648 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:00:13,607 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size5_min_samples2_eom

2026-10-25 02:00:22,390 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size5_min_samples5_eom

2026-10-25 02:00:30,390 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size5_min_samples10_eom

2026-10-25 02:00:37,910 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:00:45,364 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size10_min_samples2_eom

2026-10-25 02:00:54,107 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size10_min_samples5_eom

2026-10-25 02:01:02,031 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size10_min_samples10_eom

2026-10-25 02:01:09,660 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:01:16,666 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size20_min_samples2_eom

2026-10-25 02:01:25,608 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size20_min_samples5_eom

2026-10-25 02:01:33,791 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_min_cluster_size20_min_samples10_eom

2026-10-25 02:01:41,874 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-25 02:01:42,822 INFO Analyzer=char_wb min_df=1 seed=42: 100000 termos, 0 vetores zerados

2026-10-25 02:01:42,824 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:01:53,295 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size2_min_samples2_eom

2026-10-25 02:02:04,258 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size2_min_samples5_eom

2026-10-25 02:02:12,758 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size2_min_samples10_eom

2026-10-25 02:02:20,237 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:02:27,992 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size5_min_samples2_eom

2026-10-25 02:02:36,416 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size5_min_samples5_eom

2026-10-25 02:02:44,091 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size5_min_samples10_eom

2026-10-25 02:02:57,222 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:03:04,542 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size10_min_samples2_eom

2026-10-25 02:03:12,727 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size10_min_samples5_eom

2026-10-25 02:03:20,328 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size10_min_samples10_eom

2026-10-25 02:03:27,595 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:03:34,653 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size20_min_samples2_eom

2026-10-25 02:03:42,589 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size20_min_samples5_eom

2026-10-25 02:03:50,086 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_min_cluster_size20_min_samples10_eom

2026-10-25 02:03:57,317 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-25 02:03:58,165 INFO Analyzer=char_wb min_df=2 seed=42: 82710 termos, 0 vetores zerados

2026-10-25 02:03:58,165 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:04:07,860 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size2_min_samples2_eom

2026-10-25 02:04:17,651 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size2_min_samples5_eom

2026-10-25 02:04:25,536 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size2_min_samples10_eom

2026-10-25 02:04:32,920 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:04:40,928 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size5_min_samples2_eom

2026-10-25 02:04:50,202 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size5_min_samples5_eom

2026-10-25 02:04:58,725 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size5_min_samples10_eom

2026-10-25 02:05:12,494 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:05:20,191 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size10_min_samples2_eom

2026-10-25 02:05:29,131 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size10_min_samples5_eom

2026-10-25 02:05:36,992 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size10_min_samples10_eom

2026-10-25 02:05:44,392 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:05:51,425 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size20_min_samples2_eom

2026-10-25 02:05:59,260 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size20_min_samples5_eom

2026-10-25 02:06:06,319 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_min_cluster_size20_min_samples10_eom

2026-10-25 02:06:13,442 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-25 02:06:14,281 INFO Analyzer=char_wb min_df=5 seed=42: 40332 termos, 3 vetores zerados

2026-10-25 02:06:14,282 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:06:23,426 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size2_min_samples2_eom

2026-10-25 02:06:33,125 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size2_min_samples5_eom

2026-10-25 02:06:41,281 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size2_min_samples10_eom

2026-10-25 02:06:48,523 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:06:56,289 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size5_min_samples2_eom

2026-10-25 02:07:05,025 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size5_min_samples5_eom

2026-10-25 02:07:13,181 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size5_min_samples10_eom

2026-10-25 02:07:26,955 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:07:35,016 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size10_min_samples2_eom

2026-10-25 02:07:44,250 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size10_min_samples5_eom

2026-10-25 02:07:52,617 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size10_min_samples10_eom

2026-10-25 02:08:01,256 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:08:08,787 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size20_min_samples2_eom

2026-10-25 02:08:17,483 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size20_min_samples5_eom

2026-10-25 02:08:25,428 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_min_cluster_size20_min_samples10_eom

2026-10-25 02:08:32,867 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-25 02:08:33,675 INFO Analyzer=char_wb min_df=10 seed=42: 23938 termos, 6 vetores zerados

2026-10-25 02:08:33,692 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:08:43,292 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size2_min_samples2_eom

2026-10-25 02:08:52,946 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size2_min_samples5_eom

2026-10-25 02:09:01,120 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size2_min_samples10_eom

2026-10-25 02:09:08,820 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:09:16,911 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size5_min_samples2_eom

2026-10-25 02:09:25,792 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size5_min_samples5_eom

2026-10-25 02:09:33,752 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size5_min_samples10_eom

2026-10-25 02:09:41,495 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:09:49,075 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size10_min_samples2_eom

2026-10-25 02:09:57,728 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size10_min_samples5_eom

2026-10-25 02:10:05,713 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size10_min_samples10_eom

2026-10-25 02:10:13,644 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:10:21,325 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size20_min_samples2_eom

2026-10-25 02:10:30,305 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size20_min_samples5_eom

2026-10-25 02:10:38,725 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_min_cluster_size20_min_samples10_eom

2026-10-25 02:10:46,918 INFO Vetorizando analyzer=char_wb, min_df=1, seed=42, descricoes=20000

2026-10-25 02:10:47,620 INFO Analyzer=char_wb min_df=1 seed=42: 100000 termos, 1 vetores zerados

2026-10-25 02:10:47,621 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:10:57,792 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size2_min_samples2_eom

2026-10-25 02:11:07,781 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size2_min_samples5_eom

2026-10-25 02:11:15,585 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size2_min_samples10_eom

2026-10-25 02:11:23,096 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:11:30,655 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size5_min_samples2_eom

2026-10-25 02:11:38,656 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size5_min_samples5_eom

2026-10-25 02:11:45,709 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size5_min_samples10_eom

2026-10-25 02:11:57,808 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:12:10,260 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size10_min_samples2_eom

2026-10-25 02:12:19,075 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size10_min_samples5_eom

2026-10-25 02:12:27,212 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size10_min_samples10_eom

2026-10-25 02:12:40,592 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:12:53,676 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size20_min_samples2_eom

2026-10-25 02:13:01,376 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size20_min_samples5_eom

2026-10-25 02:13:09,146 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_min_cluster_size20_min_samples10_eom

2026-10-25 02:13:21,172 INFO Vetorizando analyzer=char_wb, min_df=2, seed=42, descricoes=20000

2026-10-25 02:13:21,828 INFO Analyzer=char_wb min_df=2 seed=42: 67664 termos, 9 vetores zerados

2026-10-25 02:13:21,828 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:13:31,072 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size2_min_samples2_eom

2026-10-25 02:13:40,395 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size2_min_samples5_eom

2026-10-25 02:13:48,026 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size2_min_samples10_eom

2026-10-25 02:13:55,310 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:14:03,493 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size5_min_samples2_eom

2026-10-25 02:14:12,781 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size5_min_samples5_eom

2026-10-25 02:14:21,185 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size5_min_samples10_eom

2026-10-25 02:14:34,438 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:14:42,260 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size10_min_samples2_eom

2026-10-25 02:14:50,975 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size10_min_samples5_eom

2026-10-25 02:14:58,344 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size10_min_samples10_eom

2026-10-25 02:15:05,380 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:15:17,193 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size20_min_samples2_eom

2026-10-25 02:15:24,725 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size20_min_samples5_eom

2026-10-25 02:15:31,785 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_min_cluster_size20_min_samples10_eom

2026-10-25 02:15:38,821 INFO Vetorizando analyzer=char_wb, min_df=5, seed=42, descricoes=20000

2026-10-25 02:15:39,522 INFO Analyzer=char_wb min_df=5 seed=42: 31705 termos, 22 vetores zerados

2026-10-25 02:15:39,523 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:15:49,061 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size2_min_samples2_eom

2026-10-25 02:15:59,180 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size2_min_samples5_eom

2026-10-25 02:16:08,012 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size2_min_samples10_eom

2026-10-25 02:16:16,393 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:16:24,731 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size5_min_samples2_eom

2026-10-25 02:16:34,290 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size5_min_samples5_eom

2026-10-25 02:16:42,705 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size5_min_samples10_eom

2026-10-25 02:16:50,480 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:16:58,523 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size10_min_samples2_eom

2026-10-25 02:17:06,842 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size10_min_samples5_eom

2026-10-25 02:17:14,618 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size10_min_samples10_eom

2026-10-25 02:17:22,061 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:17:34,253 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size20_min_samples2_eom

2026-10-25 02:17:42,392 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size20_min_samples5_eom

2026-10-25 02:17:50,127 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_min_cluster_size20_min_samples10_eom

2026-10-25 02:18:02,434 INFO Vetorizando analyzer=char_wb, min_df=10, seed=42, descricoes=20000

2026-10-25 02:18:03,029 INFO Analyzer=char_wb min_df=10 seed=42: 18111 termos, 47 vetores zerados

2026-10-25 02:18:03,029 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:18:12,493 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size2_min_samples2_eom

2026-10-25 02:18:21,880 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size2_min_samples5_eom

2026-10-25 02:18:30,041 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size2_min_samples10_eom

2026-10-25 02:18:37,860 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:18:46,211 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samples2_eom

2026-10-25 02:18:55,660 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samples5_eom

2026-10-25 02:19:04,315 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samples10_eom

2026-10-25 02:19:12,587 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:19:20,677 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size10_min_samples2_eom

2026-10-25 02:19:30,093 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size10_min_samples5_eom

2026-10-25 02:19:38,850 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size10_min_samples10_eom

2026-10-25 02:19:46,645 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:19:58,887 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size20_min_samples2_eom

2026-10-25 02:20:07,281 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size20_min_samples5_eom

2026-10-25 02:20:15,016 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_min_cluster_size20_min_samples10_eom

2026-10-25 02:20:27,313 INFO Vetorizando analyzer=word, min_df=1, seed=42, descricoes=20000

2026-10-25 02:20:27,626 INFO Analyzer=word min_df=1 seed=42: 100000 termos, 24 vetores zerados

2026-10-25 02:20:27,627 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:20:36,500 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size2_min_samples2_eom

2026-10-25 02:20:45,029 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size2_min_samples5_eom

2026-10-25 02:20:56,781 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size2_min_samples10_eom

2026-10-25 02:21:08,494 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:21:20,324 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size5_min_samples2_eom

2026-10-25 02:21:28,089 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size5_min_samples5_eom

2026-10-25 02:21:41,121 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size5_min_samples10_eom

2026-10-25 02:21:53,555 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:22:05,994 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size10_min_samples2_eom

2026-10-25 02:22:17,915 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size10_min_samples5_eom

2026-10-25 02:22:29,552 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size10_min_samples10_eom

2026-10-25 02:22:41,015 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:22:52,834 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size20_min_samples2_eom

2026-10-25 02:23:04,556 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size20_min_samples5_eom

2026-10-25 02:23:16,336 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_min_cluster_size20_min_samples10_eom

2026-10-25 02:23:28,124 INFO Vetorizando analyzer=word, min_df=2, seed=42, descricoes=20000

2026-10-25 02:23:28,430 INFO Analyzer=word min_df=2 seed=42: 23325 termos, 81 vetores zerados

2026-10-25 02:23:28,430 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:23:38,111 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size2_min_samples2_eom

2026-10-25 02:23:47,889 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size2_min_samples5_eom

2026-10-25 02:23:55,256 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size2_min_samples10_eom

2026-10-25 02:24:07,036 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:24:14,363 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size5_min_samples2_eom

2026-10-25 02:24:22,509 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size5_min_samples5_eom

2026-10-25 02:24:29,682 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size5_min_samples10_eom

2026-10-25 02:24:41,428 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:24:53,228 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size10_min_samples2_eom

2026-10-25 02:25:05,523 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size10_min_samples5_eom

2026-10-25 02:25:18,030 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size10_min_samples10_eom

2026-10-25 02:25:30,197 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:25:42,719 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size20_min_samples2_eom

2026-10-25 02:25:54,794 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size20_min_samples5_eom

2026-10-25 02:26:06,548 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_min_cluster_size20_min_samples10_eom

2026-10-25 02:26:18,219 INFO Vetorizando analyzer=word, min_df=5, seed=42, descricoes=20000

2026-10-25 02:26:18,528 INFO Analyzer=word min_df=5 seed=42: 5821 termos, 218 vetores zerados

2026-10-25 02:26:18,528 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:26:27,791 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size2_min_samples2_eom

2026-10-25 02:26:37,194 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size2_min_samples5_eom

2026-10-25 02:26:44,917 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size2_min_samples10_eom

2026-10-25 02:26:51,912 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:26:59,561 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size5_min_samples2_eom

2026-10-25 02:27:08,182 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size5_min_samples5_eom

2026-10-25 02:27:15,741 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size5_min_samples10_eom

2026-10-25 02:27:22,944 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:27:29,941 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size10_min_samples2_eom

2026-10-25 02:27:38,016 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size10_min_samples5_eom

2026-10-25 02:27:45,320 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size10_min_samples10_eom

2026-10-25 02:27:52,414 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:28:04,048 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size20_min_samples2_eom

2026-10-25 02:28:16,561 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size20_min_samples5_eom

2026-10-25 02:28:29,337 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_min_cluster_size20_min_samples10_eom

2026-10-25 02:28:41,628 INFO Vetorizando analyzer=word, min_df=10, seed=42, descricoes=20000

2026-10-25 02:28:41,968 INFO Analyzer=word min_df=10 seed=42: 2593 termos, 386 vetores zerados

2026-10-25 02:28:41,968 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:28:51,711 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size2_min_samples2_eom

2026-10-25 02:29:01,545 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size2_min_samples5_eom

2026-10-25 02:29:09,297 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size2_min_samples10_eom

2026-10-25 02:29:16,682 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:29:24,232 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size5_min_samples2_eom

2026-10-25 02:29:32,884 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size5_min_samples5_eom

2026-10-25 02:29:40,714 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size5_min_samples10_eom

2026-10-25 02:29:47,992 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:29:55,328 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size10_min_samples2_eom

2026-10-25 02:30:03,758 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size10_min_samples5_eom

2026-10-25 02:30:11,495 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size10_min_samples10_eom

2026-10-25 02:30:18,720 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:30:30,995 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size20_min_samples2_eom

2026-10-25 02:30:43,948 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size20_min_samples5_eom

2026-10-25 02:30:56,128 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_min_cluster_size20_min_samples10_eom

2026-10-25 02:31:08,520 INFO Vetorizando analyzer=word, min_df=1, seed=42, descricoes=20000

2026-10-25 02:31:09,026 INFO Analyzer=word min_df=1 seed=42: 100000 termos, 43 vetores zerados

2026-10-25 02:31:09,028 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:31:17,823 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size2_min_samples2_eom

2026-10-25 02:31:26,514 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size2_min_samples5_eom

2026-10-25 02:31:33,527 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size2_min_samples10_eom

2026-10-25 02:31:45,156 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:31:56,821 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size5_min_samples2_eom

2026-10-25 02:32:03,903 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size5_min_samples5_eom

2026-10-25 02:32:15,282 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size5_min_samples10_eom

2026-10-25 02:32:26,497 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:32:37,728 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size10_min_samples2_eom

2026-10-25 02:32:50,406 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size10_min_samples5_eom

2026-10-25 02:33:02,360 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size10_min_samples10_eom

2026-10-25 02:33:14,360 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:33:26,832 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size20_min_samples2_eom

2026-10-25 02:33:39,966 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size20_min_samples5_eom

2026-10-25 02:33:52,462 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_min_cluster_size20_min_samples10_eom

2026-10-25 02:34:04,229 INFO Vetorizando analyzer=word, min_df=2, seed=42, descricoes=20000

2026-10-25 02:34:04,764 INFO Analyzer=word min_df=2 seed=42: 27572 termos, 81 vetores zerados

2026-10-25 02:34:04,764 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:34:14,362 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size2_min_samples2_eom

2026-10-25 02:34:23,749 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size2_min_samples5_eom

2026-10-25 02:34:30,556 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size2_min_samples10_eom

2026-10-25 02:34:41,729 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:34:48,781 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size5_min_samples2_eom

2026-10-25 02:34:57,200 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size5_min_samples5_eom

2026-10-25 02:35:04,596 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size5_min_samples10_eom

2026-10-25 02:35:16,850 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:35:29,036 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size10_min_samples2_eom

2026-10-25 02:35:41,462 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size10_min_samples5_eom

2026-10-25 02:35:54,489 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size10_min_samples10_eom

2026-10-25 02:36:05,696 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:36:17,080 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size20_min_samples2_eom

2026-10-25 02:36:28,448 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size20_min_samples5_eom

2026-10-25 02:36:39,818 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_min_cluster_size20_min_samples10_eom

2026-10-25 02:36:51,396 INFO Vetorizando analyzer=word, min_df=5, seed=42, descricoes=20000

2026-10-25 02:36:52,062 INFO Analyzer=word min_df=5 seed=42: 6211 termos, 218 vetores zerados

2026-10-25 02:36:52,062 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:37:02,321 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size2_min_samples2_eom

2026-10-25 02:37:12,129 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size2_min_samples5_eom

2026-10-25 02:37:20,135 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size2_min_samples10_eom

2026-10-25 02:37:27,517 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:37:35,163 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size5_min_samples2_eom

2026-10-25 02:37:45,234 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size5_min_samples5_eom

2026-10-25 02:37:53,796 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size5_min_samples10_eom

2026-10-25 02:38:01,755 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:38:09,092 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size10_min_samples2_eom

2026-10-25 02:38:17,488 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size10_min_samples5_eom

2026-10-25 02:38:24,784 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size10_min_samples10_eom

2026-10-25 02:38:31,796 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:38:43,429 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size20_min_samples2_eom

2026-10-25 02:38:55,070 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size20_min_samples5_eom

2026-10-25 02:39:06,698 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_min_cluster_size20_min_samples10_eom

2026-10-25 02:39:18,394 INFO Vetorizando analyzer=word, min_df=10, seed=42, descricoes=20000

2026-10-25 02:39:18,863 INFO Analyzer=word min_df=10 seed=42: 2661 termos, 386 vetores zerados

2026-10-25 02:39:18,863 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:39:27,947 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size2_min_samples2_eom

2026-10-25 02:39:37,343 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size2_min_samples5_eom

2026-10-25 02:39:45,252 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size2_min_samples10_eom

2026-10-25 02:39:52,752 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:40:00,453 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size5_min_samples2_eom

2026-10-25 02:40:09,264 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size5_min_samples5_eom

2026-10-25 02:40:16,921 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size5_min_samples10_eom

2026-10-25 02:40:24,163 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:40:31,352 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size10_min_samples2_eom

2026-10-25 02:40:40,317 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size10_min_samples5_eom

2026-10-25 02:40:48,220 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size10_min_samples10_eom

2026-10-25 02:40:56,137 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:41:08,897 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size20_min_samples2_eom

2026-10-25 02:41:21,413 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size20_min_samples5_eom

2026-10-25 02:41:33,347 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_min_cluster_size20_min_samples10_eom

2026-10-25 02:41:45,117 INFO Vetorizando analyzer=word, min_df=1, seed=42, descricoes=20000

2026-10-25 02:41:45,514 INFO Analyzer=word min_df=1 seed=42: 100000 termos, 1046 vetores zerados

2026-10-25 02:41:45,514 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:41:54,724 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size2_min_samples2_eom

2026-10-25 02:42:04,233 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size2_min_samples5_eom

2026-10-25 02:42:12,863 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size2_min_samples10_eom

2026-10-25 02:42:21,378 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:42:29,584 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size5_min_samples2_eom

2026-10-25 02:42:38,372 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size5_min_samples5_eom

2026-10-25 02:42:46,557 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size5_min_samples10_eom

2026-10-25 02:42:54,897 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:43:03,097 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size10_min_samples2_eom

2026-10-25 02:43:11,864 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size10_min_samples5_eom

2026-10-25 02:43:20,415 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size10_min_samples10_eom

2026-10-25 02:43:29,049 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:43:40,546 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size20_min_samples2_eom

2026-10-25 02:43:51,883 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size20_min_samples5_eom

2026-10-25 02:44:00,887 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_min_cluster_size20_min_samples10_eom

2026-10-25 02:44:11,964 INFO Vetorizando analyzer=word, min_df=2, seed=42, descricoes=20000

2026-10-25 02:44:12,397 INFO Analyzer=word min_df=2 seed=42: 20692 termos, 3690 vetores zerados

2026-10-25 02:44:12,397 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:44:22,986 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size2_min_samples2_eom

2026-10-25 02:44:33,718 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size2_min_samples5_eom

2026-10-25 02:44:42,794 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size2_min_samples10_eom

2026-10-25 02:44:51,658 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:45:00,294 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size5_min_samples2_eom

2026-10-25 02:45:09,535 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size5_min_samples5_eom

2026-10-25 02:45:18,119 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size5_min_samples10_eom

2026-10-25 02:45:26,571 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:45:34,833 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size10_min_samples2_eom

2026-10-25 02:45:43,631 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size10_min_samples5_eom

2026-10-25 02:45:51,915 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size10_min_samples10_eom

2026-10-25 02:46:00,230 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:46:08,996 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size20_min_samples2_eom

2026-10-25 02:46:16,864 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size20_min_samples5_eom

2026-10-25 02:46:23,983 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_min_cluster_size20_min_samples10_eom

2026-10-25 02:46:32,297 INFO Vetorizando analyzer=word, min_df=5, seed=42, descricoes=20000

2026-10-25 02:46:32,723 INFO Analyzer=word min_df=5 seed=42: 3150 termos, 7981 vetores zerados

2026-10-25 02:46:32,724 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:46:43,031 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size2_min_samples2_eom

2026-10-25 02:46:53,164 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size2_min_samples5_eom

2026-10-25 02:47:04,295 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size2_min_samples10_eom

2026-10-25 02:47:14,549 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:47:24,996 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size5_min_samples2_eom

2026-10-25 02:47:35,847 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size5_min_samples5_eom

2026-10-25 02:47:46,988 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size5_min_samples10_eom

2026-10-25 02:47:56,347 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:48:04,845 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size10_min_samples2_eom

2026-10-25 02:48:13,938 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size10_min_samples5_eom

2026-10-25 02:48:23,081 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size10_min_samples10_eom

2026-10-25 02:48:32,081 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:48:41,178 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size20_min_samples2_eom

2026-10-25 02:48:50,213 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size20_min_samples5_eom

2026-10-25 02:48:59,139 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_min_cluster_size20_min_samples10_eom

2026-10-25 02:49:08,028 INFO Vetorizando analyzer=word, min_df=10, seed=42, descricoes=20000

2026-10-25 02:49:08,445 INFO Analyzer=word min_df=10 seed=42: 930 termos, 10796 vetores zerados

2026-10-25 02:49:08,445 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size2_min_samplesdefault_eom

2026-10-25 02:49:18,711 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size2_min_samples2_eom

2026-10-25 02:49:29,014 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size2_min_samples5_eom

2026-10-25 02:49:39,272 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size2_min_samples10_eom

2026-10-25 02:49:49,104 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size5_min_samplesdefault_eom

2026-10-25 02:50:00,047 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size5_min_samples2_eom

2026-10-25 02:50:10,774 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size5_min_samples5_eom

2026-10-25 02:50:21,421 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size5_min_samples10_eom

2026-10-25 02:50:31,641 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size10_min_samplesdefault_eom

2026-10-25 02:50:42,064 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size10_min_samples2_eom

2026-10-25 02:50:51,979 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size10_min_samples5_eom

2026-10-25 02:51:01,981 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size10_min_samples10_eom

2026-10-25 02:51:11,754 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size20_min_samplesdefault_eom

2026-10-25 02:51:18,209 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size20_min_samples2_eom

2026-10-25 02:51:25,136 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size20_min_samples5_eom

2026-10-25 02:51:31,972 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_min_cluster_size20_min_samples10_eom

### Calcular a metrica composta e ordenar os resultados

A silhouette e reescalada para 0 a 1 e combinada com a proporcao de descricoes classificadas (`1 - noise_fraction`). O score composto determina a ordem; silhouette e ruido servem apenas de desempate quando os scores forem iguais.

In [7]:
if not 1 <= MIN_CLUSTER_FOR_RANKING <= MAX_CLUSTERS_FOR_RANKING:
    raise ValueError(
        "Os limites devem atender a 1 <= MIN_CLUSTER_FOR_RANKING <= MAX_CLUSTERS_FOR_RANKING."
    )

if SILHOUETTE_WEIGHT < 0 or NOISE_WEIGHT < 0 or SILHOUETTE_WEIGHT + NOISE_WEIGHT <= 0:
    raise ValueError("Os pesos devem ser nao negativos e pelo menos um deles deve ser maior que zero.")

# Silhouette varia de -1 a 1; reescale para 0 a 1 para combinar com cobertura.
results["silhouette_quality"] = (results["silhouette_cosine_without_noise"] + 1) / 2
results["noise_quality"] = 1 - results["noise_fraction"]
weight_total = SILHOUETTE_WEIGHT + NOISE_WEIGHT
results["composite_score"] = (
    SILHOUETTE_WEIGHT * results["silhouette_quality"]
    + NOISE_WEIGHT * results["noise_quality"]
) / weight_total

# O score composto e o criterio principal; os outros criterios so desempataram scores iguais.
ranking = (
    results.loc[
        results["cluster_count_excluding_noise"].between(
            MIN_CLUSTER_FOR_RANKING, MAX_CLUSTERS_FOR_RANKING, inclusive="both",
        ) & results["silhouette_cosine_without_noise"].notna()
    ]
    .sort_values(
        ["composite_score", "silhouette_cosine_without_noise", "noise_fraction"],
        ascending=[False, False, True], na_position="last",
    )
    .reset_index(drop=True)
)
if ranking.empty:
    raise ValueError(
        f"Nenhum resultado atende ao intervalo de {MIN_CLUSTER_FOR_RANKING} a "
        f"{MAX_CLUSTERS_FOR_RANKING} clusters. Ajuste min_cluster_size/min_samples ou o limite."
    )
# Explicita a posicao de cada configuracao depois dos filtros e criterios acima.
ranking.insert(0, "rank", range(1, len(ranking) + 1))

In [8]:
display(ranking)

,rank,run_id,sample_seed,representation,analyzer,ngram_range,min_df,feature_count,zero_vector_count,min_cluster_size,...,frequency_weighted,cluster_count_excluding_noise,noise_count,noise_fraction,silhouette_base_sample_size,silhouette_sample_size,silhouette_cosine_without_noise,silhouette_quality,noise_quality,composite_score
0,1,seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samplesdefault_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,5,...,False,736,9817,0.49085,20000,10183,0.518910,0.759455,0.50915,0.696879
1,2,seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samples5_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,5,...,False,736,9817,0.49085,20000,10183,0.518910,0.759455,0.50915,0.696879
2,3,seed42_word_2_5_min_df10_min_cluster_size20_min_samplesdefault_eom,42,word_2_5,word,"(2, 5)",10,930,10796,20,...,False,101,15999,0.79995,20000,4001,0.712737,0.856369,0.20005,0.692289
3,4,seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samples10_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,5,...,False,381,12053,0.60265,20000,7947,0.565642,0.782821,0.39735,0.686453
4,5,seed42_char_wb_5_10_min_df10_min_cluster_size10_min_samples2_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,10,...,False,554,7848,0.39240,20000,12152,0.424243,0.712122,0.60760,0.685991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,405,seed42_char_wb_2_4_min_df2_min_cluster_size2_min_samples10_eom,42,char_wb_2_4,char_wb,"(2, 4)",2,23288,0,2,...,False,399,15816,0.79080,20000,4184,0.274880,0.637440,0.20920,0.530380
405,406,seed42_word_2_5_min_df1_min_cluster_size10_min_samples2_eom,42,word_2_5,word,"(2, 5)",1,100000,1046,10,...,False,538,9891,0.49455,20000,10109,0.076886,0.538443,0.50545,0.530195
406,407,seed42_word_2_5_min_df1_min_cluster_size10_min_samples5_eom,42,word_2_5,word,"(2, 5)",1,100000,1046,10,...,False,606,9597,0.47985,20000,10403,0.052305,0.526152,0.52015,0.524652
407,408,seed42_word_2_5_min_df2_min_cluster_size20_min_samples2_eom,42,word_2_5,word,"(2, 5)",2,20692,3690,20,...,False,125,11557,0.57785,20000,8443,0.090094,0.545047,0.42215,0.514323
408,409,seed42_word_2_5_min_df2_min_cluster_size20_min_samples5_eom,42,word_2_5,word,"(2, 5)",2,20692,3690,20,...,False,79,16508,0.82540,20000,3492,0.193761,0.596881,0.17460,0.491311

In [9]:
ranking.head(40)

,rank,run_id,sample_seed,representation,analyzer,ngram_range,min_df,feature_count,zero_vector_count,min_cluster_size,...,frequency_weighted,cluster_count_excluding_noise,noise_count,noise_fraction,silhouette_base_sample_size,silhouette_sample_size,silhouette_cosine_without_noise,silhouette_quality,noise_quality,composite_score
0,1,seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samplesdefault_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,5,...,False,736,9817,0.49085,20000,10183,0.518910,0.759455,0.50915,0.696879
1,2,seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samples5_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,5,...,False,736,9817,0.49085,20000,10183,0.518910,0.759455,0.50915,0.696879
2,3,seed42_word_2_5_min_df10_min_cluster_size20_min_samplesdefault_eom,42,word_2_5,word,"(2, 5)",10,930,10796,20,...,False,101,15999,0.79995,20000,4001,0.712737,0.856369,0.20005,0.692289
3,4,seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samples10_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,5,...,False,381,12053,0.60265,20000,7947,0.565642,0.782821,0.39735,0.686453
4,5,seed42_char_wb_5_10_min_df10_min_cluster_size10_min_samples2_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,10,...,False,554,7848,0.39240,20000,12152,0.424243,0.712122,0.60760,0.685991
5,6,seed42_char_wb_5_10_min_df5_min_cluster_size5_min_samplesdefault_eom,42,char_wb_5_10,char_wb,"(5, 10)",5,31705,22,5,...,False,764,10613,0.53065,20000,9387,0.507340,0.753670,0.46935,0.682590
6,7,seed42_char_wb_5_10_min_df5_min_cluster_size5_min_samples5_eom,42,char_wb_5_10,char_wb,"(5, 10)",5,31705,22,5,...,False,764,10613,0.53065,20000,9387,0.507340,0.753670,0.46935,0.682590
7,8,seed42_char_wb_5_10_min_df10_min_cluster_size10_min_samples5_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,10,...,False,413,10137,0.50685,20000,9863,0.485829,0.742915,0.49315,0.680473
8,9,seed42_char_wb_5_10_min_df10_min_cluster_size10_min_samplesdefault_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,10,...,False,290,12167,0.60835,20000,7833,0.551087,0.775544,0.39165,0.679570
9,10,seed42_char_wb_5_10_min_df10_min_cluster_size10_min_samples10_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,10,...,False,290,12167,0.60835,20000,7833,0.551087,0.775544,0.39165,0.679570
10,11,seed42_char_wb_4_10_min_df10_min_cluster_size5_min_samplesdefault_eom,42,char_wb_4_10,char_wb,"(4, 10)",10,23938,6,5,...,False,616,10842,0.54210,20000,9158,0.486739,0.743370,0.45790,0.672002
11,12,seed42_char_wb_4_10_min_df10_min_cluster_size5_min_samples5_eom,42,char_wb_4_10,char_wb,"(4, 10)",10,23938,6,5,...,False,616,10842,0.54210,20000,9158,0.486739,0.743370,0.45790,0.672002
12,13,seed42_char_wb_5_10_min_df10_min_cluster_size2_min_samples10_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,2,...,False,684,11875,0.59375,20000,8125,0.511575,0.755787,0.40625,0.668403
13,14,seed42_char_wb_5_10_min_df5_min_cluster_size5_min_samples10_eom,42,char_wb_5_10,char_wb,"(5, 10)",5,31705,22,5,...,False,324,13352,0.66760,20000,6648,0.558251,0.779126,0.33240,0.667444
14,15,seed42_char_wb_4_10_min_df10_min_cluster_size5_min_samples10_eom,42,char_wb_4_10,char_wb,"(4, 10)",10,23938,6,5,...,False,329,13144,0.65720,20000,6856,0.539968,0.769984,0.34280,0.663188
15,16,seed42_word_2_5_min_df5_min_cluster_size10_min_samples2_eom,42,word_2_5,word,"(2, 5)",5,3150,7981,10,...,False,924,3839,0.19195,20000,16161,0.228539,0.614270,0.80805,0.662715
16,17,seed42_word_2_5_min_df5_min_cluster_size5_min_samples10_eom,42,word_2_5,word,"(2, 5)",5,3150,7981,5,...,False,992,4233,0.21165,20000,15767,0.239333,0.619667,0.78835,0.661837
17,18,seed42_char_wb_5_10_min_df5_min_cluster_size10_min_samplesdefault_eom,42,char_wb_5_10,char_wb,"(5, 10)",5,31705,22,10,...,False,246,13590,0.67950,20000,6410,0.550247,0.775124,0.32050,0.661468
18,19,seed42_char_wb_5_10_min_df5_min_cluster_size10_min_samples10_eom,42,char_wb_5_10,char_wb,"(5, 10)",5,31705,22,10,...,False,246,13590,0.67950,20000,6410,0.550247,0.775124,0.32050,0.661468
19,20,seed42_char_wb_4_10_min_df10_min_cluster_size10_min_samples2_eom,42,char_wb_4_10,char_wb,"(4, 10)",10,23938,6,10,...,False,495,8481,0.42405,20000,11519,0.379194,0.689597,0.57595,0.661185
20,21,seed42_char_wb_4_8_min_df10_min_cluster_size5_min_samplesdefault_eom,42,char_wb_4_8,char_wb,"(4, 8)",10,21744,6,5,...,False,602,11301,0.56505,20000,8699,0.470492,0.735246,0.43495,0.660172
21,22,seed42_char_wb_4_8_min_df10_min_cluster_size5_min_samples5_eom,42,char_wb_4_8,char_wb,"(4, 8)",10,21744,6,5,...,False,602,11301,0.56505,20000,8699,0.470492,0.735246,0.43495,0.660172
22,23,seed42_char_wb_5_10_min_df2_min_cluster_size5_min_samplesdefault_eom,42,char_wb_5_10,char_wb,"(5, 10)",2,67664,9,5,...,False,630,12154,0.60770,20000,7846,0.495600,0.747800,0.39230,0.658925
23,24,seed42_char_wb_5_10_min_df2_min_cluster_size5_min_samples5_eom,42,char_wb_5_10,char_wb,"(5, 10)",2,67664,9,5,...,False,630,12154,0.60770,20000,7846,0.495600,0.747800,0.39230,0.658925
24,25,seed42_char_wb_4_10_min_df5_min_cluster_size5_min_samplesdefault_eom,42,char_wb_4_10,char_wb,"(4, 10)",5,40332,3,5,...,False,657,11491,0.57455,20000,8509,0.471281,0.735641,0.42545,0.658093
25,26,seed42_char_wb_4_10_min_df5_min_cluster_size5_min_samples5_eom,42,char_wb_4_10,char_wb,"(4, 10)",5,40332,3,5,...,False,657,11491,0.57455,20000,8509,0.471281,0.735641,0.42545,0.658093
26,27,seed42_char_wb_4_10_min_df10_min_cluster_size10_min_samplesdefault_eom,42,char_wb_4_10,char_wb,"(4, 10)",10,23938,6,10,...,False,246,13236,0.66180,20000,6764,0.525575,0.762788,0.33820,0.656641
27,28,seed42_char_wb_4_10_min_df10_min_cluster_size10_min_samples10_eom,42,char_wb_4_10,char_wb,"(4, 10)",10,23938,6,10,...,False,246,13236,0.66180,20000,6764,0.525575,0.762788,0.33820,0.656641
28,29,seed42_char_wb_3_10_min_df10_min_cluster_size5_min_samples2_eom,42,char_wb_3_10,char_wb,"(3, 10)",10,27271,0,5,...,False,971,8626,0.43130,20000,11374,0.371216,0.685608,0.56870,0.656381
29,30,seed42_char_wb_4_8_min_df10_min_cluster_size5_min_samples10_eom,42,char_wb_4_8,char_wb,"(4, 8)",10,21744,6,5,...,False,311,13559,0.67795,20000,6441,0.534973,0.767487,0.32205,0.656127
30,31,seed42_char_wb_5_10_min_df5_min_cluster_size10_min_samples2_eom,42,char_wb_5_10,char_wb,"(5, 10)",5,31705,22,10,...,False,476,9256,0.46280,20000,10744,0.388214,0.694107,0.53720,0.654880
31,32,seed42_char_wb_4_10_min_df10_min_cluster_size10_min_samples5_eom,42,char_wb_4_10,char_wb,"(4, 10)",10,23938,6,10,...,False,348,11214,0.56070,20000,8786,0.453200,0.726600,0.43930,0.654775
32,33,seed42_word_2_5_min_df5_min_cluster_size10_min_samples5_eom,42,word_2_5,word,"(2, 5)",5,3150,7981,10,...,False,861,4910,0.24550,20000,15090,0.242498,0.621249,0.75450,0.654562
33,34,seed42_char_wb_5_10_min_df5_min_cluster_size10_min_samples5_eom,42,char_wb_5_10,char_wb,"(5, 10)",5,31705,22,10,...,False,350,11655,0.58275,20000,8345,0.466892,0.733446,0.41725,0.654397
34,35,seed42_char_wb_5_10_min_df10_min_cluster_size20_min_samples2_eom,42,char_wb_5_10,char_wb,"(5, 10)",10,18111,47,20,...,False,243,9361,0.46805,20000,10639,0.388226,0.694113,0.53195,0.653572
35,36,seed42_char_wb_4_8_min_df10_min_cluster_size10_min_samples2_eom,42,char_wb_4_8,char_wb,"(4, 8)",10,21744,6,10,...,False,480,8701,0.43505,20000,11299,0.361673,0.680836,0.56495,0.651865
36,37,seed42_char_wb_5_10_min_df1_min_cluster_size5_min_samples2_eom,42,char_wb_5_10,char_wb,"(5, 10)",1,100000,1,5,...,False,958,9520,0.47600,20000,10480,0.387395,0.693698,0.52400,0.651273
37,38,seed42_word_2_5_min_df5_min_cluster_size10_min_samplesdefault_eom,42,word_2_5,word,"(2, 5)",5,3150,7981,10,...,False,897,4577,0.22885,20000,15423,0.219993,0.609997,0.77115,0.650285
38,39,seed42_word_2_5_min_df5_min_cluster_size10_min_samples10_eom,42,word_2_5,word,"(2, 5)",5,3150,7981,10,...,False,897,4577,0.22885,20000,15423,0.219993,0.609997,0.77115,0.650285
39,40,seed42_char_wb_5_10_min_df1_min_cluster_size5_min_samplesdefault_eom,42,char_wb_5_10,char_wb,"(5, 10)",1,100000,1,5,...,False,594,12607,0.63035,20000,7393,0.485973,0.742986,0.36965,0.649652

## Salvar assigments de um teste específico

In [10]:
ASSIGNMENT_RUN_ID = ASSIGNMENT_RUN_ID or ranking.iloc[0]["run_id"]

run_assignments, run_cluster_summary = summarize_clusters(
    items_by_run[ASSIGNMENT_RUN_ID],
    labels_by_run[ASSIGNMENT_RUN_ID],
)

RUN_ID = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ%f")
output_dir = OUTPUT_ROOT / f"{PERIOD_LABEL}_{RUN_ID}"
output_dir.mkdir(parents=True, exist_ok=False)

assignment_path = output_dir / f"assignments_{ASSIGNMENT_RUN_ID}.csv"
if assignment_path.exists():
    raise FileExistsError(f"Arquivo já existe: {assignment_path}")

run_assignments.to_csv(assignment_path, index=False, encoding="utf-8-sig")
print(f"Assignments salvos em: {assignment_path}")

Assignments salvos em: C:\Users\samuel.simao\Sources\Nofis-Classifier\reports\tfidf_hdbscan\202501-202512_20261025T055138Z888595\assignments_seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samplesdefault_eom.csv

## 5. Revisar um resultado e salvar relat?rios

Escolha `SELECTED_RUN_ID` ap?s comparar quantidade de clusters, ru?do e silhouette. A tabela de resumo inclui `-1` como grupo de ru?do. Os arquivos s?o gravados em uma pasta com identificador UTC ?nico para preservar execu??es anteriores.

Os gr?ficos ficam em `tsne_plots/`, um PNG por configura??o, e as coordenadas da amostra em `tsne_coordinates/`, dentro da pasta da execu??o.

In [11]:
SELECTED_RUN_ID = ranking.iloc[0]["run_id"]
selected = results.set_index("run_id").loc[SELECTED_RUN_ID]
selected_items = items_by_run[SELECTED_RUN_ID]
selected_labels = labels_by_run[SELECTED_RUN_ID]
assignments, cluster_summary = summarize_clusters(selected_items, selected_labels)
cluster_summary = cluster_summary.sort_values("frequencia_total", ascending=False).reset_index(drop=True)
cluster_sizes = assignments.loc[assignments["cluster"].ne(-1)].groupby("cluster")[DESCRIPTION_NORMALIZED].size()
singleton_clusters = cluster_sizes[cluster_sizes.eq(1)].index
frequent_singletons = assignments[assignments["cluster"].isin(singleton_clusters)].sort_values(
    FREQUENCY, ascending=False
)
frequent_noise = assignments[assignments["cluster"].eq(-1)].sort_values(
    FREQUENCY, ascending=False
)
display(cluster_summary.head(20))
display(frequent_singletons.head(20))
display(frequent_noise.head(20))

RUN_ID = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
output_dir = OUTPUT_ROOT / f"{PERIOD_LABEL}_{RUN_ID}"
output_dir.mkdir(parents=True, exist_ok=False)
results.to_csv(output_dir / "metrics.csv", index=False)
ranking.to_csv(output_dir / "ranking.csv", index=False)
assignments.to_csv(output_dir / "assignments.csv", index=False, encoding="utf-8-sig")
cluster_summary.to_csv(output_dir / "cluster_summary.csv", index=False, encoding="utf-8-sig")
frequent_singletons.to_csv(
    output_dir / "frequent_singleton_descriptions.csv", index=False, encoding="utf-8-sig"
)
frequent_noise.to_csv(
    output_dir / "frequent_noise_descriptions.csv", index=False, encoding="utf-8-sig"
)

    cluster  descricoes_unicas  frequencia_total
0        -1               9817             36428
1       537                  6              3595
2       458                 43              2531
3       534                 19              1948
4       293                 53              1735
5       314                 19              1712
6       378                 68              1665
7       229                 35              1243
8       668                 67              1229
9       734                 35              1192
10      210                 17              1090
11      726                 45              1085
12      368                 31              1017
13      610                 27              1010
14      408                  5               917
15       59                 21               902
16      615                 10               900
17      220                 14               896
18      488                 88               808
19      513                 86               790

Empty DataFrame
Columns: [descricao_normalizada, frequencia, cluster, ruido]
Index: []

,descricao_normalizada,frequencia,cluster,ruido
4904,ceia,567,-1,True
5079,chamex solution a4 c 10 resmas,442,-1,True
8014,etanol,350,-1,True
17292,saco lixo 50lts pct c 10und preto,264,-1,True
13943,pao doce com creme kg,246,-1,True
15321,polpa acai,230,-1,True
19894,vinho acai,223,-1,True
8152,farinha aveia,216,-1,True
5113,cheiro verde,204,-1,True
14141,papel a4 go office eco 500 fls fsc reciclado100 cucoc,190,-1,True
14523,papel toalha 02 dobras 20x21 abbaspel,186,-1,True
11041,lentilha,175,-1,True
13494,p t leveza flamingo 20x20cm c 1000un ti20 1000 18,171,-1,True
18490,sonho recheado,160,-1,True
12740,mistura p pao frances saco 25 quilos,159,-1,True
15352,polpa fruta graviola,157,-1,True
4534,calabresa natucarne cx 10kg 4 x2 5kg,157,-1,True
16712,rodo 40cm,157,-1,True
5452,coentro,137,-1,True
6625,desengraxax alcalino,137,-1,True

## Salvar um modelo pelo Run ID

Informe o `MODEL_RUN_ID` abaixo para exportar o TF-IDF, o HDBSCAN ajustado, suas configura??es e os assignments de treino. A exporta??o cria uma pasta nova em `models/tfidf_hdbscan/` para preservar modelos anteriores.

In [12]:
MODEL_RUN_ID = MODEL_RUN_ID or ranking.iloc[0]["run_id"]

if MODEL_RUN_ID not in labels_by_run:
    raise ValueError(f"Run ID nao encontrado. Opcoes: {list(labels_by_run)}")

model_run = results.set_index("run_id").loc[MODEL_RUN_ID]
model_items = items_by_run[MODEL_RUN_ID]
model_labels = labels_by_run[MODEL_RUN_ID]
model_representation = model_run["representation"]
analyzer, ngram_range = ANALYZER_CONFIGS[model_representation]

model_vectorizer = TfidfVectorizer(
    analyzer=analyzer,
    ngram_range=ngram_range,
    min_df=int(model_run["min_df"]),
    max_features=MAX_FEATURES, max_df=MAX_DF,
    sublinear_tf=True,
    norm="l2",
    dtype=np.float64,
)
model_matrix = model_vectorizer.fit_transform(
    model_items[DESCRIPTION_NORMALIZED].astype(str)
)
model_min_samples = (
    None if pd.isna(model_run["min_samples"]) else int(model_run["min_samples"])
)
saved_model = HDBSCAN(
    min_cluster_size=int(model_run["min_cluster_size"]),
    min_samples=model_min_samples,
    metric="cosine",
    algorithm="brute",
    cluster_selection_method=model_run["cluster_selection_method"],
    n_jobs=HDBSCAN_N_JOBS,
    copy=True,
)
saved_model.fit(model_matrix)
if not np.array_equal(saved_model.labels_, model_labels):
    raise RuntimeError("Os labels do modelo refeito nao coincidem com os assignments do Run ID.")

model_assignments, _ = summarize_clusters(model_items, model_labels)
model_output_dir = MODEL_ROOT / f"{PERIOD_LABEL}_{RUN_ID}_{MODEL_RUN_ID}"
model_output_dir.mkdir(parents=True, exist_ok=False)
pd.to_pickle(model_vectorizer, model_output_dir / "tfidf_vectorizer.pkl")
pd.to_pickle(saved_model, model_output_dir / "hdbscan_model.pkl")
model_assignments.to_csv(
    model_output_dir / "training_assignments.csv", index=False, encoding="utf-8-sig"
)
model_config = {
    "run_id": MODEL_RUN_ID,
    "period": PERIOD_LABEL,
    "dataset_name": DATASET_NAME,
    "sample_seed": int(model_run["sample_seed"]),
    "representation": model_representation,
    "analyzer": analyzer,
    "ngram_range": list(ngram_range),
    "tfidf": {
        "min_df": int(model_run["min_df"]),
        "max_features": MAX_FEATURES, "max_df": MAX_DF, "dtype": "float64",
        "sublinear_tf": True,
        "norm": "l2",
    },
    "hdbscan": {
        "min_cluster_size": int(model_run["min_cluster_size"]),
        "min_samples": model_min_samples,
        "metric": "cosine",
        "algorithm": "brute",
        "cluster_selection_method": model_run["cluster_selection_method"],
    },
    "frequency_weighted": False,
    "artifacts": {
        "vectorizer": "tfidf_vectorizer.pkl",
        "model": "hdbscan_model.pkl",
        "training_assignments": "training_assignments.csv",
    },
}
(model_output_dir / "config.json").write_text(
    json.dumps(model_config, indent=2, ensure_ascii=False), encoding="utf-8"
)
logger.info("Modelo do Run ID %s salvo em %s", MODEL_RUN_ID, model_output_dir)

2026-10-25 02:51:46,057 INFO Modelo do Run ID seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samplesdefault_eom salvo em C:\Users\samuel.simao\Sources\Nofis-Classifier\models\tfidf_hdbscan\202501-202512_20261025T055138Z_seed42_char_wb_5_10_min_df10_min_cluster_size5_min_samplesdefault_eom

## 6. Gerar visualiza??es t-SNE

Esta etapa roda depois do ajuste e do ranking. Ela projeta as matrizes TF-IDF j? calculadas e salva as coordenadas e os gr?ficos, sem executar novamente o HDBSCAN.

In [13]:
# Calcula as proje??es 2D existentes e uma proje??o 3D separada por representa??o.
tsne_by_representation = {}
tsne_3d_by_representation = {}
for (sample_seed, representation, min_df), matrix in matrices_by_representation.items():
    logger.info("Calculando t-SNE 2D para %s, min_df=%d, seed=%d", representation, min_df, sample_seed)
    tsne_indices, tsne_coordinates, tsne_dimensions = compute_tsne_projection(
        matrix, TSNE_MAX_POINTS, TSNE_PERPLEXITY, TSNE_MAX_ITER,
        TSNE_RANDOM_STATE,
    )
    tsne_by_representation[(sample_seed, representation, min_df)] = {
        "indices": tsne_indices, "coordinates": tsne_coordinates,
        "reduced_dimensions": tsne_dimensions,
    }

    logger.info("Calculando t-SNE 3D para %s, min_df=%d, seed=%d", representation, min_df, sample_seed)
    tsne_3d_indices, tsne_3d_coordinates, tsne_3d_dimensions = compute_tsne_projection(
        matrix, TSNE_MAX_POINTS, TSNE_PERPLEXITY, TSNE_MAX_ITER,
        TSNE_RANDOM_STATE, n_components=TSNE_3D_N_COMPONENTS,
    )
    if not np.array_equal(tsne_indices, tsne_3d_indices):
        raise ValueError("As proje??es 2D e 3D devem usar a mesma amostra de descri??es.")
    tsne_3d_by_representation[(sample_seed, representation, min_df)] = {
        "indices": tsne_3d_indices, "coordinates": tsne_3d_coordinates,
        "reduced_dimensions": tsne_3d_dimensions,
    }

# Salva coordenadas 2D e um PNG por configura??o.
tsne_coordinates_dir = output_dir / "tsne_coordinates"
tsne_plots_dir = output_dir / "tsne_plots"
tsne_3d_html_dir = output_dir / "tsne_3d_html"
tsne_coordinates_dir.mkdir()
tsne_plots_dir.mkdir()
tsne_3d_html_dir.mkdir()
tsne_artifacts = {}
for (sample_seed, representation, min_df), projection in tsne_by_representation.items():
    indices = projection["indices"]
    coordinates = projection["coordinates"]
    coordinate_frame = items_by_seed[sample_seed].iloc[indices][
        [DESCRIPTION_NORMALIZED, FREQUENCY]
    ].reset_index(drop=True)
    coordinate_frame["tsne_1"] = coordinates[:, 0]
    coordinate_frame["tsne_2"] = coordinates[:, 1]
    coordinate_name = f"seed{sample_seed}_{representation}_min_df{min_df}_coordinates.csv"
    coordinate_frame.to_csv(
        tsne_coordinates_dir / coordinate_name, index=False, encoding="utf-8-sig",
    )
    tsne_artifacts[f"seed{sample_seed}_{representation}_min_df{min_df}"] = {
        "coordinates_file": f"tsne_coordinates/{coordinate_name}",
        "sample_size": len(indices),
        "reduced_dimensions": projection["reduced_dimensions"],
    }

for run_id, labels in labels_by_run.items():
    result_row = results.loc[results["run_id"].eq(run_id)].iloc[0]
    representation_key = (
        int(result_row["sample_seed"]), result_row["representation"], int(result_row["min_df"]),
    )
    projection = tsne_by_representation[representation_key]
    projection_3d = tsne_3d_by_representation[representation_key]
    plot_labels = np.asarray(labels)[projection["indices"]]
    plot_path = tsne_plots_dir / f"{run_id}.png"
    save_tsne_plot(projection["coordinates"], plot_labels, run_id, plot_path)
    tsne_artifacts[f"plot:{run_id}"] = str(plot_path.relative_to(output_dir))

    plot_3d_path = tsne_3d_html_dir / f"{run_id}.html"
    save_tsne_3d_html(projection_3d["coordinates"], plot_labels, run_id, plot_3d_path)
    tsne_artifacts[f"plot_3d:{run_id}"] = str(plot_3d_path.relative_to(output_dir))

logger.info("Imagens t-SNE 2D e gr?ficos HTML 3D salvos: %d", len(labels_by_run))

run_metadata = {
    "comparison": comparison_metadata(items_by_seed[SAMPLE_SEEDS[0]]),
    "dataset_name": DATASET_NAME, "period": PERIOD_LABEL,
    "frequency_weighted": False,
    "dataset_path": str(DATASET_PATH), "max_descriptions": MAX_DESCRIPTIONS,
    "sample_seeds": SAMPLE_SEEDS, "analyzer_configs": {
        representation: {"analyzer": analyzer, "ngram_range": list(ngram_range)}
        for representation, (analyzer, ngram_range) in ANALYZER_CONFIGS.items()
    },
    "min_df_values": MIN_DF_VALUES, "max_features": MAX_FEATURES,
    "selected_run_id": SELECTED_RUN_ID,
    "min_cluster_for_ranking": MIN_CLUSTER_FOR_RANKING,
    "max_clusters_for_ranking": MAX_CLUSTERS_FOR_RANKING,
    "min_cluster_size_values": MIN_CLUSTER_SIZE_VALUES,
    "min_samples_values": MIN_SAMPLES_VALUES,
    "cluster_selection_method": CLUSTER_SELECTION_METHOD,
    "silhouette_sample_size": SILHOUETTE_SAMPLE_SIZE,
    "tsne": {
        "max_points": TSNE_MAX_POINTS, "perplexity": TSNE_PERPLEXITY,
        "max_iter": TSNE_MAX_ITER, "random_state": TSNE_RANDOM_STATE,
        "svd_components": TSNE_SVD_COMPONENTS,
        "three_dimensional_components": TSNE_3D_N_COMPONENTS,
        "artifacts": tsne_artifacts,
    },
}
(output_dir / "run.json").write_text(
    json.dumps(run_metadata, indent=2, ensure_ascii=False), encoding="utf-8"
)
logger.info("Relatorios e imagens t-SNE salvos em %s", output_dir)

2026-10-25 02:51:46,100 INFO Calculando t-SNE 2D para char_wb_2_4, min_df=1, seed=42

2026-10-25 02:51:54,689 INFO Calculando t-SNE 3D para char_wb_2_4, min_df=1, seed=42

2026-10-25 02:52:19,015 INFO Calculando t-SNE 2D para char_wb_2_4, min_df=2, seed=42

2026-10-25 02:52:32,278 INFO Calculando t-SNE 3D para char_wb_2_4, min_df=2, seed=42

2026-10-25 02:53:05,812 INFO Calculando t-SNE 2D para char_wb_2_4, min_df=5, seed=42

2026-10-25 02:53:20,066 INFO Calculando t-SNE 3D para char_wb_2_4, min_df=5, seed=42

2026-10-25 02:53:44,490 INFO Calculando t-SNE 2D para char_wb_2_4, min_df=10, seed=42

2026-10-25 02:53:53,667 INFO Calculando t-SNE 3D para char_wb_2_4, min_df=10, seed=42

2026-10-25 02:54:14,316 INFO Calculando t-SNE 2D para char_wb_2_10, min_df=1, seed=42

2026-10-25 02:54:25,207 INFO Calculando t-SNE 3D para char_wb_2_10, min_df=1, seed=42

2026-10-25 02:54:55,577 INFO Calculando t-SNE 2D para char_wb_2_10, min_df=2, seed=42

2026-10-25 02:55:12,078 INFO Calculando t-SNE 3D para char_wb_2_10, min_df=2, seed=42

2026-10-25 02:55:46,182 INFO Calculando t-SNE 2D para char_wb_2_10, min_df=5, seed=42

2026-10-25 02:55:58,549 INFO Calculando t-SNE 3D para char_wb_2_10, min_df=5, seed=42

2026-10-25 02:56:19,618 INFO Calculando t-SNE 2D para char_wb_2_10, min_df=10, seed=42

2026-10-25 02:56:28,790 INFO Calculando t-SNE 3D para char_wb_2_10, min_df=10, seed=42

2026-10-25 02:56:49,924 INFO Calculando t-SNE 2D para char_wb_3_5, min_df=1, seed=42

2026-10-25 02:57:01,426 INFO Calculando t-SNE 3D para char_wb_3_5, min_df=1, seed=42

2026-10-25 02:57:31,572 INFO Calculando t-SNE 2D para char_wb_3_5, min_df=2, seed=42

2026-10-25 02:57:46,457 INFO Calculando t-SNE 3D para char_wb_3_5, min_df=2, seed=42

2026-10-25 02:58:12,515 INFO Calculando t-SNE 2D para char_wb_3_5, min_df=5, seed=42

2026-10-25 02:58:22,055 INFO Calculando t-SNE 3D para char_wb_3_5, min_df=5, seed=42

2026-10-25 02:58:41,722 INFO Calculando t-SNE 2D para char_wb_3_5, min_df=10, seed=42

2026-10-25 02:58:50,623 INFO Calculando t-SNE 3D para char_wb_3_5, min_df=10, seed=42

2026-10-25 02:59:12,092 INFO Calculando t-SNE 2D para char_wb_3_10, min_df=1, seed=42

2026-10-25 02:59:25,483 INFO Calculando t-SNE 3D para char_wb_3_10, min_df=1, seed=42

2026-10-25 02:59:55,242 INFO Calculando t-SNE 2D para char_wb_3_10, min_df=2, seed=42

2026-10-25 03:00:08,205 INFO Calculando t-SNE 3D para char_wb_3_10, min_df=2, seed=42

2026-10-25 03:00:30,357 INFO Calculando t-SNE 2D para char_wb_3_10, min_df=5, seed=42

2026-10-25 03:00:39,510 INFO Calculando t-SNE 3D para char_wb_3_10, min_df=5, seed=42

2026-10-25 03:00:57,954 INFO Calculando t-SNE 2D para char_wb_3_10, min_df=10, seed=42

2026-10-25 03:01:07,259 INFO Calculando t-SNE 3D para char_wb_3_10, min_df=10, seed=42

2026-10-25 03:01:28,231 INFO Calculando t-SNE 2D para char_wb_4_8, min_df=1, seed=42

2026-10-25 03:01:41,213 INFO Calculando t-SNE 3D para char_wb_4_8, min_df=1, seed=42

2026-10-25 03:02:12,556 INFO Calculando t-SNE 2D para char_wb_4_8, min_df=2, seed=42

2026-10-25 03:02:25,957 INFO Calculando t-SNE 3D para char_wb_4_8, min_df=2, seed=42

2026-10-25 03:02:49,526 INFO Calculando t-SNE 2D para char_wb_4_8, min_df=5, seed=42

2026-10-25 03:02:59,071 INFO Calculando t-SNE 3D para char_wb_4_8, min_df=5, seed=42

2026-10-25 03:03:17,208 INFO Calculando t-SNE 2D para char_wb_4_8, min_df=10, seed=42

2026-10-25 03:03:25,963 INFO Calculando t-SNE 3D para char_wb_4_8, min_df=10, seed=42

2026-10-25 03:03:44,771 INFO Calculando t-SNE 2D para char_wb_4_10, min_df=1, seed=42

2026-10-25 03:03:55,430 INFO Calculando t-SNE 3D para char_wb_4_10, min_df=1, seed=42

2026-10-25 03:04:21,301 INFO Calculando t-SNE 2D para char_wb_4_10, min_df=2, seed=42

2026-10-25 03:04:35,963 INFO Calculando t-SNE 3D para char_wb_4_10, min_df=2, seed=42

2026-10-25 03:05:04,628 INFO Calculando t-SNE 2D para char_wb_4_10, min_df=5, seed=42

2026-10-25 03:05:16,596 INFO Calculando t-SNE 3D para char_wb_4_10, min_df=5, seed=42

2026-10-25 03:05:37,225 INFO Calculando t-SNE 2D para char_wb_4_10, min_df=10, seed=42

2026-10-25 03:05:46,640 INFO Calculando t-SNE 3D para char_wb_4_10, min_df=10, seed=42

2026-10-25 03:06:04,083 INFO Calculando t-SNE 2D para char_wb_5_10, min_df=1, seed=42

2026-10-25 03:06:13,665 INFO Calculando t-SNE 3D para char_wb_5_10, min_df=1, seed=42

2026-10-25 03:06:34,067 INFO Calculando t-SNE 2D para char_wb_5_10, min_df=2, seed=42

2026-10-25 03:06:45,311 INFO Calculando t-SNE 3D para char_wb_5_10, min_df=2, seed=42

2026-10-25 03:07:13,387 INFO Calculando t-SNE 2D para char_wb_5_10, min_df=5, seed=42

2026-10-25 03:07:26,977 INFO Calculando t-SNE 3D para char_wb_5_10, min_df=5, seed=42

2026-10-25 03:07:53,485 INFO Calculando t-SNE 2D para char_wb_5_10, min_df=10, seed=42

2026-10-25 03:08:04,683 INFO Calculando t-SNE 3D para char_wb_5_10, min_df=10, seed=42

2026-10-25 03:08:23,056 INFO Calculando t-SNE 2D para word_1_3, min_df=1, seed=42

2026-10-25 03:08:32,446 INFO Calculando t-SNE 3D para word_1_3, min_df=1, seed=42

2026-10-25 03:08:51,608 INFO Calculando t-SNE 2D para word_1_3, min_df=2, seed=42

2026-10-25 03:09:01,444 INFO Calculando t-SNE 3D para word_1_3, min_df=2, seed=42

2026-10-25 03:09:24,977 INFO Calculando t-SNE 2D para word_1_3, min_df=5, seed=42

2026-10-25 03:09:38,812 INFO Calculando t-SNE 3D para word_1_3, min_df=5, seed=42

2026-10-25 03:10:07,674 INFO Calculando t-SNE 2D para word_1_3, min_df=10, seed=42

2026-10-25 03:10:19,514 INFO Calculando t-SNE 3D para word_1_3, min_df=10, seed=42

2026-10-25 03:10:40,636 INFO Calculando t-SNE 2D para word_1_5, min_df=1, seed=42

2026-10-25 03:10:50,847 INFO Calculando t-SNE 3D para word_1_5, min_df=1, seed=42

2026-10-25 03:11:10,022 INFO Calculando t-SNE 2D para word_1_5, min_df=2, seed=42

2026-10-25 03:11:19,073 INFO Calculando t-SNE 3D para word_1_5, min_df=2, seed=42

2026-10-25 03:11:39,828 INFO Calculando t-SNE 2D para word_1_5, min_df=5, seed=42

2026-10-25 03:11:52,118 INFO Calculando t-SNE 3D para word_1_5, min_df=5, seed=42

2026-10-25 03:12:20,554 INFO Calculando t-SNE 2D para word_1_5, min_df=10, seed=42

2026-10-25 03:12:34,238 INFO Calculando t-SNE 3D para word_1_5, min_df=10, seed=42

2026-10-25 03:12:59,366 INFO Calculando t-SNE 2D para word_2_5, min_df=1, seed=42

2026-10-25 03:13:12,462 INFO Calculando t-SNE 3D para word_2_5, min_df=1, seed=42

2026-10-25 03:13:36,192 INFO Calculando t-SNE 2D para word_2_5, min_df=2, seed=42

2026-10-25 03:13:45,983 INFO Calculando t-SNE 3D para word_2_5, min_df=2, seed=42

2026-10-25 03:14:08,353 INFO Calculando t-SNE 2D para word_2_5, min_df=5, seed=42

2026-10-25 03:14:17,760 INFO Calculando t-SNE 3D para word_2_5, min_df=5, seed=42

2026-10-25 03:15:22,075 INFO Calculando t-SNE 2D para word_2_5, min_df=10, seed=42

2026-10-25 03:15:33,668 INFO Calculando t-SNE 3D para word_2_5, min_df=10, seed=42

2026-10-25 03:18:18,515 INFO Imagens t-SNE 2D e gr?ficos HTML 3D salvos: 640

2026-10-25 03:18:18,540 INFO Relatorios e imagens t-SNE salvos em C:\Users\samuel.simao\Sources\Nofis-Classifier\reports\tfidf_hdbscan\202501-202512_20261025T055138Z

## 7. Interpreta??o

- `noise_fraction` alta significa que muitas descri??es n?o entraram em grupos densos para os par?metros escolhidos.
- `min_cluster_size` controla o menor grupo selecion?vel. `min_samples` maior tende a exigir evid?ncia local mais forte e pode aumentar o ru?do.
- Silhouette mais alta deve ser lida junto da fra??o de ru?do e do tamanho da amostra usada para calcul?-la; uma pontua??o calculada em poucos itens pode ser enganosa.
- HDBSCAN n?o atribui automaticamente novos produtos a clusters neste fluxo e n?o define categorias sem revis?o humana.

- Os HTML em `tsne_3d_html/` cont?m uma proje??o t-SNE 3D que pode ser girada com o mouse e aberta sem depend?ncias externas.