# 76 - Experimento hibrido TF-IDF + MPNet + HDBSCAN

Este notebook combina a representacao hibrida do notebook 52 com a avaliacao e inspecao dos notebooks 74 e 75. Cada descricao recebe um vetor TF-IDF normalizado e um embedding MPNet normalizado; os blocos sao ponderados por `ALPHA` e concatenados antes do agrupamento.

**Pergunta:** a combinacao de sinais lexicais e semanticos forma grupos densos uteis sob diferentes configuracoes TF-IDF e parametros HDBSCAN?

A analise usa descricoes normalizadas unicas, sem NCM ou rotulos humanos, e contabiliza ruido explicitamente. A grade cruza cinco analyzers TF-IDF com nove configuracoes HDBSCAN (45 ajustes). O custo pode ser significativo.

## Configuracoes e comparabilidade

Controles comuns aos notebooks 70 a 76:

- Base completa `2025_NCMs_filtrados_semstopwords`, periodo 202501-202512.
- Ate 20.000 descricoes unicas para agrupamento, amostradas com semente 42 e ordenadas por descricao normalizada. Frequencia nao pondera o ajuste.
- Silhouette cosseno sobre uma amostra base fixa de ate 20.000 linhas, com semente 42. Ruido do algoritmo e excluido depois da amostragem; a quantidade efetivamente avaliada e registrada.
- Ranking exige silhouette definida e de 10 a 1.000 clusters efetivamente formados, sem contar ruido. Pesos: 0,75 para silhouette reescalada e 0,25 para cobertura do algoritmo.
- t-SNE 2D e 3D: mesmos ate 5.000 itens, semente 42, TruncatedSVD de ate 50 componentes, perplexidade 30, 1.000 iteracoes, init PCA (quando ha dimensoes suficientes), learning_rate auto e Barnes-Hut. As projecoes de representacoes diferentes sao exploratorias, nao um espaco comum de distancias.
- `comparison` em `run.json` registra os controles e o hash das descricoes/frequencias usadas no agrupamento.

TF-IDF: os mesmos 10 analyzers dos experimentos de texto, cruzados com `MIN_DF_VALUES = [1, 2, 5, 10]`, max_features 100.000, max_df 1.0, sublinear_tf True, norm l2 e dtype float64. Os vetores zerados sao registrados como diagnostico da representacao, separados do ruido do algoritmo.

MPNet: `sentence-transformers/paraphrase-multilingual-mpnet-base-v2`, batch_size 64, normalize_embeddings True e saida float32. Nao ha min_df ou analyzer no MPNet puro.

O hibrido usa alpha 0,2 como fator especifico da representacao, com normalizacao l2 por bloco e pesos sqrt(alpha)/sqrt(1-alpha). A grade HDBSCAN coincide com 74 e 75: 40 representacoes TF-IDF x 16 combinacoes = 640 ajustes. Os filtros extras de silhouette e o fallback ficam desativados para a comparacao padrao.

In [1]:
import gc
from sklearn.metrics import pairwise_distances
from sklearn import config_context
from hashlib import sha256
from datetime import datetime, timezone
from pathlib import Path
import json
import logging

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import display
from scipy import sparse
from sentence_transformers import SentenceTransformer
from sklearn.cluster import HDBSCAN
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.manifold import TSNE
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import normalize

from nofis_classifier.schema import DESCRIPTION_NORMALIZED, FREQUENCY

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("notebook76")
pd.set_option("display.max_colwidth", 140)

DATASET_NAME = "2025_NCMs_filtrados_semstopwords"
PROJECT_ROOT = next(
    (parent for parent in (Path.cwd(), *Path.cwd().parents)
     if (parent / "data" / "processed").is_dir()),
    None,
)
if PROJECT_ROOT is None:
    raise FileNotFoundError("Nao encontrei a raiz do repositorio com data/processed/.")
DATASET_DIR = PROJECT_ROOT / "data" / "processed" / DATASET_NAME
DATASET_FILES = sorted(DATASET_DIR.glob("*.parquet"))
if not DATASET_FILES:
    raise FileNotFoundError(f"Nenhum Parquet encontrado para {DATASET_NAME}: {DATASET_DIR}")
if len(DATASET_FILES) > 1:
    raise ValueError(
        f"Mais de um Parquet encontrado em {DATASET_DIR}; selecione o periodo explicitamente: "
        f"{[path.name for path in DATASET_FILES]}"
    )
DATASET_PATH = DATASET_FILES[0]
if not DATASET_PATH.stem.startswith(f"{DATASET_NAME}-"):
    raise ValueError(f"Nome de arquivo inesperado: {DATASET_PATH.name}")
PERIOD_LABEL = DATASET_PATH.stem[len(DATASET_NAME) + 1:]

# Parametros de representacao do notebook 52.
MODEL_NAME = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
MAX_DESCRIPTIONS = 20_000
SAMPLE_RANDOM_STATE = 42
ENCODE_BATCH_SIZE = 64
ANALYZER_CONFIGS = {'char_wb_2_4': ('char_wb', (2, 4)), 'char_wb_2_10': ('char_wb', (2, 10)), 'char_wb_3_5': ('char_wb', (3, 5)), 'char_wb_3_10': ('char_wb', (3, 10)), 'char_wb_4_8': ('char_wb', (4, 8)), 'char_wb_4_10': ('char_wb', (4, 10)), 'char_wb_5_10': ('char_wb', (5, 10)), 'word_1_3': ('word', (1, 3)), 'word_1_5': ('word', (1, 5)), 'word_2_5': ('word', (2, 5))}
ALPHA = 0.2

# Grade HDBSCAN e avaliacao dos notebooks 74 e 75.
MIN_CLUSTER_SIZE_VALUES = [2, 5, 10, 20]
MIN_SAMPLES_VALUES = [None, 2, 5, 10]
CLUSTER_SELECTION_METHOD = "eom"
HDBSCAN_N_JOBS = 1
SILHOUETTE_SAMPLE_SIZE = 20_000
MAX_CLUSTERS_FOR_RANKING = 1000
MIN_CLUSTER_FOR_RANKING = 10
SILHOUETTE_WEIGHT = 0.75
NOISE_WEIGHT = 0.25
TSNE_MAX_POINTS = 5_000
TSNE_PERPLEXITY = 30
TSNE_MAX_ITER = 1_000
TSNE_RANDOM_STATE = 42
TSNE_SVD_COMPONENTS = 50
TSNE_3D_N_COMPONENTS = 3
RANKING_FILTER_SILHOUETTE_ABOVE_NOISE = False
SHOW_FULL_BASE_IF_RANKING_EMPTY = False
SELECTED_RUN_ID = None  # None seleciona o primeiro run do ranking filtrado.
OUTPUT_ROOT = PROJECT_ROOT / "reports/tfidf_mpnet_hdbscan"
MODEL_ROOT = PROJECT_ROOT / "models/tfidf_mpnet_hdbscan"

METRIC_RANDOM_STATE = 42

PAIRWISE_WORKING_MEMORY_MIB = 64

MIN_DF_VALUES = [1, 2, 5, 10]

MAX_FEATURES = 100_000

MAX_DF = 1.0

ARTIFACT_RUN_ID = None

## 2. Funcoes da analise

As funcoes mantem no notebook a preparacao, a combinacao das representacoes, a avaliacao e a inspecao dos clusters. A concatenacao preserva TF-IDF esparso e valida a ordem das linhas.

In [2]:
def prepare_items(frame):
    """Limpa descricoes, agrega duplicatas e preserva a frequencia total."""
    initial_frequency = frame[FREQUENCY].sum()
    prepared = frame[[DESCRIPTION_NORMALIZED, FREQUENCY]].copy()
    prepared[DESCRIPTION_NORMALIZED] = prepared[DESCRIPTION_NORMALIZED].astype("string").str.strip()
    prepared = prepared[prepared[DESCRIPTION_NORMALIZED].notna() & prepared[DESCRIPTION_NORMALIZED].ne("")]
    prepared = prepared[prepared[FREQUENCY] >= 1].copy()
    prepared = prepared.groupby(DESCRIPTION_NORMALIZED, as_index=False, sort=False)[FREQUENCY].sum()
    if prepared[FREQUENCY].sum() != initial_frequency:
        raise ValueError("A preparacao alterou a soma de frequencia.")
    return prepared.sort_values(DESCRIPTION_NORMALIZED).reset_index(drop=True)


def combine_representations(tfidf_matrix, mpnet_matrix, alpha, tfidf_ids, mpnet_ids):
    """Normaliza e concatena TF-IDF e MPNet com pesos controlados por alpha."""
    try:
        alpha = float(alpha)
    except (TypeError, ValueError) as exc:
        raise ValueError("alpha deve ser um numero finito no intervalo [0, 1].") from exc
    if not np.isfinite(alpha) or not 0.0 <= alpha <= 1.0:
        raise ValueError("alpha deve ser um numero finito no intervalo [0, 1].")
    if tfidf_matrix.ndim != 2 or mpnet_matrix.ndim != 2:
        raise ValueError("As representacoes devem ser matrizes bidimensionais.")
    if tfidf_matrix.shape[0] != mpnet_matrix.shape[0]:
        raise ValueError("As representacoes devem ter a mesma quantidade de linhas.")
    tfidf_ids, mpnet_ids = np.asarray(tfidf_ids), np.asarray(mpnet_ids)
    rows = tfidf_matrix.shape[0]
    if len(tfidf_ids) != rows or len(mpnet_ids) != rows:
        raise ValueError("Cada matriz deve ter um identificador por linha.")
    if len(np.unique(tfidf_ids)) != rows or len(np.unique(mpnet_ids)) != rows:
        raise ValueError("Os identificadores devem ser unicos em cada representacao.")
    if not np.array_equal(tfidf_ids, mpnet_ids):
        raise ValueError("A ordem dos registros difere entre TF-IDF e MPNet.")
    if alpha == 1.0:
        return normalize(tfidf_matrix, norm="l2", axis=1, copy=True)
    if alpha == 0.0:
        return normalize(mpnet_matrix, norm="l2", axis=1, copy=True)
    tfidf_normalized = normalize(tfidf_matrix, norm="l2", axis=1, copy=True)
    mpnet_normalized = normalize(mpnet_matrix, norm="l2", axis=1, copy=True)
    tfidf_weighted = tfidf_normalized * np.sqrt(alpha)
    mpnet_weighted = mpnet_normalized * np.sqrt(1.0 - alpha)
    if sparse.issparse(tfidf_weighted):
        return sparse.hstack((tfidf_weighted, sparse.csr_matrix(mpnet_weighted)), format="csr")
    return np.concatenate((tfidf_weighted, mpnet_weighted), axis=1)


def summarize_clusters(items, labels):
    """Retorna atribuicoes e resumo de tamanho e frequencia por cluster."""
    result = items.copy()
    result["cluster"] = np.asarray(labels)
    result["ruido"] = result["cluster"].eq(-1)
    summary = (
        result.groupby("cluster", as_index=False)
        .agg(descricoes_unicas=(DESCRIPTION_NORMALIZED, "size"), frequencia_total=(FREQUENCY, "sum"))
        .sort_values("descricoes_unicas", ascending=False)
    )
    return result, summary


def score_configuration(matrix, labels, sample_size, random_state, cached_distances=None):
    """Avalia a mesma amostra de linhas, excluindo ruido somente apos amostrar."""
    labels = np.asarray(labels)
    noise_mask = labels == -1
    cluster_count = len(np.unique(labels[~noise_mask]))
    base_count = min(sample_size, len(labels))
    rng = np.random.default_rng(random_state)
    positions = np.sort(rng.choice(len(labels), size=base_count, replace=False))
    positions = positions[~noise_mask[positions]]
    sample_labels = labels[positions]
    sample_cluster_count = len(np.unique(sample_labels))
    score = np.nan
    actual_count = len(positions)
    if 2 <= sample_cluster_count < actual_count:
        with config_context(working_memory=PAIRWISE_WORKING_MEMORY_MIB):
            if cached_distances is None:
                score = float(silhouette_score(matrix[positions], sample_labels, metric="cosine"))
            else:
                sampled_distances = np.asarray(cached_distances[np.ix_(positions, positions)])
                score = float(silhouette_score(sampled_distances, sample_labels, metric="precomputed"))
    else:
        actual_count = 0
    return {
        "cluster_count_excluding_noise": cluster_count,
        "noise_count": int(noise_mask.sum()),
        "noise_fraction": float(noise_mask.mean()),
        "silhouette_base_sample_size": base_count,
        "silhouette_sample_size": actual_count,
        "silhouette_cosine_without_noise": score,
    }


def compute_tsne_projection(features, max_points, perplexity, max_iter, random_state, n_components=2):
    """Usa a mesma amostra, SVD e parametros t-SNE em todas as representacoes."""
    point_count = features.shape[0]
    sample_count = min(point_count, max_points)
    if sample_count < 3 or n_components not in (2, 3):
        raise ValueError("t-SNE exige pelo menos tres itens e n_components 2 ou 3.")
    rng = np.random.default_rng(random_state)
    indices = np.sort(rng.choice(point_count, size=sample_count, replace=False))
    sampled = features[indices]
    dimensions = min(TSNE_SVD_COMPONENTS, sampled.shape[1] - 1, sample_count - 1)
    if dimensions >= 1:
        reduced = TruncatedSVD(n_components=dimensions, random_state=random_state).fit_transform(sampled)
    else:
        reduced = sampled.toarray() if hasattr(sampled, "toarray") else np.asarray(sampled)
        dimensions = reduced.shape[1]
    coordinates = TSNE(
        n_components=n_components,
        perplexity=min(float(perplexity), (sample_count - 1) / 3),
        init="pca" if dimensions >= n_components else "random",
        learning_rate="auto", max_iter=max_iter, random_state=random_state,
        method="barnes_hut",
    ).fit_transform(reduced)
    return indices, coordinates, dimensions

def save_tsne_plot(coordinates, labels, title, output_path):
    """Salva uma visualizacao t-SNE 2D colorida pelas atribuicoes HDBSCAN."""
    labels = np.asarray(labels)
    figure, axis = plt.subplots(figsize=(12, 9))
    noise = labels == -1
    axis.scatter(coordinates[noise, 0], coordinates[noise, 1], s=10, c="#999999", alpha=0.35, label="Ruido (-1)")
    cluster_labels = np.unique(labels[~noise])
    if len(cluster_labels):
        colors = plt.get_cmap("turbo", max(len(cluster_labels), 1))
        for position, cluster in enumerate(cluster_labels):
            mask = labels == cluster
            axis.scatter(coordinates[mask, 0], coordinates[mask, 1], s=12, color=colors(position), alpha=0.75, label=f"Cluster {cluster}")
    axis.set(title=title, xlabel="t-SNE 1", ylabel="t-SNE 2")
    if len(cluster_labels) <= 15:
        axis.legend(loc="best", fontsize="small")
    figure.tight_layout()
    figure.savefig(output_path, dpi=160)
    plt.close(figure)



def save_tsne_3d_html(coordinates, labels, run_id, output_path):
    """Salva uma visualizacao t-SNE 3D interativa e autocontida em HTML."""
    points = [
        {"x": float(point[0]), "y": float(point[1]), "z": float(point[2]), "label": int(label)}
        for point, label in zip(coordinates, labels)
    ]
    points_json = json.dumps(points, separators=(",", ":"), ensure_ascii=False).replace("<", "\\u003c")
    title = json.dumps(str(run_id), ensure_ascii=False).replace("<", "\\u003c")
    page = r"""<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>t-SNE 3D</title><style>
html,body{margin:0;height:100%;font:14px system-ui,sans-serif;color:#202124;background:#f7f8fa}main{display:flex;flex-direction:column;height:100%}header{padding:12px 18px;background:white;border-bottom:1px solid #ddd}h1{margin:0 0 4px;font-size:17px}p{margin:0;color:#555}canvas{display:block;width:100%;flex:1;min-height:300px;cursor:grab}canvas:active{cursor:grabbing}
</style></head><body><main><header><h1 id="title"></h1><p>Arraste para girar; use a roda do mouse para aproximar. Ruido em cinza.</p></header><canvas id="plot"></canvas></main>
<script>const points=__POINTS__,runTitle=__TITLE__,canvas=document.getElementById("plot"),ctx=canvas.getContext("2d");document.getElementById("title").textContent="t-SNE 3D: "+runTitle;
let yaw=.65,pitch=-.35,zoom=1,dragging=false,lastX=0,lastY=0;
const colors=["#3366cc","#dc3912","#ff9900","#109618","#990099","#0099c6","#dd4477","#66aa00","#b82e2e","#316395","#994499","#22aa99","#aaaa11","#6633cc","#e67300","#8b0707","#651067","#329262","#5574a6","#3b3eac"];
const bounds=["x","y","z"].map(k=>{const a=points.map(p=>p[k]),lo=Math.min(...a),hi=Math.max(...a);return{lo,span:Math.max(hi-lo,1e-9)}});
function resize(){const r=devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(canvas.clientWidth*r));canvas.height=Math.max(1,Math.floor(canvas.clientHeight*r));ctx.setTransform(r,0,0,r,0,0);draw()}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);const scale=Math.min(w,h)*.7*zoom,cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);const projected=points.map(p=>{const x=((p.x-bounds[0].lo)/bounds[0].span-.5)*2,y=((p.y-bounds[1].lo)/bounds[1].span-.5)*2,z=((p.z-bounds[2].lo)/bounds[2].span-.5)*2,rx=x*cy-z*sy,rz=x*sy+z*cy,ry=y*cp-rz*sp,d=y*sp+rz*cp;return{x:w/2+rx*scale/2,y:h/2-ry*scale/2,d,label:p.label}}).sort((a,b)=>a.d-b.d);for(const p of projected){ctx.globalAlpha=p.label === -1 ? 0.24 : 0.78;ctx.fillStyle=p.label===-1?"#999999":colors[Math.abs(p.label)%colors.length];ctx.beginPath();ctx.arc(p.x,p.y,p.label === -1 ? 2 : 3,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
canvas.addEventListener("pointerdown",e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener("pointerup",()=>dragging=false);canvas.addEventListener("pointermove",e=>{if(!dragging)return;yaw+=(e.clientX-lastX)*.008;pitch=Math.max(-1.5,Math.min(1.5,pitch+(e.clientY-lastY)*.008));lastX=e.clientX;lastY=e.clientY;draw()});canvas.addEventListener("wheel",e=>{e.preventDefault();zoom=Math.max(.3,Math.min(5,zoom*(e.deltaY<0?1.1:.9)));draw()},{passive:false});window.addEventListener("resize",resize);resize();</script></body></html>"""
    page = page.replace("__POINTS__", points_json).replace("__TITLE__", title)
    output_path.write_text(page, encoding="utf-8")


def comparison_metadata(frame):
    """Registra controles comuns e a identidade exata da amostra de agrupamento."""
    sample = frame[[DESCRIPTION_NORMALIZED, FREQUENCY]].sort_values(DESCRIPTION_NORMALIZED).reset_index(drop=True)
    return {
        "dataset_name": DATASET_NAME,
        "training_description_count": len(sample),
        "training_sample_sha256": sha256(pd.util.hash_pandas_object(sample, index=False).values.tobytes()).hexdigest(),
        "max_descriptions": MAX_DESCRIPTIONS, "sample_seed": 42,
        "frequency_weighted": False,
        "silhouette_metric": "cosine", "silhouette_sample_size": SILHOUETTE_SAMPLE_SIZE,
        "metric_random_state": METRIC_RANDOM_STATE,
        "metric_sampling": "fixed rows, then exclude algorithmic noise",
        "min_cluster_for_ranking": MIN_CLUSTER_FOR_RANKING,
        "max_clusters_for_ranking": MAX_CLUSTERS_FOR_RANKING,
        "silhouette_weight": SILHOUETTE_WEIGHT, "noise_weight": NOISE_WEIGHT,
        "tsne": {
            "max_points": TSNE_MAX_POINTS, "perplexity": TSNE_PERPLEXITY,
            "max_iter": TSNE_MAX_ITER, "random_state": TSNE_RANDOM_STATE,
            "reduction": "TruncatedSVD", "svd_components": TSNE_SVD_COMPONENTS,
            "dimensions": [2, 3], "init": "pca", "learning_rate": "auto",
            "method": "barnes_hut",
        },
    }


def memory_mapped_features(matrix, directory, key):
    """Persiste uma CSR em arquivos novos e mantem os dados mapeados em disco."""
    paths = {}
    for name in ("data", "indices", "indptr"):
        path = directory / f"{key}_{name}.npy"
        with path.open("xb") as stream:
            np.save(stream, getattr(matrix, name), allow_pickle=False)
        paths[name] = path
    return sparse.csr_matrix(
        (np.load(paths["data"], mmap_mode="r"),
         np.load(paths["indices"], mmap_mode="r"),
         np.load(paths["indptr"], mmap_mode="r")),
        shape=matrix.shape, copy=False,
    )


def cosine_distance_cache(matrix, path):
    """Calcula cosseno uma vez e reutiliza a matriz sem alterar suas distancias."""
    logger.info("Calculando cache de distancias cosseno: %s", path.name)
    distances = pairwise_distances(matrix, metric="cosine", n_jobs=HDBSCAN_N_JOBS)
    with path.open("xb") as stream:
        np.save(stream, distances, allow_pickle=False)
    del distances
    gc.collect()
    return np.load(path, mmap_mode="r")

## 3. Carregar e preparar os dados

Origem: Parquet de data/processed/2025_NCMs_filtrados_semstopwords/. Usa a mesma amostra de ate 20.000 descricoes e a mesma ordenacao dos demais experimentos.

In [3]:
raw_items = pd.read_parquet(DATASET_PATH)
required_columns = {DESCRIPTION_NORMALIZED, FREQUENCY}
missing_columns = required_columns - set(raw_items.columns)
if missing_columns:
    raise ValueError(f"Colunas ausentes no dataset: {sorted(missing_columns)}")
base_items = prepare_items(raw_items)
logger.info("Descricoes unicas disponiveis: %d", len(base_items))
sampled_items = base_items
if MAX_DESCRIPTIONS is not None and len(base_items) > MAX_DESCRIPTIONS:
    sampled_items = base_items.sample(n=MAX_DESCRIPTIONS, random_state=SAMPLE_RANDOM_STATE)
sampled_items = sampled_items.sort_values(DESCRIPTION_NORMALIZED).reset_index(drop=True)
sampled_items.insert(0, "descricao_id", np.arange(len(sampled_items), dtype=np.int64))
if sampled_items.empty:
    raise ValueError("Nao ha descricoes validas para o experimento.")
display(sampled_items.head())
logger.info("Descricoes na amostra: %d", len(sampled_items))

RUN_ID = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ%f")
output_dir = OUTPUT_ROOT / f"{PERIOD_LABEL}_{RUN_ID}"
output_dir.mkdir(parents=True, exist_ok=False)
distance_cache_dir = output_dir / "distance_cache"
distance_cache_dir.mkdir()
feature_cache_dir = MODEL_ROOT / f"features_{PERIOD_LABEL}_{RUN_ID}"
feature_cache_dir.mkdir(parents=True, exist_ok=False)

2026-10-25 03:26:16,153 INFO Descricoes unicas disponiveis: 146999

,descricao_id,descricao_normalizada,frequencia
0,0,0 25kg adesivo epoxi massa bi componente com base resina epoxi poliamida cargas minerais para reparos,1
1,1,00001 acucar tipo cristal coloracao branca,4
2,2,00004 lixeira material aco inoxidavel capacidade 50 l tipo tampa pedal caracteristicas adicionais com 2 alcas ap,1
3,3,00006 protetor assento sanitario,2
4,4,00007 detergente composicao tensoativo anionico biodegradavel ph 6 5 7 5 c aroma neutro aspecto fisico l,1

2026-10-25 03:26:16,172 INFO Descricoes na amostra: 20000

## 4. Gerar embeddings MPNet

MPNet e calculado uma vez e reutilizado nas configuracoes TF-IDF. Os embeddings sao normalizados na funcao de combinacao, conforme o notebook 52.

In [4]:
texts = sampled_items[DESCRIPTION_NORMALIZED].astype(str).tolist()
row_ids = sampled_items["descricao_id"].to_numpy()
logger.info("Carregando modelo %s", MODEL_NAME)
encoder = SentenceTransformer(MODEL_NAME)
mpnet_matrix = encoder.encode(
    texts, batch_size=ENCODE_BATCH_SIZE, show_progress_bar=True,
    convert_to_numpy=True, normalize_embeddings=True,
).astype(np.float32, copy=False)
if mpnet_matrix.shape[0] != len(sampled_items):
    raise ValueError("MPNet nao preservou uma linha por descricao.")
logger.info("Embeddings MPNet: %d x %d", *mpnet_matrix.shape)

2026-10-25 03:26:16,194 INFO Carregando modelo sentence-transformers/paraphrase-multilingual-mpnet-base-v2

2026-10-25 03:26:16,194 INFO No device provided, using cpu

2026-10-25 03:26:16,213 INFO Loading SentenceTransformer model from sentence-transformers/paraphrase-multilingual-mpnet-base-v2.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/313 [00:00<?, ?it/s]

2026-10-25 03:29:58,787 INFO Embeddings MPNet: 20000 x 768

## 5. Ajustar TF-IDF + HDBSCAN

Cruza os mesmos analyzers e min_df de 70, 72 e 74 com a grade HDBSCAN de 74 e 75. MPNet e reutilizado. O alpha permanece como fator especifico do hibrido. Silhouette usa os controles comuns de amostragem, excluindo ruido apos selecionar as linhas.

Para evitar recalcular as mesmas distancias em cada combinacao HDBSCAN, cosseno e calculado uma vez por representacao. A grade usa essa matriz com metric=precomputed; a silhouette reutiliza os mesmos valores. As features ficam mapeadas em arquivos NPY para limitar a memoria residente. O modelo escolhido continua sendo ajustado nas features originais antes da exportacao, com verificacao exata dos labels. O cache temporario de distancias e removido apos cada representacao; os artefatos de features permanecem em models/.

In [5]:
records = []
labels_by_run = {}
items_by_run = {}
hybrid_matrices = {}
vectorizers = {}

for config_name, (analyzer, ngram_range) in ANALYZER_CONFIGS.items():
    for min_df in MIN_DF_VALUES:
        representation_key = f"{config_name}_min_df{min_df}"
        logger.info("Ajustando TF-IDF: %s (%s, %s)", config_name, analyzer, ngram_range)
        vectorizer = TfidfVectorizer(
            analyzer=analyzer, ngram_range=ngram_range, min_df=min_df,
            max_features=MAX_FEATURES, max_df=MAX_DF, sublinear_tf=True, norm="l2", dtype=np.float64,
        )
        tfidf_matrix = vectorizer.fit_transform(texts)
        if tfidf_matrix.shape[0] != len(sampled_items):
            raise ValueError(f"TF-IDF ({config_name}) nao preservou uma linha por descricao.")
        hybrid_matrix = combine_representations(tfidf_matrix, mpnet_matrix, ALPHA, row_ids, row_ids.copy())
        hybrid_matrix = memory_mapped_features(hybrid_matrix, feature_cache_dir, representation_key)
        hybrid_matrices[representation_key] = hybrid_matrix
        distance_cache_path = distance_cache_dir / f"{representation_key}.npy"
        distance_matrix = cosine_distance_cache(hybrid_matrix, distance_cache_path)
        vectorizers[representation_key] = vectorizer
        logger.info("%s: TF-IDF=%d features; hibrida=%d dimensoes; %d valores", config_name, tfidf_matrix.shape[1], hybrid_matrix.shape[1], hybrid_matrix.nnz)

        for min_cluster_size in MIN_CLUSTER_SIZE_VALUES:
            for min_samples in MIN_SAMPLES_VALUES:
                min_samples_label = "default" if min_samples is None else str(min_samples)
                run_id = (f"seed{SAMPLE_RANDOM_STATE}_{representation_key}_alpha{ALPHA:g}"
                          f"_min_cluster_size{min_cluster_size}_min_samples{min_samples_label}_{CLUSTER_SELECTION_METHOD}")
                logger.info("Ajustando HDBSCAN %s", run_id)
                model = HDBSCAN(
                    min_cluster_size=min_cluster_size, min_samples=min_samples,
                    metric="precomputed", algorithm="brute",
                    cluster_selection_method=CLUSTER_SELECTION_METHOD,
                    n_jobs=HDBSCAN_N_JOBS, copy=True,
                )
                labels = model.fit_predict(distance_matrix)
                del model
                metrics = score_configuration(hybrid_matrix, labels, SILHOUETTE_SAMPLE_SIZE, METRIC_RANDOM_STATE, cached_distances=distance_matrix)
                records.append({
                    "run_id": run_id, "sample_seed": SAMPLE_RANDOM_STATE,
                    "representation": "tfidf_mpnet_hybrid", "tfidf_config": representation_key, "analyzer_config": config_name, "min_df": min_df,
                    "analyzer": analyzer, "ngram_range": str(ngram_range), "alpha": ALPHA,
                    "tfidf_features": tfidf_matrix.shape[1], "mpnet_dimensions": mpnet_matrix.shape[1],
                    "hybrid_dimensions": hybrid_matrix.shape[1], "model_name": MODEL_NAME,
                    "min_cluster_size": min_cluster_size, "min_samples": min_samples,
                    "cluster_selection_method": CLUSTER_SELECTION_METHOD,
                    "frequency_weighted": False, **metrics,
                })
                labels_by_run[run_id] = labels
                items_by_run[run_id] = sampled_items

        # Remove only this run's disposable distance cache. Feature artifacts remain.
        del distance_matrix
        gc.collect()
        try:
            distance_cache_path.unlink()
        except PermissionError:
            logger.warning("Cache temporario ainda em uso; preservado em %s", distance_cache_path)

results = pd.DataFrame(records)
logger.info("Configuracoes HDBSCAN avaliadas: %d", len(results))

2026-10-25 03:29:58,856 INFO Ajustando TF-IDF: char_wb_2_4 (char_wb, (2, 4))

2026-10-25 03:30:01,084 INFO Calculando cache de distancias cosseno: char_wb_2_4_min_df1.npy

2026-10-25 03:34:04,213 INFO char_wb_2_4: TF-IDF=36881 features; hibrida=37649 dimensoes; 17053943 valores

2026-10-25 03:34:04,214 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 03:34:42,490 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 03:35:13,786 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 03:35:39,277 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 03:36:07,418 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 03:36:32,053 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 03:36:56,043 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 03:37:19,051 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 03:37:42,390 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 03:38:05,592 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 03:38:29,272 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 03:38:55,753 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 03:39:22,155 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 03:39:49,459 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 03:40:15,712 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 03:40:42,847 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df1_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 03:41:12,253 INFO Ajustando TF-IDF: char_wb_2_4 (char_wb, (2, 4))

2026-10-25 03:41:14,138 INFO Calculando cache de distancias cosseno: char_wb_2_4_min_df2.npy

2026-10-25 03:45:04,486 INFO char_wb_2_4: TF-IDF=23288 features; hibrida=24056 dimensoes; 17040350 valores

2026-10-25 03:45:04,498 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 03:45:31,014 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 03:45:55,455 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 03:46:18,373 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 03:46:43,956 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 03:47:07,444 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 03:47:32,089 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 03:47:55,423 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 03:48:18,211 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 03:48:40,309 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 03:49:03,653 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 03:49:28,477 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 03:49:52,451 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 03:50:17,603 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 03:50:42,998 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 03:51:06,194 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df2_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 03:51:30,080 INFO Ajustando TF-IDF: char_wb_2_4 (char_wb, (2, 4))

2026-10-25 03:51:31,510 INFO Calculando cache de distancias cosseno: char_wb_2_4_min_df5.npy

2026-10-25 03:55:19,981 INFO char_wb_2_4: TF-IDF=14247 features; hibrida=15015 dimensoes; 17016240 valores

2026-10-25 03:55:19,982 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 03:55:45,695 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 03:56:11,468 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 03:56:38,095 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 03:57:03,128 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 03:57:24,328 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 03:57:47,295 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 03:58:10,928 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 03:58:34,294 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 03:58:57,780 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 03:59:20,266 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 03:59:41,995 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 04:00:05,001 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 04:00:28,462 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 04:00:53,151 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 04:01:19,495 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df5_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 04:01:47,478 INFO Ajustando TF-IDF: char_wb_2_4 (char_wb, (2, 4))

2026-10-25 04:01:49,114 INFO Calculando cache de distancias cosseno: char_wb_2_4_min_df10.npy

2026-10-25 04:05:49,662 INFO char_wb_2_4: TF-IDF=10098 features; hibrida=10866 dimensoes; 16988809 valores

2026-10-25 04:05:49,662 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 04:06:16,196 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 04:06:41,372 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 04:07:03,685 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 04:07:26,149 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 04:07:50,567 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 04:08:15,646 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 04:08:38,729 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 04:09:01,730 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 04:09:24,389 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 04:09:47,563 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 04:10:10,130 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 04:10:33,563 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 04:10:58,833 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 04:11:23,477 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 04:11:46,327 INFO Ajustando HDBSCAN seed42_char_wb_2_4_min_df10_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 04:12:09,980 INFO Ajustando TF-IDF: char_wb_2_10 (char_wb, (2, 10))

2026-10-25 04:12:12,214 INFO Calculando cache de distancias cosseno: char_wb_2_10_min_df1.npy

2026-10-25 04:15:59,647 INFO char_wb_2_10: TF-IDF=100000 features; hibrida=100768 dimensoes; 18054442 valores

2026-10-25 04:15:59,647 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 04:16:26,651 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 04:16:50,390 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 04:17:13,398 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 04:17:36,584 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 04:17:59,381 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 04:18:23,231 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 04:18:47,819 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 04:19:10,836 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 04:19:33,452 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 04:19:56,810 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 04:20:19,050 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 04:20:42,683 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 04:21:05,290 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 04:21:29,665 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 04:21:54,413 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df1_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 04:22:18,098 INFO Ajustando TF-IDF: char_wb_2_10 (char_wb, (2, 10))

2026-10-25 04:22:20,222 INFO Calculando cache de distancias cosseno: char_wb_2_10_min_df2.npy

2026-10-25 04:26:07,337 INFO char_wb_2_10: TF-IDF=90460 features; hibrida=91228 dimensoes; 18044902 valores

2026-10-25 04:26:07,337 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 04:26:33,532 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 04:26:57,833 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 04:27:20,590 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 04:27:43,149 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 04:28:05,899 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 04:28:29,995 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 04:28:54,400 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 04:29:17,133 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 04:29:39,566 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 04:30:03,006 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 04:30:26,166 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 04:30:50,200 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 04:31:14,124 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 04:31:37,533 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 04:32:00,143 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df2_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 04:32:23,333 INFO Ajustando TF-IDF: char_wb_2_10 (char_wb, (2, 10))

2026-10-25 04:32:25,400 INFO Calculando cache de distancias cosseno: char_wb_2_10_min_df5.npy

2026-10-25 04:36:13,079 INFO char_wb_2_10: TF-IDF=45657 features; hibrida=46425 dimensoes; 17928046 valores

2026-10-25 04:36:13,082 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 04:36:42,247 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 04:37:08,700 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 04:37:31,475 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 04:37:54,369 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 04:38:16,977 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 04:38:40,095 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 04:39:03,141 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 04:39:26,161 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 04:39:50,828 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 04:40:15,634 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 04:40:38,801 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 04:41:01,460 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 04:41:25,634 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 04:41:49,001 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 04:42:13,368 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df5_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 04:42:38,673 INFO Ajustando TF-IDF: char_wb_2_10 (char_wb, (2, 10))

2026-10-25 04:42:41,202 INFO Calculando cache de distancias cosseno: char_wb_2_10_min_df10.npy

2026-10-25 04:46:28,540 INFO char_wb_2_10: TF-IDF=28020 features; hibrida=28788 dimensoes; 17812394 valores

2026-10-25 04:46:28,540 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 04:46:54,015 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 04:47:18,083 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 04:47:41,009 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 04:48:04,519 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 04:48:28,931 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 04:48:53,119 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 04:49:15,858 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 04:49:38,568 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 04:50:03,891 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 04:50:29,451 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 04:50:54,116 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 04:51:17,019 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 04:51:39,669 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 04:52:02,508 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 04:52:25,551 INFO Ajustando HDBSCAN seed42_char_wb_2_10_min_df10_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 04:52:49,940 INFO Ajustando TF-IDF: char_wb_3_5 (char_wb, (3, 5))

2026-10-25 04:52:51,445 INFO Calculando cache de distancias cosseno: char_wb_3_5_min_df1.npy

2026-10-25 04:56:37,322 INFO char_wb_3_5: TF-IDF=73193 features; hibrida=73961 dimensoes; 16792950 valores

2026-10-25 04:56:37,322 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 04:57:05,286 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 04:57:30,349 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 04:57:53,087 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 04:58:15,686 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 04:58:38,755 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 04:59:02,320 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 04:59:25,854 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 04:59:50,118 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 05:00:13,088 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 05:00:35,890 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 05:00:58,443 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 05:01:21,420 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 05:01:44,481 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 05:02:09,283 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 05:02:33,339 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df1_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 05:02:56,955 INFO Ajustando TF-IDF: char_wb_3_5 (char_wb, (3, 5))

2026-10-25 05:02:58,300 INFO Calculando cache de distancias cosseno: char_wb_3_5_min_df2.npy

2026-10-25 05:06:42,018 INFO char_wb_3_5: TF-IDF=41044 features; hibrida=41812 dimensoes; 16760801 valores

2026-10-25 05:06:42,019 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 05:07:09,421 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 05:07:34,774 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 05:07:57,776 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 05:08:20,420 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 05:08:43,497 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 05:09:06,930 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 05:09:30,042 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 05:09:54,212 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 05:10:17,845 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 05:10:40,661 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 05:11:03,355 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 05:11:26,884 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 05:11:50,947 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 05:12:14,923 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 05:12:37,589 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df2_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 05:13:01,389 INFO Ajustando TF-IDF: char_wb_3_5 (char_wb, (3, 5))

2026-10-25 05:13:02,776 INFO Calculando cache de distancias cosseno: char_wb_3_5_min_df5.npy

2026-10-25 05:16:47,768 INFO char_wb_3_5: TF-IDF=22987 features; hibrida=23755 dimensoes; 16713171 valores

2026-10-25 05:16:47,768 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 05:17:14,784 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 05:17:38,523 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 05:18:01,716 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 05:18:24,729 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 05:18:50,388 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 05:19:17,090 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 05:19:42,515 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 05:20:08,031 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 05:20:31,317 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 05:20:54,723 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 05:21:18,748 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 05:21:42,656 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 05:22:05,424 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 05:22:28,860 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 05:22:51,890 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df5_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 05:23:16,223 INFO Ajustando TF-IDF: char_wb_3_5 (char_wb, (3, 5))

2026-10-25 05:23:17,711 INFO Calculando cache de distancias cosseno: char_wb_3_5_min_df10.npy

2026-10-25 05:27:01,524 INFO char_wb_3_5: TF-IDF=15191 features; hibrida=15959 dimensoes; 16661906 valores

2026-10-25 05:27:01,524 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 05:27:28,291 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 05:27:53,116 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 05:28:16,124 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 05:28:38,484 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 05:29:01,628 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 05:29:25,014 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 05:29:48,558 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 05:30:12,925 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 05:30:36,682 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 05:30:59,916 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 05:31:22,723 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 05:31:45,830 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 05:32:10,049 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 05:32:33,428 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 05:32:57,515 INFO Ajustando HDBSCAN seed42_char_wb_3_5_min_df10_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 05:33:22,259 INFO Ajustando TF-IDF: char_wb_3_10 (char_wb, (3, 10))

2026-10-25 05:33:24,210 INFO Calculando cache de distancias cosseno: char_wb_3_10_min_df1.npy

2026-10-25 05:37:09,263 INFO char_wb_3_10: TF-IDF=100000 features; hibrida=100768 dimensoes; 17425389 valores

2026-10-25 05:37:09,264 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 05:37:35,478 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 05:37:59,651 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 05:38:22,859 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 05:38:45,611 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 05:39:08,712 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 05:39:32,462 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 05:39:55,326 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 05:40:19,376 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 05:40:43,209 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 05:41:06,482 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 05:41:29,374 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 05:41:52,254 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 05:42:14,995 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 05:42:38,660 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 05:43:03,010 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df1_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 05:43:27,409 INFO Ajustando TF-IDF: char_wb_3_10 (char_wb, (3, 10))

2026-10-25 05:43:29,312 INFO Calculando cache de distancias cosseno: char_wb_3_10_min_df2.npy

2026-10-25 05:47:13,252 INFO char_wb_3_10: TF-IDF=89379 features; hibrida=90147 dimensoes; 17414768 valores

2026-10-25 05:47:13,253 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 05:47:39,867 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 05:48:04,304 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 05:48:27,294 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 05:48:49,358 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 05:49:12,390 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 05:49:35,811 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 05:49:58,711 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 05:50:23,066 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 05:50:49,394 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 05:51:13,652 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 05:51:36,795 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 05:51:59,380 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 05:52:22,654 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 05:52:47,628 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 05:53:10,978 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df2_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 05:53:34,948 INFO Ajustando TF-IDF: char_wb_3_10 (char_wb, (3, 10))

2026-10-25 05:53:36,825 INFO Calculando cache de distancias cosseno: char_wb_3_10_min_df5.npy

2026-10-25 05:57:21,395 INFO char_wb_3_10: TF-IDF=44780 features; hibrida=45548 dimensoes; 17298467 valores

2026-10-25 05:57:21,395 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 05:57:48,355 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 05:58:12,629 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 05:58:35,679 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 05:58:58,300 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 05:59:20,962 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 05:59:44,889 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 06:00:09,113 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 06:00:33,118 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 06:00:55,929 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 06:01:19,115 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 06:01:42,381 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 06:02:05,596 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 06:02:29,601 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 06:02:53,529 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 06:03:16,472 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df5_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 06:03:40,014 INFO Ajustando TF-IDF: char_wb_3_10 (char_wb, (3, 10))

2026-10-25 06:03:41,817 INFO Calculando cache de distancias cosseno: char_wb_3_10_min_df10.npy

2026-10-25 06:07:28,143 INFO char_wb_3_10: TF-IDF=27271 features; hibrida=28039 dimensoes; 17183688 valores

2026-10-25 06:07:28,143 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 06:07:53,963 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 06:08:17,948 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 06:08:41,407 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 06:09:03,693 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 06:09:25,897 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 06:09:52,597 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 06:10:17,682 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 06:10:44,853 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 06:11:11,464 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 06:11:35,386 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 06:11:57,170 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 06:12:20,587 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 06:12:45,040 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 06:13:08,668 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 06:13:31,818 INFO Ajustando HDBSCAN seed42_char_wb_3_10_min_df10_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 06:13:55,539 INFO Ajustando TF-IDF: char_wb_4_8 (char_wb, (4, 8))

2026-10-25 06:13:57,096 INFO Calculando cache de distancias cosseno: char_wb_4_8_min_df1.npy

2026-10-25 06:17:41,718 INFO char_wb_4_8: TF-IDF=100000 features; hibrida=100768 dimensoes; 16751335 valores

2026-10-25 06:17:41,719 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 06:18:09,265 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 06:18:33,853 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 06:18:56,998 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 06:19:19,765 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 06:19:43,115 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 06:20:07,626 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 06:20:31,842 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 06:20:54,197 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 06:21:17,132 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 06:21:40,475 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 06:22:03,382 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 06:22:26,191 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 06:22:52,032 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 06:23:16,476 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 06:23:39,459 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df1_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 06:24:03,299 INFO Ajustando TF-IDF: char_wb_4_8 (char_wb, (4, 8))

2026-10-25 06:24:04,970 INFO Calculando cache de distancias cosseno: char_wb_4_8_min_df2.npy

2026-10-25 06:27:49,058 INFO char_wb_4_8: TF-IDF=73051 features; hibrida=73819 dimensoes; 16724386 valores

2026-10-25 06:27:49,058 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 06:28:15,940 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 06:28:40,227 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 06:29:03,191 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 06:29:25,790 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 06:29:49,206 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 06:30:12,789 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 06:30:36,933 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 06:31:00,767 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 06:31:23,366 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 06:31:46,736 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 06:32:09,567 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 06:32:32,563 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 06:32:55,002 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 06:33:18,528 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 06:33:42,846 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df2_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 06:34:07,384 INFO Ajustando TF-IDF: char_wb_4_8 (char_wb, (4, 8))

2026-10-25 06:34:08,950 INFO Calculando cache de distancias cosseno: char_wb_4_8_min_df5.npy

2026-10-25 06:37:55,466 INFO char_wb_4_8: TF-IDF=36185 features; hibrida=36953 dimensoes; 16628178 valores

2026-10-25 06:37:55,466 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 06:38:20,668 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 06:38:44,777 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 06:39:07,884 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 06:39:31,052 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 06:39:54,640 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 06:40:19,734 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 06:40:43,635 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 06:41:05,585 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 06:41:28,371 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 06:41:51,919 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 06:42:16,455 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 06:42:40,245 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 06:43:02,443 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 06:43:25,275 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 06:43:48,348 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df5_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 06:44:12,152 INFO Ajustando TF-IDF: char_wb_4_8 (char_wb, (4, 8))

2026-10-25 06:44:13,648 INFO Calculando cache de distancias cosseno: char_wb_4_8_min_df10.npy

2026-10-25 06:47:57,819 INFO char_wb_4_8: TF-IDF=21744 features; hibrida=22512 dimensoes; 16533562 valores

2026-10-25 06:47:57,819 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 06:48:24,980 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 06:48:50,753 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 06:49:14,219 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 06:49:37,445 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 06:50:00,412 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 06:50:23,286 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 06:50:44,991 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 06:51:07,988 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 06:51:31,988 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 06:51:59,103 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 06:52:23,990 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 06:52:48,021 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 06:53:12,126 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 06:53:35,123 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 06:53:58,049 INFO Ajustando HDBSCAN seed42_char_wb_4_8_min_df10_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 06:54:21,740 INFO Ajustando TF-IDF: char_wb_4_10 (char_wb, (4, 10))

2026-10-25 06:54:23,294 INFO Calculando cache de distancias cosseno: char_wb_4_10_min_df1.npy

2026-10-25 06:58:06,993 INFO char_wb_4_10: TF-IDF=100000 features; hibrida=100768 dimensoes; 16857538 valores

2026-10-25 06:58:07,002 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 06:58:34,188 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 06:58:59,627 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 06:59:22,250 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 06:59:44,876 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 07:00:08,242 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 07:00:32,875 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 07:00:56,926 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 07:01:19,288 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 07:01:42,428 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 07:02:05,552 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 07:02:28,921 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 07:02:51,557 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 07:03:14,314 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 07:03:39,017 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 07:04:03,438 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df1_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 07:04:26,876 INFO Ajustando TF-IDF: char_wb_4_10 (char_wb, (4, 10))

2026-10-25 07:04:28,521 INFO Calculando cache de distancias cosseno: char_wb_4_10_min_df2.npy

2026-10-25 07:08:13,354 INFO char_wb_4_10: TF-IDF=82710 features; hibrida=83478 dimensoes; 16840248 valores

2026-10-25 07:08:13,355 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 07:08:40,172 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 07:09:04,118 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 07:09:27,341 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 07:09:50,056 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 07:10:13,075 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 07:10:36,602 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 07:10:59,947 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 07:11:24,257 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 07:11:47,389 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 07:12:10,946 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 07:12:33,718 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 07:12:56,789 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 07:13:19,031 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 07:13:42,251 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 07:14:06,713 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df2_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 07:14:31,087 INFO Ajustando TF-IDF: char_wb_4_10 (char_wb, (4, 10))

2026-10-25 07:14:32,729 INFO Calculando cache de distancias cosseno: char_wb_4_10_min_df5.npy

2026-10-25 07:18:16,748 INFO char_wb_4_10: TF-IDF=40332 features; hibrida=41100 dimensoes; 16729933 valores

2026-10-25 07:18:16,749 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 07:18:43,207 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 07:19:06,644 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 07:19:29,552 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 07:19:52,657 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 07:20:16,551 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 07:20:41,224 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 07:21:04,617 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 07:21:27,473 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 07:21:49,855 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 07:22:13,246 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 07:22:36,024 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 07:22:59,579 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 07:23:23,637 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 07:23:46,814 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 07:24:09,997 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df5_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 07:24:33,804 INFO Ajustando TF-IDF: char_wb_4_10 (char_wb, (4, 10))

2026-10-25 07:24:35,363 INFO Calculando cache de distancias cosseno: char_wb_4_10_min_df10.npy

2026-10-25 07:28:19,479 INFO char_wb_4_10: TF-IDF=23938 features; hibrida=24706 dimensoes; 16622517 valores

2026-10-25 07:28:19,480 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 07:28:46,717 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 07:29:10,825 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 07:29:33,278 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 07:29:56,301 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 07:30:19,615 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 07:30:45,710 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 07:31:09,001 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 07:31:31,974 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 07:31:54,668 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 07:32:17,890 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 07:32:41,387 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 07:33:04,716 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 07:33:28,715 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 07:33:53,444 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 07:34:16,221 INFO Ajustando HDBSCAN seed42_char_wb_4_10_min_df10_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 07:34:39,760 INFO Ajustando TF-IDF: char_wb_5_10 (char_wb, (5, 10))

2026-10-25 07:34:41,246 INFO Calculando cache de distancias cosseno: char_wb_5_10_min_df1.npy

2026-10-25 07:38:25,593 INFO char_wb_5_10: TF-IDF=100000 features; hibrida=100768 dimensoes; 16418402 valores

2026-10-25 07:38:25,593 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 07:38:51,360 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 07:39:17,260 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 07:39:40,479 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 07:40:03,341 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 07:40:26,282 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 07:40:49,940 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 07:41:12,775 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 07:41:36,806 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 07:42:00,560 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 07:42:23,797 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 07:42:46,694 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 07:43:09,478 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 07:43:32,163 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 07:43:55,527 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 07:44:18,386 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df1_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 07:44:42,588 INFO Ajustando TF-IDF: char_wb_5_10 (char_wb, (5, 10))

2026-10-25 07:44:44,084 INFO Calculando cache de distancias cosseno: char_wb_5_10_min_df2.npy

2026-10-25 07:48:27,526 INFO char_wb_5_10: TF-IDF=67664 features; hibrida=68432 dimensoes; 16386066 valores

2026-10-25 07:48:27,528 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 07:48:52,861 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 07:49:18,988 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 07:49:43,996 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 07:50:07,997 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 07:50:31,564 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 07:50:55,645 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 07:51:20,016 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 07:51:42,728 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 07:52:05,478 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 07:52:28,502 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 07:52:53,484 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 07:53:18,359 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 07:53:42,458 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 07:54:06,603 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 07:54:29,639 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df2_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 07:54:53,318 INFO Ajustando TF-IDF: char_wb_5_10 (char_wb, (5, 10))

2026-10-25 07:54:54,760 INFO Calculando cache de distancias cosseno: char_wb_5_10_min_df5.npy

2026-10-25 07:58:40,763 INFO char_wb_5_10: TF-IDF=31705 features; hibrida=32473 dimensoes; 16292788 valores

2026-10-25 07:58:40,763 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 07:59:07,396 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 07:59:31,879 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 07:59:55,036 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 08:00:17,722 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 08:00:40,893 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 08:01:04,630 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 08:01:29,072 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 08:01:52,363 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 08:02:15,031 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 08:02:38,666 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 08:03:01,918 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 08:03:24,718 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 08:03:47,193 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 08:04:10,819 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 08:04:34,762 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df5_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 08:04:59,209 INFO Ajustando TF-IDF: char_wb_5_10 (char_wb, (5, 10))

2026-10-25 08:05:00,564 INFO Calculando cache de distancias cosseno: char_wb_5_10_min_df10.npy

2026-10-25 08:08:44,626 INFO char_wb_5_10: TF-IDF=18111 features; hibrida=18879 dimensoes; 16203868 valores

2026-10-25 08:08:44,626 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 08:09:10,184 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 08:09:36,330 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 08:09:59,733 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 08:10:22,564 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 08:10:45,796 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 08:11:09,605 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 08:11:32,672 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 08:11:56,631 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 08:12:20,994 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 08:12:44,053 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 08:13:07,198 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 08:13:29,899 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 08:13:52,826 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 08:14:15,862 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 08:14:38,872 INFO Ajustando HDBSCAN seed42_char_wb_5_10_min_df10_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 08:15:03,466 INFO Ajustando TF-IDF: word_1_3 (word, (1, 3))

2026-10-25 08:15:04,632 INFO Calculando cache de distancias cosseno: word_1_3_min_df1.npy

2026-10-25 08:18:48,430 INFO word_1_3: TF-IDF=100000 features; hibrida=100768 dimensoes; 15601107 valores

2026-10-25 08:18:48,431 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 08:19:15,499 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 08:19:40,999 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 08:20:03,882 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 08:20:26,660 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 08:20:49,399 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 08:21:13,192 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 08:21:35,904 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 08:21:58,582 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 08:22:23,532 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 08:22:48,024 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 08:23:11,330 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 08:23:35,274 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 08:23:59,283 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 08:24:22,700 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 08:24:45,864 INFO Ajustando HDBSCAN seed42_word_1_3_min_df1_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 08:25:11,717 INFO Ajustando TF-IDF: word_1_3 (word, (1, 3))

2026-10-25 08:25:12,758 INFO Calculando cache de distancias cosseno: word_1_3_min_df2.npy

2026-10-25 08:29:01,458 INFO word_1_3: TF-IDF=23325 features; hibrida=24093 dimensoes; 15524432 valores

2026-10-25 08:29:01,459 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 08:29:29,934 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 08:29:54,176 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 08:30:17,524 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 08:30:43,675 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 08:31:07,051 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 08:31:30,384 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 08:31:53,100 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 08:32:17,117 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 08:32:41,535 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 08:33:05,168 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 08:33:27,733 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 08:33:50,601 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 08:34:13,626 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 08:34:37,155 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 08:35:00,134 INFO Ajustando HDBSCAN seed42_word_1_3_min_df2_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 08:35:27,576 INFO Ajustando TF-IDF: word_1_3 (word, (1, 3))

2026-10-25 08:35:28,652 INFO Calculando cache de distancias cosseno: word_1_3_min_df5.npy

2026-10-25 08:39:18,187 INFO word_1_3: TF-IDF=5821 features; hibrida=6589 dimensoes; 15481567 valores

2026-10-25 08:39:18,189 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 08:39:45,528 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 08:40:09,785 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 08:40:33,115 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 08:40:58,797 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 08:41:21,807 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 08:41:44,986 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 08:42:08,868 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 08:42:33,286 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 08:42:56,386 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 08:43:19,803 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 08:43:42,511 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 08:44:05,586 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 08:44:28,450 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 08:44:51,908 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 08:45:15,044 INFO Ajustando HDBSCAN seed42_word_1_3_min_df5_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 08:45:41,639 INFO Ajustando TF-IDF: word_1_3 (word, (1, 3))

2026-10-25 08:45:42,820 INFO Calculando cache de distancias cosseno: word_1_3_min_df10.npy

2026-10-25 08:49:28,853 INFO word_1_3: TF-IDF=2593 features; hibrida=3361 dimensoes; 15461010 valores

2026-10-25 08:49:28,854 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 08:49:55,037 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 08:50:18,787 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 08:50:41,938 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 08:51:04,520 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 08:51:27,737 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 08:51:52,246 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 08:52:16,985 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 08:52:40,220 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 08:53:03,074 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 08:53:26,454 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 08:53:49,297 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 08:54:11,494 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 08:54:34,304 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 08:54:59,139 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 08:55:23,432 INFO Ajustando HDBSCAN seed42_word_1_3_min_df10_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 08:55:49,821 INFO Ajustando TF-IDF: word_1_5 (word, (1, 5))

2026-10-25 08:55:50,991 INFO Calculando cache de distancias cosseno: word_1_5_min_df1.npy

2026-10-25 08:59:35,598 INFO word_1_5: TF-IDF=100000 features; hibrida=100768 dimensoes; 15608916 valores

2026-10-25 08:59:35,598 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 09:00:01,951 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 09:00:26,443 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 09:00:49,308 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 09:01:15,107 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 09:01:38,042 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 09:02:01,749 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 09:02:26,685 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 09:02:50,642 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 09:03:13,449 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 09:03:36,597 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 09:03:59,705 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 09:04:22,241 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 09:04:45,989 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 09:05:09,289 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 09:05:33,747 INFO Ajustando HDBSCAN seed42_word_1_5_min_df1_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 09:06:01,125 INFO Ajustando TF-IDF: word_1_5 (word, (1, 5))

2026-10-25 09:06:02,508 INFO Calculando cache de distancias cosseno: word_1_5_min_df2.npy

2026-10-25 09:09:48,956 INFO word_1_5: TF-IDF=27572 features; hibrida=28340 dimensoes; 15536488 valores

2026-10-25 09:09:48,958 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 09:10:14,890 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 09:10:39,557 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 09:11:02,454 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 09:11:28,144 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 09:11:50,379 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 09:12:14,948 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 09:12:40,457 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 09:13:04,332 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 09:13:27,056 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 09:13:50,092 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 09:14:12,978 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 09:14:35,758 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 09:14:58,773 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 09:15:21,908 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 09:15:47,324 INFO Ajustando HDBSCAN seed42_word_1_5_min_df2_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 09:16:13,699 INFO Ajustando TF-IDF: word_1_5 (word, (1, 5))

2026-10-25 09:16:14,895 INFO Calculando cache de distancias cosseno: word_1_5_min_df5.npy

2026-10-25 09:20:03,025 INFO word_1_5: TF-IDF=6211 features; hibrida=6979 dimensoes; 15484749 valores

2026-10-25 09:20:03,025 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 09:20:29,150 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 09:20:53,380 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 09:21:16,748 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 09:21:42,587 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 09:22:05,484 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 09:22:29,643 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 09:22:54,351 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 09:23:18,367 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 09:23:41,394 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 09:24:04,958 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 09:24:28,025 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 09:24:50,389 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 09:25:13,225 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 09:25:36,249 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 09:26:00,249 INFO Ajustando HDBSCAN seed42_word_1_5_min_df5_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 09:26:27,209 INFO Ajustando TF-IDF: word_1_5 (word, (1, 5))

2026-10-25 09:26:28,541 INFO Calculando cache de distancias cosseno: word_1_5_min_df10.npy

2026-10-25 09:30:15,486 INFO word_1_5: TF-IDF=2661 features; hibrida=3429 dimensoes; 15462184 valores

2026-10-25 09:30:15,486 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 09:30:41,159 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 09:31:05,021 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 09:31:28,474 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 09:31:52,459 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 09:32:16,698 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 09:32:40,922 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 09:33:04,193 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 09:33:26,983 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 09:33:49,548 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 09:34:12,898 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 09:34:36,314 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 09:35:00,483 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 09:35:24,459 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 09:35:47,479 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 09:36:10,622 INFO Ajustando HDBSCAN seed42_word_1_5_min_df10_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 09:36:34,560 INFO Ajustando TF-IDF: word_2_5 (word, (2, 5))

2026-10-25 09:36:35,720 INFO Calculando cache de distancias cosseno: word_2_5_min_df1.npy

2026-10-25 09:40:27,089 INFO word_2_5: TF-IDF=100000 features; hibrida=100768 dimensoes; 15514154 valores

2026-10-25 09:40:27,089 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 09:40:54,320 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 09:41:17,662 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 09:41:40,849 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 09:42:05,855 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 09:42:30,091 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 09:42:54,528 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 09:43:17,583 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 09:43:41,394 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 09:44:06,048 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 09:44:28,985 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 09:44:55,469 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 09:45:21,086 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 09:45:44,248 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 09:46:09,449 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 09:46:34,478 INFO Ajustando HDBSCAN seed42_word_2_5_min_df1_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 09:47:00,418 INFO Ajustando TF-IDF: word_2_5 (word, (2, 5))

2026-10-25 09:47:01,595 INFO Calculando cache de distancias cosseno: word_2_5_min_df2.npy

2026-10-25 09:50:55,239 INFO word_2_5: TF-IDF=20692 features; hibrida=21460 dimensoes; 15434846 valores

2026-10-25 09:50:55,243 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 09:51:21,425 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 09:51:45,596 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 09:52:08,450 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 09:52:35,162 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 09:52:59,546 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 09:53:23,379 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 09:53:46,062 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 09:54:11,278 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 09:54:36,263 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 09:55:02,063 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 09:55:26,192 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 09:55:52,985 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 09:56:16,126 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 09:56:41,580 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 09:57:08,119 INFO Ajustando HDBSCAN seed42_word_2_5_min_df2_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 09:57:33,696 INFO Ajustando TF-IDF: word_2_5 (word, (2, 5))

2026-10-25 09:57:34,826 INFO Calculando cache de distancias cosseno: word_2_5_min_df5.npy

2026-10-25 10:01:24,498 INFO word_2_5: TF-IDF=3150 features; hibrida=3918 dimensoes; 15393044 valores

2026-10-25 10:01:24,498 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 10:01:49,664 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 10:02:16,268 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 10:02:40,931 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 10:03:04,266 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 10:03:27,497 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 10:03:50,798 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 10:04:13,698 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 10:04:36,714 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 10:04:59,198 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 10:05:22,631 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 10:05:47,098 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 10:06:10,897 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 10:06:33,462 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 10:06:55,494 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 10:07:18,032 INFO Ajustando HDBSCAN seed42_word_2_5_min_df5_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 10:07:41,665 INFO Ajustando TF-IDF: word_2_5 (word, (2, 5))

2026-10-25 10:07:42,922 INFO Calculando cache de distancias cosseno: word_2_5_min_df10.npy

2026-10-25 10:11:30,088 INFO word_2_5: TF-IDF=930 features; hibrida=1698 dimensoes; 15379152 valores

2026-10-25 10:11:30,089 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size2_min_samplesdefault_eom

2026-10-25 10:11:56,647 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size2_min_samples2_eom

2026-10-25 10:12:22,199 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size2_min_samples5_eom

2026-10-25 10:12:45,562 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size2_min_samples10_eom

2026-10-25 10:13:08,799 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size5_min_samplesdefault_eom

2026-10-25 10:13:31,783 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size5_min_samples2_eom

2026-10-25 10:13:55,385 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size5_min_samples5_eom

2026-10-25 10:14:18,032 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size5_min_samples10_eom

2026-10-25 10:14:41,202 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size10_min_samplesdefault_eom

2026-10-25 10:15:04,064 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size10_min_samples2_eom

2026-10-25 10:15:27,620 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size10_min_samples5_eom

2026-10-25 10:15:51,663 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size10_min_samples10_eom

2026-10-25 10:16:15,063 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size20_min_samplesdefault_eom

2026-10-25 10:16:37,916 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size20_min_samples2_eom

2026-10-25 10:17:00,629 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size20_min_samples5_eom

2026-10-25 10:17:23,616 INFO Ajustando HDBSCAN seed42_word_2_5_min_df10_alpha0.2_min_cluster_size20_min_samples10_eom

2026-10-25 10:17:47,516 INFO Configuracoes HDBSCAN avaliadas: 640

## 6. Filtrar e comparar configuracoes

O score combina silhouette reescalada e cobertura com os pesos configurados no inicio. O ranking aplica o intervalo de quantidade de clusters e, por padrao, exige silhouette valida maior que a fracao de ruido. Esses filtros afetam apenas a ordenacao e selecao, nao os ajustes.

Se nenhum resultado passar pelo filtro de silhouette, `SHOW_FULL_BASE_IF_RANKING_EMPTY` permite exibir as configuracoes dentro do intervalo de clusters. Os limites minimo e maximo continuam obrigatorios nesse fallback.

`MIN_CLUSTER_FOR_RANKING = 10` define o minimo do ranking. O intervalo ate `MAX_CLUSTERS_FOR_RANKING` inclui os dois extremos e nao altera os ajustes da grade. Em DBSCAN/HDBSCAN, a contagem exclui o grupo de ruido (-1).

In [6]:
if not 1 <= MIN_CLUSTER_FOR_RANKING <= MAX_CLUSTERS_FOR_RANKING:
    raise ValueError(
        "Os limites devem atender a 1 <= MIN_CLUSTER_FOR_RANKING <= MAX_CLUSTERS_FOR_RANKING."
    )

if SILHOUETTE_WEIGHT < 0 or NOISE_WEIGHT < 0 or SILHOUETTE_WEIGHT + NOISE_WEIGHT <= 0:
    raise ValueError("Os pesos devem ser nao negativos e pelo menos um deve ser maior que zero.")
results["silhouette_quality"] = (results["silhouette_cosine_without_noise"] + 1) / 2
results["noise_quality"] = 1 - results["noise_fraction"]
weight_total = SILHOUETTE_WEIGHT + NOISE_WEIGHT
results["composite_score"] = (SILHOUETTE_WEIGHT * results["silhouette_quality"] + NOISE_WEIGHT * results["noise_quality"]) / weight_total
cluster_count_mask = results["cluster_count_excluding_noise"].between(
    MIN_CLUSTER_FOR_RANKING, MAX_CLUSTERS_FOR_RANKING, inclusive="both",
)
finite_score_mask = np.isfinite(results["silhouette_cosine_without_noise"])
ranking_mask = cluster_count_mask & finite_score_mask
if RANKING_FILTER_SILHOUETTE_ABOVE_NOISE:
    ranking_mask &= (
        results["silhouette_cosine_without_noise"].notna()
        & results["silhouette_cosine_without_noise"].gt(results["noise_fraction"])
    )
ranking = (
    results.loc[ranking_mask]
    .sort_values(
        ["composite_score", "silhouette_cosine_without_noise", "noise_fraction"],
        ascending=[False, False, True], na_position="last",
    )
    .reset_index(drop=True)
)
RANKING_USED_FULL_BASE = False
if ranking.empty and SHOW_FULL_BASE_IF_RANKING_EMPTY:
    logger.warning(
        "O filtro de silhouette nao selecionou resultados; exibindo as configuracoes dentro do intervalo de clusters."
    )
    ranking = (
        results.loc[cluster_count_mask & finite_score_mask].sort_values(
            ["composite_score", "silhouette_cosine_without_noise", "noise_fraction"],
            ascending=[False, False, True], na_position="last",
        )
        .reset_index(drop=True)
    )
    RANKING_USED_FULL_BASE = True
if ranking.empty:
    raise ValueError(
        f"Nenhum resultado elegivel entre {MIN_CLUSTER_FOR_RANKING} e "
        f"{MAX_CLUSTERS_FOR_RANKING} clusters. Ajuste a grade, os limites "
        "ou o filtro de silhouette."
    )
ranking.insert(0, "rank", range(1, len(ranking) + 1))

if SELECTED_RUN_ID is None:
    SELECTED_RUN_ID = ranking.iloc[0]["run_id"]
if SELECTED_RUN_ID not in labels_by_run:
    raise ValueError(f"SELECTED_RUN_ID nao encontrado: {SELECTED_RUN_ID}")
display(ranking)

,rank,run_id,sample_seed,representation,tfidf_config,analyzer_config,min_df,analyzer,ngram_range,alpha,...,frequency_weighted,cluster_count_excluding_noise,noise_count,noise_fraction,silhouette_base_sample_size,silhouette_sample_size,silhouette_cosine_without_noise,silhouette_quality,noise_quality,composite_score
0,1,seed42_word_2_5_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom,42,tfidf_mpnet_hybrid,word_2_5_min_df5,word_2_5,5,word,"(2, 5)",0.2,...,False,982,10329,0.51645,20000,9671,0.348694,0.674347,0.48355,0.626648
1,2,seed42_word_2_5_min_df10_alpha0.2_min_cluster_size5_min_samples2_eom,42,tfidf_mpnet_hybrid,word_2_5_min_df10,word_2_5,10,word,"(2, 5)",0.2,...,False,822,10524,0.52620,20000,9476,0.354840,0.677420,0.47380,0.626515
2,3,seed42_word_2_5_min_df10_alpha0.2_min_cluster_size5_min_samplesdefault_eom,42,tfidf_mpnet_hybrid,word_2_5_min_df10,word_2_5,10,word,"(2, 5)",0.2,...,False,449,13917,0.69585,20000,6083,0.465212,0.732606,0.30415,0.625492
3,4,seed42_word_2_5_min_df10_alpha0.2_min_cluster_size5_min_samples5_eom,42,tfidf_mpnet_hybrid,word_2_5_min_df10,word_2_5,10,word,"(2, 5)",0.2,...,False,449,13917,0.69585,20000,6083,0.465212,0.732606,0.30415,0.625492
4,5,seed42_word_2_5_min_df5_alpha0.2_min_cluster_size5_min_samplesdefault_eom,42,tfidf_mpnet_hybrid,word_2_5_min_df5,word_2_5,5,word,"(2, 5)",0.2,...,False,495,14237,0.71185,20000,5763,0.464427,0.732214,0.28815,0.621198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,511,seed42_word_1_3_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom,42,tfidf_mpnet_hybrid,word_1_3_min_df1,word_1_3,1,word,"(1, 3)",0.2,...,False,752,14101,0.70505,20000,5899,0.210680,0.605340,0.29495,0.527743
511,512,seed42_word_1_3_min_df1_alpha0.2_min_cluster_size5_min_samples10_eom,42,tfidf_mpnet_hybrid,word_1_3_min_df1,word_1_3,1,word,"(1, 3)",0.2,...,False,139,15963,0.79815,20000,4037,0.272289,0.636145,0.20185,0.527571
512,513,seed42_word_2_5_min_df1_alpha0.2_min_cluster_size2_min_samples5_eom,42,tfidf_mpnet_hybrid,word_2_5_min_df1,word_2_5,1,word,"(2, 5)",0.2,...,False,673,15871,0.79355,20000,4129,0.256001,0.628000,0.20645,0.522613
513,514,seed42_word_1_3_min_df1_alpha0.2_min_cluster_size20_min_samples5_eom,42,tfidf_mpnet_hybrid,word_1_3_min_df1,word_1_3,1,word,"(1, 3)",0.2,...,False,80,14973,0.74865,20000,5027,0.223552,0.611776,0.25135,0.521670
514,515,seed42_word_1_3_min_df1_alpha0.2_min_cluster_size2_min_samples10_eom,42,tfidf_mpnet_hybrid,word_1_3_min_df1,word_1_3,1,word,"(1, 3)",0.2,...,False,308,16108,0.80540,20000,3892,0.245215,0.622608,0.19460,0.515606

## 7. Salvar metricas e todos os t-SNE

Esta celula salva metricas e ranking, coordenadas 2D por configuracao TF-IDF e os graficos 2D/3D para todos os runs. Ela nao salva assignments nem modelo. Use a celula seguinte para salvar esses artifacts de um `ARTIFACT_RUN_ID` especifico, sem recalcular os t-SNE.

In [7]:
results.to_csv(output_dir / "metrics.csv", index=False, encoding="utf-8-sig")
ranking.to_csv(output_dir / "ranking.csv", index=False, encoding="utf-8-sig")

# Calcula as projecoes para cada matriz e reutiliza cada uma nos nove runs HDBSCAN.
tsne_by_config = {}
tsne_3d_by_config = {}
for config_name, matrix in hybrid_matrices.items():
    logger.info("Calculando t-SNE 2D para %s", config_name)
    indices_2d, coordinates_2d, dimensions_2d = compute_tsne_projection(
        matrix, TSNE_MAX_POINTS, TSNE_PERPLEXITY, TSNE_MAX_ITER,
        TSNE_RANDOM_STATE, n_components=2,
    )
    logger.info("Calculando t-SNE 3D para %s", config_name)
    indices_3d, coordinates_3d, dimensions_3d = compute_tsne_projection(
        matrix, TSNE_MAX_POINTS, TSNE_PERPLEXITY, TSNE_MAX_ITER,
        TSNE_RANDOM_STATE, n_components=TSNE_3D_N_COMPONENTS,
    )
    if not np.array_equal(indices_2d, indices_3d):
        raise ValueError("As projecoes 2D e 3D precisam usar a mesma amostra.")
    tsne_by_config[config_name] = {
        "indices": indices_2d, "coordinates": coordinates_2d,
        "dimensions": dimensions_2d,
    }
    tsne_3d_by_config[config_name] = {
        "indices": indices_3d, "coordinates": coordinates_3d,
        "dimensions": dimensions_3d,
    }

coordinates_dir = output_dir / "tsne_coordinates"
plots_dir = output_dir / "tsne_plots"
html_3d_dir = output_dir / "tsne_3d_html"
coordinates_dir.mkdir()
plots_dir.mkdir()
html_3d_dir.mkdir()
tsne_artifacts = {}
for config_name, projection in tsne_by_config.items():
    indices = projection["indices"]
    frame = sampled_items.iloc[indices][
        [DESCRIPTION_NORMALIZED, FREQUENCY]
    ].reset_index(drop=True)
    frame["tsne_1"] = projection["coordinates"][:, 0]
    frame["tsne_2"] = projection["coordinates"][:, 1]
    coordinate_path = coordinates_dir / f"{config_name}_coordinates.csv"
    frame.to_csv(coordinate_path, index=False, encoding="utf-8-sig")
    tsne_artifacts[f"coordinates:{config_name}"] = str(
        coordinate_path.relative_to(output_dir)
    )

for run_id, labels in labels_by_run.items():
    config_name = results.loc[results["run_id"].eq(run_id), "tfidf_config"].iloc[0]
    projection = tsne_by_config[config_name]
    projection_3d = tsne_3d_by_config[config_name]
    labels_2d = np.asarray(labels)[projection["indices"]]
    labels_3d = np.asarray(labels)[projection_3d["indices"]]
    plot_path = plots_dir / f"{run_id}.png"
    save_tsne_plot(projection["coordinates"], labels_2d, run_id, plot_path)
    html_path = html_3d_dir / f"{run_id}.html"
    save_tsne_3d_html(projection_3d["coordinates"], labels_3d, run_id, html_path)
    tsne_artifacts[f"plot_2d:{run_id}"] = str(plot_path.relative_to(output_dir))
    tsne_artifacts[f"plot_3d:{run_id}"] = str(html_path.relative_to(output_dir))

run_metadata = {
    "comparison": comparison_metadata(sampled_items),
    "distance_computation": {
        "metric": "cosine", "grid_input": "precomputed exact distances",
        "computed_once_per_representation": True,
        "temporary_distance_cache": str(distance_cache_dir.relative_to(PROJECT_ROOT)),
        "feature_cache": str(feature_cache_dir.relative_to(PROJECT_ROOT)),
        "exported_model_input": "original hybrid features",
    },
    "dataset_name": DATASET_NAME,
    "dataset_path": str(DATASET_PATH.relative_to(PROJECT_ROOT)),
    "period": PERIOD_LABEL,
    "max_descriptions": MAX_DESCRIPTIONS,
    "sample_seed": SAMPLE_RANDOM_STATE,
    "representation": "tfidf_mpnet_hybrid",
    "alpha": ALPHA,
    "model_name": MODEL_NAME,
    "analyzer_configs": {
        name: {"analyzer": analyzer, "ngram_range": list(ngram_range)}
        for name, (analyzer, ngram_range) in ANALYZER_CONFIGS.items()
    },
    "min_df_values": MIN_DF_VALUES,
    "max_features": MAX_FEATURES, "max_df": MAX_DF,
    "min_cluster_size_values": MIN_CLUSTER_SIZE_VALUES,
    "min_samples_values": MIN_SAMPLES_VALUES,
    "cluster_selection_method": CLUSTER_SELECTION_METHOD,
    "ranking_filter_silhouette_above_noise": RANKING_FILTER_SILHOUETTE_ABOVE_NOISE,
    "show_full_base_if_ranking_empty": SHOW_FULL_BASE_IF_RANKING_EMPTY,
    "ranking_used_full_base": RANKING_USED_FULL_BASE,
    "selected_run_id": SELECTED_RUN_ID,
    "min_cluster_for_ranking": MIN_CLUSTER_FOR_RANKING,
    "max_clusters_for_ranking": MAX_CLUSTERS_FOR_RANKING,
    "output_dir": str(output_dir.relative_to(PROJECT_ROOT)),
    "tsne": {
        "max_points": TSNE_MAX_POINTS,
        "perplexity": TSNE_PERPLEXITY,
        "max_iter": TSNE_MAX_ITER,
        "random_state": TSNE_RANDOM_STATE,
        "svd_components": TSNE_SVD_COMPONENTS,
        "three_dimensional_components": TSNE_3D_N_COMPONENTS,
        "artifacts": tsne_artifacts,
    },
    "frequency_weighted": False,
}
(output_dir / "run.json").write_text(
    json.dumps(run_metadata, indent=2, ensure_ascii=False), encoding="utf-8"
)
logger.info("Metricas e todos os graficos t-SNE salvos em %s", output_dir.relative_to(PROJECT_ROOT))

2026-10-25 10:17:47,716 INFO Calculando t-SNE 2D para char_wb_2_4_min_df1

2026-10-25 10:18:01,433 INFO Calculando t-SNE 3D para char_wb_2_4_min_df1

2026-10-25 10:18:34,300 INFO Calculando t-SNE 2D para char_wb_2_4_min_df2

2026-10-25 10:18:45,923 INFO Calculando t-SNE 3D para char_wb_2_4_min_df2

2026-10-25 10:19:08,589 INFO Calculando t-SNE 2D para char_wb_2_4_min_df5

2026-10-25 10:19:18,329 INFO Calculando t-SNE 3D para char_wb_2_4_min_df5

2026-10-25 10:19:39,416 INFO Calculando t-SNE 2D para char_wb_2_4_min_df10

2026-10-25 10:19:50,350 INFO Calculando t-SNE 3D para char_wb_2_4_min_df10

2026-10-25 10:20:17,688 INFO Calculando t-SNE 2D para char_wb_2_10_min_df1

2026-10-25 10:20:33,440 INFO Calculando t-SNE 3D para char_wb_2_10_min_df1

2026-10-25 10:21:07,471 INFO Calculando t-SNE 2D para char_wb_2_10_min_df2

2026-10-25 10:21:20,067 INFO Calculando t-SNE 3D para char_wb_2_10_min_df2

2026-10-25 10:21:44,125 INFO Calculando t-SNE 2D para char_wb_2_10_min_df5

2026-10-25 10:21:54,191 INFO Calculando t-SNE 3D para char_wb_2_10_min_df5

2026-10-25 10:22:15,994 INFO Calculando t-SNE 2D para char_wb_2_10_min_df10

2026-10-25 10:22:26,820 INFO Calculando t-SNE 3D para char_wb_2_10_min_df10

2026-10-25 10:22:53,605 INFO Calculando t-SNE 2D para char_wb_3_5_min_df1

2026-10-25 10:23:08,891 INFO Calculando t-SNE 3D para char_wb_3_5_min_df1

2026-10-25 10:23:43,388 INFO Calculando t-SNE 2D para char_wb_3_5_min_df2

2026-10-25 10:23:56,197 INFO Calculando t-SNE 3D para char_wb_3_5_min_df2

2026-10-25 10:24:20,411 INFO Calculando t-SNE 2D para char_wb_3_5_min_df5

2026-10-25 10:24:30,391 INFO Calculando t-SNE 3D para char_wb_3_5_min_df5

2026-10-25 10:24:51,293 INFO Calculando t-SNE 2D para char_wb_3_5_min_df10

2026-10-25 10:25:01,800 INFO Calculando t-SNE 3D para char_wb_3_5_min_df10

2026-10-25 10:25:31,490 INFO Calculando t-SNE 2D para char_wb_3_10_min_df1

2026-10-25 10:25:54,490 INFO Calculando t-SNE 3D para char_wb_3_10_min_df1

2026-10-25 10:26:34,602 INFO Calculando t-SNE 2D para char_wb_3_10_min_df2

2026-10-25 10:26:49,595 INFO Calculando t-SNE 3D para char_wb_3_10_min_df2

2026-10-25 10:27:15,542 INFO Calculando t-SNE 2D para char_wb_3_10_min_df5

2026-10-25 10:27:26,311 INFO Calculando t-SNE 3D para char_wb_3_10_min_df5

2026-10-25 10:27:49,861 INFO Calculando t-SNE 2D para char_wb_3_10_min_df10

2026-10-25 10:28:01,988 INFO Calculando t-SNE 3D para char_wb_3_10_min_df10

2026-10-25 10:28:33,087 INFO Calculando t-SNE 2D para char_wb_4_8_min_df1

2026-10-25 10:28:50,316 INFO Calculando t-SNE 3D para char_wb_4_8_min_df1

2026-10-25 10:29:27,253 INFO Calculando t-SNE 2D para char_wb_4_8_min_df2

2026-10-25 10:29:40,353 INFO Calculando t-SNE 3D para char_wb_4_8_min_df2

2026-10-25 10:30:05,329 INFO Calculando t-SNE 2D para char_wb_4_8_min_df5

2026-10-25 10:30:15,931 INFO Calculando t-SNE 3D para char_wb_4_8_min_df5

2026-10-25 10:30:40,063 INFO Calculando t-SNE 2D para char_wb_4_8_min_df10

2026-10-25 10:30:53,395 INFO Calculando t-SNE 3D para char_wb_4_8_min_df10

2026-10-25 10:31:27,122 INFO Calculando t-SNE 2D para char_wb_4_10_min_df1

2026-10-25 10:31:44,710 INFO Calculando t-SNE 3D para char_wb_4_10_min_df1

2026-10-25 10:32:17,091 INFO Calculando t-SNE 2D para char_wb_4_10_min_df2

2026-10-25 10:32:28,805 INFO Calculando t-SNE 3D para char_wb_4_10_min_df2

2026-10-25 10:32:52,185 INFO Calculando t-SNE 2D para char_wb_4_10_min_df5

2026-10-25 10:33:03,061 INFO Calculando t-SNE 3D para char_wb_4_10_min_df5

2026-10-25 10:33:29,493 INFO Calculando t-SNE 2D para char_wb_4_10_min_df10

2026-10-25 10:33:44,648 INFO Calculando t-SNE 3D para char_wb_4_10_min_df10

2026-10-25 10:34:21,958 INFO Calculando t-SNE 2D para char_wb_5_10_min_df1

2026-10-25 10:34:37,918 INFO Calculando t-SNE 3D para char_wb_5_10_min_df1

2026-10-25 10:35:05,505 INFO Calculando t-SNE 2D para char_wb_5_10_min_df2

2026-10-25 10:35:16,728 INFO Calculando t-SNE 3D para char_wb_5_10_min_df2

2026-10-25 10:35:39,922 INFO Calculando t-SNE 2D para char_wb_5_10_min_df5

2026-10-25 10:35:52,927 INFO Calculando t-SNE 3D para char_wb_5_10_min_df5

2026-10-25 10:36:24,509 INFO Calculando t-SNE 2D para char_wb_5_10_min_df10

2026-10-25 10:36:41,422 INFO Calculando t-SNE 3D para char_wb_5_10_min_df10

2026-10-25 10:37:17,756 INFO Calculando t-SNE 2D para word_1_3_min_df1

2026-10-25 10:37:30,822 INFO Calculando t-SNE 3D para word_1_3_min_df1

2026-10-25 10:37:55,882 INFO Calculando t-SNE 2D para word_1_3_min_df2

2026-10-25 10:38:06,152 INFO Calculando t-SNE 3D para word_1_3_min_df2

2026-10-25 10:38:31,498 INFO Calculando t-SNE 2D para word_1_3_min_df5

2026-10-25 10:38:43,653 INFO Calculando t-SNE 3D para word_1_3_min_df5

2026-10-25 10:39:18,325 INFO Calculando t-SNE 2D para word_1_3_min_df10

2026-10-25 10:39:34,574 INFO Calculando t-SNE 3D para word_1_3_min_df10

2026-10-25 10:40:06,210 INFO Calculando t-SNE 2D para word_1_5_min_df1

2026-10-25 10:40:18,197 INFO Calculando t-SNE 3D para word_1_5_min_df1

2026-10-25 10:40:42,905 INFO Calculando t-SNE 2D para word_1_5_min_df2

2026-10-25 10:40:54,115 INFO Calculando t-SNE 3D para word_1_5_min_df2

2026-10-25 10:41:19,753 INFO Calculando t-SNE 2D para word_1_5_min_df5

2026-10-25 10:41:32,841 INFO Calculando t-SNE 3D para word_1_5_min_df5

2026-10-25 10:42:07,103 INFO Calculando t-SNE 2D para word_1_5_min_df10

2026-10-25 10:42:20,086 INFO Calculando t-SNE 3D para word_1_5_min_df10

2026-10-25 10:42:44,075 INFO Calculando t-SNE 2D para word_2_5_min_df1

2026-10-25 10:42:54,379 INFO Calculando t-SNE 3D para word_2_5_min_df1

2026-10-25 10:43:17,120 INFO Calculando t-SNE 2D para word_2_5_min_df2

2026-10-25 10:43:27,396 INFO Calculando t-SNE 3D para word_2_5_min_df2

2026-10-25 10:43:55,895 INFO Calculando t-SNE 2D para word_2_5_min_df5

2026-10-25 10:44:12,231 INFO Calculando t-SNE 3D para word_2_5_min_df5

2026-10-25 10:44:43,501 INFO Calculando t-SNE 2D para word_2_5_min_df10

2026-10-25 10:44:54,278 INFO Calculando t-SNE 3D para word_2_5_min_df10

2026-10-25 10:55:51,560 INFO Metricas e todos os graficos t-SNE salvos em reports\tfidf_mpnet_hdbscan\202501-202512_20261025T062616Z172896

## 8. Salvar assignments e modelo de um run especifico

Informe o `ARTIFACT_RUN_ID` e execute somente a celula de codigo abaixo. Ela salva o CSV de assignments e o modelo HDBSCAN junto do vetorizador TF-IDF, encoder MPNet e configuracao. Esta celula nao calcula nem salva t-SNE.

In [8]:
ARTIFACT_RUN_ID = ARTIFACT_RUN_ID or SELECTED_RUN_ID

if ARTIFACT_RUN_ID not in labels_by_run:
    raise ValueError(
        f"ARTIFACT_RUN_ID nao encontrado. Runs disponiveis: {list(labels_by_run)}"
    )

artifact_timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ%f")
artifact_folder = f"{PERIOD_LABEL}_{artifact_timestamp}_{ARTIFACT_RUN_ID}"
assignment_output_dir = OUTPUT_ROOT / f"assignments_{artifact_folder}"
model_output_dir = MODEL_ROOT / artifact_folder
assignment_output_dir.mkdir(parents=True, exist_ok=False)
model_output_dir.mkdir(parents=True, exist_ok=False)

artifact_items = items_by_run[ARTIFACT_RUN_ID]
artifact_labels = labels_by_run[ARTIFACT_RUN_ID]
assignments, artifact_cluster_summary = summarize_clusters(artifact_items, artifact_labels)
assignment_path = assignment_output_dir / f"assignments_{ARTIFACT_RUN_ID}.csv"
assignments.to_csv(assignment_path, index=False, encoding="utf-8-sig")

artifact_run = results.set_index("run_id").loc[ARTIFACT_RUN_ID]
config_name = artifact_run["tfidf_config"]
min_samples = None if pd.isna(artifact_run["min_samples"]) else int(artifact_run["min_samples"])
saved_model = HDBSCAN(
    min_cluster_size=int(artifact_run["min_cluster_size"]),
    min_samples=min_samples,
    metric="cosine",
    algorithm="brute",
    cluster_selection_method=artifact_run["cluster_selection_method"],
    n_jobs=HDBSCAN_N_JOBS,
    copy=True,
)
saved_model.fit(hybrid_matrices[config_name])
if not np.array_equal(saved_model.labels_, artifact_labels):
    raise RuntimeError(
        "Os labels do modelo refeito nao coincidem com os assignments do ARTIFACT_RUN_ID."
    )

encoder.save(str(model_output_dir / "sentence_transformer"))
pd.to_pickle(saved_model, model_output_dir / "hdbscan_model.pkl")
pd.to_pickle(vectorizers[config_name], model_output_dir / "tfidf_vectorizer.pkl")
assignments.to_csv(
    model_output_dir / "training_assignments.csv", index=False, encoding="utf-8-sig"
)
model_config = {
    "run_id": ARTIFACT_RUN_ID,
    "period": PERIOD_LABEL,
    "dataset_name": DATASET_NAME,
    "sample_seed": SAMPLE_RANDOM_STATE,
    "representation": "tfidf_mpnet_hybrid",
    "tfidf": {
        "config_name": config_name,
        "analyzer": artifact_run["analyzer"],
        "ngram_range": artifact_run["ngram_range"],
        "min_df": int(artifact_run["min_df"]),
        "max_features": MAX_FEATURES, "max_df": MAX_DF,
        "sublinear_tf": True,
        "norm": "l2",
        "vectorizer_artifact": "tfidf_vectorizer.pkl",
    },
    "encoder": {
        "model_name": MODEL_NAME,
        "artifact": "sentence_transformer/",
        "encode_batch_size": ENCODE_BATCH_SIZE,
        "normalize_embeddings_before_combination": True,
        "embedding_dimension": int(mpnet_matrix.shape[1]),
    },
    "combination": {
        "alpha": ALPHA,
        "normalization": "l2 per block",
        "weights": {
            "tfidf": float(np.sqrt(ALPHA)),
            "mpnet": float(np.sqrt(1.0 - ALPHA)),
        },
    },
    "hdbscan": {
        "min_cluster_size": int(artifact_run["min_cluster_size"]),
        "min_samples": min_samples,
        "metric": "cosine",
        "algorithm": "brute",
        "cluster_selection_method": artifact_run["cluster_selection_method"],
        "artifact": "hdbscan_model.pkl",
    },
    "frequency_weighted": False,
    "assignments_csv": str(assignment_path.relative_to(PROJECT_ROOT)),
    "training_assignments": "training_assignments.csv",
    "prediction_note": (
        "HDBSCAN foi ajustado sem prediction_data; o modelo nao atribui diretamente "
        "novas descricoes a clusters."
    ),
}
(model_output_dir / "config.json").write_text(
    json.dumps(model_config, indent=2, ensure_ascii=False), encoding="utf-8"
)
logger.info("Assignments salvos em %s", assignment_path.relative_to(PROJECT_ROOT))
logger.info("Modelo salvo em %s", model_output_dir.relative_to(PROJECT_ROOT))

2026-10-25 10:59:40,975 INFO Saving model to C:\Users\samuel.simao\Sources\Nofis-Classifier\models\tfidf_mpnet_hdbscan\202501-202512_20261025T135551Z608058_seed42_word_2_5_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom\sentence_transformer

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

2026-10-25 10:59:45,401 INFO Assignments salvos em reports\tfidf_mpnet_hdbscan\assignments_202501-202512_20261025T135551Z608058_seed42_word_2_5_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom\assignments_seed42_word_2_5_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom.csv

2026-10-25 10:59:45,401 INFO Modelo salvo em models\tfidf_mpnet_hdbscan\202501-202512_20261025T135551Z608058_seed42_word_2_5_min_df5_alpha0.2_min_cluster_size5_min_samples2_eom

## 9. Interpretacao e limites

- O ranking filtra por quantidade minima e maxima de clusters e, por padrao, exige silhouette nao nula e maior que a fracao de ruido. Desative `RANKING_FILTER_SILHOUETTE_ABOVE_NOISE` para remover essa segunda regra.
- Cada descricao unica tem o mesmo peso no HDBSCAN; frequencia aparece nos relatorios.
- A silhouette exclui ruido e usa ate 20.000 itens. Compare-a com cobertura e quantidade de clusters.
- t-SNE e uma projecao exploratoria; o HTML 3D permite girar e aproximar a nuvem de pontos.
- HDBSCAN e salvo sem mecanismo de predicao para novos pontos; o encoder e o vetorizador ficam disponiveis para reproduzir a representacao de treino.
- Os clusters sao exploratorios, nao categorias fiscais validadas.